### ISSUE TITLE
Scroll with Arrow Keys

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#100]
Scroll with Arrow Keys http://guake.org/ticket/411
Reported by:    galanom     Owned by:   somebody
Priority:   Fix available   Milestone:  
Component:  guake   Version:    0.4.2
Keywords:   scroll arrow keys   Cc:  
Description

Hi guys! First of all, I don't speak python nor gtk+. My work was shamelessly copied and edited from Mariano Besio <marianobesio@…> (Ticket 163).

This patch enables scrolling with arrow keys (up and down) on guake 0.4.2. I don't know if the problem was only for me, but when I pressed Shift+Up / Down instead of scrolling, an "A"/"B" was being printed. This patch corrects it.

**Comment by phil294** [comment]
Ok, and how would you change the shift pageup/down keys to something  else then? This seems to be not configurable..? @gsemet @pypingou
