### ISSUE TITLE
Guake do not show path through ssh

### ISSUE THREAD

**Issue by narukamiko** [Guake/guake#1013]
It do not show path through ssh login. For example, my home directory is "/home/jack" and it works well in my local directory. But it still show "/home/jack" when I login remote server and the home directory of my remote server is "/home/remote-jack". 
How ti fix it?

**Comment by Stibbons** [comment]
unfortunately, I don't see how we can support it. We will see if newer version of vte support it

**Comment by aichingm** [comment]
AFAIK this is not implementable via vte since ssh does not set/forward the terminal title nor the cwd of its server side. Therefor I'm closing this issue.
