### ISSUE TITLE
Multi-user key conflict?

### ISSUE THREAD

**Issue by SoniEx2** [Guake/guake#1023]
When trying to set guake to use numpad delete for open/close on two different users, and having both users logged in at the same time, it's impossible to make it work for the second user.

If I do manage to get it to set, it still fails to open/close.

Ubuntu 16.04 LTS, Brazilian ABNT2 keyboard

**Comment by aichingm** [comment]
Does this still happen with the GTK 3 version of Guake ( version 3.x.x)?

**Comment by Davidy22** [comment]
Keybindings overhauled since time of reporting, closing unless further confirmation comes in.
