### ISSUE TITLE
In multi monitor setup guake gets stuck on right / secondary display when using option "Appear on mouse display"

### ISSUE THREAD

**Issue by RonaldFindling** [Guake/guake#1025]
Option "Appear on Display 1" works as expected.
Option "Appear on Display primary" works as expected.
Option "Appear on Display 2" works as expected.

When using the option "Appear on mouse display" guake appears on the display the mouse is on only until it appears the first time on the second / right display. After that it always appears on the right / second  display.

Display Setup:
![display_setup](https://user-images.githubusercontent.com/6567878/32414356-10a69aec-c225-11e7-850b-ced8229f344c.png)

Guake Settings:
![guake_settings](https://user-images.githubusercontent.com/6567878/32414388-a9d2c7a4-c225-11e7-906e-55e613f0cc89.png)

Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful

Guake Terminal 0.8.8

GNOME Shell 3.26.1

**Comment by mgvazquez** [comment]
I have a similar issue on Fedora 28.
If 'Appear on Mouse display' is enable, and toggle on the guake, the terminal window switch between monitors every time I toggle.
Regardless of which monitor the mouse is in.

**Comment by revnil** [comment]
I have the same issue as you mgvazquez.

Arch
Gnome 3.30.2
Guake Terminal: 3.4.0
VTE: 0.54.3
VTE runtime: 0.54.3
Gtk: 3.24.2

**Comment by affitz** [comment]
Same here.

Guake Terminal: 3.4.0
VTE: 0.54.3
VTE runtime: 0.54.3
Gtk: 3.24.5

**Comment by siliconmeadow** [comment]
Same behaviour as mgvazquez has seen.

Arch
Gnome Version 3.30.2
Guake: 3.4.0-1
VTE: 0.54.3-1
Gtk: 3.24.4-1

**Comment by amadeusrotundo** [comment]
same. Guake 3.4.0 on openSUSE Tumbleweed

**Comment by ric2b** [comment]
Same, it keeps toggling between the two monitors when I toggle visibility.

Ubuntu 19.04
Guake Terminal: 3.4.0
VTE: 0.56.1
VTE runtime: 0.56.1
Gtk: 3.24.8

**Comment by landsraad** [comment]
Same strange issue of ric2b. Toggling only if mouse on primary display...

Ubuntu 19.04
Guake Terminal: 3.4.0

**Comment by Ivaylo-Korakov** [comment]
I am having something really similar as well. 
If my mouse is on the primary screen guake toggles on the secondary screen and back to the primary in a loop. 
If my mouse is on the secondary screen guake only opens on it as expected.

Ubuntu 19.04
Guake Terminal: 3.4.0
VTE: 0.56.2
VTE runtime: 0.56.2
Gtk: 3.24.8

**Comment by apien** [comment]
> I am having something really similar as well.
> If my mouse is on the primary screen guake toggles on the secondary screen and back to the primary in a loop.
> If my mouse is on the secondary screen guake only opens on it as expected.
> 
> Ubuntu 19.04
> Guake Terminal: 3.4.0
> VTE: 0.56.2
> VTE runtime: 0.56.2
> Gtk: 3.24.8

I have the same on version 3.4.x
Guake 3.6.4 built from source resolves the issue.

**Comment by vahidtwo** [comment]
i have same issue on kubuntu 1904
If my mouse is on the primary screen guake toggles on the secondary screen and back to the primary in a loop.
If my mouse is on the secondary screen guake only opens on it as expected.
guake version 3.4.0

**Comment by mlouielu** [comment]
@vahidtwo could you try to build guake from source and test it again?

**Comment by Ivaylo-Korakov** [comment]
Yes, I can confirm that it is fixed in the master branch.Thanks! Now we just wait for a new release.

**Comment by mlouielu** [comment]
Thanks, I'll close this issue.

If anyone has the same problem, please update guake to the latest version.

**Comment by heyakyra** [comment]
Related to #607
