### ISSUE TITLE
Upgrade VTE

### ISSUE THREAD

**Issue by YanDoroshenko** [Guake/guake#1026]
Upgrade to the newer version of VTE.

**Comment by Stibbons** [comment]
That’s planned part of the migration to gkt3

**Comment by gileri** [comment]
https://github.com/neovim/neovim/issues/7002#issuecomment-316284351 seems related to this.

**Comment by egmontkob** [comment]
From 0.28 (currently used by Guake) to current git, VTE has about 1100 commits (translation updates, version bumps, and reverts excluded), referring to about 270 bugreports. Sure, not supporting cursor shape changing escape sequences is one of them. :-)

**Comment by Stibbons** [comment]
done
