### ISSUE TITLE
Spec files not recognized as links

### ISSUE THREAD

**Issue by fabriciofreitag** [Guake/guake#1032]
![image](https://user-images.githubusercontent.com/4108128/33244349-4de0b0c2-d2ed-11e7-9668-30313cb0c1e9.png)

In this case "./spec/models/transmission_spec.rb:18" is not recognized as a link and "rspec ./spec/models/transmission_spec.rb:17" is considered a link altogether.

Expected behavior:
"./spec/models/transmission_spec.rb:18" is a link
"./spec/models/transmission_spec.rb:17" is a link

obs: quick open in these cases would be very helpful.

**Comment by trizes** [comment]
I've tried writing a script that would remove "rspec ./"  from command and pass to the editor. When using this script in the Quick Open menu like `remove_rspec %(file_path)s:%(line_number)s` - it still does not work. According to syslog guake or system is verifying that file exists before passing it to a script. Changing the script to just `echo` the file name did nothing.

```
Mar 11 16:51:31 iswarm org.gnome.Shell.desktop[1748]: INFO:root:Cannot open file /home/trizes/Projects/rspec ./spec/models/deal_spec.rb, it doesn't exists locally(current dir: .)
Mar 11 16:51:31 iswarm org.gnome.Shell.desktop[1748]: gio: file:///home/trizes/rspec%20./spec/models/deal_spec.rb:17: Error when getting information for file “/home/trizes/rspec ./spec/models/deal_spec.rb:17”: No such file or directory
```

**Comment by Davidy22** [comment]
In present Guake, I know some of  the regex logic has changed a bit and can observe that the first case is fixed, but the second case still occurs. Working on a fix.
