### ISSUE TITLE
Username and command colors are same = can't differentiate between them !

### ISSUE THREAD

**Issue by SghaierFiras** [Guake/guake#1034]
The issue is that my username and my pc 'sghaier@alienbeard' and the command and its output are all with same color which makes really hard to distinguish them :( 

I'm using Ubuntu 17.10

![image](https://user-images.githubusercontent.com/16582284/33271379-57fb4fbe-d387-11e7-9a83-f98576af4103.png)

**Comment by glasnak** [comment]
I don't think this is a guake issue, unless you mean the tab title?
Consider looking into [bash themes](https://github.com/Bash-it/bash-it/wiki/Themes), or even better, get zsh along with [oh-my-zsh](http://ohmyz.sh/) theming and functionality :-)

**Comment by SghaierFiras** [comment]
Done.. the issue was with ~/.bashrc 
the force_color_prompt=yes was commented so I enabled it.
and then edited the following part 
if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;35m\]\u\[\033[01;30m\]@\[\033[01;32m\]\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt
