### ISSUE TITLE
Tab Color

### ISSUE THREAD

**Issue by jmma59** [Guake/guake#1036]
Hi,
It will be precious if we can change TAB color to determine which tab is actif.
Is it possible to add configuration button to add this.

thanks to read me

**Comment by glasnak** [comment]
+1, as this seems to have broken for me recently. Using guake with CentOS 7.4 with Gnome Adwaita theme, the active tab is almost the same as other tabs. This is probably a gnome theming issue, but it affects the usability of guake significantly.

**Comment by kitingChris** [comment]
That would be great. Because default system appearance does not look that great with the black terminal.

**Comment by kofiav** [comment]
+1
