### ISSUE TITLE
Hide on focus lost + Gnome Pointer location makes terminal useless

### ISSUE THREAD

**Issue by a2nt** [Guake/guake#1038]
Pointer location option of Gnome highlights cursor and it's nice option, but I'm unable to use Ctrl+Shift+V command in terminal windows cuz it will be hidden when I will press Ctrl

**Comment by Stibbons** [comment]
it comes from your desktop manager that does somthing when you press ctrl that remove the focus from guake window. I have it as well on the alt key. annoying
