### ISSUE TITLE
Terminal won't drop down when focused on Wayland App

### ISSUE THREAD

**Issue by astrojared** [Guake/guake#1041]
At least under Ubuntu 17.10 64-bit (in an install upgraded from 17.04 Unity), when in the default GNOME Wayland, Guake will drop down if the focus is on an X-windows system app (like Firefox), but won't drop when in a Wayland app (like Evince). There is no issue when using the GNOME X-session or the Unity X-based session.

**Comment by tonyjames** [comment]
I am also experiencing this issue on Fedora 27.

**Comment by FallingSnow** [comment]
This is due to how wayland registers keypresses. Without going into detail about it, you need to register the a shortcut with your DE that will run the `guake -t` command.

**Comment by Stibbons** [comment]
this means we need to be able to trigger the DE from guake or at least print an error message

**Comment by FallingSnow** [comment]
I'm not sure I understand why that's necessary. What do you mean by trigger the DE?

**Comment by gavincabbage** [comment]
@tonyjames I seem to have solved the issue on Fedora 26 w/ @FallingSnow's suggestion if you haven't already seen- 

Settings > Keyboard, add a shortcut "guake -t" to whatever key you're already using and it works great. I just tried my best to break it for a few minutes and wasn't able. I was afraid it might duplicate or something so far no problems like that.

Thanks FallingSnow!

**Comment by gsemet** [comment]
I would be glad if you can add a note on the README about this limitation on fedora

**Comment by vvilerio** [comment]
It's the same with Ubuntu 22.04.2 LTS

**Comment by Davidy22** [comment]
@gavincabbage's solution is the recommended way to resolve this since wayland will probably never budge on global hotkeys.
