### ISSUE TITLE
Closing only remaining tab freezes Guake

### ISSUE THREAD

**Issue by jimrybarski** [Guake/guake#1068]
If I have multiple tabs open, I can close them individually with `Ctrl+Shit+W`. However, if only one tab exists and I press `Ctrl+Shift+W`, Guake will become unresponsive. This only started when I upgraded to Xubuntu 17.10 - when I was on Xubuntu 16.04 it worked as expected.

Version: Guake Terminal 0.8.8
Python: 2.7.14

**Comment by Stibbons** [comment]
can you try with [guake 3 beta](https://launchpad.net/ubuntu/+source/guake/3.0.0.b2-1) or HEAD ?

**Comment by jimrybarski** [comment]
That fixed it.
