### ISSUE TITLE
pin terminal

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#107]
pin terminal http://guake.org/ticket/397
Reported by:    meridius    Owned by:   ulidtko
Priority:   minor   Milestone:  0.5.0
Component:  guake   Version:  
Keywords:   pin,hide,show,lose,focus    Cc:  
Description

I often get into situations when I want Guake to don't hide when it loses focus, then I perform some tasks and I want it to hide again.

It's pain that to do this I have to go to menu and enable/disable this feature there. It would be much better if one could do it by right-click menu and "Pin terminal" and/or using keyboard shortcut.

**Comment by ernstki** [comment]
It seems like this was done in 3ca057a41999e77bf0f358ef0c10d87b7d41bcac, except it's called "Toggle Hide on Lose Focus" which is more of a mouthful but means basically the same thing.
