### ISSUE TITLE
Guake 3.0.0 fails to start if screen is not composited

### ISSUE THREAD

**Issue by City-busz** [Guake/guake#1070]
[This line](https://github.com/Guake/guake/blob/24839dca7ca8b3003fe82e58112687ab5649921d/guake/guake_app.py#L254) should be `self.window.set_visual(screen.get_system_visual())` instead of `self.window.set_visual(screen.get_system_visual)`, otherwise Guake crashes and won't run if the screen is not composited (e.g. with Openbox window manager).

**Comment by Stibbons** [comment]
Fixed on HEAD. Should work
