### ISSUE TITLE
[gtk3] Requires dev packages

### ISSUE THREAD

**Issue by egmontkob** [Guake/guake#1079]
This [Ubuntu package](https://launchpad.net/ubuntu/bionic/amd64/guake/3.0.0.b2-1) requires certain development packages, such as `libglib2.0-dev`, `libgtk-3-dev` and `libvte-2.91-dev`. Presumably they pull in dozens of other packages as dependencies, if not hundreds (complete X11 development suite).

Enduser applications should require solely non-development packages, such as `libglib2.0-0`, `libgtk-3-0` and `libvte-2.91-0`.

The package also requires `libvte-common` which belongs to the gtk2-based vte 0.28. The correct one is `libvte-2.91-common`, if required at all.

(Is this the right place for this bugreport, or shall I report on launchpad?)

**Comment by Stibbons** [comment]
Probably on https://tracker.debian.org/pkg/guake

**Comment by egmontkob** [comment]
Sure, indeed. [887429](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=887429).

**Comment by Stibbons** [comment]
I have added more documentation in read me and bootstrap script for maintainers
