### ISSUE TITLE
[gtk3] Remove or manually implement visible bell

### ISSUE THREAD

**Issue by egmontkob** [Guake/guake#1081]
There's even a note in guake's source: "TODO PORT remove this. the new vte has now[sic] visual bell feature".

Either remove the option, or Guake itself could catch the "bell" signal and do some visual stuff (e.g. show an icon, toggle VTE's color palette back and forth, ...) on its own.

**Comment by aichingm** [comment]
I think that's my fault. It should just say "no" instead of "now"

Sorry my bad...

**Comment by Stibbons** [comment]
oh, no problem. That something we can do later, of even completely discard visual bell (or provide a mecanism for an external plugin to act on, like a notification,...)
