### ISSUE TITLE
[gtk3] Scrollback lines not configurable

### ISSUE THREAD

**Issue by egmontkob** [Guake/guake#1082]
"Scrolling" tab.

The input field for the "Scrollback lines" number is active, however, the - and + buttons are insensitive. No matter what I type for the number (which is 0 initially), the scrollback is only 1024 lines. As I close and reopen the prefs window, the number is 0 again.

Expected: -/+ buttons active. The displayed number reflects the current value. The entered number is saved respected. Ideally another option (checkbox) for infinite scrollback.

(Technical: VTE stores the scrollback in compressed and encrypted, unlinked temporary files under /tmp.)

On a side note, the checkboxes "On output" and "On key stroke" don't make too much sense to me without a header like "Scroll to bottom".

**Comment by egmontkob** [comment]
Let me mention here that the other GtkSpinButton, namely "Max tab name length" on the General tab also suffers from the same problem.

**Comment by egmontkob** [comment]
Thanks!

Some followup nitpicking:

The default value is 1024. The +/- buttons jump on multiples of 1000, and any manually entered value is also rounded.

- The default should be a value that is also configurable later.

- Spinbuttons can be set up in a way that the +/- buttons jump in bigger steps, yet any value entered in between is also accepted.

- There's no technical reason in VTE for preferring powers of two at all. IMHO the default should be a more user-friendly value (a round number in decimal rather than binary).

**Comment by egmontkob** [comment]
By the way, jumping by 1000 is a really nice thing that [I'd like to have for gnome-terminal too](https://bugzilla.gnome.org/show_bug.cgi?id=792760) :-)

**Comment by Stibbons** [comment]
I agree :)

**Comment by sp4c30x1** [comment]
how can i set infinite scroll ?

**Comment by gsemet** [comment]
Update to HEAD?
