### ISSUE TITLE
[gtk3] Prefs GtkFrame border

### ISSUE THREAD

**Issue by egmontkob** [Guake/guake#1086]
In the gtk2 version, GtkFrames (there's plenty of them in Preferences) had their title displayed only and the frame itself hidden (GTK_SHADOW_NONE).

In the gtk3 version, the frame itself is shown (probably GTK_SHADOW_ETCHED_IN) resulting in a much more crowded look.

Unless this change was intentional, I'd consider reverting to the previous look.

**Comment by Stibbons** [comment]
Yes the pref window is ugly for the moment, but there is looot of bug in the glade file to do :(
Thanks for the report anyway!

**Comment by Stibbons** [comment]
fixed on HEAD
