### ISSUE TITLE
[gtk3] No URL recognition

### ISSUE THREAD

**Issue by egmontkob** [Guake/guake#1088]
In the gtk2 version, URLs and email addresses were recognized (text underlined and mouse pointer changed on mouse hover, additional entry in context menu).

In the gtk3 version this doesn't work.

**Comment by egmontkob** [comment]
See also relevant #944.

**Comment by egmontkob** [comment]
Similarly, the Quick Open feature on filenames doesn't work either.

**Comment by egmontkob** [comment]
I _might_ be facing this issue because I'm using an Ubuntu Guake package along with VTE from git, whereas Ubuntu patches VTE around regex stuff. I don't clearly understand how an unpatched app is supposed to / does work along with a patched VTE, or the other way around.

If it works for you then please just close this bug and don't worry about it.

**Comment by egmontkob** [comment]
Probably a duplicate of #1078. (I was testing with 3.0.0.b2.)

**Comment by Stibbons** [comment]
Should be fixed on HEAD
