### ISSUE TITLE
FYI: New APIs in VTE 0.52

### ISSUE THREAD

**Issue by egmontkob** [Guake/guake#1089]
FYI: VTE 0.52 (to be released in March 2018) adds 3 new functionalities and their corresponding APIs (already present in git). It's up to you whether you want to hook up and make config options for them.

Hopefully Ubuntu Bionic 18.04 LTS is going to ship VTE 0.52. If you care about this distro and would like your app to offer these features in this long term support release, you should probably release a new version of your app in time which (conditionally to this VTE version) enables these features.

- `vte_terminal_{get,set}_cell_{height,width}_scale`: Increased line spacing and character spacing mostly for accessibility for people with imperfect sight. (`gnome-terminal` added two new spinbuttons below the font chooser.)

- `vte_terminal_{get,set}_bold_is_bright`: Whether escape sequences such as `\e[1;35m` switch to bright colors in addition to bold (legacy behavior) or switch to bold and leave the color intact (new behavior, required for solarized, base16 and similar modern color schemes). (`gnome-terminal` added a new checkbox "Show bold text in bright colors" at the bottom of the Colors tab.) (And while at it, we've removed "Allow bold text" from `gnome-terminal`'s UI, and will probably start deprecating its API in about a year. I see no sane reason for this option to exist.)

- `vte_terminal_{get,set}_text_blink_mode`: VTE now implements blinking text (`\e[5m`) and enables it by default, this option lets you disable it or make it conditional to the terminal being (un)focused. (`gnome-terminal` added an "Allow blinking text:" "Never" / "When focused" / "When unfocused" / "Always" dropdown to the General tab of profile prefs.)

Please refer to VTE's source tree for details, e.g. compile with `--enable-gtk-doc` and check the generated docs under `doc/reference/html/index.html`.

**Comment by Stibbons** [comment]
Good to know, yes I'll update guake asap :) Thanks for all the bug report, I'll try to fix them quickly :)

**Comment by egmontkob** [comment]
FYI: vte-0.56 / gnome-terminal 3.32 (March 2019) will flip the default of "bold is bright" to false. That is, unless you add a config option or a hardwired call to re-enable it, guake users will see a somewhat different (more logical, but maybe a bit unusual) behavior.

**Comment by eli-schwartz** [comment]
So apparently this never happened :p

**Comment by baongoc124** [comment]
Is it possible to disable blinking text in guake? I hate it with passion...

**Comment by eli-schwartz** [comment]
As far as I know, that was never implemented. Personally I don't believe programs should ever emit such output anyway...

Are you interested in implementing the option? :)
