### ISSUE TITLE
[gtk3] Opens terminal by default

### ISSUE THREAD

**Issue by egmontkob** [Guake/guake#1091]
In the gtk2 version, the command "guake" only presented a desktop notification about F12.

In the gtk3 version, it also opens the terminal.

I'm not a guake user myself, so it's hard for me to imagine, but I expect it's the kind of terminal emulator that you start up (I mean you start up the process listening for F12) when the desktop starts, and then invoke when required. So probably the former behavior makes more sense.

Anyway, opening up a terminal straight away doesn't play nicely along with the message "press F12 to use it". I mean it's already there and usable, and F12 hides it, so why shall I press F12 to use it?? If this new behavior is the new preferred one, maybe consider using different wording such as "press F12 to toggle its window" or alike...?

**Comment by Stibbons** [comment]
That’s nice of you of these exhaustive bug reports! That’s very valuable for a delopper !
I take your point, I think your right :)

**Comment by aichingm** [comment]
@Stibbons this is be fixed by #1123

**Comment by Stibbons** [comment]
yes, fixed on HEAD
