### ISSUE TITLE
[gtk3] Prefs window doesn't pop up nicely

### ISSUE THREAD

**Issue by egmontkob** [Guake/guake#1092]
The way the Preferences window appears isn't too nice.

It's hard to tell exactly what happens because it happens so quickly, but it resizes and moves itself at least once (maybe twice) after being presented (with some/all of its contents being transparent at the first size and location) until it finally settles and shows its stuff.

Ideally, whenever it appears, it should appear at its final size and position. This probably requires that all its contents (including the dynamically generated ones, such as the actual keyboard shortcuts, the possible choices in combo boxes) are filled in before presenting the window.

**Comment by Stibbons** [comment]
yes, this is probably when the virtual terminal is added after load, in page "Appearance"

**Comment by egmontkob** [comment]
Apparently it's not VTE in Appearance, but the "Quick open in current terminal" regexes that dictate the overall width, see #1120.

**Comment by Stibbons** [comment]
was indeed coming from the quick open
