### ISSUE TITLE
[gtk3] Centered labels

### ISSUE THREAD

**Issue by egmontkob** [Guake/guake#1094]
The Preferences dialog contains plenty of labels that are centered and IMHO look horrible. In gtk2 they were left aligned (xalign=0).

Shell -> Default interpreter

Apparance -> Font, Cursor shape (probably Cursor blink mode too), Built-in schemes, Color palette, Demo

(While at it, Use the system fixed width font is indented by way too much.)

Compatibility -> Backspace, Delete

**Comment by Stibbons** [comment]
should be better now, isn't it?

**Comment by egmontkob** [comment]
Definitely :)
