### ISSUE TITLE
[gtk3] Close: Thinks process is running

### ISSUE THREAD

**Issue by egmontkob** [Guake/guake#1097]
Preferences -> General -> Prompt on close tab: With process running

Try to close a tab where only the initial shell is running.

The gtk2 version closed it without a prompt, as expected. The gtk3 always prompts.

**Comment by aichingm** [comment]
Just tested it with current HEAD doesn't happen anymore/for me. Can you confirm?

**Comment by aichingm** [comment]
Can't reproduce and from reviewing the code this should work fine. **If not please just reopen :wink:**

**Comment by egmontkob** [comment]
Now it's the other way around, it never warns me (not even if I set "Prompt on close tab: Always" and a process is running.) Right clicking on the tab label and choosing "Close" immediately closes the tab. (@ ebf97fac)

I'm not offered the possibility to reopen.
