### ISSUE TITLE
[gtk3] Unfullscreen also sends F11

### ISSUE THREAD

**Issue by egmontkob** [Guake/guake#1100]
Execute `cat`.

Press F11. The terminal goes fullscreen, and nothing appears at `cat`, as expected.

Press F11 again. The terminal restores its original size, and additionally, `^[[23~` also appears at `cat`, that is, the F11 keystroke was delivered to VTE as well.

**Comment by thomasave** [comment]
The same is true for F24 for loosing focus and F25 for gaining focus of the Guake window.
This is especially annoying when working with vim in insert mode.

**Comment by egmontkob** [comment]
I can no longer reproduce it. Has it been fixed explilcitly? Or accidentally? :)

**Comment by gsemet** [comment]
accidently?

**Comment by egmontkob** [comment]
According to `git bisect`, it was fixed by commit 69ae4fe8. No freakin' idea how :-D

**Comment by egmontkob** [comment]
Actually, before that change unfullscreening raised an error about a missing argument (fixed in that change), where I guess the entire handler of the keypress bailed out, making GTK or VTE think the event wasn't properly handled and so handled it itself. Makes sense.
