### ISSUE TITLE
[gtk3] Conflicting default shortcut of Ctrl+F2

### ISSUE THREAD

**Issue by egmontkob** [Guake/guake#1101]
Ctrl+F1 to Ctrl+F10 are the default shortcuts for switching to tab 1 to 10. However, Ctrl+F2 is also the default shortcut for Rename Tab, and this latter one seems to override the former.

**Comment by aichingm** [comment]
@Stibbons  What do you think about Ctrl+Shift+R as new shortcut for "Rename Tab"? 
(I can implement and test)

**Comment by Stibbons** [comment]
perfect !
