### ISSUE TITLE
Wiki missing instruction

### ISSUE THREAD

**Issue by kitingChris** [Guake/guake#1103]
Execute the following command**s** to bootstrap all needed system dependencies:

> $ ./bootstrap-debian.sh
> $ ./bootstrap-pip.sh

Had tried without pip and got several errors during make install

**Comment by Stibbons** [comment]
which errors?

**Comment by kitingChris** [comment]
pipenv not available; pip not installed. That type of errors. Was a fresh system with no full python installed ;)

**Comment by Stibbons** [comment]
you need to install packages in ./bootstrap-debian.sh so that python3-pip should be installed. You may have to do 
```
python3 -m ensurepip --upgrade
```
https://docs.python.org/3/library/ensurepip.html

**Comment by kitingChris** [comment]
So the bootstrap-debian.sh should have installled python3-pip? Mh looked for me like it didnt but its now hard to comprehend afterwards. If only bootstrap-debian.sh should be necessary then this issue is needless.
