### ISSUE TITLE
[gtk3] Manual installation gets confused by python version

### ISSUE THREAD

**Issue by egmontkob** [Guake/guake#1104]
Trying to manually install from current git, on Ubuntu Artful with python3 being 3.6:

    $ make
    [...]
    $ sudo make install
    [...]
    Copying Guake.egg-info to /usr/local/lib/python3.6/dist-packages/Guake-3.0.3.dev6.egg-info
    running install_scripts
    Installing guake script to /usr/local/bin
    Error opening directory “/usr/local/lib/python3.5/dist-packages/guake/data/”: No such file or directory
    Makefile:35: recipe for target 'install-system' failed
    make: *** [install-system] Error 1

After manually creating the aforementioned missing directory as root (containing `3.5` in its name), and re-running `sudo make install`, it completes successfully. The manually created `3.5` directory remains empty, whereas its `3.6` counterpart is populated with precious content.

**Comment by egmontkob** [comment]
On a somewhat related note, just recently you added this to `README.rst`:

    First, be sure to use Python 3.5. For instance under Ubuntu 17.04, PyGtk and ``python3-gi`` does not
    work well if the default python 3 interpreter is forced to Python 3.6.

17.04 is beyond its EOL. 17.10 no longer ships python 3.5 (it ships 3.6 and 3.7-alpha), and so will 18.04 LTS. The same goes for Debian Testing.

Given that we're currently "rushing" for 18.04 LTS not to drop its Guake package, I don't think you're taking the right approach here. IMO whatever that "does not work well" is, it should be fixed / worked around to work seamlesslly.

**Comment by Stibbons** [comment]
hello. I understand. I have people that complains that guake does not work on python 3.6 because gtk does not (ubuntu <17.04). 

The version is fixed by the Pipfile, you can try to unleash it so your virtualenv will be created in python 3.6 if it is the default version (and if gtk works in it).
The code itself is compatible python 3.5+ (look at the `.travis.yml` file). The limiting factor is gtk

**Comment by Stibbons** [comment]
Can you look at #1106 if it works for you?

**Comment by egmontkob** [comment]
Installing worked fine from the current dev/gsemet branch, if that's what you mean :) Thanks!

The prefs dialog looks much nicer... adwaita-dark is hurting my eyes big time, I hope it'll be behind some settings and the user's default theme used by default :-)

**Comment by Stibbons** [comment]
Yes of course the theme will be configurable :)
