### ISSUE TITLE
[gtk3] Guake window is open upon startup

### ISSUE THREAD

**Issue by kenny-wettlaufer** [Guake/guake#1113]
Am I missing something in the new settings window? I have a PC that runs ProjectM Visualizers & the guake terminal opens up overtop of it. I've switched back to guake-gtk2 for now. 
Sorry if this seems tedious or if I missed something but I can't have guake opening up ontop of projectM, really nice to see Guake move to gtk3!

**Comment by Stibbons** [comment]
you mean guake does not open on top of ProjectM ? is it https://github.com/projectM-visualizer/projectm ? Is there other GTK3 application than can goes on top of it?

**Comment by trinaldi** [comment]
I've also set guake to open on startup. When GNOME opens, Guake starts "maximized" (toggled on).

**Comment by MeissnerEffect** [comment]
I have the same problem.

**Comment by Stibbons** [comment]
fixed on HEAD
