### ISSUE TITLE
Where's the settings ?

### ISSUE THREAD

**Issue by stehgold** [Guake/guake#1117]
Hi,
don't you love when updates break things...

I had green text on a black background now it's white on black. I want green on black but where are the settings ? Right-click doesn't help and looking for guake-preferences shows nothing.

What happened to "Don't fix if it's not broken" ?

**Comment by Stibbons** [comment]
please execute the following command in your system:
```
sudo apt get uninstall guake
```
this will not break anything important, do not worry. Just don't update or even use guake if you do not like it.

And if it is to say that there is not more "Guake Preferences" link in the app menu, just open a ticket saying "No more preference link in desktop".

**Comment by Stibbons** [comment]
Gnome 3 under ubuntu 17.10 does not seem to like `X-GNOME-PersonalSettings` anymore

**Comment by desbma** [comment]
I lost all my config too when updading from 0.8.12 to 3.0.2.

I reverted back to 0.8.12 and all is working fine again.

I'm on Arch Linux and I use the [official package](https://www.archlinux.org/packages/community/any/guake/).

**Comment by Stibbons** [comment]
normally guake 0.8 already supported gsettings. But you can easily rebuild your configuration with the preference panel.

**Comment by desbma** [comment]
You mean there is now way to import the 0.8.x config without setting everything manually again in the GUI of 3.0.x version?

**Comment by Stibbons** [comment]
is it such a big deal?

**Comment by desbma** [comment]
Guake is free software so I can't complain. But it is annoying enough so that I would clearly consider it a bug though.
Isn't it possible to just automatically migrate between the old and new settings storage format like most software do?

**Comment by Stibbons** [comment]
normaly the format hasn't changed, we switched to dconf some releases ago so the update should work. If it isn't, i guess it is either the package that performs a dconf -reset /apps/guake, or you used, indirectly `make reset` target. But it is not a "main" feature to ensure the config stay between 0.8 and 3.0, given the huge among of internal reworks we've done last month

**Comment by es02** [comment]
Okay, so prefs vanish due to the move form gconf to dconf, that's fine - irritating, but fine.
The problem is there does not seem to be a way to _change_ the current settings like there was previously (guake-preferences).

What is the expected way of modifying the preferences for guake 3.x?

**Comment by Scimmia22** [comment]
You're probably confused because of https://github.com/Guake/guake/commit/6992344667aa0dbac145725d89cac445983814ab#diff-39f8b7caa8c9b7050798d9834c0311d1

"OnlyShowIn=GNOME;"

**Comment by es02** [comment]
Yeah, thats a suitably daft change.
No wonder it appears broken.

**Comment by Stibbons** [comment]
If someone can do the pr to add the link for pref i will accept it. But Ubuntu has changed and will probably change again (gnome as well?).
You can still do guake -p anyway

**Comment by lalilulelost** [comment]
Just ended up here from Google, so I'm leaving this for anyone else coming from a search:

If you can't find guake-prefs, running `guake -p` should open the preferences window.
