### ISSUE TITLE
"Open in browser" menu option

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#113]
"Open in browser" menu option  http://guake.org/ticket/368
Reported by:    iElectric   Owned by:   somebody
Priority:   minor   Milestone:  0.5.0
Component:  guake   Version:    0.4.2
Keywords:       Cc:  
Description

I miss the option from gnome-terminal, saves quite some time.

**Comment by Stibbons** [comment]
Feature implemented in 0.8. Broken in 3.0 for the moment
