### ISSUE TITLE
[gtk3] Inconsistent upper/lowercase shortcuts, and Primary vs. Control

### ISSUE THREAD

**Issue by egmontkob** [Guake/guake#1138]
Default shortcuts go like

    <Control><Shift>q – lowercase q
    <Control><Shift>R – uppercase R
    <Control>minus – lowercase m
    <Control>Down – uppercase D
etc.

They are shown on the UI exactly as present in org.guake.gschema.xml, should be trivial to clean up.

I'd say the desired form is what happens when the user sets these keys graphically, but hey, stupid GTK+ then calls `<Control>` as `<Primary>` instead, I don't know if it's possible (and if, how) to change it to a user-friendly name. I mean, who the heck knows what Primary is? Why is GTK+ so silly??

Terminator shows them in more user-friendly way. E.g. what's shown as `<Primary><Shift>t` in Guake is shown as `Shift+Ctrl+T` in Terminator, after the user has pressed this as the new shortcut. Maybe take a look what Terminator does differently?

(Pretty low priority compared to the modifiers not being shown up to just a few minutes ago :-))

**Comment by Stibbons** [comment]
yes it is pretty easy to do, i'll see if i can rework that later

**Comment by aichingm** [comment]
Also `<Control>minus` `<Control>equals` looks wired to my eyes 😆 
![screenshot_20180122_003306](https://user-images.githubusercontent.com/6470959/35200306-d141a51c-ff0b-11e7-8e8d-6bc1ebb480f3.png)

From the UI perspective `Ctrl+Shift+=` look much cleaner than `<Control><Shift>equals`. But anyways as egmontkob said this is also very unimportant to me.

**Comment by egmontkob** [comment]
Looks like this is implemented now on master :)

**Comment by Stibbons** [comment]
:)
