### ISSUE TITLE
Feature Request: Save Sessions

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#114]
Feature Request: Save Sessions  http://guake.org/ticket/367
Reported by:    huahaiy     Owned by:   somebody
Priority:   major   Milestone:  0.5.0
Component:  guake   Version:  
Keywords:       Cc:  
Description

I use guake at work as my main terminal and use KDE at home. One feature from konsole that I miss in guake is being able to save the session state, so that all my previously opened and named tabs are restored when I restart guake.

**Comment by cirosantilli** [comment]
+1. I'd also like to automatically save and reopen the seesion, as asked at: http://askubuntu.com/questions/98754/maintain-terminal-session-after-reboot

**Comment by Suor** [comment]
+1 would be very nice to have.

**Comment by MbarekFiras** [comment]
+1

**Comment by calvinwankhede** [comment]
+1

**Comment by Phiwa** [comment]
+1

**Comment by byted** [comment]
+1

**Comment by kodedyret** [comment]
+1

**Comment by puregardenia** [comment]
I install the application by compile the source file, and It can't get the status and config before restart the system. most important, It can't get the CONFIG! when I restart the system, It like a new application just now. Anybody know the problems

**Comment by puregardenia** [comment]
I got the solution [#788](https://github.com/Guake/guake/issues/788)

**Comment by DareDevil73** [comment]
+1

**Comment by zasca** [comment]
+1

**Comment by avrilfanomar** [comment]
+1

**Comment by kecalcze** [comment]
+1

**Comment by fabriciogpp** [comment]
+1

**Comment by linxon** [comment]
+1

**Comment by gaursagar** [comment]
+1

**Comment by FedeG** [comment]
+1

**Comment by knochenhans** [comment]
+1

**Comment by avrilfanomarremit** [comment]
I've got a solution: I didn't reboot for a month. Works perfectly ;)

**Comment by AndrewEastwood** [comment]
LOL

**Comment by arturespl** [comment]
+1

**Comment by imranashraf** [comment]
+1

**Comment by frederiksnijder** [comment]
+10

**Comment by kusha** [comment]
+1

**Comment by frederik-labbe** [comment]
+9000

**Comment by curtisz** [comment]
@gsemet With this last **0.8.11** milestone removed, what's the plan for this feature request?

**Comment by gsemet** [comment]
I need this feature myself, so... patience ! :)

**Comment by nbozeman** [comment]
Let's do it! +1

**Comment by rsansores** [comment]
hahah feature request from 2013!!!

bump +1

**Comment by gsemet** [comment]
Hi guys. Yes 6 years has passed, indeed, but I did not saw any contribution from your part on this request. So, I understand this feature would be cool to have, and now the big rework is done, it would actually be quite trivial to do.
However, life is life, I do not have time to work on it for the moment. I barely have time to maintain the code, do the review of volunteers that try to improve Guake instead of just complaining on issues, and merge and do some releases from time to time.

So, if you really want this feature to land in Guake, just open your favorite code editor, Visual Studio code is a marvel nowdays, but vim or Pycharm users are also welcomed. I would be delighted to do your review.

Sorry guys, but I have some diapers to change and other maintainance work to do 😭🍼👶.
This is the kind of release you do not want to miss!

**Comment by AndrewEastwood** [comment]
looks like a plan. just need a bit of python knowledge :)

**Comment by drNoob13** [comment]
> Sorry guys, but I have some diapers to change and other maintainance work to do sobbaby_bottlebaby.
This is the kind of release you do not want to miss!
Absolutely reasonable. The diaper exchange should be your first priority. This kind of rolling release is time-consuming. :)

I am thinking about writing a script to automate many ROS (Robot Operating System) script execution in a robot client and a host PC based on Guarke.

**Comment by gsemet** [comment]
tmux is a good replacement until Guake has this feature :)

**Comment by AndrewEastwood** [comment]
... but it less convenient

**Comment by mlouielu** [comment]
This should be done by #1515 & #1528

**Comment by hazaeluz** [comment]
Is this merge on Master comming officially on next version? or should I just go ahead and get the code/compile and install myself?

**Comment by mlouielu** [comment]
This feature is published since 3.6.0 and add terminal split save/restore
in #1580 (not publish in tag yet, but on master)

You can build it by yourself from code, or take a try on `python -m pip
install guake --upgrade`



hazaeluz <notifications@github.com> 於 2019年5月8日 週三 22:55 寫道：
