### ISSUE TITLE
[gtk3] Slow to open

### ISSUE THREAD

**Issue by FallingSnow** [Guake/guake#1145]
Version: 3.0.3
System: Arch Linux w/ GNOME Shell 3.26.2 on Wayland

Opening guake via a global hot key (that calls `guake -t`) registered with gnome is much slower at opening than pre 3.0 guake. Same thing when right clicking guake and opening preferences, there is a 300-500ms delay before guake hides and the preferences are opened.

As I said, on guake 2.x this delay did not exist.

P.S. Is there a way to disable the opening animation so that the delay is less noticeable.

**Comment by egmontkob** [comment]
Really nice speedup! :-)

**Comment by Stibbons** [comment]
Hum, I guess you did that because the global hotkey through the pref window does not work on Wayland, is it? i have done some improvement on head ?

**Comment by FallingSnow** [comment]
> Hum, I guess you did that because the global hotkey through the pref window does not work on Wayland, is it?

Yes

>  have done some improvement on head, you can give a try

Much faster, thank you.

**Comment by FallingSnow** [comment]
Seems to have slowed down again.

**Comment by vlow** [comment]
Opening / closing guake by using `guake -t` is still pretty slow for me (~500ms on a fast machine). I already disabled all animations in Gnome but that does not seem to do the trick. Any way I can make it faster?

Here is my support info:
```
❯ guake --support
<details><summary>$ guake --support</summary>

Guake Version:		3.7.0

Vte Version:		0.70.2

Vte Runtime Version:	0.70.2

--------------------------------------------------
GTK+ Version:		3.24.35

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: gnome

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 -  XWAYLAND0
    * Geometry:		3840 x 2160 at 0, 0
    * Size:		940 x 530 mm²
    * Primary:		True
    * Refresh rate:	59.98 Hz
    * Subpixel layout:	unknown
```

**Comment by Davidy22** [comment]
Use guake-toggle over guake -t, the main guake program includes some amount of imports will eventually be unused if you only want to toggle.

**Comment by vlow** [comment]
Thanks for that, it's notably faster using `guake -t`.
