### ISSUE TITLE
Prefs window jumps on resize

### ISSUE THREAD

**Issue by egmontkob** [Guake/guake#1149]
Resize the prefs window.

On gnome-shell + X11 it starts moving upwards.

On unity7 + X11 it crazily jumps between two different positions.

(I couldn't test with Wayland as Guake segfaults for me on startup, is that a known issue?)

I have absolutely no idea what could cause this kind of jumping. (An easy workaround might be to make the prefs dialog non-resizeable.)

**Comment by Stibbons** [comment]
not reproduce, only thing on ubuntu is the top title part is resized

**Comment by aichingm** [comment]
no jumping here

**Comment by egmontkob** [comment]
The behavior is apparently somehow triggered by the `window_position` property being set to `center-always` in prefs.glade (along with the window being resizable). Setitng it to `center` fixes it in both desktop environment where I've encountered the problem: the prefs window is centered initially, but later you can move/resize as you wish.

Apparently `center-always` doesn't work well with a resizable window. The window manager wants to resize it at one corner, leaving the opposite corner in place. The window wants to keep re-centering itself, resulting in the opposite corner moving too. These two contradict each other, and that fight somehow results in the crazy behavior.

**Comment by gsemet** [comment]
Ho, can you submit a pull request?

**Comment by egmontkob** [comment]
Just replace `center-always` with `center`, and/or make the window non-resizable. Any of these should be fine. Thanks!

**Comment by aichingm** [comment]
@egmontkob does this still happen?

**Comment by egmontkob** [comment]
Yes (@ ebf97fac)
