### ISSUE TITLE
Can't make Guake invisible with option 'Hide on lose focus'

### ISSUE THREAD

**Issue by MikauSchekzen** [Guake/guake#1150]
I just updated Guake to 3.0.3, and now I can no longer hide Guake with the 'Toggle Guake visibility' shortcut. When I press it, it seems to be hiding, but then immediately opens again. It hides when I alt-tab out of it like normal, though.

I tried it as Ctrl-Shift-C and F12, and it happens in both cases. It doesn't happen if the 'Hide on lose focus' option is unchecked, and it didn't happen before I updated Guake (I think I was using 3.0.1 before, but I'm not sure, and I'm not sure if I can still check that) with 'Hide on lose focus' checked.

I applied the update with Antergos' package manager tray application (pamac 6.2.2-1, according to its about screen).

OS: Antergos
DE: XFCE 4.12
Guake version: 3.0.3

**Comment by Stibbons** [comment]
Indeed i reproduced the issue
