### ISSUE TITLE
guake --hide and guake --show don't work correctly

### ISSUE THREAD

**Issue by epsilon77** [Guake/guake#1154]
Hi!

Version: 3.0.2

"guake --hide" actually shows the terminal, while "guake --show" hides it.   The --toggle-visibility option doesn't work either

For more info: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=888093

Regards!

**Comment by aichingm** [comment]
@epsilon77 Can you test on HEAD? This should be fixed by #1123

**Comment by Stibbons** [comment]
fixed on head

**Comment by barak** [comment]
Seems fixed in 3.0.3
