### ISSUE TITLE
Scroll back settings not considered

### ISSUE THREAD

**Issue by epsilon77** [Guake/guake#1155]
Hi

Version: 3.0.2

The 'scrollback' settings are not "working". No matters what I set in scrollback section in guake preference (0, for unlimited scrollback, or any other number) long outputs are not shown completely

For more info: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=888069

Regards

**Comment by Stibbons** [comment]
indeed, I have fixed it on HEAD
