### ISSUE TITLE
Quick open on selection

### ISSUE THREAD

**Issue by gsemet** [Guake/guake#1157]
As a User, when I select a file path in my terminal, I expect the right click menu to display a new item "Open file", that behaves like Quick Open.

**Comment by egmontkob** [comment]
While at it, please also take a look at #945. Should be pretty easy for you (take care to have vte >= 0.50 as condition for calling the API), try out with e.g. `ls --hyperlink` from coreutils-8.28.

**Comment by Stibbons** [comment]
hum, I don't have this need for the moment, I am on the quick open enhancement now :) 
Even my `ls` does not have the `--hyperlink` option :)
