### ISSUE TITLE
F12 hotkey could not disappear window

### ISSUE THREAD

**Issue by jrjang** [Guake/guake#1158]
F12 works fine to appear the window, but could not disappear when pressing F12 again. If pressing ctrl+F1, the window will disappear.

**Comment by Stibbons** [comment]
it does not disappear after a few seconds?

**Comment by jrjang** [comment]
The window indeed disappear when pressing F12, but appear again quickly. That is the window will disappear and appear quickly after pressing F12.

**Comment by leoleotte** [comment]
The window now disappears and reappears immediately when pressing F12 with the terminal open, if you keep holding the key it eventually disappears for good but it's really annoying.

**Comment by Stibbons** [comment]
Are you under wayland ? On HEAD their should have the logic to avoid
immediat redisplay if libkeybinder returns lot of events
-- 
-----
Gaetan

**Comment by AqqalukS** [comment]
I have the same problem, did you found a solution? It worked before the update.

**Comment by Stibbons** [comment]
can you try with HEAD? I have fixed this issue but not released yet

**Comment by jrjang** [comment]
Using HEAD (7fb39459c9dd) works fine for F12 hotkey.

Thanks.
