### ISSUE TITLE
Guake 3 does not follow system theme

### ISSUE THREAD

**Issue by Confucij** [Guake/guake#1159]
I have light shell theme installed and all application within system follows it, but today Guake updates to 3.0.3 (Arch Linux) and it uses the dark theme which looks ugly in light environment. 
![screenshot from 2018-01-24 15-47-41](https://user-images.githubusercontent.com/941997/35335321-ecd27432-011d-11e8-994d-6a5481c69dc0.png)

![screenshot from 2018-01-24 15-46-42](https://user-images.githubusercontent.com/941997/35335303-dd33817e-011d-11e8-8378-ef84dc4d57af.png)

is it only me and there is some setting to overcome this or this is a bug?

**Comment by Stibbons** [comment]
yes, if the Numix or Adwaita theme is found it applies it directly. My mistake. I need to write the logic to let user select its theme. You can edit `guake/guake_app.py` function `_select_gtk_theme` to disable it temporarily.
I agree I should have put a feature gate on that

**Comment by Confucij** [comment]
Thank you! Fixed by commenting!

**Comment by Stibbons** [comment]
and fixed on HEAD :)
