### ISSUE TITLE
shortcut for toggling transparency

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#117]
shortcut for toggling transparency  http://guake.org/ticket/361
Reported by: 	snegawik 	Owned by: 	somebody
Priority: 	trivial 	Milestone: 	
Component: 	guake 	Version: 	
Keywords: 		Cc: 	bostonvaulter
Description

hey, it would be great if it would be possbible to toggle transparency by a shortcut, so I could toggle between 0% and the set value in the preferences(e.g.70%).

**Comment by rvraghav93** [comment]
I really need this feature and am willing to help add this feature... Could someone help me in getting started?

**Comment by Stibbons** [comment]
you can hack the code, look for an existing shortcut and add your new one just aside of it :)

**Comment by thardev** [comment]
Hello @Stibbons this is not already implemented yet?
![transparency](https://cloud.githubusercontent.com/assets/8918134/10717319/5e8c20ac-7b54-11e5-9de8-72638ba37f51.png)

**Comment by Stibbons** [comment]
indeed!

**Comment by rvraghav93** [comment]
That does an incremental transparency change not a toggle right?

**Comment by thardev** [comment]
Hello @rvraghav93!
Yeah, you are right, I understood this the wrong way, I'll work on it and in my next pull request it will be implemented :smile:

**Comment by rvraghav93** [comment]
@thardev That would be awesome.. Thanks!

**Comment by thardev** [comment]
Hello @rvraghav93 
I'm working on this but the way to implement it is not really clear for me, when you toggle the transparency it should be at its highest level (100%) and then when you toggle it again it should return to previous state? Is that the way?

**Comment by rvraghav93** [comment]
Yes that is what xterm (in mac) does it IIRC... Thanks heaps for working on this!

**Comment by jep-dev** [comment]
I'm used to the behavior in Tilda and the transparency toggle seems a little odd to me here. When transparency is enabled at 30%, and you toggle it, why wouldn't the window be opaque? This seems to toggle opacity, not transparency. I normally keep the window around 30%, so I can read the window beneath an area of whitespace, but still read the text in the editor (at least over native windows and websites in night mode.) If your current theme is light-on-dark, 100% transparency makes everything in the terminal essentially unreadable, so you're better off toggling visibility instead. My current workaround is to increase/decrease the window transparency each time. Are there any plans to add configuration other than bgcolor/fgcolor to the command line arguments, or is there any way I could accomplish this another way?

**Comment by Stibbons** [comment]
From what i see, toggle transparence does not work

**Comment by Stibbons** [comment]
Restest again, work as expected. Toggle transparency toggles between user defined transparency and no transparency

**Comment by jep-dev** [comment]
Ah, I was on the apt version when I thought I was on the repo. Thanks, looks fine!
