### ISSUE TITLE
Preferences window launcher on none Gnome systems

### ISSUE THREAD

**Issue by aichingm** [Guake/guake#1170]
This line disables the Preferences launcher for all none Gnone systems:
https://github.com/Guake/guake/blob/93099961f7c90a22089b76a8a9acf1414bea56e5/guake/data/guake-prefs.template.desktop#L10

Is there a reason for this?

Can it be removed? Or should we add an separate one for none Gnone systems? With something like: `NotShowIn=GNOME` in it?

**Comment by Stibbons** [comment]
can you try removing it? I actually added it in an attempt to restore it, but in either case it does not work :(
ubuntu 17.10 and up disallow custom setting in system panel :(
