### ISSUE TITLE
Stay on top setting broken

### ISSUE THREAD

**Issue by FallingSnow** [Guake/guake#1171]
Version: 3.0.4

Using Wayland with Gnome, so that might be connected to the issue.

![screenshot from 2018-01-25 15-27-33](https://user-images.githubusercontent.com/2512197/35417933-62cec17e-01e4-11e8-8d08-fa5e6962a1b4.png)

**Comment by Stibbons** [comment]
i do not have wayland to test it :(

**Comment by seghers** [comment]
I'm still experiencing this bug on Fedora 30 (Gnome 3.32.2).
Does anyone have a quick fix or is it related to 
https://github.com/Guake/guake/issues/1343


off-topic: I'd like to thank everyone involved in this great piece of software. I've used it every day for the past few years.

**Comment by mlouielu** [comment]
Hi, what version of the guake are you using? Are you using x11 or Wayland?

Thanks

seghers <notifications@github.com> 於 2019年10月18日 週五 17:11 寫道：

**Comment by seghers** [comment]
@mlouielu 
Guake Version: 3.6.3
Wayland

**Comment by mlouielu** [comment]
Is a Wayland issue, Wayland didn't allow any window to be set on top.

**Comment by vasilakisfil** [comment]
I am not on wayland and have this issue, but running Guake Terminal 3.0.5 (from Ubuntu repo) on 18.04. I ll try to compile from source now.

**Comment by michaelarnauts** [comment]
@mlouielu

I've just switched from X11 to Wayland, and this issue appeared. When I set a nautilus window on top, it works fine, so Wayland does support putting windows on top.

**Comment by mlouielu** [comment]
> @mlouielu
> 
> I've just switched from X11 to Wayland, and this issue appeared. When I set a nautilus window on top, it works fine, so Wayland does support putting windows on top.

Yes, due to the security issue (Window override on other is bad), and design concept (Wayland support 3D desktop... so you cannot tell which is on top :p) that Wayland team concern, it didn't support this.

**Comment by ajoy39** [comment]
This seems to be resolved, at least for me. On Ubuntu 21.10 using Wayland and Guake 3.8 (official ubuntu repo only has up to 3.6 so those still experiencing this try using the LinuxUprising repo).

**Comment by FallingSnow** [comment]
This seems to be working for me now on
```
Guake Terminal: 3.8.6.dev0
VTE: 0.66.2
VTE runtime: 0.66.2
Gtk: 3.24.31
```
