### ISSUE TITLE
Scrolling on tab bar to switch tabs doesn't work anymore

### ISSUE THREAD

**Issue by timawesomeness** [Guake/guake#1177]
The update to GTK3 seems to have removed it

**Comment by Stibbons** [comment]
using the mouse wheel ?

**Comment by timawesomeness** [comment]
Yeah. It worked in 0.8.x/GTK2 versions.

**Comment by Stibbons** [comment]
ok. Set as bug for 3.0.5

**Comment by egmontkob** [comment]
FYI: See https://git.gnome.org/browse/gnome-terminal/tree/src/terminal-notebook.c?h=3.26.2#n374.

According to that command, gtk3 removed mouse wheel scrolling on notebook tabs, and gnome-terminal decided to bring it back.
