### ISSUE TITLE
Tab panel ignores system dark theme (gtk-3.18)

### ISSUE THREAD

**Issue by cyl1zard** [Guake/guake#1179]
After update guake from 0.x to 3.x tab panel ignores the system dark theme and now is always white, doesn't matter which theme I use.
Before: https://i.imgur.com/o4id6Ch.png
After: https://i.imgur.com/1B1ITSh.png
OS: ArchLinux 
Awesome WM + gtk 3.18

**Comment by Stibbons** [comment]
yes. Dark theme is supported in HEAD and 3.0.4 but you need to edit the dconf manually (no UI for theme selection).
Closes as fixed in HEAD (Still need to add the UI in preference panel)

**Comment by gsemet** [comment]
that's weird, I have the oposite now on guake 3.2.0. Tab is always dark, can someone reproduce?
