### ISSUE TITLE
Preferences panel is invisible

### ISSUE THREAD

**Issue by GijsGoudzwaard** [Guake/guake#1182]
Version 3.0.5.
Elementary OS Loki 0.4

**Comment by GijsGoudzwaard** [comment]
When using expose windows it does show that the preferences panel is there, just not visible.

**Comment by Davidy22** [comment]
Does this still occur for you in latest git master? If you can't compile, we'll soon have a release out via pypi as well.

**Comment by Davidy22** [comment]
Since this report is for older versions and there's no chance of reproducing anymore, closing.
