### ISSUE TITLE
Cannot change scheme from preferences -> appearance

### ISSUE THREAD

**Issue by aj326** [Guake/guake#1183]
I cannot pick a scheme at all. When I click on the drop-down menu, nothing happens
![screenshot from 2018-02-01 04-50-31](https://user-images.githubusercontent.com/5359836/35674808-7b90e468-070b-11e8-9f44-d1698e71c163.png)

More info this behavior has been happening before and after using https://github.com/ziyenano/Guake-Color-Schemes

**Comment by gsemet** [comment]
Should not be related to this tool, we do not use gconf anymore since some time. Can you reset the dconf setting (`dconf -reset /apps/guake`) and see if it still fail?

**Comment by egmontkob** [comment]
"When I click on the drop-down menu, nothing happens" – Do you mean the menu with the more than 100 entries doesn't even open?

**Comment by aj326** [comment]
The "Built-in schemes" menu, yes.

**Comment by aj326** [comment]
@gsemet , when do a dconf reset, nothing changes

**Comment by siliconmeadow** [comment]
I've been having the same problem on one of my machines. When I click on the menu it's slightly darker as if it's about to display the menu, but nothing happens. Clicking on it again puts it into the initial state.

I dug a bit deeper and found the names of the themes here:
https://github.com/Guake/guake/blob/3.0.4/guake/palettes.py
and then used dconf editor to change the custom value in /apps/guake/style/font/palette-name to Solarized Dark Higher Contrast.

Not ideal, but satisfying that I found a way around it and learned a bit more about how it works. :-)

![image](https://user-images.githubusercontent.com/158008/35718345-f9af8612-07db-11e8-9653-ed74da1d5d62.png)

**Comment by gsemet** [comment]
so if somehow the value is incorrect in this setting, the user cannot change it again. that's a bug to fix :) thanks for the analysis

**Comment by siliconmeadow** [comment]
Even **after** correcting it with dconf editor to an official value in `pallets.py`, the user cannot change to another item in the 'Built-in schemes' menu in the Guake preferences dialog.

**Comment by gsemet** [comment]
dconf reset -f /apps/guake
 does not even fix it?

**Comment by egmontkob** [comment]
Should be `dconf reset -f /apps/guake/`. Without the trailing slash this command does nothing.

**Comment by egmontkob** [comment]
Under `/apps/guake/style/font` there's a `palette` and a `palette-name` field. I'm wondering what happens if these two are out of sync.

**Comment by aj326** [comment]
Developments! @egmontkob, it sort of works! If I select the dropdown menu, and use my arrow keys on my keyboard, or the mouse wheel, I can change the scheme!
(I wonder if I caould have done this before resetting the dconf database for guake! I have a feeling I could have done that without the reset ... whoops! The dropdown menu still doesn't drop though, so I am thinking this is a bug

**Comment by aj326** [comment]
@egmontkob, also, I am using linux. running `locate palette | grep guake` spits out many files. Two of them are interesting:
`/usr/lib/python3.6/site-packages/guake/palettes.py`
`/home/aj/.local/share/virtualenvs/aj-DZYqhgLn/lib/python3.6/site-packages/guake/palettes.py`
those files basically list the different palletes' names and associated design code, as such
`PALETTES = {
    '3024 Day': (
        '#090903030000:#DBDB2D2D2020:#0101A2A25252:#FDFDEDED0202:#0101A0A0E4E4:'
        '#A1A16A6A9494:#B5B5E4E4F4F4:#A5A5A2A2A2A2:#5C5C58585555:#E8E8BBBBD0D0:'
        '#3A3A34343232:#4A4A45454343:#80807D7D7C7C:#D6D6D5D5D4D4:#CDCDABAB5353:'
        '#F7F7F7F7F7F7:#4A4A45454343:#F7F7F7F7F7F7'
    ),
....
}.`
Which file in linux actually sets the scheme (or palette)?

**Comment by egmontkob** [comment]
> The drop-down menu still doesn't drop though, so I am thinking this is a bug

Sounds to me like an issue with GTK+ or the desktop environment, perhaps related to the menu being way taller than what fits in the screen, and hence requires scrolling.

**Comment by aj326** [comment]
@egmontkob, any ideas on how to fix my GTK+?

**Comment by roachsinai** [comment]
Same issue on Manjaro17.1.7 :-(((

**Comment by gsemet** [comment]
can you update and use 3.0.5 ?

**Comment by roachsinai** [comment]
Oh, sorry,  my version is 3.0.4. Will check it after the upgrade.

**Comment by gsemet** [comment]
Do you have the latest version?
