### ISSUE TITLE
Nothing happens when I click on Search on web or Open link from the right-click context menu when I select a url/text

### ISSUE THREAD

**Issue by aj326** [Guake/guake#1184]
GNOME Shell 3.26.2, Arch Linux.

**Comment by gsemet** [comment]
Which version? Have you tried with HEAD?

**Comment by aj326** [comment]
I pulled the latest HEAD. Opening URLs works. Searching the web doesn't work

**Comment by gsemet** [comment]
Should work on 3.2.0
