### ISSUE TITLE
Closing a tab hangs guake

### ISSUE THREAD

**Issue by michaelarnauts** [Guake/guake#1186]
Looks like the same as #551 

I'm running on the latest master branch, when closing a tab by typing exit or CTRL+D, I notice the following output (in the terminal that started guake):

```
Terminal exited: <terminal.GuakeTerminal object at 0x7f1e5d17b090 (guake+terminal+GuakeTerminal at 0x2e61870)>
```

When I try to close the tab manually by right clickiing and picking close in the popup menu, the following exception is thrown.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/guake/guake_app.py", line 1576, in close_tab
    self.delete_tab(pagepos)
  File "/usr/local/lib/python3.6/dist-packages/guake/guake_app.py", line 1920, in delete_tab
    procs = self.notebook.get_running_fg_processes_tab(pagepos)
  File "/usr/local/lib/python3.6/dist-packages/guake/guake_notebook.py", line 75, in get_running_fg_processes_tab
    fdpty = terminal.get_pty().get_fd()
AttributeError: 'NoneType' object has no attribute 'get_fd'
```

I'm running on Ubuntu 17.10.

**Comment by gsemet** [comment]
should be fixed in head

**Comment by michaelarnauts** [comment]
> I'm running on the latest master branch...

That's the code I've tested.

**Comment by robert-alfaro** [comment]
I have the same issue with Guake 3.0.5 on Ubuntu 18.04.

**Comment by gsemet** [comment]
Can you try with HEAD?
