### ISSUE TITLE
'Refocus if open' not working on Manjaro gnome

### ISSUE THREAD

**Issue by GijsGoudzwaard** [Guake/guake#1188]
The 'Refocus if open' option is enabled but when I unfocus guake and then toggle guake through the bound keyboard shortcut it hides instead of refocussing.

I'm on gnome 3.26.2 with Manjaro 17.1.4
Guake is on version 3.0.4

**Comment by dwuttke90** [comment]
same for arch with kde.
seems like it doesnt reveive any window state events when loosing focus.

**Comment by chrisandrewcl** [comment]
This is also not working for me on Ubuntu 17.10.

Some more information: the first work

**Comment by gsemet** [comment]
can you open a pull request with your change? seems valid to me
