### ISSUE TITLE
3.0.4 breaks theme in the bottom bar

### ISSUE THREAD

**Issue by jonnyabu** [Guake/guake#1192]
Forgive me here - first time posting so I'll probably not submit exactly what you want.

On my two Manjaro Cinnamon systems, when Guake upgraded from 3.0.2 to 3.0.4, the bottom tab bar lost the ability to be themed with the rest of the desktop.  Instead of a dark bar it gives what I think is a standard white Gnome-looking bar, which is quite ugly (to me.)  So I reverted back to 3.0.2 and the color went back to being correct.  

I'm not sure if that's a theme issue or a Guake one but I figured I'd drop it in here since that's the only update I've done that's had that happen on me.

Below is what it looks like when it's correct:

![image](https://user-images.githubusercontent.com/36394483/36084045-c7fdf586-0f7e-11e8-949e-6822c0e05f07.png)

**Comment by egmontkob** [comment]
In #1104 it was promised that the theme would be configurable (not done yet, at least not via UI), plus I agree that it's really bad that the default isn't the desktop's default. So let me +1 this bugreport / feature request. The default should be a coherent look across the user's desktop, that is, Guake not overriding the user's (or distribution's) choice.

**Comment by gsemet** [comment]
That's weird, because by default on guake 3.0.4, it uses the default theme (on my ubuntu system, the white ugly gtk theme) and only if you overwrite the settings in dconf-editor, you can turn to use a black theme.

I guess what is missing is a way to retrieve the current gtk theme of the desktop (not the "other GTK3 apps") and apply the same theme. By default (again, on my Ubuntu), GTK3 app and gnome integrated application does not have the same theme

**Comment by egmontkob** [comment]
Unlike for OP, it's not the theme _variant_ for me. All my other GTK+ apps use Ubuntu's default Ambiance, where Guake uses GTK+'s default Adwaita (the light variant thereof). I've tried wiping out my Guake settings, as well as with another user too.

**Comment by gsemet** [comment]
yes, i think there is a detail ubuntu apps does generic gtk3 app doesn't

**Comment by egmontkob** [comment]
Not sure what you're saying. All my gtk3 apps use Ambiance, except Guake. Even simple ones like `gtk3-demo`. Guake also used Ambiance in version 3.0.0 or so. Just don't do anything theme-specific unless the user explicitly asked for, and you'll be good.

**Comment by gsemet** [comment]
I have added a new check, should fix it

**Comment by egmontkob** [comment]
Works for me, thanks (at least to the extent that I get Ambiance by default – I haven't tried setting the setting.)
