### ISSUE TITLE
Exception when launching guake

### ISSUE THREAD

**Issue by MaryAlex** [Guake/guake#1195]
Guake 3.0.4
OS: Kali GNU/Linux Rolling
GNOME: 3.26.2
python3.6 and 3.7(I've tried both)
Output is below. Help please.

ERROR:root:Error parsing
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/usr/lib/python3/dist-packages/pbr/util.py", line 249, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/usr/lib/python3/dist-packages/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/usr/lib/python3/dist-packages/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/usr/lib/python3/dist-packages/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/usr/lib/python3/dist-packages/pbr/packaging.py", line 755, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name Guake was given, but was not able to be found. error in setup command: Error parsing /root/Downloads/guake-3.0.4/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name Guake was given, but was not able to be found.

**Comment by gsemet** [comment]
did you used the .zip file? Don't. Checkout with Git or install the distribution package from pypi:
```bash
$ pip3 install --user guake
```

**Comment by MaryAlex** [comment]
Okey, thank you, I'll try it letter

**Comment by MaryAlex** [comment]
Yes, it worked. Thank you. But I don't see any of such warning in readme... But maybe it just I'm such stupid. Anyway. Thank you for help!
