### ISSUE TITLE
Gnome shell logs and journald

### ISSUE THREAD

**Issue by Deathorn** [Guake/guake#1203]
Hello. Every time I open guake, tons of logs litters my journald:

```
gnome-shell[3304]: Object Meta.WindowActor (0x558f3b8ab710), has been already finalized. Impossible to get any property from it.
org.gnome.Shell.desktop[3304]: == Stack trace for context 0x558f213d8170 ==
org.gnome.Shell.desktop[3304]: #0 0x7ffc9e3fdf10 I   resource:///org/gnome/shell/ui/tweener.js:73 (0x7fd6ac0ddef0 @ 9)
org.gnome.Shell.desktop[3304]: #1 0x7ffc9e3fdfb0 b   resource:///org/gnome/shell/ui/tweener.js:105 (0x7fd6ac0df230 @ 36)
org.gnome.Shell.desktop[3304]: #2 0x7ffc9e3fdff0 I   resource:///org/gnome/shell/ui/tweener.js:92 (0x7fd6ac0df098 @ 52)
org.gnome.Shell.desktop[3304]: #3 0x7ffc9e3fea70 I   resource:///org/gnome/gjs/modules/tweener/tweener.js:203 (0x7fd6ac0e9cd0 @ 54)
org.gnome.Shell.desktop[3304]: #4 0x7ffc9e3febc0 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:332 (0x7fd6ac0e9d58 @ 1626)
org.gnome.Shell.desktop[3304]: #5 0x7ffc9e3fec70 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:345 (0x7fd6ac0e9de0 @ 100)
org.gnome.Shell.desktop[3304]: #6 0x7ffc9e3fed00 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:360 (0x7fd6ac0e9e68 @ 10)
org.gnome.Shell.desktop[3304]: #7 0x7ffc9e3fed80 I   resource:///org/gnome/gjs/modules/signals.js:126 (0x7fd6ac0e2b38 @ 386)
org.gnome.Shell.desktop[3304]: #8 0x7ffc9e3fee30 b   resource:///org/gnome/shell/ui/tweener.js:208 (0x7fd6ac0df808 @ 159)
org.gnome.Shell.desktop[3304]: #9 0x7ffc9e3fee90 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fd6ac0c2bc0 @ 71)
org.gnome.Shell.desktop[3304]: #10 0x7ffc9e3fee90 I   resource:///org/gnome/shell/ui/tweener.js:183 (0x7fd6ac0df780 @ 20)
org.gnome.Shell.desktop[3304]: #11 0x7ffc9e3fef20 I   self-hosted:917 (0x7fd6ac0ee5e8 @ 394)
org.gnome.Shell.desktop[3304]: == Stack trace for context 0x558f213d8170 ==
org.gnome.Shell.desktop[3304]: #0 0x7ffc9e3fdf10 I   resource:///org/gnome/shell/ui/tweener.js:80 (0x7fd6ac0ddef0 @ 82)
org.gnome.Shell.desktop[3304]: #1 0x7ffc9e3fdfb0 b   resource:///org/gnome/shell/ui/tweener.js:105 (0x7fd6ac0df230 @ 36)
org.gnome.Shell.desktop[3304]: #2 0x7ffc9e3fdff0 I   resource:///org/gnome/shell/ui/tweener.js:92 (0x7fd6ac0df098 @ 52)
org.gnome.Shell.desktop[3304]: #3 0x7ffc9e3fea70 I   resource:///org/gnome/gjs/modules/tweener/tweener.js:203 (0x7fd6ac0e9cd0 @ 54)
org.gnome.Shell.desktop[3304]: #4 0x7ffc9e3febc0 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:332 (0x7fd6ac0e9d58 @ 1626)
org.gnome.Shell.desktop[3304]: #5 0x7ffc9e3fec70 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:345 (0x7fd6ac0e9de0 @ 100)
org.gnome.Shell.desktop[3304]: #6 0x7ffc9e3fed00 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:360 (0x7fd6ac0e9e68 @ 10)
org.gnome.Shell.desktop[3304]: #7 0x7ffc9e3fed80 I   resource:///org/gnome/gjs/modules/signals.js:126 (0x7fd6ac0e2b38 @ 386)
gnome-shell[3304]: Object Meta.WindowActor (0x558f3b8ab710), has been already finalized. Impossible to set any property to it.
org.gnome.Shell.desktop[3304]: #8 0x7ffc9e3fee30 b   resource:///org/gnome/shell/ui/tweener.js:208 (0x7fd6ac0df808 @ 159)
org.gnome.Shell.desktop[3304]: #9 0x7ffc9e3fee90 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fd6ac0c2bc0 @ 71)
org.gnome.Shell.desktop[3304]: #10 0x7ffc9e3fee90 I   resource:///org/gnome/shell/ui/tweener.js:183 (0x7fd6ac0df780 @ 20)
org.gnome.Shell.desktop[3304]: #11 0x7ffc9e3fef20 I   self-hosted:917 (0x7fd6ac0ee5e8 @ 394)
```

Since I prefer to look up the logs in guake too (with journalctl -f in one tab), it really pisses me off to scroll and find the right strings. Since I can't filter out this logs due to limitations (or "features") of systemd, I didn't find how to disable gnome-shell logging and I didn't find anything related in issues here, can you please tell me what i can do with it?

Thanks.

I'm using Arch Linux, Guake 3.0.4

**Comment by dereckson** [comment]
I can repro both on Arch and Fedora Rawhide fresh installations, so I'd guess it's a bug occurring in recent GNOME 3 builds.

On Arch, I've this information after the stacktrace reported above:

Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]: ================================================================================
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]: Window display
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]: gtk.gdk.WindowState = 0
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]: GDK_WINDOW_STATE_STICKY? False
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]: GDK_WINDOW_STATE_WITHDRAWN? False
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]: GDK_WINDOW_STATE_ABOVE? False
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]: GDK_WINDOW_STATE_ICONIFIED? False
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]: Showing the terminal
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]: set_final_window_rect
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   height_percents = 50
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   width_percents = 100
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   halignment = 0
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   valignment = 0
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   vdisplacement = 0
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   hdisplacement = 0
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]: Current monitor geometry
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   window_rect.x: 0
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   window_rect.y: 0
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   window_rect.height: 1024
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   window_rect.width: 1280
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]: is unity: False
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]: Correcteed monitor size:
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   total_width: 1280
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   total_height: 1024
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]: RESIZING MAIN WINDOW TO THE FOLLOWING VALUES:
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   window_rect.x: 0
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   window_rect.y: 0
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   window_rect.height: 512
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   window_rect.width: 1280
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]: Updated window position: (root_x=0, root_y=0)
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]: Moving window to: <Gdk.Rectangle object at 0x7f9514672a68 (GdkRectangle at 0x55e896625e70)>
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]: set_final_window_rect
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   height_percents = 50
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   width_percents = 100
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   halignment = 0
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   valignment = 0
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   vdisplacement = 0
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   hdisplacement = 0
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]: Current monitor geometry
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   window_rect.x: 0
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   window_rect.y: 0
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   window_rect.height: 1024
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   window_rect.width: 1280
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]: is unity: False
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]: Correcteed monitor size:
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   total_width: 1280
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   total_height: 1024
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]: RESIZING MAIN WINDOW TO THE FOLLOWING VALUES:
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   window_rect.x: 0
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   window_rect.y: 0
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   window_rect.height: 512
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]:   window_rect.width: 1280
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]: Updated window position: (root_x=0, root_y=27)
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]: order to present and deiconify
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]: Current window position: (root_x=0, root_y=27)
Mar 22 16:05:19 graywell.dereckson.drake guake[831]: atk_object_set_description: assertion 'description != NULL' failed
Mar 22 16:05:19 graywell.dereckson.drake guake[831]: atk_object_set_description: assertion 'description != NULL' failed
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]: Received window state event: <flags GDK_WINDOW_STATE_STICKY | GDK_WINDOW_STATE_ABOVE | GDK_WINDOW_STATE_FOCUSED | GDK_WINDOW_STATE_TOP_RESIZABLE | GDK_WINDOW_STATE_RIGHT_RESIZABLE | GDK_WINDOW_STATE_BOTTOM_RESIZABLE | GDK_WINDOW_STATE_LEFT_RESIZABLE of type Gdk.WindowState>
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]: Received window state event: <flags GDK_WINDOW_STATE_STICKY | GDK_WINDOW_STATE_ABOVE | GDK_WINDOW_STATE_TOP_RESIZABLE | GDK_WINDOW_STATE_RIGHT_RESIZABLE | GDK_WINDOW_STATE_BOTTOM_RESIZABLE | GDK_WINDOW_STATE_LEFT_RESIZABLE of type Gdk.WindowState>
Mar 22 16:05:19 graywell.dereckson.drake guake.desktop[831]: Received window state event: <flags GDK_WINDOW_STATE_STICKY | GDK_WINDOW_STATE_ABOVE | GDK_WINDOW_STATE_FOCUSED | GDK_WINDOW_STATE_TOP_RESIZABLE | GDK_WINDOW_STATE_RIGHT_RESIZABLE | GDK_WINDOW_STATE_BOTTOM_RESIZABLE | GDK_WINDOW_STATE_LEFT_RESIZABLE of type Gdk.WindowState>
qMar 22 16:05:26 graywell.dereckson.drake guake.desktop[831]: Received window state event: <flags GDK_WINDOW_STATE_STICKY | GDK_WINDOW_STATE_ABOVE | GDK_WINDOW_STATE_TOP_RESIZABLE | GDK_WINDOW_STATE_RIGHT_RESIZABLE | GDK_WINDOW_STATE_BOTTOM_RESIZABLE | GDK_WINDOW_STATE_LEFT_RESIZABLE of type Gdk.WindowState>
Mar 22 16:06:14 graywell.dereckson.drake guake.desktop[831]: Received window state event: <flags GDK_WINDOW_STATE_STICKY | GDK_WINDOW_STATE_ABOVE | GDK_WINDOW_STATE_FOCUSED | GDK_WINDOW_STATE_TOP_RESIZABLE | GDK_WINDOW_STATE_RIGHT_RESIZABLE | GDK_WINDOW_STATE_BOTTOM_RESIZABLE | GDK_WINDOW_STATE_LEFT_RESIZABLE of type Gdk.WindowState>
Mar 22 16:06:19 graywell.dereckson.drake guake.desktop[831]: Received window state event: <flags GDK_WINDOW_STATE_STICKY | GDK_WINDOW_STATE_ABOVE | GDK_WINDOW_STATE_TOP_RESIZABLE | GDK_WINDOW_STATE_RIGHT_RESIZABLE | GDK_WINDOW_STATE_BOTTOM_RESIZABLE | GDK_WINDOW_STATE_LEFT_RESIZABLE of type Gdk.WindowState>

**Comment by jtojnar** [comment]
This is GNOME Shell bug, I am getting the same error when using <kbd>alt</kbd>-<kbd>tab</kbd>. IIRC it first appeared in 3.26 updated.

**Comment by gsemet** [comment]
on HEAD I have filtered all these logs if you do not have started with -v

**Comment by xMordax** [comment]
Same here, it just fills up my syslog with spam that I dont need.
Any new on a fix here?

**Comment by callum-p** [comment]
Same here

**Comment by pabloab** [comment]
@gsemet filling journald with unimportant stuff could make very difficult to find important (even dangerous)  things. Please consider rising the priority of this issue. Currently 8%* of my journalctl is guake-related.
I think is unlikely a gnome problem since i don have the same issue with other programs. My case: Guake 3.0.5-1 @ Gnome 3.28.3, Ubuntu 18.04.2.

**Comment by callum-p** [comment]
I ended up uninstall Guake because of this. Haven't missed it TBH.

Sorry for filling the issue with my junk message, thumbs down to you too jtojnar :D.

**Comment by jtojnar** [comment]
This IS a GNOME Shell issue and it was resolved in 3.30. While a [proper fix](https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/4) has still to come, these particular messages should be no longer shown. If you see some other message on GNOME 3.30+, please open a new issue.

**Comment by dror-g** [comment]
Hi, getting similar log entries on Mate WM.
I understand this is a Gnome/GDK issue, but not sure how/which version of it is used in Mate.
 
```Apr 20 00:16:58 DeathMagnetic org.mate.panel.applet.MateMenuAppletFactory[1448]: ================================================================================
Apr 20 00:16:58 DeathMagnetic org.mate.panel.applet.MateMenuAppletFactory[1448]: Window display
Apr 20 00:16:58 DeathMagnetic org.mate.panel.applet.MateMenuAppletFactory[1448]: gtk.gdk.WindowState = 0
Apr 20 00:16:58 DeathMagnetic org.mate.panel.applet.MateMenuAppletFactory[1448]: GDK_WINDOW_STATE_STICKY? False
Apr 20 00:16:58 DeathMagnetic org.mate.panel.applet.MateMenuAppletFactory[1448]: GDK_WINDOW_STATE_WITHDRAWN? False
Apr 20 00:16:58 DeathMagnetic org.mate.panel.applet.MateMenuAppletFactory[1448]: GDK_WINDOW_STATE_ABOVE? False
Apr 20 00:16:58 DeathMagnetic org.mate.panel.applet.MateMenuAppletFactory[1448]: GDK_WINDOW_STATE_ICONIFIED? False
Apr 20 00:16:58 DeathMagnetic org.mate.panel.applet.MateMenuAppletFactory[1448]: hiding the terminal
Apr 20 00:16:58 DeathMagnetic org.mate.panel.applet.MateMenuAppletFactory[1448]: Received window state event: <flags GDK_WINDOW_STATE_WITHDRAWN | GDK_WINDOW_STATE_STICKY | GDK_WINDOW_STATE_ABOVE | GDK_WINDOW_STATE_FOCUSED of type Gdk.WindowState>
Apr 20 00:16:58 DeathMagnetic org.mate.panel.applet.MateMenuAppletFactory[1448]: Received window state event: <flags GDK_WINDOW_STATE_WITHDRAWN | GDK_WINDOW_STATE_ABOVE | GDK_WINDOW_STATE_FOCUSED of type Gdk.WindowState>
```

**Comment by zeusintuivo** [comment]
I think we should close this issue, because is not related to Guake, tweener.js is part of the gnome that is not directly linked to Guake, it has to do more the special effects using to extensions in gnome.Shell.desktop
@Davidy22

**Comment by pabloab** [comment]
Using gnome 3.36. I confirm it seems fixed. Now Guake doesn't litter too much the logs. I only wish I could get rid of those "INFO     Showing the terminal" (`journalctl | grep guake | cut -d\  -f6- | sort | uniq -c | sort -rn`), but at least is not anymore on the top 20 (`journalctl | awk '{print $5}' | sort | uniq -c | sort -rn | head -20`).

**Comment by Davidy22** [comment]
Closing since fixed. Most of the messages were trimmed prior to 3.7, I personally downgraded the show/hide terminal messages to debug in 3.8 so a version newer than that will hide those for you too.

**Comment by iconoclasthero** [comment]
Is this the final resolution?  I'm trying to look through /var/log/syslog and am finding a lot of guake stuff I would also describe as "litter" that I would much rather not be there.

**Comment by jtojnar** [comment]
@iconoclasthero The issue here has been resolved. Please open a new issue with a snippet of the logs and guake version if you are experiencing similar bug.
