### ISSUE TITLE
Guake won't save all my settings

### ISSUE THREAD

**Issue by crazy69joker420** [Guake/guake#1205]
When I change the guake preferences to customize my terminal it works till I reboot or restart my PC.. I keep trying and nothing works... PS. I am kinda new to Linux.

**Comment by gsemet** [comment]
do you use Guake 3?

**Comment by crazy69joker420** [comment]
Yes I believe so

**Comment by crazy69joker420** [comment]
What ever one comes with "apt-get install guake"

**Comment by crazy69joker420** [comment]
Using mint 18

**Comment by gsemet** [comment]
can you show us the version ? it does not happen on guake 3

**Comment by crazy69joker420** [comment]
that’s the one im using

![img_20180308_095858064](https://user-images.githubusercontent.com/37113204/37157966-3449dbe6-22b8-11e8-96a4-8e90765ed162.jpg)

**Comment by gsemet** [comment]
it is an old one. Please ask mint to update guake or install from current source

**Comment by crazy69joker420** [comment]
So I do apt-get install guake update??

**Comment by gsemet** [comment]
should do. If it does, it the package repository that have a too old guake, or you need to update your distro

**Comment by crazy69joker420** [comment]
Everything is up to date idk what I'm doing wrong so I'm gonna uninstall and reinstall and try again
