### ISSUE TITLE
Confusing notification on startup

### ISSUE THREAD

**Issue by sdicke** [Guake/guake#1209]
Distribution: Antergos
Guake version: 3.0.4-2
GTK version:  3.22.28-1
Desktop enviroment: KDE

If I run the application, the notification as shown in the screenshot pop ups. This is reproducible. I am bit confused that a placeholder for the shortcut is shown instead of the shortcut itself.

![Screenshot](http://212.144.102.119/guake.png)

**Comment by gsemet** [comment]
look like an error in the german translation, it should print the hotkey
