### ISSUE TITLE
Can't fully uninstall guake

### ISSUE THREAD

**Issue by LuckyKoala** [Guake/guake#1210]
* Guake version: 0.8.4-1
* GNOME version: 3.18.2
* Linux distribution: Ubuntu 16.04.1

I installed guake using `sudo apt-get install guake`, uninstalled it by `sudo apt remove guake` and `sudo apt auto-remove`.
After that, i was told that guake had been uninstalled, but when i press `F12`, guake shell will still show except it can't function now.

The first line of this shell is `*** VTE ***: Failed to load terminal capabilities from '/etc/termcap'`

And anything i input to this shell is broken, for example, when i press `Backspace`, it echo `space` which i guess is it can't handle the `signal` anymore since guake is uninstalled.

What i want is to `fully uninstall` guake, which means i should not see the terminal show again when i press `F12`.

So what do i miss?

**Comment by LuckyKoala** [comment]
I came across a idea that maybe there is a process which is still running guake program, so i use `ps -aux | grep guake`, and i see `luckyko+  8240  0.0  0.6 757816 50716 ?        Sl   3月12   1:11 python2 -m guake.main`.

Now the shell will not show again after i killed this process.

**Comment by muhammedMoussa** [comment]
this worked for me: `sudo apt-get remove --auto-remove guake `
