### ISSUE TITLE
Guake takes at least 30secs-1 minute to actually open.

### ISSUE THREAD

**Issue by slipperyBishop** [Guake/guake#1211]
Guake Version: 3.0.4
Using Archlinux with i3-wm
linux kernel 4.15.10-1
gtk version: gtk3 3.22.28-1

After starting Guake it stops before the Main GTK loop is reached for around a minute before it continues and actually shows the window/toolbar icon.
I compiled the HEAD branch and the problem still remains.

not sure what else you want me to post.

**Comment by gsemet** [comment]
weird... I do not see how I can reproduce it. Can you dump me here the logs ?

**Comment by slipperyBishop** [comment]
hey sorry for the late reply, I figured it out.
When guake first starts it sends a notification through dbus and dbus wasn't handling it well, I think it was just timing out. I removed some packages that had competing notification servers and now notifications are showing fine and there is no hang.

not sure if you want to just close this issue or if there is someway to prevent this bug in the future.
If you need more information just ask!

Thanks, regards slipperyBishop.

**Comment by gsemet** [comment]
there are a lot of application that relies on dbus...
