### ISSUE TITLE
click "new tab" on tab names reverses all the customerized tab names

### ISSUE THREAD

**Issue by cinqs** [Guake/guake#1213]
- **Guake Version**: 0.8.7
  - SysOS version: CentOS 7 with Gnome 3.22.2

When you have multiple tabs open and renamed, if you right click on one of the tabs, and click "new tab". one new tab is opened but all the previous tabs' names will be reversed to the default names.

I believe this is a bug

**Comment by gsemet** [comment]
It should not happen on more recent version of guake 0.8

**Comment by cinqs** [comment]
Hi, Will you update the *yum repos*? because I usually compile the source as the last option. Thanks
