### ISSUE TITLE
Segfault on Ubuntu 17.10 (Wayland)

### ISSUE THREAD

**Issue by jgoclawski** [Guake/guake#1224]
- **Guake Version**: 3.0.5 (3.0.4 as well)
  - Please describe **your system**: Ubuntu 17.10 (Wayland), GNOME 3.26.2

The bug only happens on Wayland. When I switch to Xorg, guake works ok.
On Wayland sometimes it crashes and sometimes it works. Usually after w few reboots guake finally starts.

Output:
```
$ guake -t
Logging configuration complete
DBus not running, starting it
Wanted GTK theme: 'Arc-Dark'
Prefer dark theme: False
reload_global: 'F12'
[1]    16177 segmentation fault (core dumped)  guake -t
```
When trying with sudo:
```
$ sudo guake -t
Logging configuration complete
DBus not running, starting it
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused
[1]    16225 segmentation fault  sudo guake -t
```

Output in dmesg:
```
[ 1168.701723] guake[16805]: segfault at 42 ip 00007fd827438ad4 sp 00007fffb8a40320 error 6 in libX11.so.6.3.0[7fd8273a6000+134000]
[ 1171.740910] guake[16850]: segfault at 0 ip 00007fd2fee62659 sp 00007fff84cba490 error 4 in libgtk-3.so.0.2200.25[7fd2feb7b000+6fd000]
```

(first log is when calling guake without sudo, the second one is with sudo)

I used to have similar problems with workrave, but the following workaround fixes the problem for workrave - https://github.com/rcaelers/workrave/issues/88

For the record:
```
$ echo $DISPLAY
:0
```

Is there any info I can provide to help with fixing this? What might be the cause?

**Comment by cothan** [comment]
I have the same issue.

**Comment by gsemet** [comment]
Do you know how I can install wayland from an iso that would run in a VM (mac Parallels)?

**Comment by jgoclawski** [comment]
@gsemet Not sure about Mac Parallels, but it seems there are issues with Wayland - https://forum.parallels.com/threads/installing-ubuntu-17-10-on-parallels-desktop-3.342537/. You should be able to use Virtualbox though and test Wayland there (with 3D acceleration disabled) - https://ubuntuforums.org/showthread.php?t=2370233

**Comment by gsemet** [comment]
Can you see at #1340, seems to have someone happy to have guake working under wayland :)
