### ISSUE TITLE
Crash after enter path in settings for custom_command_file

### ISSUE THREAD

**Issue by igorog** [Guake/guake#1229]
Arch Linux **'any'** Repository: **guake 3.0.5-2** Community Maintainers: Balló György Build Date: 2018-03-27 16:51 UTC Last Updated: 2018-03-27 17:00 UTC
**System:** (Linux 4.15.15-1-ARCH #1 SMP PREEMPT Sat Mar 31 23:59:25 UTC 2018 **x86_64** GNU/Linux)
**DE:** Cinnamon
**Steps to reproduce: Crash after enter path in settings for ~/.config/gconf/apps/guake/custom-command-file.json.**

> Output:
 (guake:2058): IBUS-WARNING **: 16:15:18.360: Unable to connect to ibus: Не удалось подключиться к: В соединении отказано
/usr/lib/python3.6/site-packages/gi/overrides/Gtk.py:1612: Warning: unable to set property 'accel-key' of type 'guint' from value of type 'gchararray'
  return _Gtk_main(*args, **kwargs)
/usr/lib/python3.6/site-packages/gi/overrides/Gtk.py:1612: Warning: unable to set property 'accel-mods' of type 'GdkModifierType' from value of type 'gchararray'
  return _Gtk_main(*args, **kwargs)
(guake:2058): GLib-GIO-ERROR **: 16:15:35.367: Settings schema 'guake.general' does not contain a key named 'custom_command_file'

**Comment by igorog** [comment]
Well, the menu has appeared, the application does not fall ...... and further - anything. Сustom commands - do not work !!!!!! In addition, pay attention to the work of the mouse in the Midnight Commander !!!! The mouse is working - it's wrong! The right button - does not work!

**Comment by gsemet** [comment]
Can you open a new ticket for this pbl on right click + another for custom command does not work

**Comment by jazzmale** [comment]
UBUNTU 18.04 Gnome 
4.15.0-23-lowlatency x86_64

guake 3.0.5-1 
Also tried newest debian sid 3.2.2-2_all

All the same: crash after entering path to custom commands menu file.

**Comment by gsemet** [comment]
you need to update to HEAD. I do not use custom command that much, but do not hesitate to try to hack the code and fix it :) Python is easy
