### ISSUE TITLE
PCRE2 not supported in Ubuntu 17.10

### ISSUE THREAD

**Issue by gsemet** [Guake/guake#1230]
Ubuntu 17.10 disabled PCRE2 on their integration of VTE. This prevents adding matchers that uses regular expressions.
This breaks url open and quick open features.

User can still select the content in the terminal and Ctrl+click on it to open it, or right click to open the url with the contextual menu.

**Comment by egmontkob** [comment]
> Ubuntu 17.10 disabled PCRE2 on their integration of VTE.

Same for 18.04.

> This prevents adding matchers that uses regular expressions.

This is not true per se, maybe guake uses a method that doesn't work, but regexes still work e.g. in gnome-terminal using another (glib?) engine.

**Comment by gsemet** [comment]
yes, but how does they do? Maybe they do not use PyVTE?
I always receive an "PCRE2 not supported" exception? This only breaks the underlying of the text + the quick open features.

**Comment by egmontkob** [comment]
I'm sorry but I don't really know what exactly the Ubuntu patch does and how exactly that influences the API, let alone the Python binding.

**Comment by egmontkob** [comment]
My 2 cents: If Ubuntu patches their VTE, they should also patch whichever app it breaks.

**Comment by gsemet** [comment]
i found in the gnome terminal source their fix and reproduced in guake. it's indeed a fallback to glib + the multiline compile flag, mandatory in some versions

**Comment by gsemet** [comment]
Thanks for your help :)
