### ISSUE TITLE
Data not installed

### ISSUE THREAD

**Issue by jtojnar** [Guake/guake#1252]
As mentioned in https://github.com/Guake/guake/issues/1236, pixmaps and GtkBuilder files should be installed by the `install` make target, so we do not need to install them manually like [Arch does](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/guake&id=2b70f1e9e4f905f713b3948407e3b71a83077d26#n48)

**Comment by gsemet** [comment]
ok, glade weren't installed most pixmap weren't:
