### ISSUE TITLE
Attempting to port Guake to Void Linux MUSL...

### ISSUE THREAD

**Issue by kenny-w1** [Guake/guake#1268]
Hello, I am trying to port guake (gtk3) onto void linux, I have got gtk2 guake to work, but not 3.
I've tried deleting the /etc/gtk-3.0/settings.ini file, seems to change nothing, the errors still come up.

https://pastebin.com/ivW8yNP3

**Comment by gsemet** [comment]
not sure how to help, don't know void linux, and it seems you don't have a gtk install that I may know...

**Comment by kenny-w1** [comment]
Unrelated to this issue but Guake(gtk3) just froze up on my Arch-based distro & stopped me from being able to click on anything, I just had to SSH into my desktop from my laptop & send a pkill guake command to free my computer.

**Comment by kenny-w1** [comment]
Can't seem to make Guake gtk3 work in Void Linux at all, can get gtk2 to work though... 
In order to make Guake Gtk2 work I need to use the PKGBUILD instructions from the arch AUR..
I was hoping you could tell me how I can apply this command from the old guake-gtk2-git on the AUR to the new guake gtk3(how I get guake to work on Void):

PYTHON=$(which python2) ./autogen.sh --prefix=/usr --sysconfdir=/usr/share --disable-static

**Comment by gsemet** [comment]
the build system has completely changed, please read the README. Have your tried the install from source?

**Comment by kenny-w1** [comment]
Yes I've tried from source & yes I've checked the README, I have also in addition to the way in the README tried some of the commands in the PKGBUILDs for guake-git & guake-gtk2-git on the AUR.

**Comment by gsemet** [comment]
i don't know what does --disable-static. you can look at the makefile and if something is missing you can open a pull request

**Comment by Vlad-Romanov** [comment]
Hello, I have altered the Makefile and now Guake works in Void Linux.
https://github.com/Vlad-Romanov/Void-Guake

**Comment by aichingm** [comment]
you don't have to change https://github.com/Vlad-Romanov/Void-Guake/blob/78af3d5213cc0f809199c2e2ba7dc93ca2c64c7a/Makefile#L6  you can use `make --prefix=/usr`. what is the reason for commenting out the release targets?
