### ISSUE TITLE
Open URL ceased to work

### ISSUE THREAD

**Issue by squalou** [Guake/guake#1295]
Hi,

I'm running Arch, I've just updated guake to 3.2.0, with gnome 3.28.1

There's also been a python update with the same system update, so *maybe* I've just switch from gtk2 version to gtk3, I don't know for sure. Maybe I have remnant of 0.8 guake somewhere in a conf file, I did notice that I had to redo some manual config, like global dark theme. So ... maybe there's a remnant of config somwhere in the way.

## Before :
Until then, I could 'ctrl click' on anything that looked like an url  (say : https://github.com/Guake), it would open it in my default browser. The link itself was disaplyed with an underline.

## After :
Now, it doesn't work anymore
No underline, nothing happens on ctrl click.

When launching guake from a terminal I can see warnings, but nothing once it's launched. FOr the records here are the warnings :

`
(guake:4380): Vte-WARNING **: 15:28:05.004: (vtegtk.cc:1916):int vte_terminal_match_add_regex(VteTerminal*, VteRegex*, guint32): runtime check failed: (_vte_regex_get_compile_flags(regex) & PCRE2_MULTILINE)
`

It's 100% reproductible on my PC, even after reinstall. Did not purge entirely config files ... since I don"t know which one I should delete. I can try if someone gives me the list.

regards,
and thanks for the job !

**Comment by gsemet** [comment]
Hi. I can reproduce it on fedora with vte 0.52, but I think the link worked... i'll check that this evening !

**Comment by jaawerth** [comment]
Looks like [this is the culprit](https://github.com/Guake/guake/commit/cf059854#diff-e10dc964d7688fdf1ebd2ad6b5620ea3R172) - it changed over to using `Vte.Regex.new_for_match`, which has a [different function signature](https://lazka.github.io/pgi-docs/Vte-2.91/classes/Regex.html#Vte.Regex.new_for_match) from that of [Glib.Regex.new](https://people.gnome.org/~gcampagna/docs/GLib-2.0/GLib.Regex.new.html)

PR incoming!

**Comment by squalou** [comment]
I did try the patch locally : urls are indeed recognized now, Right click 'open link' works fine.

Still, one question : Ctrl Click does nothing.
Is it somehow related ?

**Comment by gsemet** [comment]
@squalou do you have logs on what happen on Ctrl+click ? Does right click works?

**Comment by jaawerth** [comment]
Whoops! I tested the PR with the context menu->open URL, and it didn't occur to me to also check ctrl+click, but I'm seeing the same behavior.

@gsemet Here's the log info + stacktrace I'm getting with ctrl+click in the latest master (after the PR merge):

```
INFO     Guake initialized
INFO     --no-startup-script argument defined, so don't execute the startup script
INFO     Showing the terminal
Traceback (most recent call last):
  File "/home/jesse/Tinkering/guake/guake/terminal.py", line 295, in button_press
    self._on_ctrl_click_matcher((s, None))
  File "/home/jesse/Tinkering/guake/guake/terminal.py", line 320, in _on_ctrl_click_matcher
    found_matcher = self._find_quick_matcher(value)
  File "/home/jesse/Tinkering/guake/guake/terminal.py", line 328, in _find_quick_matcher
    g = re.compile(extractor).match(value)
TypeError: expected string or bytes-like object
```

**Comment by gsemet** [comment]
can you edit the file and replace `value` by `str(value)` ?

**Comment by jaawerth** [comment]
Will do! I figured I'd dig into it after work if you didn't beat me to it anyway, so I'll try that first and see where it takes me...

**Comment by jaawerth** [comment]
It's coming back `None`, so casting it to a string prevents the error but still results in nothing happening. `s = self.hyperlink_check_event(event)` on [line 294](https://github.com/Guake/guake/blob/3.2.1/guake/terminal.py#L294) appears to be returning `None` even for a valid hyperlink.

I'll see what I turn up after digging deeper. If I can't solve it quickly tonight I'm happy to file a separate issue for the `ctrl+click` bug.

**Comment by jaawerth** [comment]
So... it feels hacky, but I was able to get it working by adding a fallback for `self.hyperlink_check_event(event)` returning `None` (see [this commit](https://github.com/jaawerth/guake/commit/aa302cd36541dfe1012c0eb26a0e40d66d0b7678)). I couldn't quite get to why it's happening, but letting it fallback to the rest of the conditional chain (using the regex matcher, etc) seems to work.

I feel like it's working around the problem (no idea if it's a Vte bug or something else), but if that works for you I'm happy to PR it.

**Comment by squalou** [comment]
Copied the whole 'terminal.py' from your patch (applying the few lines changed did not work, anyway I had line number mistamatch, something probably moved since the release I have)
Anyway : workaraound works for me.
thx !

**Comment by gsemet** [comment]
I have fixed it on HEAD, if you want to try

**Comment by jaawerth** [comment]
Yep, saw you applied the commit. Working for me!
