### ISSUE TITLE
No option that set the Backgroud image in version 3.0.5 ?

### ISSUE THREAD

**Issue by SkipperJK** [Guake/guake#1297]

**Comment by SkipperJK** [comment]
Is option removed???

**Comment by aichingm** [comment]
Yes this option is removed. Vte (the underlying terminal emulator) has removed support for background images and reimplementing it in guake itself would be a not so easy task.

**Comment by gsemet** [comment]
sadly, that's true.

**Comment by franktopel** [comment]
That's too bad. Why did they remove such a beautiful feature in the first place? What about terminix as an alternative?
