### ISSUE TITLE
Dupplicate theme entries

### ISSUE THREAD

**Issue by aichingm** [Guake/guake#1304]
Guake shows me every Gtk-Theme twice in the combobox:

![screenshot_20180425_145133](https://user-images.githubusercontent.com/6470959/39247772-9b4245ec-489a-11e8-8da9-793f6a41db7e.png)

I'm not an Gtk-Theme expert and I'm running on KDE so this might be only my system.
> Guake Terminal: 3.2.1
VTE: 0.52.1
VTE runtime: 0.52.1
Gtk: 3.22.30

**Comment by gsemet** [comment]
That's probably because they appear in two different folder. I need to uniquify this list ! good catch
