### ISSUE TITLE
Ubuntu 18.04 - typing exit in terminal, guake hangs

### ISSUE THREAD

**Issue by lsv** [Guake/guake#1309]
Guake Version: 3.0.5
Ubuntu 18.04 (just released)

If you type `exit` in the guake terminal, Guake terminal just hangs, you can only click `F12` to open guake, and you can switch to another tab, but not possible to open a new tab.

And if you type `exit` in the tab you switched to, then this tab also hangs

I got a ubuntu error report, and I send it (I dont know where it sends to) and now I dont get it anymore, but I remember I saw something about `hvalign`

**Comment by gsemet** [comment]
can you try with 3.2 or HEAD? Should be fixed

**Comment by lsv** [comment]
is there a deb file for it, cant find it - and building from source is just not my cup of tea :/

**Comment by gsemet** [comment]
You need to wait for the Debian maintainer to update his scripts. See [this page](https://tracker.debian.org/pkg/guake).
