### ISSUE TITLE
Error install in Ubuntu 18.04

### ISSUE THREAD

**Issue by tglhteam** [Guake/guake#1321]
```
anton-z@antonz-desktop:~/guake-master$ sudo make
generating desktop files
cp -f guake/paths.py.in guake/paths.py
# Generic
# Dev environment:
sed -i -e 's|{{ LOCALE_DIR }}|/usr/local/share/locale|g' guake/paths.py
sed -i -e 's|{{ IMAGE_DIR }}|/home/anton-z/guake-master/data/pixmaps|g' guake/paths.py
sed -i -e 's|{{ GUAKE_THEME_DIR }}|/home/anton-z/guake-master/data/themes|g' guake/paths.py
sed -i -e 's|{{ GLADE_DIR }}|/home/anton-z/guake-master/data|g' guake/paths.py
sed -i -e 's|{{ SCHEMA_DIR }}|/home/anton-z/guake-master/data|g' guake/paths.py
generating po/pl.po
generating po/nl.po
generating po/gl.po
generating po/fr.po
generating po/es.po
generating po/it.po
generating po/ru.po
generating po/id.po
generating po/ca.po
generating po/sv.po
generating po/uk.po
generating po/zh_CN.po
generating po/hr.po
generating po/tr.po
generating po/de.po
generating po/el.po
generating po/hu.po
generating po/cs.po
generating po/fa.po
generating po/pt_BR.po
generating po/ja.po
generating po/pa.po
generating po/ko.po
generating po/nb.po
rm -f /home/anton-z/guake-master/data/gschemas.compiled
glib-compile-schemas --strict /home/anton-z/guake-master/data
# 'make' target, so users can install guake without need to install the 'dev' dependencies

anton-z@antonz-desktop:~/guake-master$ sudo make install
install -Dm644 "/home/anton-z/guake-master/data/guake.desktop" "//usr/local/share/applications/guake.desktop"
install -Dm644 "/home/anton-z/guake-master/data/guake-prefs.desktop" "//usr/local/share/applications/guake-prefs.desktop"
mkdir -p //usr/local/share/guake/pixmaps
install -Dm644 /home/anton-z/guake-master/data/pixmaps/*.png "//usr/local/share/guake/pixmaps/"
install -Dm644 /home/anton-z/guake-master/data/pixmaps/*.svg "//usr/local/share/guake/pixmaps/"
install -Dm644 /home/anton-z/guake-master/data/pixmaps/guake.png "//usr/local/share/pixmaps/guake.png"
mkdir -p //usr/local/share/guake
mkdir -p //usr/local/share/guake
install -Dm644  /home/anton-z/guake-master/data/*.glade "//usr/local/share/guake"
mkdir -p //usr/local/share/guake
install -Dm644 "/home/anton-z/guake-master/data/autostart-guake.desktop" "//usr/local/share/guake"
mkdir -p //usr/local/share/glib-2.0/schemas
install -Dm644 "/home/anton-z/guake-master/data/org.guake.gschema.xml" "//usr/local/share/glib-2.0/schemas/"
if [ 1 = 1 ]; then glib-compile-schemas //usr/local/share/glib-2.0/schemas; fi
for f in $(find po -iname "*.mo"); do \
	l="${f%%.*}"; \
	lb=$(basename $l); \
	install -Dm644 "$f" "//usr/local/share/locale/$lb/LC_MESSAGES/guake.mo"; \
done;
# you probably want to execute this target with sudo:
# sudo make install
Installing from on your system is not recommended.
Please prefer you application package manager (apt, yum, ...)
/usr/bin/python3: No module named pip
Makefile:73: recipe for target 'install-guake' failed
make: *** [install-guake] Error 1
 ```

Whats problem, please help!

**Comment by aichingm** [comment]
It seams you have not installed the dependencies. Did you run 
`./scripts/bootstrap-debian-dev.sh run make`?

**Comment by tglhteam** [comment]
No, i not run. Now i try to run.

**Comment by tglhteam** [comment]
anton-z@antonz-desktop:~/guake-master$ sudo make install
install -Dm644 "/home/anton-z/guake-master/data/guake.desktop" "//usr/local/share/applications/guake.desktop"
install -Dm644 "/home/anton-z/guake-master/data/guake-prefs.desktop" "//usr/local/share/applications/guake-prefs.desktop"
mkdir -p //usr/local/share/guake/pixmaps
install -Dm644 /home/anton-z/guake-master/data/pixmaps/*.png "//usr/local/share/guake/pixmaps/"
install -Dm644 /home/anton-z/guake-master/data/pixmaps/*.svg "//usr/local/share/guake/pixmaps/"
install -Dm644 /home/anton-z/guake-master/data/pixmaps/guake.png "//usr/local/share/pixmaps/guake.png"
mkdir -p //usr/local/share/guake
mkdir -p //usr/local/share/guake
install -Dm644  /home/anton-z/guake-master/data/*.glade "//usr/local/share/guake"
mkdir -p //usr/local/share/guake
install -Dm644 "/home/anton-z/guake-master/data/autostart-guake.desktop" "//usr/local/share/guake"
mkdir -p //usr/local/share/glib-2.0/schemas
install -Dm644 "/home/anton-z/guake-master/data/org.guake.gschema.xml" "//usr/local/share/glib-2.0/schemas/"
if [ 1 = 1 ]; then glib-compile-schemas //usr/local/share/glib-2.0/schemas; fi
for f in $(find po -iname "*.mo"); do \
	l="${f%%.*}"; \
	lb=$(basename $l); \
	install -Dm644 "$f" "//usr/local/share/locale/$lb/LC_MESSAGES/guake.mo"; \
done;
# you probably want to execute this target with sudo:
# sudo make install
Installing from on your system is not recommended.
Please prefer you application package manager (apt, yum, ...)
The directory '/home/anton-z/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/anton-z/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Ignoring typing: markers 'python_version < "3.5"' don't match your environment
Requirement already satisfied: pbr in /usr/lib/python3/dist-packages (from -r requirements.txt (line 13))
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/usr/lib/python3/dist-packages/pbr/util.py", line 249, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/usr/lib/python3/dist-packages/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/usr/lib/python3/dist-packages/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/usr/lib/python3/dist-packages/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/usr/lib/python3/dist-packages/pbr/packaging.py", line 755, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name Guake was given, but was not able to be found.
error in setup command: Error parsing /home/anton-z/guake-master/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name Guake was given, but was not able to be found.
Makefile:73: recipe for target 'install-guake' failed
make: *** [install-guake] Error 1

Such is the error...

**Comment by gsemet** [comment]
Please use markdown to format your comment (I've done it for you).
Then please do not download the zip file, it will not work. Checkout from git.
