### ISSUE TITLE
Transparency behind tab row?

### ISSUE THREAD

**Issue by abcarroll** [Guake/guake#1323]
Hello,

For one, I sincerely don't know if this is a bug, or some kind of intended behaviour change, or perhaps some kind of bizarre issue that Guake itself isn't responsible for (ie, an issue with GTK), however...

I reinstalled my system and got the latest Guake version.  And, in the latest HEAD version (commit a4c9f1a74fb5), the row of tabs, there is transparency behind it.  The background does not take the color of the theme/WM.  The only section "colored in" is the round button.  Everything else is 100% transparent behind the tab row/section.  This makes it very difficult to see the tab list (behind most backgrounds, i.e. especially if you have a XFCE panel of the same color that is typically where the tab list would be).

I can get a screenshot if this doesn't make sense.  ~However, I removed the self-installed version and instead switched to the older version provided by Debian repos (3.0.5) and it doesn't have this problem.

Edit: Actually, I was mistaken.  I must've been looking at this wrong.  Here is a screenshot, which is present on 3.0.5 as well as the commit mentioned above:

![weirdtransparency](https://user-images.githubusercontent.com/961513/39836045-2398b556-53a0-11e8-87d0-4d1e44944577.png)

**Comment by abcarroll** [comment]
[guake.log](https://github.com/Guake/guake/files/1989281/guake.log)

Attaching log, if it helps any.

**Comment by abcarroll** [comment]
Certainly the same results after a reboot.

Currently running Debian Stable, although I am moving to Debian Testing as we speak (it's a new install).

I am using XFCE 4.12 using the "adwaita" GTK theme.  I also tried every GTK theme that came with my install, and all produced the same results.

```
$ uname -a
Linux cat 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1 (2018-04-29) x86_64 GNU/Linux
$ cat /etc/issue
Debian GNU/Linux 9 \n \l
```

I'm really unsure of what else I could give you that would be applicable here.  If you have something specific though, please ask away, as this is driving me pretty crazy.  

I am going to try going backwards a few dozen commits at a time on the git repository and see if I can narrow it down to a specific commit where the behaviour begins occurring.

**Comment by abcarroll** [comment]
Went back to the tag '3.0.1', and still has this behaviour.  

I'll try to go back further later, but beyond this, the build system seems to have changed significantly and had a few problems with the older build system.

**Comment by gsemet** [comment]
I can reproduce but this does not fix it
