### ISSUE TITLE
Font of active tab in tab bar is always white

### ISSUE THREAD

**Issue by pszalanski** [Guake/guake#1326]
The theme selection works fine for me, thanks for that.

However, no matter what theme I have selected, the active tab has a white font color, which makes it illegible on most of my themes, especially my system theme, which is Ambiance on Ubuntu.

See here:
![screenshot from 2018-05-14 08-26-18](https://user-images.githubusercontent.com/4761826/39981375-adc2b14c-5750-11e8-9564-b8d36252ebd6.png)

**Comment by gsemet** [comment]
which version of guake are you under? Have you tried with latest version from HEAD?

**Comment by pszalanski** [comment]
It was checked out yesterday.

**Comment by abcarroll** [comment]
Having the same thing here.  Had to downgrade to the version supplied by my distro's pkg manager, 3.2.2

**Comment by pszalanski** [comment]
I guess this was caused by the following commit: https://github.com/Guake/guake/commit/21cf658bacd2b3559ebdb36a1527d0c3631e631f

**Comment by abcarroll** [comment]
Verified this.  You can temporarily fix this by changing the `css_data = ` assignment, around line 421 of `guake/guake_app.py`, as below:

```
        css_data = dedent(
            """
            .tab {{
              color: #aaaaaa;
            }}
            
            .tab:checked {{
              color: #000000;
              background-color: {};
            }}
            """.format(selected_bg_color)
        ).encode()
```

If I understood the intent of 21cf658 a little better, I would attempt a real patch, but I just don't understand what the commit was trying to accomplish.

**Comment by gsemet** [comment]
I can reproduce it on latest. I'll see if I can fix it asap
