### ISSUE TITLE
Exiting the shell crashes an individual tab

### ISSUE THREAD

**Issue by kroltan** [Guake/guake#1331]
**Guake Version:** 3.0.5
**System:** Ubuntu 18.04 LTS
Possibly related to #1014

If I open a tab in Guake, then exit it through Ctrl+D or by running exit, then the will stop responding to all input. I can still switch to another tab and use it normally, but it is forever crashed and unclosable.

Only closing Guake completely solves the issue.

**Comment by gsemet** [comment]
please use the issue search feature of github prior to opening an issue, this has been raised multiple time recently. This has been fixed on the source code of Guake, but ubuntu package are a few months late. Please ask for ubuntu to update their guake package
