### ISSUE TITLE
Ctrl+F2 interfere with Byobu (but others Ctrl+F_ don't)

### ISSUE THREAD

**Issue by pabloab** [Guake/guake#1334]
Ubuntu 18.04 fresh install, Guake 3.0.5-1, Gnome 3.28.1. Also on Guake 0.8.5-1~webupd8~xenial0. Ubuntu 16.04.4 LTS x86_64.

When installing Byobu and [using it inside Guake](https://github.com/Guake/guake/issues/71#issuecomment-186029163) everything seems OK, except for the very important feature of split vertical screen. I have to disable <kbd>Ctrl+F2</kbd> on Guake:

![screenshot](https://i.stack.imgur.com/OkyV1.png)

What's really strange is that al the others equally shortcuts like <kbd>Ctrl+F1</kbd> works fine, byobu "take it" before Guake, the problem seems just with <kbd>Ctrl+F2</kbd>.

**Comment by Davidy22** [comment]
Keybinding code has been overhauled since this was filed, does this still occur for you?

**Comment by pabloab** [comment]
It seems fixed :smile:.
