### ISSUE TITLE
Outdated guake in official distibution packages.

### ISSUE THREAD

**Issue by seghers** [Guake/guake#1335]
I'm a happy guake user for years. 
Thank you.

I'm running Fedora 28
```
dnf install -y guake
guake --version
```

> Guake Terminal 0.8.8

Is there any way the repo could get a more recent version.

**Comment by gsemet** [comment]
Hello. You can contact the fedora maintainer, @pypingou.

**Comment by pypingou** [comment]
I'm running guake 3.2.1 on my f27 box atm but the version that is currently in the repo works better than the new one, so I'm not pushing it.

Basically, the window doesn't hide anymore, I need to use the mouse to set the focus on another window or use alt-tab, quite annoying.

This may be related to wayland I'm not sure and I didn't investigate yet but as it is the old version works better.

**Comment by seghers** [comment]
Hello
@pypingou 
I have a similar error in 0.8.8
Could you try my 'fix'?
I use **<ALT> + space**

- change Guake Preferences: Keyboard shortcuts: Toggle Guake visibility: everything but  **<ALT> + space**
- change Gnome Keyboard shortcut for 'Activate the window menu' from (<ALT> + space) TO (Disabled or something different)
- add Gnome Keyboard shortcut for Guake:
-- name: Toggle Guake
-- command: **<ALT> + space**   
-- shortcut: guake -t

**Comment by pypingou** [comment]
@seghers I don't really care to fix this for me, I'll just downgrade if this annoys me enough. But your workaround isn't something I'm willing to encourage people to use in a RPM shipped in a distro, so until we fix this issue upstream, I will not update guake in Fedora, sorry :(

**Comment by pypingou** [comment]
On Mon, May 28, 2018 at 01:23:22PM +0000, Gaetan Semet wrote:
>    @pypingou You mean the second time you hit the global shortcut the window
>    is not hidden while it should be? Does it appear to hide + reopen very
>    fast?

The second one, disappears and comes right back

> On wayland I now recommand to not use Guake binding but to use guake
>    -t command in the system shortcut. It seems to work for others.

It may work, but I still consider this a work around rather than a fix.

**Comment by gsemet** [comment]
Ok this is linked to the function get_server_time used in X11 to delay the multiple input a window receive, but it does not exist on Wayland.

**Comment by Moulick** [comment]
as @gsemet said, the problem is with Wayland, not guake. Tilix suffers from kinda the same problem.

**Comment by pypingou** [comment]
> as @gsemet said, the problem is with Wayland, not guake. 

Do you have a bug id where we could track the issue?

**Comment by Moulick** [comment]
Its not a problem rather a case of missing functionality with wayland.

Kinda same problems in Tilix : https://github.com/gnunn1/tilix/issues/1314

**Comment by pypingou** [comment]
Reading that ticket, I don't see any link asking the wayland developers if there is a way around or a fix planned for this or suggestions on how to do this now.

**Comment by nlpsuge** [comment]
Just want you guys to know that the Guake in Fedora 30 is up-to-date now. Very thanks the maintainer. :-)

**Comment by vlow** [comment]
Hey @pypingou, I hope your still the right person to talk to about this. I've noticed that the current Fedora package is about a year behind the current Guake release. I'm wondering if this is a deliberate decision on your side or if there is anything I could do to help bringing 3.9.0 to the official Fedora repos.

**Comment by paseaf** [comment]
> Hey @pypingou, I hope you're still the right person to talk to about this. I've noticed that the current Fedora package is about a year behind the current Guake release. I'm wondering if this is a deliberate decision on your side or if there is anything I could do to help bringing 3.9.0 to the official Fedora repos.

I submitted [a PR for Guake 3.9.0](https://src.fedoraproject.org/rpms/guake/pull-request/4) to the official repo a month ago and it's still open.

As a temporary solution, for people who want to use the latest Guake on Fedora, feel free to install my build for now or build it on your own. The spec file is included.
https://github.com/paseaf/guake-rpm
