### ISSUE TITLE
Can't bind since Ubuntu 18.04 update

### ISSUE THREAD

**Issue by MrDJthib** [Guake/guake#1340]
Console show this :
** (guake:14095): WARNING **: 18:52:19.209: Binding '<Super>asterisk' failed!
My caracteristics:
Guake Terminal 3.2.2
VTE 0.52.1
Gtk 3.22.30
GNOME 3.28.1

**Comment by gsemet** [comment]
do you use wayland?

**Comment by MrDJthib** [comment]
Yes but before on Ubuntu 17.10 I was already on and binding worked perfectly

**Comment by gsemet** [comment]
dont know how it worked i never had the binding working under wayland (see [this page on the doc](http://guake.readthedocs.io/en/latest/user/faq.html#note-on-wayland))

**Comment by gsemet** [comment]
Can you see if this recommendation works: https://github.com/kupferlauncher/keybinder/issues/11

**Comment by MrDJthib** [comment]
The solution with guake -t works well, i'll try the recommandation

**Comment by MrDJthib** [comment]
The recommandation didn't work, I suppose the update of ubuntu updated wayland and so now makes this error

**Comment by gsemet** [comment]
i though ubuntu reversed back to x11 ?

**Comment by MrDJthib** [comment]
Yes but I made some modification in previous version and thus I still have wayland. The upgrade updated all softwares and after I've got this bug. I'll take a look on previous version of Gnome, Guake, etc. when they were working to see differences.

**Comment by gsemet** [comment]
"Because Gtk2 applications are ran in XWayland. env GDK_BACKEND=x11 would make a Gtk3 application run under XWayland too"
so guake 0.8 (on gtk2) should work natively on wayland, while gtk3 app (guake 3) should have this env var set prior to launch, apparently.

**Comment by MrDJthib** [comment]
Ok I got it I was on guake 0.8 and the Ubuntu upgrade updated it to guake 3. Finally, the recommmandation with the environment variable worked, it was because I was doing it wrong.
Thank you :smile:

**Comment by gsemet** [comment]
cool :) can you manage to make this environment variable in `/usr/local/share/applications/guake.desktop` ?
Something by replacing:
```
Exec=guake
```
by 
```
Exec= env GDK_BACKEND=x11 guake
```
will it fix for everyone ?

**Comment by MrDJthib** [comment]
Tested and it works on Wayland and X11 :)

**Comment by gsemet** [comment]
great, I'll prepare a patch on master and if you agree to test, it will please all wayland users !

**Comment by MrDJthib** [comment]
No problem :)

**Comment by deekosta** [comment]
I just ran into this issue on Arch in 2019; GNOME 3.32, fully updated, Wayland. My solution was to add a manual keybinding for the "guake" command to F12 in GNOME Settings. Works like a dream!

**Comment by samtuke** [comment]
@deekosta Works for me too (Fedora 30). For others, see [Gnome docs on custom shortcuts](https://help.gnome.org/users/gnome-help/stable/keyboard-shortcuts-set.html.en).

**Comment by charbelcs123** [comment]
Tried all solutions, still failing to bind indicator to guake:
![image](https://user-images.githubusercontent.com/16317176/82799123-35933b80-9e82-11ea-9ee9-3ded86fe3748.png)
![Uploading image.png…]()

**Comment by insign** [comment]
`env GDK_BACKEND=x11 guake-toggle`

Solution for me.
