### ISSUE TITLE
Atrocious font rendering on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by iwarford** [Guake/guake#1341]
I've just upgraded to 18.04, and the first thing that struck me was how terrible the font looks.

I use Inconsolata-LGC at 11 pt, and this has looked fine for years.  After the latest upgrade, something has made the font rendering painful to look at.  

Before:

![8770f7320935658ea08cdb06325946df](https://user-images.githubusercontent.com/119796/41004530-326803e0-68e8-11e8-9021-e4780394b0de.png)

After (zoomed in on the text to prove to myself that the pixels are indeed random colors on the screen):

![bad_font_no_donut](https://user-images.githubusercontent.com/119796/41004418-ca069c80-68e7-11e8-8f11-20152728d0f6.png)

I don't see anything in the options to control font hinting at all, if that's what's wrong.  I run XFCE so I don't have any of the Unity control panels easily accessible.

**Comment by gsemet** [comment]
hi. look like gtk3 has changed a bit. does this also apply to gnome-terminal (that share the same virtual terminal component "VTE" ?)

**Comment by iwarford** [comment]
Yes and no.  It's definitely not that great in gnome-terminal, and worse than it was before 18.04, but it's not as bad as it is in Guake.  I don't see actual differently coloured pixels in gnome-terminal.  Attached is the same chunk of the data file I used in the Before example in gnome-terminal:

![gnome-terminal](https://user-images.githubusercontent.com/119796/41010035-175965ec-6903-11e8-9c95-6a42c829e1c1.png)

It's still pretty bad compared with what it used to be, but it doesn't have the colours around the edge of the rendering.

**Comment by egmontkob** [comment]
> the pixels are indeed random colors

Not so much "random", rather it's called subpixel rendering. If set up properly, it typically improves readability. If set up improperly (e.g. GTK's belief about the order of subpixels is incorrect, perhaps you've rotated your monitor) then it might easily look terrible. Or just look up how to disable subpixel rendering in GTK if that's your preference.

An inherent problem of talking about subpixel rendering issues is that no matter how good or bad it looks for you, a screenshot doesn't convey this: on my computer it looks exactly as it would look with Guake on _my_ computer, not _yours_.

**Comment by egmontkob** [comment]
Anyway, VTE just uses GTK (Pango) rendering. If there's anything wrong, it's those components to double check. If there's a difference between Guake and GNOME Terminal then probably they are started up with different environment variables (GNOME Terminal is launched by the user's systemd via dbus, thus inheriting systemd's env variables rather than the launching context's) and the difference between the env vars causes the different behavior of GTK.

**Comment by gsemet** [comment]
you can hack the code in python pretty easily, the environment variables are propagated directly (and some are forced, like xterm-256 that might annoy you)

**Comment by Davidy22** [comment]
Closing because issue appears to come from another package
