### ISSUE TITLE
Can't disable transparecy in tab bar on Kubuntu 18.04

### ISSUE THREAD

**Issue by Fempter** [Guake/guake#1344]
Hello, 

I have Guake ver. 3.0.5 and in Kubuntu 18.04, the tab bar is transparent and I cannot remove that. Is it a bug?

![screenshot_20180607_125331](https://user-images.githubusercontent.com/25738180/41095519-e881b738-6a51-11e8-81e9-8f25f4d50fba.png)

**Comment by gsemet** [comment]
Should be fixed on HEAD

**Comment by aichingm** [comment]
The tab bar has been completely rewritten and now uses the GTKs default notebook tab bar. 

I'm closing this issue since it is not longer relevant to the code base.
