### ISSUE TITLE
[question] is it possible to change the gtk theme from command line

### ISSUE THREAD

**Issue by kufii** [Guake/guake#1345]
**Guake Version**: 3.2.1

I'm just wondering if this possible. I have a script that changes my gtk theme at night and it works on every application but guake. I tried doing dconf write, and it works, but only on reboot. Is there a way to make it apply automatically or no?

**Comment by gsemet** [comment]
Hello. I got a similar request on the gitter, why not. That would be something like a new command line argument `guake --change-palette paletename` (or `guake --next-palette`).

**Comment by ryanerwin** [comment]
It looks like commit cce2b8d above is to address the "change palette" which is fantastic and works great.

Maybe there was confusion or maybe I missed something, but it looks like #1345 is about a way to set the GTK+ theme that Guake uses from the command line.

My use case is that I frequently toggle the GTK+ theme with day/night mode toggles like Night Theme Switcher:
https://extensions.gnome.org/extension/2236/night-theme-switcher/

Ideally Guake would pick up the theme change instantly like most other GTK+ apps, but if that's not possible would be fantastic to have some way to change the theme (including the night mode setting) from the guake command line.

![image](https://user-images.githubusercontent.com/2156415/97419532-c0e69080-193c-11eb-93e2-74567b14387e.png)

**Comment by gsemet** [comment]
pull requests are welcome !
