### ISSUE TITLE
dmesg output is truncated

### ISSUE THREAD

**Issue by schnittchen** [Guake/guake#1351]
```
 ~ ✘ guake --version
Guake Terminal: 3.2.1
VTE: 0.52.2
VTE runtime: 0.52.2
Gtk: 3.22.30
```

When I excute dmesg from the shell within guake, the output is truncated. When I run it several times, it is truncated at different lines. Most of the time, I end up at the end of a dmesg line with no shell prompt. Sometimes I see this error: `dmesg: write error`.

I get at the complete output by piping into less.

**Comment by aichingm** [comment]
This seams to be a issue related to vte. 
But i can't confirm this with guake version 3.3.2 nor HEAD anyway.
Does this also happen with different terminal emulators?

**Comment by gsemet** [comment]
also does not have any problem with dmesg. Maybe install libutemp ?

**Comment by schnittchen** [comment]
I'm not currently experiencing this bug.
