### ISSUE TITLE
multiple instances with different key bindings

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#136]
multiple instances with different key bindings http://guake.org/ticket/265
Reported by:    haxwithaxe  Owned by:   somebody
Priority:   trivial     Milestone:  0.5.0
Component:  guake   Version:  
Keywords:       Cc:  
Description

this is a feature request for the ability to make different instances of guake have different key bindings (and possibly other settings) so the separate terminals could be toggled and possibly positioned separately. a trick i use with chrome is to point the different instances at different config files. maybe that would be a convenient solution :)

thanks for reading. i love guake and it's my terminal emulator of choice.

**Comment by Esavier** [comment]
I would love to have that feature implemented. It would be especially useful for admins. Each F-Key for other server group or something like this. I am kind of tired of switching each console by alt-tab :(

**Comment by vlad-zakharov** [comment]
What about the feature? It could be very useful when working with multiple monitors, especially when you  are working both on your local machine and remotely: you can open different instances of guake for local host and remote hosts binding them to different keys. 
Thx.

**Comment by Stibbons** [comment]
If you want this feature, please vote on [FeatHub](https://feathub.com/Guake/guake)
