### ISSUE TITLE
Copy URL to clipboard in right-click menu

### ISSUE THREAD

**Issue by spvkgn** [Guake/guake#1363]
In Guake 0.8 have been context menu entry for copy URL to clipboard, in Guake 3 I did not find this feature which would be useful. At least upper 'Copy' entry does not copy URL to clipboard.

Guake 3.2.2
Ubuntu 18.04, MATE Desktop 1.20, gtk 3.22.30, vte 2.91 (0.52.2)

**Comment by gsemet** [comment]
You need to select and copy the url

**Comment by aichingm** [comment]
@spvkgn What would be the difference between `copy` and `copy URL`?
I can't remember to have ever used `copy URL` so pardon my asking.

**Comment by spvkgn** [comment]
@aichingm I mean that in 0.8 the `Copy` allows to copy URL to clipboard easier - without selecting full text with mouse as it needs in 3.x.

**Comment by gsemet** [comment]
Indeed, this has been deprecated. Copy without selection means copy the current word, copy with selection will of course copy the selected text.
There is the "Open link" conditionally displayed if the cursor is on a link, maybe we can add a "copy hyperlink" item in the menu
