### ISSUE TITLE
Ubuntu 18.04 - Cannot start guake after pip3 install

### ISSUE THREAD

**Issue by tryfon** [Guake/guake#1368]
Running Ubuntu 18.04.1
After installing guake successfully with command 'pip3 install guake --user guake' running just 'guake' from the terminal throws: 'Command 'guake' not found, but can be installed with:
sudo apt install guake'
'pip3 show guake' tells me it is installed under '/home/tryfon/.local/lib/python3.6/site-packages'

How do I run it???

**Comment by gsemet** [comment]
Hi. You probably does not have ~/.local/bin in your $PATH
