### ISSUE TITLE
Ability to change X and Y position in preferences window

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#137]
Ability to chnge Y position  http://guake.org/ticket/264
Reported by:    nikom   Owned by:   somebody
Priority:   minor   Milestone:  0.5.0
Component:  guake   Version:    0.4.2
Keywords:   size position   Cc:  
Description

It would be very useful to have implemented this functionality. I, for one, would love to be able set up guake so it would show up from bottom of the screen.

**Comment by Stibbons** [comment]
Need to rework completely the window size calculation.
