### ISSUE TITLE
Guake hides behind gnome panel when multiple displays being used

### ISSUE THREAD

**Issue by jonathanballs** [Guake/guake#1373]
When using guake on multiple monitors. It will often be positioned under the top bar on the primary monitor. I have set guake to open on the monitor where my mouse is so it can open on either monitor however when being opened on the monitor with the panel it stays at the top underneath the panel. This doesn't happen when using only a single monitor.

[Example here](https://imgur.com/a/rtNeCIR)

Guake Terminal: 3.3.2
OS: Arch Linux
Displays: 2 * 1080p

**Comment by aichingm** [comment]
There is already an issue describing the same behaviour #1162. Guake has no fix for this at the moment. But a workaround which you could try, have a look at: #1167

**Comment by jonathanballs** [comment]
@aichingm I was not aware. I tried to search but there were so many open issues that I didn't see those ones.
