### ISSUE TITLE
Ctrl+D closes tab even though action is rebound

### ISSUE THREAD

**Issue by mbspng** [Guake/guake#1379]
I have rebound "close tab" to Alt-W. Ctrl-D closes tabs anyway. Given that Ctrl-D is normally expected to delete a character to the right of the cursor but unexpectedly closes a tab whence there are not characters to the right of the cursor is especially bad.

Not that my custom binding works just fine, just Ctrl-D also still performs the same action if there are no characters to the right of the cursor **and** the line is empty.

**Comment by egmontkob** [comment]
It's your shell (`bash` I presume) that decides to quit upon Ctrl-D. Consult its manpage, look for "ignoreeof", and you might also want to check the `stty` manual page looking for "eof" for further details. This has nothing to do with Guake.

**Comment by mbspng** [comment]
You are right. `set -o ignoreeof` disables this behavior in bash and zsh.
