### ISSUE TITLE
Closing old issues

### ISSUE THREAD

**Issue by aichingm** [Guake/guake#1386]
Hey @gsemet I just came by an old issue #1002 and closed it without much thinking since the OP asked to close the issue. The only reason I was able to close the issue is my resent promotion, I didn't put much thought in to it and just hit the button but I probably should have asked you first if it is ok if I close some of the fixed issues. Sorry about that! 

So here it comes: Hey, do you mind if I close some of old and fixed issues?

**Comment by gsemet** [comment]
sure, if you add the reason and set the milestone to "Next version" :)
