### ISSUE TITLE
Open Link on underlined URL not working

### ISSUE THREAD

**Issue by michaelmyc** [Guake/guake#1387]
Hi,

I'm running Arch/Manjaro, with guake 3.22.30 and gnome 3.28.3. My default browser is set to chrome. 

I'm having issues with opening the links in guake. The links are properly underlined, and the right-click menu offers the option to "open link", but I am not able to bring up a browser window no matter if I ctrl-click it or use the right-click option. 

It isn't a system-wide issue since I am able to use ctrl-click to open up chrome from gnome-terminal and built-in terminal in vscode. 

I don't know how to bring up guake log, so I can't provide more feedback. I'd be happy to go through the log if anyone tells me where they are, lol.

**Comment by gsemet** [comment]
which version of guake do you have? The version 3.22.30 does not exist

**Comment by un1whal** [comment]
Sorry, that was GTK. Guake is 3.3.2

**Comment by un1whal** [comment]
I realized that what's happening is I have to add http:// or https:// in front of the url. Plain url does not work. The output of `which xdg-open` is  `/usr/bin/xdg-open`.

**Comment by aichingm** [comment]
Yes it has to have a schema in front of it. If not everything with a dot in it would qualify as a valid url imaging for example you print a python script with `cat` every `self.property` would be a valid link.

**Comment by un1whal** [comment]
@aichingm great point, but I guess we should remove the clickability of it so it would be less confusing.

**Comment by gsemet** [comment]
Feel free to propose an update on the python code, it is not hard to read but at the end it should produce a well crafted regular expression that might be trickier to get.
