### ISSUE TITLE
Context menus hide main window in "hide on focus loss" mode

### ISSUE THREAD

**Issue by gsemet** [Guake/guake#1395]

**Comment by aichingm** [comment]
With HEAD?
That's my fault! I removed the preventHide field and didn't had time to reimplement something instead. I thought about storing the preventHide field in the window with setattr/getattr so that it is "closer" to the thing it belongs to.

**Comment by gsemet** [comment]
yes, I use hide on focus loss and I see that behavior. If you have a better idea than this weird variable, you can try, or else I will reimplement a similar boolean to prevent unwanted loss. The problem is that the window loose focus when the menu is displayed :(

**Comment by aichingm** [comment]
#1396 should fix this ;)

**Comment by aichingm** [comment]
sorry about that, it was a miss match between GdkWindow and GtkWindow... should work with the new pr :crossed_fingers: 

added a little bonus :wink:

**Comment by gsemet** [comment]
On select + right click, the context menu does not show up :)

**Comment by gsemet** [comment]
no its ok with #1397 :)

**Comment by aichingm** [comment]
What do you mean by select + right click?
