### ISSUE TITLE
Wrong auto renaming tab name

### ISSUE THREAD

**Issue by ferrwan** [Guake/guake#1398]
The auto renaming always change the last tab.
e.g
I opened 4 tabs
* focus on 1st tab, type command vim. I expected the 1st tab name to be renamed into vim, but the result is the 4th tab name change to vim
* focus on 2nd tab, type another command (sudo apt update). Expected 2nd tab name change to `sudo apt update`, but the result is the 4th tab's name change to `sudo apt update`

I'm using Ubuntu 18.04
Installed Guake from the source
Dell Latitude 3480

**Comment by aichingm** [comment]
5f8ed30 should fix this. Can you pull from me https://github.com/aichingm/guake.git and try it on master?

**Comment by gsemet** [comment]
should be fixed in HEAD :)

**Comment by ferrwan** [comment]
The renaming has fixed.

But, I found another thing in my Guake. When I paste things, it always paste in the last tab, not on focused tab.

**Comment by aichingm** [comment]
How are you pasting text by crtl+shift+v, right-click+context menu or middle-click?

**Comment by ferrwan** [comment]
`ctrl+shift+v`
