### ISSUE TITLE
multiple action on click on url

### ISSUE THREAD

**Issue by gsemet** [Guake/guake#1400]
Ctrl + click on a url => several tabs are opened (sometimes 2 or 3, sometimes more)

**Comment by aichingm** [comment]
How do you do trigger this bug? I use `echo http://www.example.com` and then ctrl+left-click on the underlined url but it only opens the url in the browser.

**Comment by gsemet** [comment]
In my system it open like 3 or 4 tabs !

**Comment by kornrunner** [comment]
I'd say this would be resolved by #1475

**Comment by robert-matusewicz** [comment]
I think that is resolved now. I tried to reproduce that Ubuntu 19.10 (Guake 3.6.3) and every time I CTRL+click on a link, it opens only one tab.

**Comment by gsemet** [comment]
great !
