### ISSUE TITLE
Documentation Update: Installing on manjaro

### ISSUE THREAD

**Issue by thatguyaknow** [Guake/guake#1429]
As per the request for info on the docs [https://guake.readthedocs.io/en/stable/user/installing.html](url) I was able to install Guake on Manjaro Gnome version 17.1.12 by simply executing this: 

pacman -S guake 

This should would on any arch-based distro with pacman installed (which is likely installed by default).

**Comment by gsemet** [comment]
Can you add your remark in the documentation by a pull requests?
