### ISSUE TITLE
"New Tab" resets colors set by "--bgcolor" command line

### ISSUE THREAD

**Issue by Speedkore** [Guake/guake#1437]
Version 3.4.1
If i set the background color from command line, which works now (thank you!), and then right click on a tab, and use "new tab" action, then all tabs reset to default colors, and i lose the background color set with the command line.

I really like this command line feature, to auto change bg color on ssh connection, and don't fuck up a server thinking that i'm in local :D

**Comment by gsemet** [comment]
look like the color is not saved per tab and so the color are refreshed somehow. Make sense to keep the color per tab (maybe we can even add a small button to change the color on each term)

**Comment by Speedkore** [comment]
Whatever will be fine if we don't lose the color 
Thank you very very very much!

**Comment by mlouielu** [comment]
guake/guake_app.py:706 self.settings.styleFont.triggerOnChangedValue(self.settings.styleFont, 'palette') trigger this, when calling terminal_spawned(term, term.pid)

**Comment by mlouielu** [comment]
When `terminal_spawned`, it should not load up config to all terminals (which is done by gsettings.fstyle_changed / fpalette_changed...etc), but only the new one

**Comment by VinnieThePooh** [comment]
Version 3.6.5 (installed via `apt install guake` on Debian 11) reproduces the problem.
I have xfce customized terminal and would like to have consistent style across all terminals including guake.

**Comment by Davidy22** [comment]
3.6.5 is not the latest version, cannot reproduce on 3.8.
