### ISSUE TITLE
`guake --new-tab dir` opens tab in $HOME dir

### ISSUE THREAD

**Issue by conformist-mw** [Guake/guake#1451]
- `Guake Terminal`: 3.4.0
- `VTE`: 0.54.1
- `VTE runtime`: 0.54.1
- `Gtk`: 3.24.1

expected: 
`guake -n Downloads` open new tab and switch directory to Downloads (as in early versions)

actual:
always change dir to `$HOME`.

**Comment by rodrigopitanga** [comment]
Can reproduce it on 3.4.1.
Fixed, PR on the way.
