### ISSUE TITLE
word_chars can not be changed on Ubuntu 18

### ISSUE THREAD

**Issue by romange** [Guake/guake#1454]
Version: 18.04.1
1. `gconftool-2 --type string --set /apps/guake/general/word_chars -- ` does not change the behavior of word chars
2. `gsettings  set guake.general word-chars` does not change the behavior of word chars.

* Tried to add `:` to the list or remove `~` but did not succeed to change the behavior.

**Comment by Davidy22** [comment]
`gsettings set guake.general word-chars "-A-Za-z0-9,./?%&amp;#:_"` should set a new value for word-chars. Guake reads this on startup, so you'll need to restart guake for this setting to take effect. gconftool-2 will not affect guake.
