### ISSUE TITLE
Ansi code RCP not working after xUbuntu upgrade

### ISSUE THREAD

**Issue by mbirth** [Guake/guake#1461]
- **Guake Version**: 3.3.0 (`3.3.0-1`)
  - Please describe **your system**: xUbuntu 18.10 / Gtk2 `2.24.32-3ubuntu1` / Gtk3 `3.24.1-1ubuntu2`

I have a script that uses SCP and RCP for prettier output. This worked fine with xUbuntu 18.04 and Guake 3.0.5-1. After the upgrade to 18.10, RCP now doesn't seem to work anymore. The text appears directly after each other instead of new items overwriting the previous ones.

![image](https://user-images.githubusercontent.com/130302/48770753-b8509e80-ecbf-11e8-9fbc-7a3800857025.png)

The release names like `tara???` should only appear while it's checking and at the end be overwritten by the slightly gray `bionic` at the end of the line.

The tool I've used is https://github.com/mbirth/apt-urlcheck .

**Comment by egmontkob** [comment]
This is a [regression in VTE 0.54.0 and 0.54.1](https://gitlab.gnome.org/GNOME/vte/issues/48), 0.54.2 fixes it. There's nothing Guake developers could do here, you should ask Ubuntu to release new vte2.91 packages with the fix backported.

**Comment by mbirth** [comment]
If other people want to chime in: https://bugs.launchpad.net/ubuntu/+source/vte2.91/+bug/1804457
