### ISSUE TITLE
URLs with special characters get uncomplete recognized

### ISSUE THREAD

**Issue by marzzzello** [Guake/guake#1463]
Guake version: 3.3.2
I tried to install the newest version via AUR and also like desriped in docs but both failed with 
```
Traceback (most recent call last):
  File "/usr/local/bin/guake", line 6, in <module>
    from guake.main import exec_main
ModuleNotFoundError: No module named 'guake'
 ```
I am on Arch-Linux and Gnome 3.30.2.

So I have a question/bug about the klickable URLs:
Is intended that links with special characters are not correctly recognized? The Gnome Terminal behaves like Guake too. But eg. Yakuake does recognize the complete URL.
![bildschirmfoto von 2018-11-25 17-18-38](https://user-images.githubusercontent.com/15198431/48981667-88930380-f0d0-11e8-9c42-8572ad860bda.png)
The URL from the second and third echo is recognized including the first special character but the rest gets cut off.

A workaround could be to use something like this (from #945):
```
echo -e '\e]8;;file:///path/to/aaäaa/file\e\\This is a file\e]8;;\e\\'
```

**Comment by gsemet** [comment]
That's a regular expression problem. Your solution is to use \e]8 magic, sorry.
