### ISSUE TITLE
guake trasnsparenry not work

### ISSUE THREAD

**Issue by liqiang0330** [Guake/guake#1477]
guake trasnsparenry not work on debian sid i3wm 

my computer:
debian sid
kernel:4.11.0-2
i3wm 

guake terminal:3.4.0
vte:0.54.2
gtk:3.24.2

at the same time .lxterminal transparency can work .just guake can not work..

**Comment by gsemet** [comment]
works pretty well here, does not see what may prevent it from working. Maybe a bug in the VTE component ?
