### ISSUE TITLE
Closing a tab by shortcut broken after update from 3.3.2 to 3.4.0

### ISSUE THREAD

**Issue by jesusofsuburbia** [Guake/guake#1478]
Hi everyone,

I upgraded guake a while ago to ` 3.4.0` on Arch (`4.19.12-arch1-1-ARCH`), Gnome is [up-to-date](https://www.archlinux.org/groups/x86_64/gnome/).

(_as described below, the upgrade happened on 12/12/18, but it looks like I started using the new version after a reboot today_)

Guake Version:
> Guake Terminal: 3.4.0
> VTE: 0.54.3
> VTE runtime: 0.54.3
> Gtk: 3.24.2

## The Bug

Closing a Tab by shortcut is broken. It works without issue when using middle-click or the right-click menu.

When running `guake --verbose`, I get the following error when I press the shortcut to close a Tab:

> TypeError: delete_page_current() takes from 1 to 2 positional arguments but 5 were given

Note that this seems to be the case independent from the selected shortcut. I chose different shortcuts, the bug is the same.

I thought it was due to an update from `3.3.x` to `3.4.0` ~~but I can't prove this at the moment~~. My `pacman.log` shows the update happened on 12/12/18 ~~but I'm not sure if I rebooted in-between.~~. EDIT: it definitely happened after the upgrade (after looking through the journal and pacman.log).

Thanks for your work. I follow this issue and can provide more info if needed!

**Comment by haleuh** [comment]
Confirmed on Ubuntu 18.04 as well with the master version.

**Comment by HaoyeTang** [comment]
Same here on Arch

**Comment by jesusofsuburbia** [comment]
>  EDIT: Just ran from source, the bug was apparently fixed so just wait for the next release :>

@HaoyeTang thanks a lot for the info! That's some great news!
