### ISSUE TITLE
"Copy" mode to allow selection using the keyboard only

### ISSUE THREAD

**Issue by krlmlr** [Guake/guake#148]
In this "Copy" mode, the caret can be moved with the keys on the keyboard, and selection can be started and stopped by pressing, say, `Space`. Stopping the selection also copies it to the clipboard.

Very similar features are available in GNU `screen` and Windows's `cmd.exe`. It would be nice if Guake could support this natively.

Fixes #147.

**Comment by Stibbons** [comment]
If you want this feature, please vote on [FeatHub](https://feathub.com/Guake/guake)
