### ISSUE TITLE
Transparency doesn't work in Ubuntu 18.04 bionic/KDE 5.44.0/Plasma 5.12.7

### ISSUE THREAD

**Issue by Legionof7** [Guake/guake#1488]
- **Guake Version**: Guake Terminal 3.0.5

When I slide the transparency slider, Guake doesn't turn transparent, it just applies a gray background. 
![image](https://user-images.githubusercontent.com/6224601/51231085-1d6aee00-1917-11e9-9b19-44a8fd19ed06.png)

**Comment by Arakananta** [comment]
Have you try to reinstall? I just install Guake three or four days ago and the transparancy working properly
im using Ubuntu 18.04

![ubuntu 18 04 01-2019-01-28-03-10-31](https://user-images.githubusercontent.com/33978908/51806334-776e9a80-22ab-11e9-88b5-b5a64de855a9.png)

**Comment by Legionof7** [comment]
Fixed, need to change Compositor Rendering Backend settings. 
![image](https://user-images.githubusercontent.com/6224601/53382049-be41c580-3927-11e9-8086-8ac3e6a001e5.png)
