### ISSUE TITLE
No option to set a background image in version 3.4.0

### ISSUE THREAD

**Issue by daf0x** [Guake/guake#1495]
> Yes this option is removed. Vte (the underlying terminal emulator) has removed support for background images and reimplementing it in guake itself would be a not so easy task.
> 
> _Originally posted by @aichingm in https://github.com/Guake/guake/issues/1297#issuecomment-383323815_

For me this seems to be a case of  **[Citation needed]**...

Currently (x11-libs/vte-0.28.2-r208) the VTE demo app (`/usr/bin/vte`) still has the `--background` option:
```$ /usr/bin/vte --help
Usage:
  vte [OPTION…]  - test VTE terminal emulation

Help Options:
  -?, --help                     Show help options
  --help-all                     Show all help options
  --help-gtk                     Show GTK+ Options

Application Options:
  -A, --antialias                Disable the use of anti-aliasing
  -B, --background               Specify a background image
  -C, --console                  Watch /dev/console
  ...
```
Starting `vte` with this option and an image also works just fine. So as far as I can tell, there is nothing from preventing this option from working in Guake, too.

**Comment by gsemet** [comment]
Yes, this is no more supported by VTE. Sorry for the broken feature.
