### ISSUE TITLE
Show/hide key confused with `guake --show -s 0`

### ISSUE THREAD

**Issue by Huge** [Guake/guake#1499]
**a bug**: after firing up Guake with `guake --show -s 0` the toggle key( default F12) is confused as it doesn't hide the guake window and second press is needed.  This is weird a bug as it doesn't happen, ie. works fine, when using `guake --show` without the argument for tab swiching.
 
  - **Guake Version**: 3.4.0
  - Fedora 29

**Comment by mlouielu** [comment]
Invoke by guake/main.py, when calling with some option, it will set `only_show_hide` to False, causing not to call `remote_object.show_hide()`, and `-s` is one of the option that will set it to False
