### ISSUE TITLE
--new-tab does not change current directory to NEW_TAB parameter

### ISSUE THREAD

**Issue by luchano** [Guake/guake#1504]
Either guake --new-tab o guake -n does not honor the NEW_TAB parameter and does not change the current dir to NEW_TAB

**Guake Version**:  3.4.0
**System** Archlinux  with GNOME Version 3.30.2

**Comment by ivoshm** [comment]
I think it's duplicate of #1451 ... patch is in source already (and works) but not released in version yet.

**Comment by luchano** [comment]
Sorry, didn't show up when search for duplicated issues
