### ISSUE TITLE
Guake always uses dark colors

### ISSUE THREAD

**Issue by Rapti** [Guake/guake#1507]
In a recent update, Guake started only using the theme's dark colors (the top row in Guake's appearance settings). Guake always displays the darker color, even if it should display the brighter one.
In other words: `\033[0;32m` and `\033[1;32m` produce the same color. They produced different colors previously. The latter one still causes text to be bold though.

  - **Guake Version**: 3.4.0
  - My System: Arch Linux 64 bit (fully up to date)
  - WM: KDE Plasma

**Comment by egmontkob** [comment]
This was an intentional change in VTE 0.56. For details, see:
- #1089 
- https://bugzilla.gnome.org/show_bug.cgi?id=762247
- https://bugzilla.redhat.com/show_bug.cgi?id=1687141
- https://bugs.launchpad.net/terminator/+bug/1820544

**Comment by Rapti** [comment]
Hm. Thanks. I see why this behavior is pretty outdated, but it would be great if Guake added a checkbox to reenable this behavior as plenty of programs still rely on it.

**Comment by eli-schwartz** [comment]
@Rapti I implemented the option and released a new package for Arch Linux with it cherry-picked.

I did not notice the change for a while after the vte3 update until I restarted, and then spent the last day trying to figure out what changed, where. :p

**Comment by Rapti** [comment]
That's great to hear. Thank you!
