### ISSUE TITLE
tab labels not diplayed in fullscreen mode

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#151]
tab labels not diplayed in fullscreen mode  http://guake.org/ticket/259
Reported by: 	bluh 	Owned by: 	somebody
Priority: 	trivial 	Milestone: 	0.5.0
Component: 	guake 	Version: 	0.4.2
Keywords: 		Cc: 	
Description

would be nice if there was an option to also display the tab labels in fullscreen mode.

**Comment by manoevis** [comment]
@egustavson thanks, this trick works, but I've edited it before compiling in path_to_cloned_guake_repo/src/guake/guake_app.py

**Comment by manoevis** [comment]
sure, done. #439 pr.

**Comment by Stibbons** [comment]
thanks!
