### ISSUE TITLE
Right-Click+Close closes two tabs instead of one

### ISSUE THREAD

**Issue by amezin** [Guake/guake#1513]
- **Guake Version**: 3.5.0
  - Arch Linux, Gnome 3.32.0, vte3 0.56.0

After the fix for https://github.com/Guake/guake/issues/1438 (https://github.com/Guake/guake/pull/1505) was merged, right-click+Close closes two tabs, the one that I intended to close, and also a tab after it. Only closing the last tab works correctly (because theres nothing after it)

Reverting the patch restores the correct behavior, only one tab gets closed

**Comment by ivoshm** [comment]
I have no issue on:
* *Guake Version:* 3.5.0
* Manjaro Linux (Arch based), XFCE 4.13 on GTK 3, vte3 0.56.0

Maybe specific GNOME problem ...

**Comment by mlouielu** [comment]
Should this be resolved by #1515, I revert the #1438 in it

**Comment by gsemet** [comment]
I close as fixed. If the issue reappear can you open a new ticket ?
