### ISSUE TITLE
Closing a tab fails and makes it white and unusable

### ISSUE THREAD

**Issue by tryfon** [Guake/guake#1532]
Ubuntu 18.04 up to date, Guake 3.5.0

When closing a tab it doesn't close and becomes white and unusable. After this happens every new tab doesn't assume a proper name, doesn't have any transparency and guake refuses to quit, I have to kill it every time. Are there any logs somewhere I could attach to this ticket?

**Comment by gsemet** [comment]
Should be linked to our notebook rework

**Comment by AleksandrGilmanov** [comment]
As i found, it happened after 3.3.0 and before 3.4.0.
Also if we have single console in the single tab and type "exit" or close it with right click -> close terminal it works correct.
Also such broken terminals appears even if we remove session.json file - I can't "forget" this sessions.

Hope it'll help. And thanks for guake - it's great.

**Comment by gsemet** [comment]
Fixed in #1548
