### ISSUE TITLE
Logging to file

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#155]
Logging to file  http://guake.org/ticket/239
Reported by: 	markstinson 	Owned by: 	somebody
Priority: 	trivial 	Milestone: 	0.5.0
Component: 	guake 	Version: 	0.4.1
Keywords: 		Cc: 	
Description

It would be nice if saving the backlog or terminal to a file were possible.

**Comment by riOwnage** [comment]
Has anyone found a way to automatically log files with timestamps in the name with a python script instead of right click and save as?
