### ISSUE TITLE
New feature "search box" doesn't look good with dark GTK themes.

### ISSUE THREAD

**Issue by chax** [Guake/guake#1561]
Hi, i just tested this new feature and i must say search box doesn't look good with dark theme because overlay background is light-colored and dark themes usually have light-colored fonts, so it's barely visible and it's very hard to read what you type. At first i thought it's not working because i couldn't see the text at all until i really focused my eyes on the search box. Also, background is not transparent as the rest of the terminal, so it looks really ugly and it really stands out from the rest of design. At least make background the right color (the one provided by the current selected GTK theme).

  - **Guake Version**: 3.6.0
  - System: Solus Budgie
    - i packaged Guake myself to test new 3.6.0 features, this version is still not in official Solus package repository

This is probably due to hardcoded value of background color as can be seen here:
https://github.com/Guake/guake/blob/0bba1b06e63584193157e5f670f67e7aa5b17a52/guake/boxes.py#L118-L121

**Comment by mlouielu** [comment]
Hi @chax, can you help to upload a picture of your Guake?

So we have three problems:
* Terminal background color isn't correct
* Search highlight color didn't fit your theme, and
* Search box background color

right?

thanks

**Comment by chax** [comment]
![image](https://user-images.githubusercontent.com/632945/56801525-ea8d9b80-681d-11e9-8546-f70a119a7f6c.png)

**Comment by mlouielu** [comment]
@chax thanks for your picture, I'll take a look to fix this.

So, terminal didn't affect, but:
* Search box's text entry cannot see the text
* Search box background color isn't fit to theme

**Comment by chax** [comment]
That is correct assessment.

**Comment by chax** [comment]
i tried to replace line 120 ` b'    background-color: #CFCFCF;' `
with line ` b'    border: none;' `
and for me, it looks much better already
i will provide screenshot so you can see for youself.

**Comment by chax** [comment]
![image](https://user-images.githubusercontent.com/632945/56804135-0183bc00-6825-11e9-9187-97aa9494254f.png)

**Comment by gsemet** [comment]
Ok. I have no pbl on "Adwaita" theme.

![Capture du 2019-04-26 13-29-18](https://user-images.githubusercontent.com/133498/56804917-a1424980-6827-11e9-9626-af6f88ad6f62.png)

We probably do no want to hardcode any background color and take the one from the theme

**Comment by chax** [comment]
Then this should be easy fix, should i expect next release 3.6.1 soon?

**Comment by mlouielu** [comment]
Remove hardcode background-color with Adwaita theme:
![Selection_967](https://user-images.githubusercontent.com/28770408/56805256-08c5bc80-685b-11e9-9c5e-4693d97da3be.png)

The Gtk.Frame will get no color when looking at it. Trying to fix this with both light/dark theme

**Comment by chax** [comment]
It also looks better without borders, therefore i set `border: none`

**Comment by gsemet** [comment]
Here what I have on HEAD:
![Capture du 2019-04-26 14-56-27](https://user-images.githubusercontent.com/133498/56809358-eec4b380-6833-11e9-8242-0a2623aacbc9.png)
![Capture du 2019-04-26 14-56-54](https://user-images.githubusercontent.com/133498/56809365-f1bfa400-6833-11e9-84a2-309ae5684b85.png)
![Capture du 2019-04-26 14-57-18](https://user-images.githubusercontent.com/133498/56809370-f421fe00-6833-11e9-8757-50d4ef9aeb32.png)

**Comment by chax** [comment]
Nice, much better already, but i also like how it looks without background. Can you make than as a checkbox option somewhere in settings to have no background at all? If that would be to complicated, i'm good with this solution also. At least it takes theme colors now, so it's consistent with rest of design.

**Comment by gsemet** [comment]
I tried transparency it displays the background not the terminal. Don't know how to do it better, but @mlouielu  PR does the job with the background color. I release 3.6.1 asap

**Comment by chax** [comment]
Very good, this was very fast response in solving this issue. Thanks to both @gsemet and @mlouielu in fixing this so quickly. I'm waiting for 3.6.1, so i can do the packaging for Solus.

**Comment by mlouielu** [comment]
No problem, thanks for you quickly report on this :)

I think for transparent the search box & un-padding search box should open another feature request issue.

**Comment by chax** [comment]
Yep, for now, this is perfect.
