### ISSUE TITLE
tab save fails on splitted terminal (DualTerminalBox)

### ISSUE THREAD

**Issue by gsemet** [Guake/guake#1571]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/guake/utils.py", line 82, in wrapper
    g.save_tabs()
  File "/usr/local/lib/python3.5/dist-packages/guake/guake_app.py", line 1162, in save_tabs
    'directory': page.child.terminal.get_current_directory(),
AttributeError: 'DualTerminalBox' object has no attribute 'terminal'
```

**Comment by gsemet** [comment]
@mlouielu can you look at this, look like split terminal is not fully supported by tab session save :)

**Comment by mlouielu** [comment]
Yep, I'm trying to implement split save/restore now
[mlouielu/guake/wip-save-restore-terminal-split](
https://github.com/mlouielu/guake/tree/wip-save-restore-terminal-split?files=1
)

But I remember it still will store the first terminal (or last focus, I
guess) in current version

Gaetan Semet <notifications@github.com> 於 2019年4月30日 週二 21:56 寫道：

**Comment by mlouielu** [comment]
Here is the WIP: [wip-save-restore-terminal-split](https://github.com/mlouielu/guake/tree/wip-save-restore-terminal-split?files=1)

**Comment by gsemet** [comment]
ok

**Comment by mlouielu** [comment]
After testing now, an `DualTerminalBox` will block `save_tabs`... I'll make it work ASAP

**Comment by mlouielu** [comment]
@gsemet Can you take a test on [wip-save-restore-terminal-split](https://github.com/mlouielu/guake/tree/wip-save-restore-terminal-split)?

For Gtk-CRITICAL, I've opened an issue [on VTE](https://gitlab.gnome.org/GNOME/vte/issues/122)

**Comment by gsemet** [comment]
Ok i la Check it tomorrow

**Comment by gsemet** [comment]
Confirmed: your fork seem to support splitted screen pretty fine :)
