### ISSUE TITLE
3.6.2 no longer shows tray icon

### ISSUE THREAD

**Issue by eli-schwartz** [Guake/guake#1572]
While attempting to package https://github.com/Guake/guake/releases/tag/3.6.2 for Arch Linux, I discovered that the new version no longer shows a tray icon. This happened between 3.6.1 and 3.6.2.

Possibly fallout from reorganizing the data directory? I'm not clear on what changes are expected to be made as a result of this -- the files are being packaged in their new location, but not being picked up by my test package.

**Comment by mlouielu** [comment]
Could it be the preferences be accidentally changed by cancel `General/General/Show tray icon`?

I've using [PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/guake) and change `_commit` to tag/3.6.2, build it by `makepkg -Acs`, installed by `pacman -U`, when run up Guake, the tray icon still appear in my LXDE.

**Comment by eli-schwartz** [comment]
I did not modify those preferences at all, but had downgraded... re-updating to guake 3.6.2 it works. I have no idea how it stopped working before, in that case. :/

**Comment by gsemet** [comment]
Hum, that’s weird :(
