### ISSUE TITLE
Add background image to guake

### ISSUE THREAD

**Issue by mlouielu** [Guake/guake#1603]
FeatHub: https://feathub.com/Guake/guake/+22

We've the reference from https://github.com/gnunn1/tilix/issues/576 & https://github.com/gnunn1/tilix/commit/7ccb7f1c329ec7bb731f13d1f5ab5b157c2032f9 that background image can add back without modifying VTE, only done by cairo.

Here is the WIP preview on guake: 
![Guake!_978](https://user-images.githubusercontent.com/28770408/57824801-e32f3180-77ce-11e9-9ed8-60efe56f2cce.png)

**Comment by egmontkob** [comment]
FYI: See also [vte bug 767575](https://bugzilla.gnome.org/show_bug.cgi?id=767575) and its result `vte_terminal_set_clear_background()` available since vte 0.52.

**Comment by mlouielu** [comment]
Ah, finally know why `vte_terminal_set_background_operator` [was removed](https://gitlab.gnome.org/GNOME/vte/commit/bc532dc160406aaea35756e9a9e8f755c82fddb2).

But I wonder if that is needed? I've use `set_clear_background(False)` when I'm testing with VTE, but for guake, it only get wierd background color whenever I choice which palette:

![Guake!_979](https://user-images.githubusercontent.com/28770408/57838851-13d79100-77f8-11e9-9596-2327e7605234.png)

My solution is to add the `draw` callback with `connect_after`:

https://github.com/Guake/guake/blob/74645dc816b8f46f8ecce12a88b421cb4e3f00b2/guake/notebook.py#L338-L340

Which were use `connect` by [xfce4-terminal](https://git.xfce.org/apps/xfce4-terminal/tree/terminal/terminal-screen.c?id=f784f668abe9dc8a35fa53a2032eddb52ac526a9#n272) and [tilix](https://github.com/gnunn1/tilix/blob/master/source/gx/tilix/session.d#L1002)

So in the lifecycle, it will call the callback after VTE draw:

```
INFO     Showing the terminal
vte_terminal_get_preferred_height()
vte_terminal_get_preferred_width()
vte_terminal_realize()
vte_terminal_map()
vte_terminal_size_allocate()
vte_terminal_get_preferred_height()
vte_terminal_get_preferred_width()
vte_terminal_draw()
draw root_terminal_box
```

Thus, we will not overlapped by VTE draw now. But maybe some performance drop, since we draw the child twice.

Not sure do I lost something inside the fancy cairo world... how do you think @egmontkob?

**Comment by mlouielu** [comment]
tilix with `addOnDraw(&onDraw)`:
![Selection_980](https://user-images.githubusercontent.com/28770408/57840260-dd4f4580-77fa-11e9-8f0a-323cff3f4fc0.png)

tilix with `addOnDraw(&onDraw, ConnectFlags.AFTER)`:
![Selection_981](https://user-images.githubusercontent.com/28770408/57840283-e8a27100-77fa-11e9-86f7-7f017d4647c9.png)

In this way, if the background image it transparent, it can also transparent to background (which chris said that always is transparent or background image, not transparent + background image)

CC @gnunn1

**Comment by egmontkob** [comment]
Unfortunately I'm not familiar enough with the story to help you any further.

**Comment by Davidy22** [comment]
Feature is merged, closing issue.
