### ISSUE TITLE
Terminal unclickable at bottom right by search box

### ISSUE THREAD

**Issue by Speedkore** [Guake/guake#1609]
I would like to know if I'm the only one with this problem, seems that in the bottom right side of the window terminal does not respond to left click or right clicks, so i can't click in the scroll bar to scroll up when i have a long scroll history, or start selecting a line command from there. It is like a little zone where mouse clicks doesn't work.

-------------------------------------------------------------------------------
Guake Version:		3.6.4

Vte Version:		0.54.2

Vte Runtime Version:	0.54.2

--------------------------------------------------
GTK+ Version:		3.24.5

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: lightdm-xsession

--------------------------------------------------
Display: :0.0

RGBA visual: True

Composited: True

* Monitor: 0 -  VGA-1
    * Geometry:		1920 x 1148 at 0, 0
    * Size:		508 x 304 mm²
    * Primary:		True
    * Refresh rate:	59.96 Hz
    * Subpixel layout:	unknown

**Comment by mlouielu** [comment]
My first thought is because the search box (is hide when not call, but it
is still there)

I'll take the to verify it.

Speedkore <notifications@github.com> 於 2019年5月20日 週一 16:14 寫道：

**Comment by gsemet** [comment]
Probably the searchbox indeed
