### ISSUE TITLE
Guake properties looks bad on double DPI.

### ISSUE THREAD

**Issue by Yournished** [Guake/guake#1612]
When Cinnamon is set to "Double (Hi-DPI)" in Cinnamon settings (the program is called "General"), the title of the window is over-cropped:

![guake](https://user-images.githubusercontent.com/12552668/58386492-11c6bc80-7fc6-11e9-8973-67698cc51d75.png)

This is for Guake 0.8.8 and Debian 9 stable.

**Comment by mlouielu** [comment]
Hi @Yournished, could you take a look at [install from source](https://guake.readthedocs.io/en/latest/user/installing.html#install-from-source) and re-test again?

For what I know, 0.8.8 is the legacy version using gtk2, and is not maintained now.

**Comment by Yournished** [comment]
@mlouielu Actually, I hadn't realized how old 0.8.8 was - it seems like a lot of libraries changed between 0.8* and 3.* and so Debian stable (stretch) must have been stuck on the old one. I ended up upgrading to Debian testing (buster) and getting Guake 3.4.0 which does not have this issue.

It is probably not worth trying to fix the 0.8.8 bug - for instance Debian is apparently planning to make buster the stable version soon. As I no longer have the problem, I'll close the issue. Sorry to bother you guys!
