### ISSUE TITLE
Exit command doesnt work

### ISSUE THREAD

**Issue by BeatLink** [Guake/guake#1614]
**Describe the bug**

Running the command `exit` results in that tab freezing

**Expected behavior**
The tab should close. If it is the last tab, guake should either quit or hide

**Actual behavior**
The tab freezes, there is no more prompt and the tab cannot be closed manually from the context menu

**To Reproduce**

enter the command `exit` in any guake tab

-------------------------------------------------------------------------------

Usage: guake [options]

guake: error: no such option: --support

(Guake 3.0.5)

**Comment by mlouielu** [comment]
Hi there,

Could you install guake via source and test it again? Since 3.0.5 is an old
version and such a issue has been fixed in latest version.

Thanks.

BeatLink <notifications@github.com> 於 2019年6月10日 週一 02:02 寫道：

**Comment by BeatLink** [comment]
Sure thing

**Comment by BeatLink** [comment]
Issue Resolved! Turns out it was just the old version in the default repositories
