### ISSUE TITLE
Typing exit freezes/blocks the terminal

### ISSUE THREAD

**Issue by dulex123** [Guake/guake#1619]
**Describe the bug**

If you run `exit` it will freeze the guake terminal window.

**Expected behavior**

Close the window

**Actual behavior**

What you actually get.

**To Reproduce**

Provide the steps to reproduce the behavior

**Comment by gsemet** [comment]
you need to install the libtemp0 library

**Comment by dulex123** [comment]
@gsemet Do you know the appropriate debian package name?

**Comment by gsemet** [comment]
It is written in our online doc

**Comment by dulex123** [comment]
Thanks. For any future reference the package can be installed with:
sudo apt-get install libutempter0. 

Any ideas why this isnt a hard dependency? It kinda breaks normal behaviour, shoud be mandatory.

**Comment by gsemet** [comment]
It is on a recent package (or it should). I do know if the packager has updated it

**Comment by dulex123** [comment]
thanks!
