### ISSUE TITLE
Tray icon

### ISSUE THREAD

**Issue by alabotski** [Guake/guake#1623]
Linux Mint 19.1 Cinnamon
So icon is displayed in the tray

![image](https://user-images.githubusercontent.com/439337/60764960-8c8df780-a09b-11e9-86f0-72c96a6c1323.png)

**Comment by ivoshm** [comment]
Probably duplicate with  #1110.

**Comment by gsemet** [comment]
do you have hires screen?

**Comment by alabotski** [comment]
What screen?

**Comment by Davidy22** [comment]
Closing because of duplicate of #1110, provide updates in that bug report if more information can be contributed.
