### ISSUE TITLE
Giving back to guake

### ISSUE THREAD

**Issue by aichingm** [Guake/guake#1629]
Sorry this took so long (busy university term and I had to sort out things with bountysource).

@gsemet Just claim it, it's not as much as I thought after taxes and stuff but It should help keep the show running.

I hope to have a little more time to contribute in the near future.

https://www.bountysource.com/issues/77904161-giving-back-to-guake

**Comment by Davidy22** [comment]
Leaving a reminder ping to @gsemet here because you might be interested in this. Also, github has a built in sponsor feature now that we could enable for future things along these lines.

**Comment by gsemet** [comment]
Ok, i try to claim the money and will put here a little accountancy of what will be done with it. The main expanses I have is only the domain name guake-project.org which should be 12$ a  year.
