### ISSUE TITLE
hotkey to toggle "hide on lose focus"

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#163]
hotkey to toggle "hide on lose focus"  http://guake.org/ticket/220
Reported by:    elitak  Owned by:   somebody
Priority:   trivial     Milestone:  
Component:  guake   Version:    0.4.1
Keywords:       Cc:  
Description

I found having a hotkey to toggle the "hide on lose focus" state useful for when I want to keep the console up in certain situations, like when I want to copy something from there. Here's my patch that adds this feature. I also cleaned up one of the related methods.

I'd recommend changing all instances of "lose focus" with "blur", but I realize that's probably just a personal preference. Feel free to modify my patch in this respect before accepting it.

**Comment by johnbeard** [comment]
Is this done by 3ca057a41999e77bf0f358ef0c10d87b7d41bcac?

**Comment by SergiyKolesnikov** [comment]
This one is implemented and can be closed.

**Comment by ernstki** [comment]
This is the same issue as #107, and I think that one could be closed as well.

People who once used [Visor](https://visor.binaryage.com/) / TotalTerminal on OS X might use this vocabulary of "pinning" the terminal open, because that's what Visor called it.
