### ISSUE TITLE
building old versions

### ISSUE THREAD

**Issue by brandor5** [Guake/guake#1631]
I'm debugging issues on a new laptop (and change of guake version) and trying to build a previous version of guake to see if the issue is the newer version of guake or something else.

However, when I checkout a tag and attempt to build I always end up with the latest version.

Is it possible to build older versions? Am I just missing something?

I'm on fedora 30 and attempting to build 3.4.0 or 3.5.0.

Thanks!

**Comment by aurora-of-earth** [comment]
@brandor5
> Is it possible to build older versions? Am I just missing something?

Yes, you are.
Go to <a href="https://github.com/Guake/guake/releases">github.com/Guake/guake/releases</a> and get an older source snapshot and build it.

**Comment by Davidy22** [comment]
You also need to make sure you've uninstalled guake in all other locations when building from source, or you'll just have your regular guake installation pop up.
