### ISSUE TITLE
Toogle Shortcut is not working

### ISSUE THREAD

**Issue by isashi** [Guake/guake#1640]
Hello,
I recently got an issue when I try to toggle the guake terminal with shortcuts. I've been using Guake for more than one year and I never got this problem. I haven't changed anything on my system/configuration except the daily regular "sudo dnf update".
If I open Guake with the icon, it appears and works normally.

Here's more info about my system:
OS: Fedora 30
DE: Gnome
Kernel: 5.2.9-200.fc30.x86_64

Let me know if there is any more information I need to provide.

**Describe the bug**
Cannot toggle visibility of guake terminal throught shortcut

**Expected behavior**
Pressing my toggle visibility shortcut should show the guake terminal

**Actual behavior**
If I press the shortcut nothing happens. I tried to change the shortcut for the toggle visibility in the Guake Preferences but I received the following error:

> A problem happened when binding {{ my_shortcut }} key. Please use Guake Preferences dialog to choose another key.

I already tried different shortcuts and I get this error message ONLY if I try to change the "Toggle Guake Visibility" (I can normally change the shortcuts of the other actions)

**To Reproduce**
Press the toggle guake visibility #shortcut

-------------------------------------------------------------------------------
$ guake --support
Guake Version:		3.6.3

Vte Version:		0.56.3

Vte Runtime Version:	0.56.3

--------------------------------------------------
GTK+ Version:		3.24.10

GDK Backend:		__gi__.GdkWaylandDisplay

--------------------------------------------------
Desktop Session: gnome

--------------------------------------------------
Display: wayland-0

RGBA visual: True

Composited: True

* Monitor: 0 - BOE 0x06a9
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		340 x 190 mm²
    * Primary:		False
    * Refresh rate:	60.01 Hz
    * Subpixel layout:	unknown

**Comment by aurora-of-earth** [comment]
@Isashi That's a problem with Wayland.
Guake doen't support wayland very well.
To fix this issue:
- Remove the guake shortcut from inside of guake itself, if you've set it there at all.
- Go to GNOME's Settings > Devices > Keyboard
- Scroll down the screen and add a custom shortcut.(put 'guake' in the 'Command' field)

That's all.

**Comment by Isashi** [comment]
@aurora-of-earth Thanks a lot, the suggested workaround is perfect.

**Comment by freekvh** [comment]
> @Isashi Guake doesn't support wayland very well, there's no problem with GNOME; You'll have the same sort of issue on KDE Plasma or any other desktop environment.
> To fix this:
> 
>     * Remove the guake shortcut from inside of guake itself, if you've set it there at all.
> 
>     * Go to GNOME's Settings > Devices > Keyboard
> 
>     * Scroll down the screen and add a custom shortcut.(put 'guake' in the 'Command' field)

Except, I can't disable the Guake shortcut. Delete does nothing.

**Comment by aurora-of-earth** [comment]
@freekvh 
> Except, I can't disable the Guake shortcut. Delete/Backspace does nothing.

Go to GNOME's Settings > Devices > Keyboard Shortcuts
Then scroll down to the list of Custom Shortcuts, then select guake from the list and click on remove.

**Comment by freekvh** [comment]
> @freekvh
> 
> > Except, I can't disable the Guake shortcut. Delete/Backspace does nothing.
> 
> Go to GNOME's Settings > Devices > Keyboard Shortcuts
> Scroll down to the list of 'Custom Shortcuts', then select guake from the list and click on 'Remove'.

That is not the shortcut I want to disable, I want to disable Guake's one (which fails to set every time one logs in causing an error notification). Try to use Guake on Wayland, you will know what people mean.

**Comment by zevdg** [comment]
Go to apps/guake/keybindings/global/show-hide in dconf-editor and set custom value to `disabled`.

**Comment by vinyll** [comment]
What worked for me:
1. disabled Guake shortcut in Guake preferences
2. set a gnome shortcut (settings > keyboard > view and customize shortcuts > custom shortcuts > + ), give a name (eg: "guake toggle"), set `guake -t` as command et define my favorite shortcut
3. click "Add" to save and it's all :+1:

**Comment by Davidy22** [comment]
There's some amount of reports on wayland that I've missed when cleaning these up, but the solution to all of them is just about what @vinyll describes because wayland blocks the built in guake toggle shortcut. I would recommend using `guake-toggle` over `guake -t` though, it's a little bit faster because it strips out some extra stuff.

**Comment by freekvh** [comment]
I don't think this is solved because the issue is that when you switch between X and Wayland every now and then (because you sometimes use your Nvidia card but normally the battery saving on board graphics, for example), under X you'll have a double shortcut now. This will cause Guake to open and close immediately again. A solution would be that we can disable native toggling entirely and leave it up to Gnome under both X and Wayland...

**Comment by Davidy22** [comment]
You can actually already disconnect Guake's native toggling by unsetting `toggle guake visibility` in keyboard shortcuts in preferences. Maybe one day when x is fully dead the setting'll be fully excised but it's still default set for the X users for now.

**Comment by SaiVenkatDhulipudi** [comment]
I am unable to toggle Guake when using Google Chrome.

<details><summary>$ guake --support</summary>

Guake Version:		3.8.5

Vte Version:		0.68.0

Vte Runtime Version:	0.68.0

--------------------------------------------------
GTK+ Version:		3.24.33

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: ubuntu

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - XWAYLAND0
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		340 x 190 mm²
    * Primary:		True
    * Refresh rate:	59.962 Hz
    * Subpixel layout:	unknown
