### ISSUE TITLE
Open or Refocus function

### ISSUE THREAD

**Issue by pykong** [Guake/guake#1651]
I like to have the following behavior bound to a single key:
1) IF guake is closed THEN opens and focuses 
2) IF guake is open and focused THEN closes
3) IF guake is open and _not_ focused THEN focuses

I understand that 1) and 2) together represent the standard toggling behavior.
There is also a function to focus and already opened guake window 3).

Background: My guake window is confined to my laptop screen, from where I switch over to my external monitor. Now I would like to be able to switch back to the guake window using the same key I used to open the guake window in the first place. I really do not like to have to use a second key to achieve that behavior.

**Comment by gsemet** [comment]
Hi. Make sense but you need today to hit the key twice to focus. I am open to pull request for the behavior you describe

**Comment by pykong** [comment]
@gsemet Thanks for your response. Great, you agree that such a feature would make sense.
I can not promise I will make a **PR** because of time reasons, still, I'll see what I can do.

**Comment by pykong** [comment]
@gsemet 
I still want to implement this. As the one most familiar with the code base do you got some guidance for me how I should go about this?

**Comment by gsemet** [comment]
Hi. Check out the code, look at the doc on how to start your dev environment, then hack the python code :)

**Comment by pykong** [comment]
> Hi. Check out the code, look at the doc on how to start your dev environment, then hack the python code :)

Haha, best advice ever! OK, I'll do that!

**Comment by pykong** [comment]
@gsemet I was having another run at this.
Then I realized there is already a feature apparently implementing this:

![image](https://user-images.githubusercontent.com/20211140/71325780-1c144f00-24f2-11ea-830c-c3f0f1d7c48b.png)

However it is not working for me on Linux Mint 19.3 Cinnamon.
Likely this issue will then transform into a bugfixing one.

**Comment by pykong** [comment]
Refocus is there but not working.
Hence, closing this issue in favor of bug issue:
https://github.com/Guake/guake/issues/1698
