### ISSUE TITLE
Cannot set transparency to 0 with keyboard shortcuts

### ISSUE THREAD

**Issue by aBARICHELLO** [Guake/guake#1652]
**Describe the bug**

Holding the keyboard command to decrease transparency stops at around 1% instead of 0%, thus forcing the user to input the command to disable all transparency or to move the slider manually in the 'Preferences' window.

Screenshot:
![image](https://user-images.githubusercontent.com/16687318/66062929-bb8bfc00-e518-11e9-9f98-1fe3f6c4865a.png)

-------------------------------------------------------------------------------
<details><summary>$ guake --support</summary>

Guake Version:		3.6.3

Vte Version:		0.58.0

Vte Runtime Version:	0.58.0

--------------------------------------------------
GTK+ Version:		3.24.10

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: cinnamon

--------------------------------------------------

**Comment by aBARICHELLO** [comment]
Hey @gsemet,
Shouldn't the user be able to reach all transparency levels with the increase/decrease hotkeys? Why are they implemented differently from the slider in the preference settings (only including the range [2 - (MAX_TRANSPARENCY-2)]

https://github.com/Guake/guake/blob/bf4dd87d24d0f680dc2e7245a741933b2990a3e8/guake/guake_app.py#L832-L838

**Comment by gsemet** [comment]
Hi. I do not know, this is probably an old behavior. You can make a pull request if your want

**Comment by aBARICHELLO** [comment]
Ok thanks, will open a PR soon
