### ISSUE TITLE
guake hangs after typing exit

### ISSUE THREAD

**Issue by achozex** [Guake/guake#1655]
**Describe the bug**

guake hangs after using exit command

**Expected behavior**

close the current tab?

**Actual behavior**

the current tab hangs , cant create a new tab from it or do any command , ctrl+c not working

**To Reproduce**

1)open guake
2)type exit

**Comment by achozex** [comment]
Guake Terminal 3.0.5
Linux Mint 19.2 Cinnamon

**Comment by EJTH** [comment]
Same issue here.
Quake 3.0.5
Ubuntu 18.04

**Comment by gsemet** [comment]
Can you update guake ? 3.0.5 is pretty old

**Comment by achozex** [comment]
tested on 3.4.0 and 3.6.4  . all good
thanks.
