### ISSUE TITLE
make run fail

### ISSUE THREAD

**Issue by Ni5h1** [Guake/guake#1656]
OS: Ubuntu 18.04.3 LTS
GNOME Shell: 3.28.4
pipenv: version 2018.11.26

**Describe the bug**
https://guake.readthedocs.io/en/stable/contributing/dev_env.html
`./scripts/bootstrap-dev-arch.sh`, `make dev`, `sudo make install-schemas`, `make dev PYTHON_INTERPRETER=python3.6` are ok. But, `make run` fail.

```
$ make run
rm -f /tmp/guake/guake/data/gschemas.compiled
glib-compile-schemas --strict /tmp/guake/guake/data
pipenv run ./scripts/run-local.sh
execute Guake GTK3 for developer.
bash: line 5: pew: command not found
Traceback (most recent call last):
  File "guake/main.py", line 41, in <module>
    from guake.support import print_support
  File "/tmp/guake/guake/support.py", line 5, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
Done
```

It says pew command not found. And this error can be fixed by `pipenv install pew`.

The bug is similar to #1353, and https://github.com/Guake/guake/issues/1353#issuecomment-417863111 says "normally if you install pipenv, pew get installed". But I found https://github.com/pypa/pipenv/pull/2521 says "Pew is no longer vendored."

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:		3.6.3

Vte Version:		0.52.2

Vte Runtime Version:	0.52.2

--------------------------------------------------
GTK+ Version:		3.22.30

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: ubuntu-communitheme-snap

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 -  LVDS-1
    * Geometry:		1366 x 768 at 0, 0
    * Size:		277 x 156 mm²
    * Primary:		True
    * Refresh rate:	60.10 Hz
    * Subpixel layout:	horizontal-rgb

**Comment by Bost** [comment]
I've compiled guake 3.7.0 from the source using `make && sudo make install` only to get:
```bash
$ guake --version
Traceback (most recent call last):
  File "/usr/local/bin/guake", line 6, in <module>
    from guake.main import exec_main
  File "/usr/local/lib/python3.8/site-packages/guake/main.py", line 41, in <module>
    from guake.support import print_support
  File "/usr/local/lib/python3.8/site-packages/guake/support.py", line 5, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```
> It says pew command not found. And this error can be fixed by pipenv install pew.

That doesn't help :-(

**Comment by gsemet** [comment]
please read the README and the build instruction
