### ISSUE TITLE
Please add an option to disable "Guake is now running ..." notification

### ISSUE THREAD

**Issue by condsqn** [Guake/guake#1661]
As the title says. I have Guake set to auto-start via GNOME Tweak Tool. Every time I log in I get this notification: "Guake is now running. Press F12 to use it."

Thanks, but I know Guake is running. I have set it to do so -- all the time. I know which shortcut to use. I use it tens of times daily. Give me an override to disable this unneeded notification.

Also, I have tried disabling Guake notifications in GNOME Settings, but it doesn't seem to work.

**Comment by bialad** [comment]
I run version 3.4.0 and it has an option:

Properties - General - Enable popup notifications on startup

**Comment by aurora-of-earth** [comment]
@condsqn Just do as @bialad has stated. uncheck the <pre>Enable popup notifications on startup</pre> box and done.
Please close the issue if you think the problem is resolved.

**Comment by condsqn** [comment]
Sorry, I must be running an old version or just shortsighted. Closing nao.
