### ISSUE TITLE
Command line option "--new-tab=DIR" does not change directory

### ISSUE THREAD

**Issue by vbachvarov** [Guake/guake#1663]
Hello, I use guake's command line interface heavily.
I noticed quite a while ago that opening a new tab with "-n DIR" or "--new-tab=DIR" stopped setting tab's initial directory correctly.
Now every time I open a new tab from the command line the directory is always "~".

I have guake 3.4.0_1, and the behavior is identical on Arch and FreeBSD.

**Comment by ivoshm** [comment]
Already solved in #1451 nearly year ago.
Please use current version.

**Comment by vbachvarov** [comment]
I have just discovered that the bug is caused by not passing the "directory" argument from new_page_with_focus() to new_page() in notebook.py.
This seems to have been fixed in master. I'll have to probably ask the package maintainers to update.
