### ISSUE TITLE
History UTF-8 command, prompt length bug

### ISSUE THREAD

**Issue by YanDoroshenko** [Guake/guake#1665]
After bringing up history with a command having UTF-8 chars prompt is broken (2 chars too short).

**Expected behavior**
Bringing up history with a command having UTF-8 chars does not break prompt length.

**Actual behavior**
Bringing up history with a command having UTF-8 chars breaks prompt length - 3 chars are deleted instead of 1.

**To Reproduce**
1. Enter any UTF-8 char (for example a gear - ⚙, \u2699 into prompt
2. Press `Enter` to execute
3. See `bash: $'\342\232\231': command not found` message and normal prompt
4. Press up to see the latest executed command
5. Press down to hide the latest executed command
6. See the broken prompt (3 chars are removed from the prompt string instead of one)
-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:		3.6.3

Vte Version:		0.58.2

Vte Runtime Version:	0.58.2

--------------------------------------------------
GTK+ Version:		3.24.12

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: openbox

--------------------------------------------------
Display: :0.0

RGBA visual: True

Composited: True

* Monitor: 0 - DEL HDMI-0
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		476 x 268 mm��
    * Primary:		True
    * Refresh rate:	60.00 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - LGD eDP-1-1
    * Geometry:		1920 x 1080 at 1920, 0
    * Size:		344 x 194 mm��
    * Primary:		False
    * Refresh rate:	60.02 Hz
    * Subpixel layout:	unknown

**Comment by Davidy22** [comment]
Can't paste the gear from the original post, used ⚙ instead, unable to reproduce. I do notice vte 0.58.x, does this still happen on a newer vte version?

Vte still has issues besides this for wide characters though. While I suspect this has already been fixed upstream, vte still doesn't quite give wide characters the space they need yet

**Comment by YanDoroshenko** [comment]
Don't know whether it was an issue with my locale or something really was broken in vte, but now everything works perfectly fine. Closing the issue, feel free to reopen if necessary.

**Comment by Davidy22** [comment]
VTE probably fixed the basic unicode render issues already because that's pretty major, but there's still some unicode spacing issues remaining, you might find that wide unicode characters interact poorly with characters to the right of them still.
