### ISSUE TITLE
Guake drastically slows down over time

### ISSUE THREAD

**Issue by phil294** [Guake/guake#1666]
**Describe the bug**

Over time, Guake gets less and less responsive, up to the point of not being usable anymore. When a desktop session (maybe interrupted by suspends) goes on for multiple hours, everything slows down: After 12 hours of accumulated uptime, pressing F12 results in a ~2 second delay, before guake is visible. And once guake is visible, every keypress is also delayed over time. However, this seems to be only visual, as all inupts are correctly processed. It feels as if the "repainting loop" slows down.

I noticed that by pressing <kbd>ctrl</kbd>, the lagging effect can be cancelled and the next repaint will happen immediately, but is slow afterwards again.

You can temporarily fix it by opening a new tab (<kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>t</kbd>) and closing it again. The interface responds smoothly again, as long as guake is open. But once you close and reopen it (F12), the lagging effect is back. Opening and closing a new tab every time you want to use Guake is not really feasible of course, so you need to either restart or use an entirely different terminal emulator in the first place.

**Expected behavior**

For the terminal not to slow down over time.

**Actual behavior**

Dramatical slow down over time.

**To Reproduce**

Dont turn off the computer for multiple hours. I am not sure whether it depends on any sort of usage.

The bug might be Arch-based only, as the creator of #1145 is using it too. Note that in this issue (closed), the comment "Seems to have slowed down again." has currently 7 upvotes.

The issue should be trackable by a simple `git bisect`, however as reproducing it takes several hours each, this is rather cumbersome. At least now we have an open issue for this.

I will be glad to work on this if others can give any more hints.

-------------------------------------------------------------------------------

Guake Version:		3.6.3

Vte Version:		0.56.3

Vte Runtime Version:	0.56.3

--------------------------------------------------
GTK+ Version:		3.24.10

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: xfce

--------------------------------------------------
Display: :0.0

RGBA visual: True

Composited: True

* Monitor: 0 -  eDP-1
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		344 x 193 mm²
    * Primary:		True
    * Refresh rate:	60.01 Hz
    * Subpixel layout:	unknown

----------------------------
Probably not relevant, but system information:
OS: Manjaro 18.1.0 Juhraya (this is based on Arch Linux)
Kernel: x86_64 Linux 4.19.69-1-MANJARO
CPU: Intel Core i7-6700HQ @ 8x 3.5GHz
GPU: Intel Corporation HD Graphics 530 (rev 06)
RAM: 19962MiB

**Comment by ooobik** [comment]
Just pitching in - by any chance is your scrollback buffer huge and you're running logs in guake? A few months ago I had a similar issue but that was caused by gigabytes of logs being saved into scrollback buffer.

**Comment by phil294** [comment]
Not really - set to 1000 (can only input in multiple of 1000 steps). But I will track RAM usage now

**Comment by gsemet** [comment]
I do not have this issue on Ubuntu, even with infinite scroll. There is probably a setting enabled on your side that causes this behavior. Can you look at memory consumption?

**Comment by phil294** [comment]
After a lot of digging, I got to the core: Disabling the XFCE window compositor feature fixes this. Got the idea from [this reddit post](https://www.reddit.com/r/linuxquestions/comments/b58bd5/xorg_has_heavy_cpu_usage_since_i_have_switched/).

Memory consumption was never an issue, e.g. `VIRT 935M, RES 120M, MEM% 0.6 python3 /usr/bin/guake` in a very laggy state.

With guake, my `xfwm4`(xfce window manager) process cpu usage was at about ~25% all the time  which by itself is pretty crazy. After opening guake, it went up to 100% on one core. Going down again when opening a new tab.

Without the compositor (setting in "Window Manager Tweaks"), it is now consitently below 10%.

Interstingly, my `~/.xsession-errors` is filled with
    Hiding the terminal
    Showing the terminal
    Spawning new terminal at /home/phi
even though it probably shouldnt...? Those dont particularly look like "errors" to me.

Either way, I am not sure if Guake still has some kind of bug as it was the only program I encountered that raised xfwm4 to 100%. Using the compositor and Guake probably should not interfere with each other.

**Comment by hydrargyrum** [comment]
I have the same issue regarding the slowness.

When the symptoms occur, killing guake and then restarting it doesn't solve the issue though, the fresher guake process immediately has the same problem that took days to occur on the (killed) old guake, which makes me wonder if guake is the real culprit here.

I don't how to investigate into that bug, but it's really painful, makes guake pretty unusable after a few days.

**Comment by phil294** [comment]
Are you also using Xfce? Does disabling the window compositor fix it for you, as described above?

**Comment by hydrargyrum** [comment]
> Are you also using Xfce? Does disabling the window compositor fix it for you, as described above?

Yes. And as soon as I re-enable the compositor, guake exposes the problem again.

**Comment by ivoshm** [comment]
I have similar configuration (Manjaro XFCE, Intel graphics - model 620, XFCE compositor on) and never noticed problem.

**Comment by hydrargyrum** [comment]
I'm starting to see the same problem with other terminals, like terminator.

The problem might be more general than Guake and maybe be a [bug](https://bugzilla.xfce.org/show_bug.cgi?id=15963) in xfwm compositor.

**Comment by hydrargyrum** [comment]
Without disabling the compositor, rebooting xfwm periodically by running `xfwm4 --replace` every now and then hides the problem under the carpet because then whatever xfwm leaks doesn't grow big enough for it to be noticeable. But it's a very microsoft-style fix.

**Comment by peldax** [comment]
Archlinux, XFCE, confirming the issue, disabling compositor makes everything smooth again, thanks for the workaround.

```
$ guake --version

Guake Terminal: 3.7.0
VTE: 0.60.1
VTE runtime: 0.60.1
Gtk: 3.24.14
```

**Comment by EduBM7** [comment]
I have the same issue with Pop!_OS, using gnome here, how can I fix this ?

**Comment by phil294** [comment]
It seems this is no longer an issue. I can now successfully use XFCE with active window compositor + Guake for multiple hours without any lags occuring. Anyone else still got problems?
Anyway, I'll close this.

**Comment by hydrargyrum** [comment]
The [corresponding XFCE issue](https://gitlab.xfce.org/xfce/xfwm4/-/issues/351) seems to have been closed as a patch was merged. Indeed I didn't notice the issue recently.
