### ISSUE TITLE
Old version in Ubuntu repos

### ISSUE THREAD

**Issue by Asgoret** [Guake/guake#1667]
In ubuntu repos guake version is 3.0.5 (fresh install on ubuntu 18)

**Comment by robert-matusewicz** [comment]
@Asgoret that is true for Ubuntu 18.10, but it's nothing the developers of Guake can do about that. If you really want to have a newer version of Guake on Ubuntu, you need to request Ubuntu developers to backport the package - the procedure is described here: https://wiki.ubuntu.com/UbuntuBackport - Ubuntu 19.10 contains Guake 3.6.3 and you can request to backport that to 18.10

I hope that will help you!

**Comment by gsemet** [comment]
Ubuntu does not want to update minor version (from 3.4.x to 3.5.0 for example) for god knows the reason. I cannot do anything against this stupid policy, but what I can do it provide pip package and maybe soon snap package (#1677).
