### ISSUE TITLE
Tab renaming is slow

### ISSUE THREAD

**Issue by vasilakisfil** [Guake/guake#1678]
**Describe the bug**

Tab renaming in version 3.6.4 is slow. I just upgraded from 3.0.4 which was super fast.
Since Guake doesn't support tab naming based on path or something that runs, I have this little script in my .zsh:

```zsh
function chpwd {
    guake -r ${PWD##*/}
}
```

basically it sets the current path (the last segment) as the tab name, whenever the current dir changes. That was super fast but with 3.6.4 `guake -r foobar` takes something like 1 second, so cd in to a dir takes 1 second which is quite annoying.

**Expected behavior**

`guake -r foobar` should be fast enough, around 100ms.

**Actual behavior**
`guake -r foobar` is slow, around 1000ms.

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:          3.6.4

Vte Version:            0.52.2

Vte Runtime Version:    0.52.2

--------------------------------------------------
GTK+ Version:           3.22.30

GDK Backend:            GdkX11.X11Display

--------------------------------------------------
Desktop Session: ubuntu

--------------------------------------------------
Display: :1

RGBA visual: True

Composited: True

* Monitor: 0 -  eDP-1
    * Geometry:         1920 x 1080 at 0, 0
    * Size:             293 x 162 mm²
    * Primary:          True
    * Refresh rate:     60.03 Hz
    * Subpixel layout:  unknown

**Comment by ivoshm** [comment]
Try this way:
```
$ dbus-send --session --type=method_call --print-reply --dest=org.guake3.RemoteControl /org/guake3/RemoteControl org.guake3.RemoteControl.rename_current_tab string:'foobar'
```

Example output on my system (Guake 3.6.3):
```
method return time=1573457943.895407 sender=:1.32 -> destination=:1.144 serial=33 reply_serial=2

real	0m0,006s
user	0m0,002s
sys	0m0,003s
```

**Comment by vasilakisfil** [comment]
Ok I think that's a valid solution for me so closing this issue. Many thanks!
