### ISSUE TITLE
Start at login not working on Ubuntu 19.10

### ISSUE THREAD

**Issue by FranzFelberer** [Guake/guake#1684]
**Describe the bug**

Checking the start at login option doesn't result in the start of the guake terminal at start/login.   

**To Reproduce**
* check the box on Ubuntu 19.10. 
* Restart Ubuntu

-------------------------------------------------------------------------------
guake --support
<details><summary>$ guake --support</summary>

Guake Version:		3.6.3

Vte Version:		0.58.2

Vte Runtime Version:	0.58.2

--------------------------------------------------
GTK+ Version:		3.24.12

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: ubuntu

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - DEL DP-1
    * Geometry:		1920 x 1080 % 2 at 0, 0
    * Size:		597 x 336 mm²
    * Primary:		True
    * Refresh rate:	60.00 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - APP eDP-1
    * Geometry:		1280 x 800 % 2 at 1920, 178
    * Size:		286 x 179 mm²
    * Primary:		False
    * Refresh rate:	59.97 Hz
    * Subpixel layout:	unknown

**Comment by robert-matusewicz** [comment]
Hi,

thanks for raising the issue. Unfortunately, it's not really the issue in Guake, but in the Ubuntu/Debian package. I already raised an issue in Ubuntu tracker https://bugs.launchpad.net/ubuntu/+source/guake/+bug/1850926 and forwarded that to Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=944046

Please, look at those issues if you want to know more about the issue.

**Comment by FranzFelberer** [comment]
Thanks, I use gnome-tweak to have it started.
