### ISSUE TITLE
Custom color settings for every tab/terminal

### ISSUE THREAD

**Issue by Polar-Fox** [Guake/guake#1687]
Hi all

I suggest to add custom color settings to every tab (or even terminal).
If a tab does not have custom color settings, it would use global color settings.

Why:

1. It would open the possibility to make background colors (set by **--bgcolor*** options) persist after restarting Guake.
2. Right now Guake has a bug: when the Settings window is opened the background colors are reset to settings. So this bug would be fixed.

When a user runs **--bgcolor*** or **--fgcolor*** command it should affect custom color settings of a tab or several tabs.
And **--reset-colors*** commands should reset colors to settings colors.

I was thinking about doing this (though I don't mind if anybody wants to do it :) ).
@gsemet, would you accept such a feature?

With this feature **--change-palette** command can be modified (or another command can be added) in the future to allow changing the color scheme of a single tab/terminal.

**Comment by gsemet** [comment]
No problem for this feature. If you can even add a menu item in the context menu on each tab that would be awesome.
