### ISSUE TITLE
Refocus not working when calling guake-toggle

### ISSUE THREAD

**Issue by pykong** [Guake/guake#1698]
**Describe the bug**

The refocus function is not working.

**Expected behavior**

With guake's refocus option enabled:
When guake's window is visible and not focused, running `guake -t` or `guake-toggle` should return focus to the open window.

**Actual behavior**
Under said circumstances guake's window gets hidden.

What you actually get.

Described already

**My debugging so far**

I have debugged the reason for guake not refocusing down to this line:

https://github.com/Guake/guake/blob/9d3ef38b6c0fbca3c846e7b55f1a68fccdbd6f8f/guake/guake_app.py#L570

where ~~`self.losefocus_time` and~~ `event_time` will always be **0** no matter what.

Setting `event_time` to an arbitrarily high number so the statement evaluates true if `self.losefocus_time > 0` keeps the window open at all times and it can neither be closed nor focused via the normal toggle command (albeit by other means such as mouse).

**Other issues**

#1651
#1188
#1212
-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:		3.6.3

Vte Version:		0.52.2

Vte Runtime Version:	0.52.2

--------------------------------------------------
GTK+ Version:		3.22.30

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: cinnamon

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 -  eDP-1-1
    * Geometry:		1920 x 1080 at 932, 1600
    * Size:		344 x 193 mm²
    * Primary:		True
    * Refresh rate:	60.01 Hz
    * Subpixel layout:	unknown
* Monitor: 1 -  DP-1-3
    * Geometry:		3840 x 1600 at 0, 0
    * Size:		880 x 367 mm²
    * Primary:		False
    * Refresh rate:	59.99 Hz
    * Subpixel layout:	unknown

**Comment by pykong** [comment]
@gsemet If you gave me some useful input on the issue I might be able to bring forth a PR.

**Comment by pykong** [comment]
**Further analysis:**
I can now confirm that the refocus function indeed works!
However, it has to be toggled via the shortcut setup in `guake` itself, i.e. F12.

In contrast I have been toggling `guake` by a system shortcut calling `guake-toggle`.

**Comment by pykong** [comment]
Modifying the `show_hide` method in the following way perfectly conducts `refocus` when toggling via `guake-toggle`.

@gsemet 
What do the dozen lines of commented-out code found in the current implementation of `show_hide` tell us about implementing this functionality? Actually, I interpret those as sign of warning or relic of a previous attempt at implementing this feature.

https://github.com/Guake/guake/blob/f4238c1938a4d59f236226bf07f75c88cec111d4/guake/guake_app.py#L559-L582

Would anything prevent my modification to become an actual **PR**

### Modification
```py
    def show_hide(self, *args):
        """Toggles the main window visibility
        """
        print("show_hide called.")
        log.debug("Show_hide called")
        if self.forceHide:
            self.forceHide = False
            return

        if not HidePrevention(self.window).may_hide():
            return

        if not self.win_prepare():
            return

        if not self.window.get_property('visible'):
            print("window not visible")
            log.info("Showing the terminal")
            self.show()
            self.set_terminal_focus()
            return

        should_refocus = self.settings.general.get_boolean('window-refocus')
        has_focus = self.window.get_window().get_state() & Gdk.WindowState.FOCUSED
        print("should_refocus: ", should_refocus)
        print("has_focus: ", has_focus)
        if should_refocus and not has_focus:
            self.window.get_window().focus(0)
            self.set_terminal_focus()
        else:
            log.info("Hiding the terminal")
            self.hide()
```

**Comment by gsemet** [comment]
Yes, that’s a sign the code is tricky and any modification can have unknown impact. Try to git blame these lines, but if I remember well, during the great migration to gtk3, we broke some features or at least not fully migrated some code.
So, the only thing I can tell you if you have the courage to change this code is to really test it, in lot of different settings.
We can beta test it, release a preversion of Guake with a new reworked show_hide but these lines have been touched so many time I don’t think there is anyone knowing every case it should handle...

**Comment by pykong** [comment]
@gsemet Thanks for your response.
In the absence of extensive test cases covering "lot of different settings" I do not feel capable of ensuring the said modification will not break things.

I could however make a **PR** with the said modification which could eventually become a pre-version as you suggested.
