### ISSUE TITLE
Please re-add original author to docs and license

### ISSUE THREAD

**Issue by gabrielfalcao** [Guake/guake#1703]
Hello Guake maintainers,

I'd like to start by thanking you for continuously giving love to Guake and keeping it an amazing tool for lovers of GTK.

I'm the original author of the project, it started in 2007 as the [guake-gnome-vte sourceforge project](https://sourceforge.net/projects/guake-gnome-vte/) (before github was mainstream)

Around 2009 I stopped using Linux for desktop  and contributing to Guake. 
https://github.com/Guake/guake/commits?author=gabrielfalcao.

At some point my name was removed from the headers of *most* python files as well as from the list of authors.

You can see the original and old commits here: https://github.com/gabrielfalcao/guake/blob/master/AUTHORS

The original code (still distributed) with my name on the "about window": https://github.com/Guake/guake/blob/d75d29022a890c26ce806107f9789faee83ef469/guake/about.py#L4

This is very unfortunate because Guake was one of my greatest creations and became a living organism, but without proper credit it becomes hard to prove that I've built something valuable to the world.

## What I ask

Please kindly add a small footnote to README.rst and to the docs website so that I can get proper credit.

I intend to apply for a visa and would benefit from having my name mentioned somewhere else than the "About" window of the application, that way lawyers can refer to that link rather than having to install the application.

Thank you

**Comment by oelmekki** [comment]
FYI, this was posted [on hacker news](https://news.ycombinator.com/item?id=22523814).

**Comment by AmazingTurtle** [comment]
The file was deleted in 2017 in [this](https://github.com/Guake/guake/commit/089d72aab3c1708ed3476e42fad7659d8b25fdb7#diff-3d350169560e75d0cf9fc8e3574a3639) commit by @gsemet

**Comment by gsemet** [comment]
Hi all and hi @gabrielfalcao ! AUTHORS file is actually automatically generated by PBR using the git history, so all authors are automatically synced when building the wheel. So the file does not need to be committed.
This list is as of today the following:
```
A S Alam <apreet.alam@gmail.com>
Adolfo Correa <fitomillennium@hotmail.com>
Adonis K <aklp08@gmail.com>
Airfunker <airfunker@gmail.com>
Aleksandar Krsteski <alekrsteski@gmail.com>
Aleksandr Mezin <mezin.alexander@gmail.com>
Alessio Garzi <agarzi@clouditalia.com>
Alessio Garzi <gun101@email.it>
Alex Shkop <ashkop@sciforce.solutions>
Alexander Mezin <mezin.alexander@gmail.com>
Alexander Shlemov <shlemovalex@gmail.com>
Allan Nordhøy <epost@anotheragency.no>
Andrea Azzarone <azzaronea@gmail.com>
Andy Bakun <github@thwartedefforts.org>
Anthony Hepple <anthony@dhdevelopment.co.uk>
Arctic Ice Studio <development@arcticicestudio.com>
Barichello <artur@barichello.me>
Ben Wolsieffer <benwolsieffer@gmail.com>
Berk Demirkır <perq87@gmail.com>
Bersam Karbasion <bersam.k@gmail.com>
Bjørn Lie <zaitor@opensuse.org>
Bouska <pablo.martin-gomez@laposte.net>
Brandon Curtis <brandon.curtis@gmail.com>
ButterflyOfFire <ButterflyOfFire@protonmail.com>
Carlos Joel Delgado Pizarro <cj@carlosjoel.net>
DJ Amireh <cactusbin@gmail.com>
Dan Pasanen <dan.pasanen@gmail.com>
Daniel Milde <daniel.milde@firma.seznam.cz>
Daniel Nylander <po@danielnylander.se>
Danny Graham <good.midget@gmail.com>
Denis Gerasimov <denis-gonzo@users.noreply.github.com>
Denis Subbotin <denis.subbotin@teligent.ru>
Dennis Koot <koter84@gmail.com>
Dirk den Hoedt <dirkdenhoedt@gmail.com>
Dom Sekotill <kodo@gmx.co.uk>
Dorian Marchal <marchal.dorian@gmail.com>
Doug Hellmann <doug@doughellmann.com>
Eduardo Grajeda <tatofoo@gmail.com>
EifX <bitbucket@eifx.de>
Eiichi Sato <sato.eiichi@gmail.com>
Eli Schwartz <eschwartz@archlinux.org>
Elijah Lynn <elijah@elijahlynn.net>
Evaldas Grudzinskas <manoevis@users.noreply.github.com>
Evgeniy Abduzhapparov <evgeniy.abduzhapparov@foxycart.com>
FI <step21@devtal.de>
Florian Reimair <office@florianreimair.at>
Fors <forsssety@gmail.com>
Frank Dietrich <bits_n_bytes@gmx.de>
FreedomBen <FreedomBen@users.noreply.github.com>
GS <rpgsxj2016@foxmail.com>
Gabriel Falcao <root@gabrielfalcao.com>
Gabriel Falcão <gabriel@nacaolivre.org>
Gaetan <gaetan@localhost.localdomain>
Gaetan SEEMET <gaetan@xeberon.net>
Gaetan SEMET <gaetan@xeberon.net>
Gaetan Semet <gaetan.semet@intel.com>
Gaetan Semet <gaetan@xeberon.net>
Gavin Cabbage <gavincabbage@users.noreply.github.com>
Giulio De Pasquale <giulio@depasquale.eu>
Gordeev Boris <gordeevbr@gmail.com>
Grigory Ustinov <grenka@altlinux.org>
Guilhem Lettron <guilhem+github@lettron.fr>
Guillaume Kulakowski <guillaume@kulakowski.fr>
Hans Joachim Desserud <github@desserud.org>
Heimen Stoffels <vistausss@outlook.com>
Hosted Weblate <hosted@weblate.org>
IWAI, Masaharu <iwaim.sub@gmail.com>
Ian MacLeod <imac@google.com>
Ian VanSchooten <ian@badgelabsllc.com>
Igor <f2404@yandex.ru>
Ildar Ahmadullin <Polar-Fox@users.noreply.github.com>
Ilya Zlobin <shadowxnex@gmail.com>
ImmortalPC <guillaumenuel@hotmail.com>
Ishak BELAHMAR <newishak@gmail.com>
Ivan Baldin <ivan.baldin@gmail.com>
Ivan Masár <helix84@centrum.sk>
Jacob Jenner Rasmussen <jacob@jener.dk>
Jan Tojnar <jtojnar@gmail.com>
Jared Stiff <jared.stiff@gmail.com>
Jeff Schwanebeck <jschwanebeck@users.noreply.github.com>
Jekyll Wu <adaptee@gmail.com>
Johan Mickos <jmickos@bu.edu>
Jon Rogers <lonepie@gmail.com>
Jonathan Lao-kan <oneofdays@gmail.com>
Jonathan Ogilvie <jonathan.ogilvie@inin.com>
Jordan Rinke <me@jordanrinke.com>
Julian <julian@fedoraproject.org>
KUSABA Takeshi <maleic1618@gmail.com>
Kaian <kaian@irontec.com>
Kasra Keshavarz <kasra545@gmail.com>
Kevin James <KevinJames@thekev.in>
Klaas Neirinck <klaas.neirinck@gmail.com>
Lincoln de Sousa <lincoln@alfaiati.net>
Lincoln de Sousa <lincoln@comum.org>
Lincoln de Sousa <lincoln@guake.org>
Lincoln de Sousa <lincoln@minaslivre.org>
Lincoln de Sousa <lincoln@semteto.(none)>
Louie Lu <git+nctu_nems@louie.lu>
Louie Lu <git@louie.lu>
Louie Lu <nctu@louie.lu>
MaTachi <dannie92@gmail.com>
Marcel Partap <mpartap@gmx.net>
Marcelo Jorge Vieira <metal@alucinados.com>
Marco Leogrande <dark.knight.ita@gmail.com>
Marek Šuppa <mrshu@users.noreply.github.com>
Mariano Besio <marianobesio@gmail.com>
Mario Aichinger <aichingm@gmail.com>
Markus Wamser <wamserma@users.noreply.github.com>
Martin Lukeš <martin.meridius@gmail.com>
Matej Marcisovsky <matej.marcisovsky@firma.seznam.cz>
Matheus C. Manoel <matheuscmanoel@gmail.com>
Matt G <mgaut72@gmail.com>
Matt Gautreau <mgaut72@email.arizona.edu>
Matthias Lisin <matthias.lisin@googlemail.com>
Maurizio De Santis <desantis.maurizio@gmail.com>
Max Mertens <max.mail@dameweb.de>
Maxim Ivanov <ulidtko@gmail.com>
Maxim Zalata <zalatik@gmail.com>
Maximiliano Najle <maximiliano.najle@globant.com>
Michaël Arnauts <michael.arnauts@destiny.be>
Mikhail Fast <mouseratti@gmail.com>
Mikhail Koshel <mouseratti@gmail.com>
Morgan Antonsson <morgan.antonsson@gmail.com>
MrTuxHdb <mrtux@ubuntu-vn.org>
Mátyás Somfai <somfai.matyas@gmail.com>
Nacho Vidal <nacho.vfranco@gmail.com>
Naftuli Kay <rfkrocktk@gmail.com>
NishiYuki <nishiyk256@gmail.com>
Nuno Gonçalves <ulukyn@gmail.com>
Oliver Haessler <oliver@redhat.com>
Olivier Bourdoux <olivier.bourdoux@gmail.com>
Ozzyboshi <gun101@email.it>
Patrick Paul <pztrick44@gmail.com>
Paul <paulhooijenga@gmail.com>
Paul Hooijenga <paulhooijenga@gmail.com>
Pavel Alexeev <pahan@hubbitus.info>
Pavel Borecki <pavel.borecki@gmail.com>
Pavel Lang <langpavel@phpskelet.org>
Pavel Sofishchenko <login.spv@gmail.com>
Paweł Świątkowski <inquebrantable@gmail.com>
Pedro Ladaria <pedro.ladaria@gmail.com>
Phaiax <phaiax-git@invisibletower.de>
Philip Waritschlager <eochgls@web.de>
Philipp Hagemeister <phihag@phihag.de>
Pierre-Yves Chibon <pingou@guake.org>
Pierre-Yves Chibon <pingou@pingoured.fr>
Piotr Drąg <piotrdrag@gmail.com>
Priit Laes <plaes@plaes.org>
Ralph Bean <rbean@redhat.com>
Ricardo A. Hermosilla Carrillo <ra.hermosillac@gmail.com>
Ricardo Fuhrmann <fuhrmanns@gmail.com>
Robert Stanfield <robert@stanfield.it>
Robert van Drunen <r.j.m.vandrunen@gmail.com>
Robin Bauknecht <robin.bauknecht@gmail.com>
Rodrigo Rodrigues da Silva <pitanga@members.fsf.org>
Roman Zimmer <hello@roman-zimmer.app>
Roman Zimmer <roman.zimmer@sprylab.com>
Ruined1 <ruined1@gmail.com>
Ryan McGeary <ryan@mcgeary.org>
SAWADA Takeo <g640287@mail.ecc.u-tokyo.ac.jp>
Sandy <bwrsandman@gmail.com>
Sebastian Pipping <sebastian@pipping.org>
Sebastian Wagner <sebix@sebix.at>
Selivanov Pavel <selivan@users.noreply.github.com>
Serafim Nenarokov <serafim.nenarokov@flant.ru>
Shane Smith <shane.smith.baz@gmail.com>
Shubham Kumar Jha <skjha832@gmail.com>
Simon Thyßen <simon.thyssen@gmx.de>
Sinkerine <git@15cm.net>
SoniEx2 <endermoneymod@gmail.com>
Stefan Tatschner <stefan@sevenbyte.org>
Stefano Tortarolo <stefano.tortarolo@gmail.com>
Stephen M. Coakley <me@stephencoakley.com>
Stibbons <gaetan@xeberon.net>
Sylvestre Ledru <sylvestre.ledru@scilab-enterprises.com>
Taha Jahangir <mtjahangir@gmail.com>
Thomas Stratmann <thomas.stratmann@9elements.com>
Toby Dimmick <tobydimmick@hotmail.com>
Toby Huang <ruofei77@gmail.com>
Tom Briden <tom@decompile.me.uk>
Ulf Rompe <ulf@rompe.org>
Vadim Kotov <vkotovv@gmail.com>
Versus Void <versusvoid@gmail.com>
Vincent Cloutier <cloutier@users.noreply.github.com>
Voronwe <fanafet@yandex.ru>
Xiaojie Lin <lxj2048@gmail.com>
Xinyu Ng <wuxinyumrx@gmail.com>
Xtreak <tirkarthi@users.noreply.github.com>
Xue Qianming <xueqianming200@gmail.com>
Your Name <you@example.com>
Zach Borboa <zborboa@google.com>
bendev <https://github.com/bendev>
boscowitch <boscowitch@boscowitch.de>
chrisandrew.cl <chris@chrisandrew.cl>
dmartinezc <dmartinezc@gmail.com>
dnoway <dnoway@gmail.com>
dorian-marchal <marchal.dorian@gmail.com>
dsolodukhin3 <david.solodukhin@gatech.edu>
el_libre como el chaval <el.libre@gmail.com>
filipsohajek <filip.sohajek@gmail.com>
gbonnema <gbonnema@xs4all.nl>
guake_root <guake_root>
h4rvey r0ss <h4rvey@protonmail.com>
jaawerth <jaawerth@gmail.com>
jadrian <jadrian@cs.brown.edu>
kazutaka <kazutaka@vinelinux.org>
krassowski <krassowski.michal@gmail.com>
leela <52065244+leela52452@users.noreply.github.com>
lonepie <lonepie@gmail.com>
max ulidtko <ulidtko@gmail.com>
mr.Shu <mr@shu.io>
nessunkim <nessunkim@gmail.com>
panpan <alban.inquel@gmail.com>
panpann <alban.inquel@gmail.com>
pathmann <thomas.pathmann@googlemail.com>
pierrey <pierrey@cyan.pingoured.fr>
pierrey <pierrey@green.pingoured.fr>
pingou <pingou@pingoured.fr>
pleycpl <h4rvey@protonmail.com>
r1pp3rj4ck <r1pp3rj4ck@w4it.eu>
radek-sprta <mail@radeksprta.eu>
rgaudin <rgaudin@gmail.com>
ruro <ruro.ruro@ya.ru>
samuelorsi125t <samuelorsi125t@gmail.com>
sangwoojoo <sangwoojoo@naver.com>
scinart <akubeej@gmail.com>
seth-- <xd.seth@gmail.com>
spresse1 <steve@pressers.name>
ssantos <ssantos@web.de>
suve <veg@svgames.pl>
tensor-zeng <tensor-zeng@outlook.com>
thardev <dbravo.iessabadell@gmail.com>
thardev <thardev@users.noreply.github.com>
tirkarthi <tir.karthi@gmail.com>
true-datura <grrrr@protonmail.com>
ulidtko <ulidtko@gmail.com>
uloco <uloco@schiefewelt.de>
vantu5z <vantu5z@mail.ru>
versusvoid <chaoskeeper@mail.ru>
vkotovv <vkotovv@gmail.com>
wty <haavard@havdal.net>
xiangcai <ziyenano@gmail.com>
zqb-all <zhuangqiubin@gmail.com>
Денис Сергеевич Герасимов <denis-gonzo@users.noreply.github.com>
庄秋彬 <zhuangqiubin@gmail.com>
甘 露 <rhythm.gan@gmail.com>
```
This does not reflect the list of MAINTAINERS the project had.

As of the header files, I do not remember cleaning them, I am using a lot of tools such as isort that can change the header files. If you desire it, we can put a list of maintainers, I am not sure it should be in the python files themselves, I would prefer the `MAINTAINERS` file (with the years of "active duty" for instance)

**Comment by aliakhtar** [comment]
I’m a user of Guake and I’m also an international software developer. I understand first hand how hard and painful visas can be.

I 100% support @gabrielfalcao ‘a request here. If he is the original author of Guake, and wants to use that to demonstrate his expertise in his visa application, he would need that fact listed on a publicly available website, which non technical people (lawyers, immigration officers) can read.

He is also entitled to being listed as ‘Original author’ separately from a list of maintainers with 1000 other people on it. The role he played as the original author was unique, and deserves some recognition for it.

This is the norm for many open source projects, eg memcached and others. Many projects list the original author somewhere on the site.

This also sets a good example for future open source developers - if you start a project, the community will look out for you when you need it.

I’m all in favour or also having a list of maintainers which lists the years / months of active maintainence, in addition to listing Gabriel as the original author.

Even Facebook still mentions Eduardo as a cofounder 😉.

Thank you to all the people who maintain Guake.

**Comment by gsemet** [comment]
I am completely aligned with you. We just need to find out the best way to pay the tribute back to the original author. I have put the MAINTAINERS file in the root of the project, but I am not sure of the information inside it ! @ulidtko, @pypingou, @clarete, @gabrielfalcao  and maybe other, can you check it and if not correct, propose PR on it.

**Comment by aliakhtar** [comment]
I think Gabriel has asked to be listed on the website so non technical people can view it. I think the way memcached credits the original author is what we should use: https://memcached.org/about

**Comment by gsemet** [comment]
The website source is here: https://github.com/Guake/guake-website. I am open to a good solution that would not require active maintainance of the author list !

**Comment by Z1488** [comment]
@gabrielfalcao I have imported the SVN to Github in case you're interested.
https://github.com/Z1488/guake-svn

Sorry if it's too unrelated to the issue.

**Comment by gsemet** [comment]
We can move this project in the guake repository for posterity sake (as [guake/guake-svn](https://github.com/guake/guake-svn))

**Comment by justinclift** [comment]
As a general concept, the approach we took for sqlitebrowser was to add a History section to the front page of the repo (and pretty much mirrored to the About page of the website):

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/#history

Maybe that would work for this situation too? :smile:

**Comment by gsemet** [comment]
thanks... I hope to find the creds to deploy a new version asap...

**Comment by Zensavona** [comment]
Fastest PR I ever had merged 😂

**Comment by justinclift** [comment]
Gah.  That could have done with review too, as the initial wording is less than good. :frowning:

**Comment by gsemet** [comment]
I have imported the project in https://github.com/Guake/guake-svn.

@justinclift you can do another PR :)

**Comment by justinclift** [comment]
> @justinclift you can do another PR :)

Good point.  Done. :grin:

**Comment by gabrielfalcao** [comment]
> thanks... I hope to find the creds to deploy a new version asap...

I would be happy to contribute to this, just tell me how ? 😄

**Comment by gsemet** [comment]
ok I found my ftp credentials back :)

**Comment by gabrielfalcao** [comment]
> ok I found my ftp credentials back :)

Oh I misunderstood "creds" for "credits", assumed you were talking about some PaaS that needed payment 🤷‍♂

**Comment by aliakhtar** [comment]
doesn't look like its deployed to the site yet, http://guake-project.org/

**Comment by gabrielfalcao** [comment]
> doesn't look like its deployed to the site yet, http://guake-project.org/

@gsemet åre you able to deploy it?

**Comment by gsemet** [comment]
Hi. Hard time recently, I try my best. It is actually a pity to have a simple web site dépendant on so much node/grunt/npm packages and having to rebuilt and deploy...

**Comment by gsemet** [comment]
should be good :D

**Comment by justinclift** [comment]
Checking now, and yep, the updated info is there. :smile:

**Comment by gabrielfalcao** [comment]
Thanks @gsemet and @justinclift I'm closing this issue.

**Comment by justinclift** [comment]
Uh oh.  Just noticed the link to "many contributors" in the text fragment for this is very broken. :frowning:

**Comment by justinclift** [comment]
PR to fix the problem: https://github.com/Guake/guake-website/pull/9
