### ISSUE TITLE
Modernize and Overhaul Code Base

### ISSUE THREAD

**Issue by pykong** [Guake/guake#1710]
It makes me sad to see this great project slowly dying due to a lack of maintenance.

As of writing this, there are no less than 390 open issues on this repository.
Its [Feature Request](https://github.com/Guake/guake#features-request) displays 72 open requests with the most painfully needed request of an official Launchpad PPA counting 181 votes and not being addressed for a whole year now. The repository itself has seen the last commit in Mid December 2019, with 24 stale branches rotting away undeleted and uncared for.

To get out of this rut significant dedication would be required in the form of core and new contributors. To attract fresh contributors, I suggest modernizing and cleaning up the codebase to make it more inviting.

My **PR** #1709 might serve as a starting point in this regard. It includes the following adaptions:

- Moving from `pipenv` to `poetry`, as developing with the latter is so much more pleasant, just talking dependency resolution here. This includes the addition of a `pyproject.toml` file.
- Moving from `yapf` to `black` for formatting, as it is what everyone seems to be using nowadays and I consider a significantly better tool.
- Sort and cleanup imports.
- Dropping Python 3.5 support as it reaches EOL this year anyway, allowing us to use features of Python 3.6 syntax, especially f-strings. (Syntax has been modernized  via [pyupgrade](https://github.com/asottile/pyupgrade))
- Using [pre-commit](https://github.com/pre-commit/pre-commit) for managing git hooks.

Some further suggestions not covered in that **PR** are:
- Move from Travis CI to GitHub Actions for testing and deployment (new contributors would not need to open Travis CI account for running tests against their fork.)
- Major refactoring. We should strive to break down the monolithic structure into smaller more understandable pieces.
- ~~Using PyTest for all things testing, as it is simply the best test suite for python.~~ **EDIT:** It already does.
- Type annotate entire code base, which gives us type safety and also might pave a way for increasing performance via [mypyc](https://github.com/python/mypy/tree/master/mypyc)

**Comment by gsemet** [comment]
hi ! thanks for your dedication. I mostly agree on what you are saying, so you can count on me to help you integrating your changes. I have less and less time to maintain guake myself, and indeed there are some rotting stuff arround that need clean up. First I can close old pull requests where i have no more anwer on it, and maybe delete older branches.

As for moving to black/poetry, if it make life better let's go. I have reworked a lot the build system but it is still quite hard to checkout a development environment (guake relies on system dependencies,...)... so yes lot of work needed, hopefully I got last year amazing contribution, move to gtk3, ... So it is always very pleased to see contributors willing to help clean old code base !

**Comment by pykong** [comment]
@gsemet Great! Thanks for your response. And thanks for this amazing project. 
I know firsthand how time consuming maintaining a project can be.

Let's discuss small steps to move forward.

**Comment by pykong** [comment]
Closing this **PR**, as it is decided to break it down into smaller more manageable ones.
Discussions may continue on the accompanying thread: https://github.com/Guake/guake/issues/1710

**Comment by pykong** [comment]
I believe the first step forward would be to migrate to `poetry`. 
I have just opened a dedicated issue: https://github.com/Guake/guake/issues/1717

**Comment by matheo** [comment]
@pykong thanks for you efforts here.

I wonder how difficult would be to add the name of the current `git branch` to Guake,
I'm missing this now that I'm handling a ton of repositories.
Thanks in advance!

**Comment by pykong** [comment]
@matheo 
Do you mean like `guake_my_awesome_feature_branch`?
If so consider it done for my next **PR**.

**Comment by matheo** [comment]
I mean, like if you're inside a git project, show the branch name:
![image](https://user-images.githubusercontent.com/260185/74600050-7f85ad80-5059-11ea-8d26-a83950000bb6.png)

**Comment by gsemet** [comment]
That s a job for your shell , not Guake itself

**Comment by pykong** [comment]
I have closed **PR**: #1724 as adapting the build process proved to be too challenging.
Hence this halt the entire project of modernizing and overhauling the code base.

**Comment by gsemet** [comment]
I think you can decouple the issue. Moving to poetry is a part, but you can still try using black or other of your ideas

**Comment by pykong** [comment]
Yes, you are right. Maybe I got a bit too ambitious.
I am going to make a separate **PR** for using black.

**Comment by matheo** [comment]
@gsemet a tip to get it working on my Ubuntu please?
I'm not familiar with this stuff at all :(

**Comment by gsemet** [comment]
I am using zsh with oh-my-zsh, it rocks !

**Comment by matheo** [comment]
@gsemet Great suggestion, thank you very much!

I will install it now that I managed to customize my `.bashrc` hehe
![image](https://user-images.githubusercontent.com/260185/74873239-d70f6c00-532c-11ea-9cc1-f7f8bcc1b395.png)
