### ISSUE TITLE
Feature request: Ditch pipenv for poetry

### ISSUE THREAD

**Issue by pykong** [Guake/guake#1717]
# Why ditch pipenv?
Without exception, every python package developer I know totally despises `pipenv`.
Pipenv certainly did not become the official dependency management tool of PyPA, because it is an inherently good tool but rather because of the influence of its creator.

For a more in-depth analysis of `pipenv`, I recommend the following rant:
[Pipenv: promises a lot, delivers very little](https://chriswarrick.com/blog/2018/07/17/pipenv-promises-a-lot-delivers-very-little/)

Among its many flaws, there is a single one that totally ruins developing any package using `pipenv`: Its unacceptably slow, and buggy dependency resolution. I have experienced far too often that after 20 minutes of `pipenv` trying to get its act together resolving dependencies the whole process exits with an error. 
Usually, this followed by some kind of issue where `pipenv` complaints about its dependencies not being locked. All of my attempts to resolve this issue ultimately resort to deleting the virtual environment and start anew.

# Why we should be using poetry
I never ever experienced the same kind of issue with `poetry`.
I do not have the numbers, but I hear a lot that people migrating over to `poetry` and it is also what I am using. It comes with the following features:
- it is dependency resolution works quick and reliable
- its command-line interface is a joy to use
- it is under active development and just reached 1.0.0 last December.

Additionally, the `pyproject.toml` used by `poetry` can also hold configuration data, like that for formatters, linters or test tools. While not all dev tools support this file format yet, its support is constantly growing. This promises that one day we will see a single configuration file for each python project, instead of half a dozen.

# How to migrate to poetry
Once I get the OK to move forward, I am going to prepare a **PR** featuring the following:
- moving dependencies into a new `pyproject.toml`
- adapting Travis to work with `poetry`
- migrating configuration files into `pyproject.toml` if possible
- rewrite docs where necessary

## What I need

All I need is an OK by the maintainers that we want to do it and I would start working on the **PR** right away.

Also: Should we be working towards a big release? Like striving for `guake 4.0.0` where we want to integrate more breaking changes and features?

**Comment by gsemet** [comment]
Only thing that I d like to keep is pbr and its magic:
- auto versioning from git tag 
- setup.py install_requises injection. If we move to full poetry build that is useless but we loose auto version

Reno for release note can be replaced by another one

**Comment by pykong** [comment]
@gsemet Let me have a look into that. It will take me a couple of days longer but maybe it is an issue someone already has solved.

**Comment by gsemet** [comment]
If it does not change anything for the user we can just release a new minor version.

**Comment by gsemet** [comment]
Solved not really (there is a plug-in for that but plugin syste comes in 1.1... soon )

**Comment by pykong** [comment]
OK. The changes will be totally transparent to the user.
Great that there is a plugin, this should simplify things. :)
Let's get back to the plugin once my **PR** is ready.

I plan to plan to have the **PR** ready by the weekend.

**Comment by pykong** [comment]
Closed. See: https://github.com/Guake/guake/pull/1724#issuecomment-587327563
