### ISSUE TITLE
Format via black

### ISSUE THREAD

**Issue by pykong** [Guake/guake#1726]
We should move to `black` as it is a more modern alternative to `yapf``.
It seems it is what most folks are using this day.
See also: https://github.com/Guake/guake/issues/1710

### Question: Which line length should we use?
`black` default to 88 chars per line, in contrast to PEP8's 80 chars.
Should we stay at 100 chars or adopt the recommended 88 ones?

**Comment by gsemet** [comment]
88 chars is ok for me. I more worried about some formatting rules they want to enforce without configuration, something the end result is not easily readable (i tend to prefer readability and maintainability over elegance and smallness).

So let's have a look :)

**Comment by pykong** [comment]
@gsemet It would be a very small and readily made **PR**.
So in case you do not like it just deny its merge: No problem.

I should have it ready this evening.

**Comment by pykong** [comment]
I am afraid I can not do it. As much as I wished to contribute to this great project, there are obstacles too big for me to overcome. 

This time `pipenv` is giving me such a hard time - that I why I wanted to move away from it in the first place. Even trying to just install and lock, will result in a version conflict.

I am going to focus on #1711, that is the only thing I can do.

<details><summary>LOG</summary>
<p>

#### Version mismatch.

```txt
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: ERROR: Could not find a version that matches typed-ast<1.4.0,>=1.3.1,>=1.4.0
Tried: 0.5, 0.5.1, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.5.6, 0.6.0, 0.6.1, 0.6.2, 0.6.2, 0.6.2, 0.6.2, 0.6.3, 0.6.3, 0.6.3, 0.6.3, 0.6.3, 0.6.3, 1.0.0, 1.0.0, 1.0.0, 1.0.0, 1.0.0, 1.0.0, 1.0.0, 1.0.0, 1.0.0, 1.0.0, 1.0.0, 1.0.0, 1.0.0, 1.0.0, 1.0.1, 1.0.1, 1.0.1, 1.0.1, 1.0.1, 1.0.1, 1.0.1, 1.0.1, 1.0.1, 1.0.1, 1.0.1, 1.0.1, 1.0.1, 1.0.1, 1.0.2, 1.0.2, 1.0.2, 1.0.2, 1.0.2, 1.0.2, 1.0.2, 1.0.2, 1.0.2, 1.0.2, 1.0.2, 1.0.2, 1.0.2, 1.0.2, 1.0.3, 1.0.3, 1.0.3, 1.0.3, 1.0.3, 1.0.3, 1.0.3, 1.0.3, 1.0.3, 1.0.3, 1.0.3, 1.0.3, 1.0.3, 1.0.3, 1.0.4, 1.0.4, 1.0.4, 1.0.4, 1.0.4, 1.0.4, 1.0.4, 1.0.4, 1.0.4, 1.0.4, 1.0.4, 1.0.4, 1.0.4, 1.0.4, 1.1.0, 1.1.0, 1.1.0, 1.1.0, 1.1.0, 1.1.0, 1.1.0, 1.1.0, 1.1.0, 1.1.0, 1.1.0, 1.1.0, 1.1.0, 1.1.0, 1.1.0, 1.1.0, 1.1.0, 1.1.0, 1.1.0, 1.1.0, 1.1.0, 1.1.0, 1.1.0, 1.1.1, 1.1.1, 1.1.1, 1.1.1, 1.1.1, 1.1.1, 1.1.1, 1.1.1, 1.1.1, 1.1.1, 1.1.1, 1.1.1, 1.1.1, 1.1.1, 1.1.1, 1.1.1, 1.1.1, 1.1.1, 1.1.1, 1.1.1, 1.1.1, 1.1.2, 1.1.2, 1.1.2, 1.1.2, 1.1.2, 1.1.2, 1.1.2, 1.1.2, 1.1.2, 1.1.2, 1.1.2, 1.1.2, 1.1.2, 1.1.2, 1.1.2, 1.1.2, 1.1.2, 1.1.2, 1.1.2, 1.1.2, 1.1.2, 1.2.0, 1.2.0, 1.2.0, 1.2.0, 1.2.0, 1.2.0, 1.2.0, 1.2.0, 1.2.0, 1.2.0, 1.2.0, 1.2.0, 1.2.0, 1.2.0, 1.2.0, 1.2.0, 1.2.0, 1.2.0, 1.2.0, 1.2.0, 1.2.0, 1.3.0, 1.3.0, 1.3.0, 1.3.0, 1.3.0, 1.3.0, 1.3.0, 1.3.0, 1.3.0, 1.3.0, 1.3.0, 1.3.0, 1.3.0, 1.3.0, 1.3.0, 1.3.0, 1.3.0, 1.3.0, 1.3.0, 1.3.1, 1.3.1, 1.3.1, 1.3.1, 1.3.1, 1.3.1, 1.3.1, 1.3.1, 1.3.1, 1.3.1, 1.3.1, 1.3.1, 1.3.1, 1.3.1, 1.3.1, 1.3.1, 1.3.1, 1.3.1, 1.3.1, 1.3.2, 1.3.2, 1.3.2, 1.3.2, 1.3.2, 1.3.2, 1.3.2, 1.3.2, 1.3.2, 1.3.2, 1.3.2, 1.3.2, 1.3.2, 1.3.2, 1.3.2, 1.3.2, 1.3.2, 1.3.2, 1.3.2, 1.3.4, 1.3.4, 1.3.4, 1.3.4, 1.3.4, 1.3.4, 1.3.4, 1.3.4, 1.3.4, 1.3.4, 1.3.4, 1.3.4, 1.3.4, 1.3.4, 1.3.4, 1.3.4, 1.3.4, 1.3.4, 1.3.4, 1.3.4, 1.3.5, 1.3.5, 1.3.5, 1.3.5, 1.3.5, 1.3.5, 1.3.5, 1.3.5, 1.3.5, 1.3.5, 1.3.5, 1.3.5, 1.3.5, 1.3.5, 1.3.5, 1.3.5, 1.3.5, 1.3.5, 1.3.5, 1.4.0, 1.4.0, 1.4.0, 1.4.0, 1.4.0, 1.4.0, 1.4.0, 1.4.0, 1.4.0, 1.4.0, 1.4.0, 1.4.0, 1.4.0, 1.4.0, 1.4.0, 1.4.0, 1.4.0, 1.4.0, 1.4.0, 1.4.0, 1.4.1, 1.4.1, 1.4.1, 1.4.1, 1.4.1, 1.4.1, 1.4.1, 1.4.1, 1.4.1, 1.4.1, 1.4.1, 1.4.1, 1.4.1, 1.4.1, 1.4.1, 1.4.1, 1.4.1, 1.4.1, 1.4.1, 1.4.1, 1.4.1
There are incompatible versions in the resolved dependencies.

```

</p>
</details>

**Comment by gsemet** [comment]
i know this is quite hard and agree with you poetry makes life easier. I'll see what i can do

**Comment by gsemet** [comment]
so do you think it does the job? :D

**Comment by pykong** [comment]
@gsemet Sorry, for giving you a hard time here.

A while a go it was inded the defnite package tool to use.
But it now provides a barrier for me and certainly anyone wanting to contribute.
(I suppose you have been aware of its shortcomings as well: https://github.com/pypa/pipenv/issues/1050#issuecomment-361404488)

Yes, if you could try to fix: #1724 that would  be a huge win for `Guake`.
It would make it easier or even possible at all for new contributors to get started.

**Comment by gsemet** [comment]
Yes I know pipenv is bugged as hell and I want to get rid of it. Soon, poetry 1.1 will be released with the plugin system. I am seeing what step is missing to replace pbr as well. It takes time you know :)

I migrated master to black, works quite good :)

**Comment by pykong** [comment]
Congrats for switching to `black`. The code base looks much better now. :)
I am looking forward to Guake on poetry, then!
