### ISSUE TITLE
Inactive menus in Dwarf Fortress are invisible in ncurses mode

### ISSUE THREAD

**Issue by Edojp** [Guake/guake#1732]
**Describe the bug**
Non-active menu items blend into the background when launching Dwarf Fortress in ncurses mode (PRINT_MODE:TEXT). I have tried several different terminal emulators (such as konsole, xfce4-terminal) and only Guake has this issue. I have tried several different color schemes including manually tweaking individual colors but it does not make a difference. Have also tried changing the font.

**Expected behavior**

Inactive menu items should be visible in a different color.

**Actual behavior**

Inactive menu items are invisible.

**To Reproduce**

Run Dwarf Fortress and set PRINT_MODE:TEXT in ~/.dwarffortress/data/init/init.txt

-------------------------------------------------------------------------------

Please run `$ guake --support`, and paste the results here.
<details><summary>$ guake --support</summary>

Guake Version:		3.6.3

Vte Version:		0.58.3

Vte Runtime Version:	0.58.3

--------------------------------------------------
GTK+ Version:		3.24.14

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: None

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - SHP eDP1
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		290 x 170 mm²
    * Primary:		True
    * Refresh rate:	59.93 Hz
    * Subpixel layout:	unknown

**Comment by Edojp** [comment]
Side by side pic displaying the issue here. Left is Guake, right is xfce4-terminal:

![Screenshot from 2020-03-04 17-00-56](https://user-images.githubusercontent.com/50192929/75858975-89baf080-5e3c-11ea-8fa8-4f3fd924af90.png)

**Comment by egmontkob** [comment]
Does enabling "Preferences -> Appearance -> Bold text is also bright" fix this?

Or do you have a "Color palette" (on that same page) where the two rows of colors are identical? Guake offers quite a few such palettes.

**Comment by Edojp** [comment]
Gah - bold text option did indeed fix, that was the probably the only option I didn't try... sigh. Thanks so much!

**Comment by egmontkob** [comment]
> only Guake has this issue

More terminals have this issue, e.g. GNOME Terminal's latest versions, many other VTE-based terminals, Kitty, Alacritty.

Please report the problem to Dwarf Fortress's developers, point them to https://bugzilla.gnome.org/show_bug.cgi?id=762247, especially comments 29-31. They can and should fix this so that it works in all the terminals, without users having to set a particular setting.

**Comment by egmontkob** [comment]
FYI: Same problem reported for the Alacritty terminal here: https://github.com/alacritty/alacritty/issues/3295

**Comment by Edojp** [comment]
I did raise a bug for this with DF but sadly it has not been looked at for over a year. Will give it another prod!
