### ISSUE TITLE
Guake crashes gnome theme on launch

### ISSUE THREAD

**Issue by serpro69** [Guake/guake#1737]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Guake.

For how to run the latest Guake in your computer, please refer to [Install from source](https://guake.readthedocs.io/en/latest/user/installing.html#install-from-source).

**Describe the bug**

Sometimes launching guake makes my gnome theme to crash (could be something else, not the theme itself, not sure how to investigate this so ideas are welcome).
Not sure how to describe this properly so I've attached a few screenshots as well with before and after launch view.
Basically sometimes on guake launch the theme changes, all the top tray icons disappear, ubuntu dock crashes. 

before:
![before](https://user-images.githubusercontent.com/22973227/76703070-dde09300-66ce-11ea-8c20-d88357b035a7.png)

after:
![after](https://user-images.githubusercontent.com/22973227/76703050-b38ed580-66ce-11ea-9343-df383a266fef.png)

This happens maybe 10% of the times. Haven't figured out how to restore after crash so I just log out of the session and log back in.

If someone can help me understand what logs to check to figure out what exactly is happening and why please let me know and I'll update the issue with more details.

-------------------------------------------------------------------------------
<details><summary>$ guake --support</summary>

Guake Version:          3.7.0

Vte Version:            0.52.2

Vte Runtime Version:    0.52.2

--------------------------------------------------
GTK+ Version:           3.22.30

GDK Backend:            GdkX11.X11Display

--------------------------------------------------
Desktop Session: gnome-classic

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 -  eDP-1
    * Geometry:         2560 x 1440 at 0, 0
    * Size:             344 x 194 mm²
    * Primary:          True
    * Refresh rate:     119.98 Hz
    * Subpixel layout:  unknown

**Comment by Davidy22** [comment]
Hello, unable to reproduce this myself, what's the name of the theme you're using? Are you still using it?

**Comment by serpro69** [comment]
Hi,

I haven't had this issue for quite some time now, so I don't think it's still valid.
I'm also on Ubuntu 20.04 now, with newer gnome version, so upgrading from 18.04 might've solved it as well.
