### ISSUE TITLE
Documentation - readthedocs install page is oldish. 

### ISSUE THREAD

**Issue by shirishag75** [Guake/guake#1748]
the readthedocs page seems old, the last time somebody seemed to have worked on it was in 2018. 

I am talking specifically about https://guake.readthedocs.io/en/latest/user/installing.html#install-from-source

I dunno what versions of the dependencies are needed not just to build but to run. We have the latest VTE on testing which upstream has released as well as the latest stable gtk+ which upstream has. 

So if and when the new version is built by the maintainer, it should fit right in. 

Perhaps the page also needs to be updated a bit as I don't know what else might be missing.

**Comment by Davidy22** [comment]
Finally updated in #2033, closing
