### ISSUE TITLE
error when start application?

### ISSUE THREAD

**Issue by js-abc007** [Guake/guake#1756]
[ERROR] missing mandatory dependency: cairo
[ERROR] missing at least one system dependencies. You need to install additional packages for Guake to run
[ERROR] On Debian/Ubuntu you need to install the following libraries:
    sudo apt-get install -y --no-install-recommends \
        gir1.2-keybinder-3.0 \
        gir1.2-notify-0.7 \
        gir1.2-vte-2.91 \
        gir1.2-wnck-3.0 \
        libkeybinder-3.0-0 \
        libutempter0 \
        python3 \
        python3-cairo \
        python3-dbus \
        python3-gi \
        python3-pbr \
        python3-pip

**Comment by ulidtko** [comment]
Sorry, but can you read?

**Comment by Davidy22** [comment]
Resolvable by following dependency installation recommendation, closing.
