### ISSUE TITLE
Segfault on start

### ISSUE THREAD

**Issue by michaelothing** [Guake/guake#1762]
Recently Guake is not working. I installed guake-git from the AUR, but, I have also tried the one in the arch repo. I don't know what is causing it. If  I uninstall and delete files every once in a while I can get it to work, but, on next reboot it is broken again. This is what I get starting from terminal:

lazarus@Minerva ~]$ guake
Guake not running, starting it
Loading Gnome schema from: /usr/share/glib-2.0/schemas
Language previously loaded from: /usr/share/locale
Guake Terminal 3.7.1
VTE 0.60.2
Gtk 3.24.20
created fresh notebook for workspace 0
Spawning new terminal at /home/lazarus
current workspace is 0
can't bind show-focus key
Spawning new terminal at /home/lazarus
Spawning new terminal at /home/lazarus
Guake tabs restored from /home/lazarus/.config/guake/session.json
Guake initialized
Guake tabs saved to /home/lazarus/.config/guake/session.json
Segmentation fault (core dumped)

-------------------------------------------------------------------------------

[lazarus@Minerva ~]$ guake --support
<details><summary>$ guake --support</summary>

Guake Version:		3.7.1

Vte Version:		0.60.2

Vte Runtime Version:	0.60.2

--------------------------------------------------
GTK+ Version:		3.24.20

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: gnome-xorg

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - SAM DisplayPort-1
    * Geometry:		2560 x 1440 at 0, 0
    * Size:		697 x 392 mm²
    * Primary:		True
    * Refresh rate:	144.00 Hz
    * Subpixel layout:	unknown
[lazarus@Minerva ~]$

**Comment by cubedtear** [comment]
I have been having a similar issue, which was also mentioned in https://github.com/Guake/guake/issues/1749#issuecomment-632189285. Maybe check if the "solution" I posted there works for you.

**Comment by michaelothing** [comment]
Well for now it works. I will have to see if it keeps working.
