### ISSUE TITLE
xdg-open fails to open firefox 

### ISSUE THREAD

**Issue by treeshateorcs** [Guake/guake#1763]
**Describe the bug**

when i try to open a website with xdg-open, for some reason it doesn't open in the existing firefox window, but it tries to start a new firefox session, so i get an error after a few seconds, and the site doesn't open at all

this doesn't happen with chrome, which explicitly states that it will open a new tab in the existing session, after issuing an xdg-open command. neither does it happen in gnome-terminal (with both firefox or chrome)

**Expected behavior**

site should open in the existing firefox session

**Actual behavior**

![image](https://user-images.githubusercontent.com/60894565/82730920-196d8e00-9d0c-11ea-91ad-57e4c2d864a6.png)

**To Reproduce**

1. install firefox and guake
2. make firefox your default browser
3. `xdg-open "https://google.com"` in guake

-------------------------------------------------------------------------------
<details><summary>$ guake --support</summary>

Guake Version:		3.7.0

Vte Version:		0.60.2

Vte Runtime Version:	0.60.2

--------------------------------------------------
GTK+ Version:		3.24.20

GDK Backend:		__gi__.GdkWaylandDisplay

--------------------------------------------------
Desktop Session: gnome

--------------------------------------------------
Display: wayland-0

RGBA visual: True

Composited: True

* Monitor: 0 - AUO 0x243d
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		310 x 170 mm²
    * Primary:		False
    * Refresh rate:	60.03 Hz
    * Subpixel layout:	unknown

**Comment by eeshugerman** [comment]
Does it "fix" the issue if you do `GDK_BACKEND=wayland xdg-open "https://google.com"`?

I run into this issue with other programs -- Firefox is running with `GDK_BACKEND=wayland`, but then other programs try to open a tab in Firefox without setting this variable and apparently Firefox doesn't like that.

Not sure what the proper fix is, but it seems to me it would be ideal if Firefox could handle the situation gracefully so this is fixed everywhere.

**Comment by eeshugerman** [comment]
There's some [related discussion on Firefox bug tracker](https://bugzilla.mozilla.org/show_bug.cgi?id=1635830). Looks like the solution might be to run Firefox with `MOZ_ENABLE_WAYLAND=1` instead of `GDK_BACKEND=wayland`. But I haven't tested this yet.

**Comment by Davidy22** [comment]
If this is solved with firefox related settings entirely, I'll close this as this is probably a firefox issue
