### ISSUE TITLE
open markdown format link support

### ISSUE THREAD

**Issue by roachsinai** [Guake/guake#1768]
If I pasted a markdown link like `[Guake/guake: Drop-down terminal for GNOME](https://github.com/Guake/guake)` to guake, then press `Ctrl LeftMouseClick`,  failed to open it.

But if delete the last `)` means for `[Guake/guake: Drop-down terminal for GNOME](https://github.com/Guake/guake` use `Ctrl LeftMouseClick` can open the link at browser.

## Expected behavior

Support `Ctrl LeftMouseClick` works for markdown link like `[Guake/guake: Drop-down terminal for GNOME](https://github.com/Guake/guake)`.

**Comment by Davidy22** [comment]
Tested in latest master and looks like this is fixed. Likely was fixed as a side effect of #1900
