### ISSUE TITLE
Terminal appears on wrong monitor if primary screen is right of secondary one

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#177]
Terminal appears on wrong monitor if primary screen is right of secondary one
http://guake.org/ticket/201
Reported by:    maweaver    Owned by:   somebody
Priority:   Fix available   Milestone:  0.5.0
Component:  guake   Version:  
Keywords:       Cc:     perperenator@…, alex@…
Description

get_final_window_rect, assumes window_rect.x is 0, which may not always be the case. If the starting X coordinate is > 0 it gets reset to 0 by the calculations. The X coordinates should be added to, not set directly:

if halignment == ALIGN_CENTER:

```
window_rect.x += (total_width - window_rect.width) / 2
```

if halignment == ALIGN_LEFT:

```
window_rect_x += 0
```

elif halignment == ALIGN_RIGHT:

```
window_rect.x += total_width - window_rect.width
```

**Comment by jl2035** [comment]
It looks like this was fixed back in 2014. Why am I getting this behaviour on up-to-date ElementaryOS?

**Comment by brianbourke75** [comment]
I am also seeing this behavior in Arch linux (guake 0.8.5)

**Comment by jl2035** [comment]
Oh.. just realized that I'm running Guake 0.4.4. Why does Ubuntu use such old version..?

**Comment by mdesantis** [comment]
Just old release... on 14.04 guake is 0.4.4, on 16.04 it has been updated to 0.8.4: http://packages.ubuntu.com/xenial/guake

**Comment by jl2035** [comment]
Well, this will be interesting to see, next time I format my laptop.

**Comment by mdesantis** [comment]
Extract from guake readme: 

> 
> PPA
> 
> An external, unofficial PPA for latest version of Ubuntu seems to integrate Guake regularly. Check it at the following URL:
> 
>     https://launchpad.net/~webupd8team/+archive/ubuntu/unstable

**Comment by mabushey** [comment]
Guake used to open in whatever monitor the mouse pointer was in, but now it's opening only in the right window. I'm running guake 0.8.5-1 on Arch.

**Comment by Stibbons** [comment]
Look like a bug in the dual monitor support :(

**Comment by jl2035** [comment]
I have moved my primary monitor to the left side of my office table. This is how I'm getting around this issue. :(

**Comment by mabushey** [comment]
The weird thing is it started working correctly again, without a reboot or any changes... The problem started after I rebooted into the 4.4 Kernel and went away after an hour. My primary monitor is on the left side. BTW I love Guake!

**Comment by buddemat** [comment]
Seems this issue is still relevant in 2020? When I move my primary display to the left, guake opens on the correct screen, when I move it to the right, it opens on the left (secondary) screen regardless of where the mouse pointer is (though scaled down to the size of the smaller primary display when the mouse pointer is there).

(Guake 3.6.3, Ubuntu 20.04.1 LTS)

**Comment by jatpatel1** [comment]
> Seems this issue is still relevant in 2020? When I move my primary display to the left, guake opens on the correct screen, when I move it to the right, it opens on the left (secondary) screen regardless of where the mouse pointer is (though scaled down to the size of the smaller primary display when the mouse pointer is there).
> 
> (Guake 3.6.3, Ubuntu 20.04.1 LTS)

Same Issue for me too on Ubuntu 20.04.1 LTS :-(

**Comment by zdenda-online** [comment]
Same issue here Ubuntu 20.10

**Comment by maxidev** [comment]
Same issue: "Linux Mint 20.1 Ulyssa"
