### ISSUE TITLE
Please add support for python 3.7

### ISSUE THREAD

**Issue by strahlc** [Guake/guake#1770]
The `setup.cfg` in currect master branch list only python 3.5 and python 3.6 as compatible.
``` 
Programming Language :: Python :: 3.5
Programming Language :: Python :: 3.6
```
Please add support for python 3.7, because some linux distros (including my gentoo installation) uses python 3.7 as default.

**Comment by Bost** [comment]
And also `python 3.8` please. Thanks

**Comment by opncow** [comment]
Yes, please. Same issue here.
