### ISSUE TITLE
Characters in the terminal randomly turn into symbols

### ISSUE THREAD

**Issue by UnoSD** [Guake/guake#1773]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Guake.

For how to run the latest Guake in your computer, please refer to [Install from source](https://guake.readthedocs.io/en/latest/user/installing.html#install-from-source).

**Describe the bug**

After running commands, occasionally, all characters of the terminal turn into symbols.

**Expected behavior**

Characters to stay readable.

**Actual behavior**

![2020-06-19_11-30](https://user-images.githubusercontent.com/1582987/85195726-e13a7a80-b2cc-11ea-8b11-b7de720bf355.png)

**To Reproduce**

Typing and hitting enter, rarely.

-------------------------------------------------------------------------------

Please run `$ guake --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting. And make sure you run the command **OUTSIDE** the Guake.

<details><summary>$ guake --support</summary>

Guake Version:		3.7.0

Vte Version:		0.60.3

Vte Runtime Version:	0.60.3

--------------------------------------------------
GTK+ Version:		3.24.20

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: xfce

--------------------------------------------------
Display: :0.0

RGBA visual: True

Composited: True

* Monitor: 0 - BOE eDP-1
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		294 x 165 mm²
    * Primary:		True
    * Refresh rate:	59.98 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - BTC DVI-I-2-2
    * Geometry:		1680 x 1050 at 1920, 30
    * Size:		473 x 296 mm²
    * Primary:		False
    * Refresh rate:	59.85 Hz
    * Subpixel layout:	unknown
* Monitor: 2 - IVM DVI-I-1-1
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		477 x 268 mm²
    * Primary:		False
    * Refresh rate:	60.00 Hz
    * Subpixel layout:	unknown

**Comment by Davidy22** [comment]
Unable to reproduce, what commands exactly are being run? What font are you using?

**Comment by UnoSD** [comment]
It has been a while now, I cannot remember if there was a specific command/combination. Has not happened in a long time.

**Comment by Davidy22** [comment]
I think the most valuable information to provide for this specific bug would be the font and shell program you're using, in case the issue is being caused by either of them isntead. Will close since this hasn't happened in a while.

**Comment by UnoSD** [comment]
I'm using `Bash` and `Fira Code Regular 16`

**Comment by Davidy22** [comment]
Oh, I know fira code has ligatures which VTE doesn't support. They've improved a bit at error handling I think but they're still very solidly on not supporting ligatures yet. I suspect your issue from back then that you aren't experiencing now was due to vte choking on ligatures, if you were using fira when you submitted this.
