### ISSUE TITLE
Bottom alignment does not work in Fedora 32

### ISSUE THREAD

**Issue by Archehandoro** [Guake/guake#1776]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Guake.

For how to run the latest Guake in your computer, please refer to [Install from source](https://guake.readthedocs.io/en/latest/user/installing.html#install-from-source).

**Describe the bug**

Bottom alignment does not work in Fedora 32.

**Expected behavior**

The terminal should show at the bottom all times.

**Actual behavior**

When having bottom alignment configured, after pressing F12, the terminal shows always at the top, except in these occasions:

- The first time the terminal it's use after a reboot. In this case, the terminal opens once at the bottom, or at the middle of the screen one time, until it's then closed and reopened again.
- When opening a new tab via ctrl + shift + t brings the terminal to the bottom, but then again it's taken to the top after closing/showing it.

**To Reproduce**

Press F12 key to show terminal.

-------------------------------------------------------------------------------

Please run `$ guake --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting. And make sure you run the command **OUTSIDE** the Guake.

Guake Version:		3.6.3

Vte Version:		0.60.3

Vte Runtime Version:	0.60.3

--------------------------------------------------
GTK+ Version:		3.24.20

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: gnome-xorg

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - IVM DP-1
    * Geometry:		2560 x 1440 at 0, 0
    * Size:		597 x 336 mm²
    * Primary:		True
    * Refresh rate:	70.00 Hz
    * Subpixel layout:	unknown

Thank you so much!

**Comment by Davidy22** [comment]
Working in Fedora 36, GNOME version, presuming fixed
