### ISSUE TITLE
"Backspace" to Disable Shortcut Fails

### ISSUE THREAD

**Issue by moore-bryan** [Guake/guake#1778]
Running Guake 3.6.3-4.fc32 on Asus Zenbook with Fedora 32 (Wayland), GNOME 3.36.3, and 5.6.19-300.fc32.x86_64 kernel.

The well-known Wayland keybinding issue can be worked around by setting the F12 key in GNOME; however, there is no way to _disable_ the F12 keybinding in Guake itself because "Backspace" fails to delete the shortcut.

Let me know if there's any additional information needed...

**Comment by mkoshelev** [comment]
As a workaround, you change this binding directly in dconf: `gsettings set guake.keybindings.global show-hide '"disabled"'`

**Comment by moore-bryan** [comment]
> As a workaround, you change this binding directly in dconf: `gsettings set guake.keybindings.global show-hide "'disabled'"`

Thank you!

**Comment by brendankhoury** [comment]
I am having a similar issue. I am unable to change keyboard shortcuts using the Guake Preferences gui. I am using Linux Mint 20.

**Comment by SeanPedersen** [comment]
Working to allow the reset of show-hide hotkey right now here https://github.com/Guake/guake/pull/1807
Should be fixed soon

**Comment by Davidy22** [comment]
Fix has been merge and I can no longer reproduce this, so closing issue.

**Comment by xahon** [comment]
Guake doesn't want to reset a shortcut in vanilla Ubuntu 18.04 (v 3.0.5-1)

**Comment by Suor** [comment]
Still having this issue in Manjaro KDE.
```bash
$ guake --version                                                                                                                                 ✔ 
Guake Terminal: 3.11.dev0
VTE: 0.82.3
VTE runtime: 0.82.3
Gtk: 3.24.51
```
