### ISSUE TITLE
Dropdown stopped working

### ISSUE THREAD

**Issue by davdet** [Guake/guake#1779]
Guake is set up as a startup application on my system but the dropdown hotkey doesn't work as expected. The message shows up on startup, but to toggle the dropdown I always need to open Guake Preferences first. Used to work fine until two weeks ago.

OS: Manjaro Linux x86_64 
Host: XPS 15 7590 
Kernel: 5.6.16-1-MANJARO 
Uptime: 32 mins 
Packages: 1213 (pacman), 7 (flatpak), 5 (snap) 
Shell: bash 5.0.17 
Resolution: 3840x2160 
DE: GNOME 
WM: Mutter 
WM Theme: Matcha-dark-sea 
Theme: Matcha-dark-sea [GTK2/3] 
Icons: Papirus-Dark-Maia [GTK2/3] 
Terminal: guake 
CPU: Intel i7-9750H (12) @ 4.500GHz 
GPU: Intel UHD Graphics 630 
GPU: NVIDIA GeForce GTX 1650 Mobile / Max-Q 
Memory: 5222MiB / 15649MiB 

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:		3.7.0

Vte Version:		0.60.3

Vte Runtime Version:	0.60.3

--------------------------------------------------
GTK+ Version:		3.24.20

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: gnome

--------------------------------------------------
Display: :1

RGBA visual: True

Composited: True

* Monitor: 0 - SDC eDP-1
    * Geometry:		1920 x 1080 % 2 at 0, 0
    * Size:		344 x 194 mm²
    * Primary:		True
    * Refresh rate:	60.00 Hz
    * Subpixel layout:	unknown

**Comment by salbador** [comment]
I got insights in this regard. I did some research.  I have a way to reproduce this error. I assumed here "dropdown" means "dropdown menu" ?

**Comment by dev-dd** [comment]
I mean the drop-down terminal. It doesn't toggle without opening (and then closing) Guake Preferences first.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by zeusintuivo** [comment]
If you change the file ` /home/user/_/laptop_computer_setup/guake/guake/customcommands.py:64 ` to 
```python
    def build_menu(self):
        if not self.should_load():
            return None
        menu = Gtk.Menu()
        log.info("Loading menu json file: %s", self.get_file_path())
        cust_comms = self._load_json(self.get_file_path())
        if not cust_comms:
            return None
        for obj in cust_comms:
            try:
                self._parse_custom_commands(obj, menu)
            except AttributeError:
                log.error("Loading menu json file: %s", self.get_file_path())
                log.error("_parse_custom_commands parsing type: %s", type(obj))
                log.error("_parse_custom_commands parsing json: %s", obj)
                # AttributeError: 'str' object has no attribute 'get', ignore and move on
                pass
            
        return menu
```
It logs the following 
```log
ERROR    Loading menu json file: /home/user/.config/guake/session.json
ERROR    _parse_custom_commands parsing type: <class 'str'>
ERROR    _parse_custom_commands parsing json: schema_version
INFO     _parse_custom_commands parsing type: <class 'str'>
INFO     _parse_custom_commands parsing json: timestamp
ERROR    Loading menu json file: /home/user/.config/guake/session.json
ERROR    _parse_custom_commands parsing type: <class 'str'>
ERROR    _parse_custom_commands parsing json: timestamp
INFO     _parse_custom_commands parsing type: <class 'str'>
INFO     _parse_custom_commands parsing json: workspace
ERROR    Loading menu json file: /home/user/.config/guake/session.json
ERROR    _parse_custom_commands parsing type: <class 'str'>
ERROR    _parse_custom_commands parsing json: workspace
INFO     Guake tabs saved to /home/user/.config/guake/session.json
``` 
And it keeps working. 
# It's a patch but perhaps not the right solution. The real question to solve here is why is this method failing while reading the  `  session.json ` file ?
