### ISSUE TITLE
If the shell immediately exits, the user never sees the error message

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#178]
If the shell immediately exits, the user never sees the error message
http://guake.org/ticket/199
Reported by:    kkinder     Owned by:   somebody
Priority:   major   Milestone:  0.5.0
Component:  guake   Version:  
Keywords:       Cc:  
Description

If the user has a problem launching his shell that causes the shell to show an error message, the user never sees that message, because guake immediately disappears; all you see is a flash of where the terminal is for a split second.

**Comment by Stibbons** [comment]
If you want this feature, please vote on [FeatHub](https://feathub.com/Guake/guake)
