### ISSUE TITLE
Some code quality issues found in guake

### ISSUE THREAD

**Issue by pnijhara** [Guake/guake#1787]
I have been using guake for a long time and so I thought of trying a code quality checkup. I forked this repo and thus ran a [DeepSource](https://deepsource.io) analysis on my [forked repo](https://github.com/pnijhara/guake/tree/pnijhara-patch-1).
The best part was there were not more than 25 issues found.
- Antipatterns: 8
- Security Issues: 17

Quite a less number, however, can be fixed in no time.
You can find the detailed report here &rarr; https://deepsource.io/gh/pnijhara/guake/issues/?category=recommended

Some of the issues can be fixed in a single click using DeepSource Autofix tool.

Do let me know which of the issues are solvable. I would love to send a patch with some fix.

I have also added a DeepSource config file `.deepsource.toml` in my forked repo to let DeepSource run analysis on it. The file can be found [here](https://github.com/pnijhara/guake/blob/pnijhara-patch-1/.deepsource.toml).

**Comment by ulidtko** [comment]
Hey, nice work!

I'd love to integrate some code quality tools into the CI here — so, this little experiment appreciated.

Skimming through the issues: nice, that's likeable.

We definitely need to address all of these issues.

--------------------------------------------

Regarding `assert isinstance(pid, int)` — this whole block smells:
https://github.com/Guake/guake/blob/00d880f78a793c481efe027225ddbc81a97bcf11/guake/terminal.py#L555-L563

What's worse — it's got a copy-pasted replica already, here:
https://github.com/Guake/guake/blob/d4c3d203e3e0c827c4869bd1626acb7c3a366736/guake/prefs.py#L715-L724

Justs cries for refactor.

---------------------------------------------------------------

Oh BTW — can deepsource detect copy-paste?.. Is there tweakable threshold of *"you've copy-pasted too much, sorry"* ?

**Comment by pnijhara** [comment]
Thank you @ulidtko!
I will send a patch with some fix that will contain a config file as `.deepsource.toml`. This file will allow DeepSource to analyze Guake. I will other details in the PR.

> Oh BTW @pnijhara — can deepsource detect copy-paste?.. Is there tweakable threshold of "you've copy-pasted too much, sorry" ?
We don't do it at the moment but we might add a checker for this in the upcoming releases.
