### ISSUE TITLE
send commands or pwd with keyboard shortcuts

### ISSUE THREAD

**Issue by runmain** [Guake/guake#1790]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Guake.

For how to run the latest Guake in your computer, please refer to [Install from source](https://guake.readthedocs.io/en/latest/user/installing.html#install-from-source).

---------------------------------------

Please use [FeatHub](https://feathub.com/Guake/guake) to fill-up a feature request.

This allow us to spot directly which are the most requested features.

**Comment by Davidy22** [comment]
You can bind custom commands like pwd to arbitary keyboard shortcuts using the [bind](https://www.geeksforgeeks.org/bind-command-in-linux-with-examples/) command in bash, [bindkey](https://jdhao.github.io/2019/06/13/zsh_bind_keys/) in zsh and a similar command in various other shells, independent of guake.
