### ISSUE TITLE
Security Issue: Exposure of sensitive function, malicious user can arbitrary command via an execute_command d-bus method.

### ISSUE THREAD

**Issue by junorouse** [Guake/guake#1796]
**Describe the bug**

We understand that the usability of `-e` option. (https://github.com/Guake/guake/issues/720)
BTW, it must not be exposured in d-bus interfaces.

**Expected behavior**

guake must not exposure execute_command in d-bus interfaces.

*Do not exposure execute_command in d-bus interface.*

**Actual behavior**

guake exposure execute_command in d-bus interface.

**To Reproduce**

We can use gdbus to call an execute_command d-bus method.

```
$ gdbus call -e -d org.guake3.RemoteControl -o /org/guake3/RemoteControl -m org.guake3.RemoteControl.execute_command "id > /tmp/1234"
$ cat /tmp/1234
uid=1000(juno) gid=1000(juno) groups=1000(juno),4(adm),20(dialout),21(fax),24(cdrom),25(floppy),26(tape),27(sudo),29(audio),30(dip),44(video),46(plugdev),100(users),109(netdev),112(bluetooth),115(lpadmin),117(scanner)
```

-------------------------------------------------------------------------------

```
juno@abcd:/tmp/p/$ guake --support
Usage: guake [options]

guake: error: no such option: --support

```

cc. @bbb1g

**Comment by junorouse** [comment]
And also execute_command_by_uuid affected.

```
execute_command_by_uuid(in  s tab_uuid,
                                                        in  s command);
```

**Comment by ghostshadow** [comment]
Hi, it is nice, that you fix a potential security issue, but is there any concept for keeping the `-e` option working without the dbus call?
I use this option at a few places and would like to know now, if this option is going to be supported in the future or if i have to find another method for implementing my use cases.

**Comment by Davidy22** [comment]
Only the dbus call has been disconnected, -e is still a flag
