### ISSUE TITLE
Feature Request for the background image function

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#180]
Feature Request for the background image function http://guake.org/ticket/187
Reported by:    Arabus  Owned by:   somebody
Priority:   minor   Milestone:  
Component:  guake   Version:    0.4
Keywords:   background-image, image, background, image size, scale image    Cc:  
Description

It would be nice if one could control whether the background image is tiled, stretched, or centered. Currently one hsa to supply an image sized for ones current screen resolution to have it fill the screen. Also one has to switch to fullscreen mode then , to view to the full picture.

Since guake currently is drop down only a "stick to bottom" option for the background image would be nice too. this would allow to supply guake with a small and broad version of an image (e.g. 1280x320) that would always be displayed at the bottom of the terminal with the background color starting above the upper image border.

**Comment by Stibbons** [comment]
Backgroup image feature no more supported

**Comment by mvpossum** [comment]
Why has this feature been removed? I don't like transparency because if I have a terminel below guake the letters get mixed. I don't like a plain black color. What I used to do was to put my desktop wallpaper as background image. The result looked great, now I updated guake and I don't have it anymore :(

**Comment by Stibbons** [comment]
this feature has been removed from the VTE component we use for the virtual terminal. There is no way of readding it back, sory

**Comment by maximpap** [comment]
@gsemet Please let's think how to come it back, because it's a really useful feature. :-1:

**Comment by gsemet** [comment]
pull request on the VTE component ?
