### ISSUE TITLE
Only runs as sudo ubuntu 20.04

### ISSUE THREAD

**Issue by Pilly170** [Guake/guake#1804]
Ive tried searching for the file listed below before posting.

Running ubuntu 20.04, Installed via apt
Running guake in gui, nothing happens when run.
running guake in terminal

`PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.8/dist-packages/s3transfer-0.3.3.dist-info'`

when i run support option ^^ exactly the same.

When i run guake via terminal with sudo. it works, as well as the support command.

**Comment by a-serafimovich** [comment]
Using 20.04 too, but don't have this problem.

**Comment by woodpenker** [comment]
> Ive tried searching for the file listed below before posting.
> 
> Running ubuntu 20.04, Installed via apt
> Running guake in gui, nothing happens when run.
> running guake in terminal
> 
> `PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.8/dist-packages/s3transfer-0.3.3.dist-info'`
> 
> when i run support option ^^ exactly the same.
> 
> When i run guake via terminal with sudo. it works, as well as the support command.

please check this file's permission, using cmd like: `ls -al /usr/local/lib/python3.8/dist-packages/s3transfer-0.3.3.dist-info` to make sure this file is not only readable to root user.

**Comment by Davidy22** [comment]
The quoted file in the report seems to be an unrelated package, and the installation process works for others so this is probably a local environment issue. Try removing the offending packages as root and then installing guake. You can also install from pypi, which may or may not deal with your issue.
