### ISSUE TITLE
Alternative <F12> behavior

### ISSUE THREAD

**Issue by fde-capu** [Guake/guake#1810]
Guake is lovely.
I would like `<F12>` to behave alternatively like: minimize all windows and bring Guake to focus.
I find myself constantly using `<super+D>` then `<F12>`;
Maybe keep `<F12>` as is, and implement `<super+F12>` for this effect.
Motivation: aesthetics: I like to use semi-transparent Guake over beautiful desktop backgrounds.

**Comment by renyhp** [comment]
You can probably set up a OS-level shortcut. The command to show the desktop would be `wmctrl -k on`, while the command to show guake would be `guake --show`.

Just remove the binding in the Guake preferences, then go to your OS preferences and add super+F12 as a shortcut for the command `wmctrl -k on && guake --show`.

**Comment by fde-capu** [comment]
Perfect, thank you, also for the commands instruction. Let this be a suggestion for an extra option inside Guake, still.
