### ISSUE TITLE
[Question] Is there a way to force close a tab while a process is running?

### ISSUE THREAD

**Issue by renyhp** [Guake/guake#1812]
### The problem

```
$ python3
>>> while True:
...   pass
... 
```

The process is now hanging. (Of course, this is just for demonstrating purposes; I know I can make python responsive again with Ctrl+C, but that's not the point. To be clear: my problem arises whenever a process is hanging and I **can't** stop it with Ctrl+C)

Guake does not respond to tab right click > Close. I can't find the way to close this tab without quitting Guake.

### Question

Is this by design? / Is there another way? / Can this feature be added?

-------------------------
#### Workaround
Ctrl+Z suspends the process and sends it to background. [Link to askubuntu](https://askubuntu.com/questions/510811/what-is-the-difference-between-ctrl-z-and-ctrl-c-in-the-terminal)

**Comment by Davidy22** [comment]
There is a close tab keyboard shortcut that I have bound to CTRL+SHIFT+W but you might choose another combination for. You can find it in preferences under keyboard shortcuts, tab management, and rebind close tab.

**Comment by renyhp** [comment]
Actually, I tried that, but the tab does not close.

**Comment by Davidy22** [comment]
I just tested the infinite loop in python again and force exit still works for me. In preferences under keyboard shortcuts, what shortcut do you see by "Close tab"? Does it work?

**Comment by renyhp** [comment]
Keyboard shortcuts says "Close tab" is Ctrl+W, because I set it that way. Using it doesn't work for me. I also tried to set it to Ctrl+Shift+W again, the tab is still not closed.

**Comment by Davidy22** [comment]
Does the keyboard shortcut do anything anywhere else? It might be getting captured by another process, or another shortcut inside guake.

**Comment by Davidy22** [comment]
Actually, in relation to #1863, try starting guake from a terminal and try to close a tab. Do you see the same traceback printed in that issue?

**Comment by Davidy22** [comment]
Alright, I think I found the issue. Do you have the "Prompt when close tab" option in preferences set to anything other than "Never"? I think I found an issue in there that I've submitted a pull request to fix.

**Comment by Davidy22** [comment]
Merged a patch that will fix that if it was your issue.

**Comment by renyhp** [comment]
That was it, thank you very much!
