### ISSUE TITLE
Guake window doesn't appear after pressing shortcut on Wayland

### ISSUE THREAD

**Issue by ramazanemreosmanoglu** [Guake/guake#1814]
I use wayland. after running it, notification says: "An error occurred while assigning the f12 shortcut. Please select a new shortcut using the guake options window.". And when i press f12, nothing happens. Console output can help you:

```
11:54:50 emre@fedora:~% guake
Guake not running, starting it

(guake:12649): Gtk-WARNING **: 11:56:17.128: Theme parsing error: gtk.css:7173:46: Junk at end of value for background-color
Guake Terminal 3.6.3
VTE 0.62.1
Gtk 3.24.23

(guake:12649): Gtk-CRITICAL **: 11:56:17.306: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
created fresh notebook for workspace 0
Spawning new terminal at /home/emre

(guake:12649): VTE-WARNING **: 11:56:17.317: (../src/vtepty.cc:667):bool _vte_pty_spawn_sync(VtePty*, const char*, const char* const*, const char* const*, GSpawnFlags, GSpawnChildSetupFunc, gpointer, GDestroyNotify, GPid*, int, GCancellable*, GError**): runtime check failed: ((spawn_flags & ignored_spawn_flags()) == 0)
current workspace is 0

** (guake:12649): WARNING **: 11:56:17.405: Binding 'F12' failed!
can't bind show-focus key
Cannot found tabs session.json file
Guake initialized
```

I tried changing f12 with other shortcuts, but the same error raises.

NOTE: If i switch to Xorg, f12 shortcut works.

NOTE 2: I know, there is a [similar issue](https://github.com/Guake/guake/issues/492), but my problem is different. In that issue, guake opens when other window opened, but guake never opens on my computer.

-------------------------------------------------------------------------------
<details><summary>$ guake --support</summary>

Guake Version:		3.6.3

Vte Version:		0.62.1

Vte Runtime Version:	0.62.1

--------------------------------------------------
GTK+ Version:		3.24.23

GDK Backend:		__gi__.GdkWaylandDisplay

--------------------------------------------------
Desktop Session: gnome

--------------------------------------------------
Display: wayland-0

RGBA visual: True

Composited: True

* Monitor: 0 - CMN 0x14c4
    * Geometry:		1366 x 768 at 0, 0
    * Size:		310 x 170 mm²
    * Primary:		False
    * Refresh rate:	60.00 Hz
    * Subpixel layout:	unknown

**Comment by pi1Mg** [comment]
Have you tried [workaround](https://github.com/Guake/guake/issues/492#issuecomment-119075514)?

> 
    Open the keyboard shortcuts for your environment (for Gnome, that's Settings::Keyboard::Shortcuts)
    Add a new shortcut named "Toggle Guake", with the command "guake -t", and set the hotkey for it


It helped me on Fedora 33 Wayland.

**Comment by ramazanemreosmanoglu** [comment]
Thank you, it works, but guake opens so late. (About 3 seconds after)

**Comment by mrbeardad** [comment]
So, are you decided to fix this bug essentially now? Because the tray icon is lost.

**Comment by matthew-kenny** [comment]
So, can confirm this issue is affecting ubuntu 21.04 beta default installation as its now using wayland by default.

**Comment by scarlehoff** [comment]
> Thank you, it works, but guake opens so late. (About 3 seconds after)

I have this problem as well (wayland, gnome, in arch). I wonder whether there's any trick to make it faster when using `-t` (like skipping certain checks or animations)

**Comment by abh-pro** [comment]
> Thank you, it works, but guake opens so late. (About 3 seconds after)
Instead of `guake -t` try using [`guake-toggle`](https://github.com/Guake/guake/issues/492#issuecomment-538902686), it is much faster

**Comment by Pound-Hash** [comment]
In version `3.8.2`, I don't need to run `guake-toggle` anymore to render the terminal quickly; `guake` or `guake -t` are just as fast.

Debian 11
Gnome 3.38.5
Guake Terminal: 3.8.2.dev6
VTE: 0.62.3
VTE runtime: 0.62.3
Gtk: 3.24.24

**Comment by Davidy22** [comment]
The behavior in `guake` shouldn't have changed, it should still be measurably slower than guake-toggle, although it is still somewhat fast and if your machine is fast enough you may not notice anything regardless.

**Comment by Pound-Hash** [comment]
> The behavior in `guake` shouldn't have changed, it should still be measurably slower than guake-toggle, although it is still somewhat fast and if your machine is fast enough you may not notice anything regardless.

The Guake window is opening noticeably quicker for me than it was on version `3.6.3-2` (from Debian's main repos).

**Comment by Davidy22** [comment]
Switched to wayland a bit ago to get first hand experience for wayland issues, now going back though the backlog. Wayland explicitly blocks programs from assigning their own global keyboard shortcuts, the expected way to set a global keyboard shortcut on a wayland system is to go into your system's provided keyboard shortcut manager and assign `guake-toggle` from there. If you still have a global keyboard shortcut assigned from inside Guake preferences, Guake will still attempt to bind it on wayland and fail because of intentional wayland design.
