### ISSUE TITLE
all pasted text is highlighted in black

### ISSUE THREAD

**Issue by linuxgirl22** [Guake/guake#1822]
**Describe the bug**
Every text pasted into Guake is highlighted in black. 

Text highlighted in black. 

**Expected behavior**
Normal clean text, with no highlighting. 

Clean text. 

**Actual behavior**
Text highlighted in black. 

What you actually get.
Text highlighted in black. 

**To Reproduce**
Paste any text into Guake command line. 

Provide the steps to reproduce the behavior
Paste any text into Guake command line. 
-------------------------------------------------------------------------------

guake --support
<details><summary>$ guake --support</summary>

Guake Version:		3.7.0

Vte Version:		0.62.1

Vte Runtime Version:	0.62.1

--------------------------------------------------
GTK+ Version:		3.24.24

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: mate

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - DEL HDMI-1
    * Geometry:		2560 x 1440 at 0, 0
    * Size:		597 x 336 mm²
    * Primary:		True
    * Refresh rate:	59.95 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - ROW DP-1
    * Geometry:		1920 x 1080 at 2560, 0
    * Size:		575 x 323 mm²
    * Primary:		False
    * Refresh rate:	60.00 Hz
    * Subpixel layout:	unknown

**Comment by Davidy22** [comment]
Text pasted into a shell will be highlighted, which goes against the expected behavior in the report. If you are using a light guake theme, the highlight color will tend to be black, which should also be expected.
