### ISSUE TITLE
Guake does not start under ubuntu 21.04

### ISSUE THREAD

**Issue by romange** [Guake/guake#1841]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Guake.

For how to run the latest Guake in your computer, please refer to [Install from source](https://guake.readthedocs.io/en/latest/user/installing.html#install-from-source).

**Describe the bug**
Guake does not start. 

Guake Terminal: 3.7.0
VTE: 0.62.3
VTE runtime: 0.62.3
Gtk: 3.24.25

**Expected behavior**

**Actual behavior**

```
(guake:34925): VTE-WARNING **: 22:41:21.476: (../src/vtepty.cc:691):bool _vte_pty_spawn_sync(VtePty*, const char*, const char* const*, const char* const*, GSpawnFlags, GSpawnChildSetupFunc, gpointer, GDestroyNotify, GPid*, int, GCancellable*, GError**): runtime check failed: ((spawn_flags & ignored_spawn_flags()) == 0)
...
guake:34925): Gdk-CRITICAL **: 22:41:43.570: gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed
/usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1304: Warning: unable to set property 'accel-key' of type 'guint' from value of type 'gchararray'
  Gtk.TreeStore.set_value(self, treeiter, column, value)
/usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1304: Warning: unable to set property 'accel-mods' of type 'GdkModifierType' from value of type 'gchararray'
  Gtk.TreeStore.set_value(self, treeiter, column, value)
```

What you actually get.

**To Reproduce**

install guake on ubuntu 21.04 via `sudo pip3 install guake`

try running guake

-------------------------------------------------------------------------------

Please run `$ guake --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting. And make sure you run the command **OUTSIDE** the Guake.

**Comment by romange** [comment]
<details><summary>$ guake --support</summary>

Guake Version:		3.7.0

Vte Version:		0.62.3

Vte Runtime Version:	0.62.3

--------------------------------------------------
GTK+ Version:		3.24.25

GDK Backend:		__gi__.GdkWaylandDisplay

--------------------------------------------------
Desktop Session: ubuntu

--------------------------------------------------
Display: wayland-0

RGBA visual: True

Composited: True

* Monitor: 0 - HPN HP Z24n G2
    * Geometry:		1920 x 1200 at 0, 0
    * Size:		520 x 320 mm²
    * Primary:		False
    * Refresh rate:	59.95 Hz
    * Subpixel layout:	unknown

**Comment by bigunclemax** [comment]
same problem
<details><summary>$ guake --support</summary>

Guake Version:		3.6.3

Vte Version:		0.62.3

Vte Runtime Version:	0.62.3

--------------------------------------------------
GTK+ Version:		3.24.25

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: ubuntu

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 -  XWAYLAND0
    * Geometry:		1920 x 1080 at 1080, 1004
    * Size:		340 x 190 mm²
    * Primary:		True
    * Refresh rate:	59.96 Hz
    * Subpixel layout:	unknown
* Monitor: 1 -  XWAYLAND1
    * Geometry:		1080 x 1920 at 0, 0
    * Size:		340 x 600 mm²
    * Primary:		False
    * Refresh rate:	59.96 Hz
    * Subpixel layout:	unknown

**Comment by bigunclemax** [comment]
https://github.com/Guake/guake/issues/1642#issuecomment-580668579

This happened besauce Ubuntu 21.04 use Wayland by default. This solution worked for me.

> Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Guake.
> 
> For how to run the latest Guake in your computer, please refer to [Install from source](https://guake.readthedocs.io/en/latest/user/installing.html#install-from-source).
> 
> **Describe the bug**
> Guake does not start.
> 
> Guake Terminal: 3.7.0
> VTE: 0.62.3
> VTE runtime: 0.62.3
> Gtk: 3.24.25
> 
> A clear and concise description of what the bug is.
> 
> **Expected behavior**
> 
> A clear and concise description of what you expected to happen.
> 
> **Actual behavior**
> 
> ```
> (guake:34925): VTE-WARNING **: 22:41:21.476: (../src/vtepty.cc:691):bool _vte_pty_spawn_sync(VtePty*, const char*, const char* const*, const char* const*, GSpawnFlags, GSpawnChildSetupFunc, gpointer, GDestroyNotify, GPid*, int, GCancellable*, GError**): runtime check failed: ((spawn_flags & ignored_spawn_flags()) == 0)
> ...
> guake:34925): Gdk-CRITICAL **: 22:41:43.570: gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed
> /usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1304: Warning: unable to set property 'accel-key' of type 'guint' from value of type 'gchararray'
>   Gtk.TreeStore.set_value(self, treeiter, column, value)
> /usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1304: Warning: unable to set property 'accel-mods' of type 'GdkModifierType' from value of type 'gchararray'
>   Gtk.TreeStore.set_value(self, treeiter, column, value)
> ```
> 
> What you actually get.
> 
> **To Reproduce**
> 
> install guake on ubuntu 21.04 via `sudo pip3 install guake`
> 
> try running guake
> 
> Please run `$ guake --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting. And make sure you run the command **OUTSIDE** the Guake.

**Comment by romange** [comment]
Thanks, worked for me as well
