### ISSUE TITLE
Add custom color schemes 

### ISSUE THREAD

**Issue by KonstantMan** [Guake/guake#1850]
I like creating a lot of custom color schemes with pywal and since i use guake a lot it would be nice to have to add custom color schemes ,like adding the color scheme  i have created in a folder and i could choose from the scheme's list .
I know you can add your own scheme by choosing the colors but that's time consuming and not so precise since you can't exactly find the exact colors

**Comment by Davidy22** [comment]
Just going to leave a link to #1767 which should resolve this generally. For the time being, I'm looking at wal's [instructions page](https://github.com/dylanaraps/pywal/wiki/Getting-Started#applying-the-theme-to-new-terminals) and I just added

```
(cat ~/.cache/wal/sequences &)
```
to my bashrc file and it loads my color scheme nicely. Is there more that you wanted this to do?

**Comment by Davidy22** [comment]
Oh, just realised #1766 exists. Closing due to duplicate, but you can add more info there, and when the pr gets finished that one will be closed too.
