### ISSUE TITLE
Google search from right click menu is broken.

### ISSUE THREAD

**Issue by tejaskale** [Guake/guake#1851]
**Describe the bug**

Right Click --> Search on Web opens 
```html
https://www.google.com/#q=__interrupt_vector_35&safe=off
```

**Expected behavior**

It should open
```html
https://www.google.com/search?query=__interrupt_vector_35&safe=off
```

Probably also a good idea to remove the `safe=off` parameter.

**Actual behavior**

The current link opens a google page with a blank search box.

**To Reproduce**

Select Text ---> Right Click ---> Search on Web.

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:		3.6.3

Vte Version:		0.60.3

Vte Runtime Version:	0.60.3

--------------------------------------------------
GTK+ Version:		3.24.20

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: ubuntu

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - LGD eDP-1
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		309 x 174 mm²
    * Primary:		True
    * Refresh rate:	60.02 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - GSM DP-1
    * Geometry:		3840 x 2160 at 1920, 0
    * Size:		600 x 340 mm²
    * Primary:		False
    * Refresh rate:	60.00 Hz
    * Subpixel layout:	unknown

**Comment by trinaldi** [comment]
I noticed the same and opened a [PR](https://github.com/Guake/guake/pull/1794) some time ago fixing it.

I use Arch and using the `guake-git` from AUR it works fine.
If you're having this issue change the `callbacks.py` and `guake_app.py` files located on `/usr/lib/python3.9/site-packages/guake/` folder (I'm using Python 3.9, YMMV)

**Comment by Davidy22** [comment]
Pull request that fixes this has been merged, closing.
