### ISSUE TITLE
Tab names not showing correct directory with zsh

### ISSUE THREAD

**Issue by amlamarra** [Guake/guake#1853]
In Guake Preferences > Shell, I select `/usr/bin/zsh` as the "Default interpreter."
In Guake Preferences > Main Window, I have the following options set:
![image](https://user-images.githubusercontent.com/14570369/119163739-afc0b680-ba29-11eb-8def-2947f8ba4eec.png)

The terminal opens and shows the correct directory initially (my $HOME dir), but when I move around, the title is not updated.
![image](https://user-images.githubusercontent.com/14570369/119164072-0928e580-ba2a-11eb-8036-5acc1a368d27.png)

Also, opening a new tab shows a tab title of `Terminal`.

This works as expected when I use `/bin/bash` as the "Default interpreter."

-------------------------------------------------------------------------------

I'm using Ubuntu 20.04.2

<details><summary>$ guake --support</summary>

Guake Version:		3.7.1

Vte Version:		0.60.3

Vte Runtime Version:	0.60.3

--------------------------------------------------
GTK+ Version:		3.24.20

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: xubuntu

--------------------------------------------------
Display: :0.0

RGBA visual: True

Composited: True

* Monitor: 0 -  Virtual1
    * Geometry:		1264 x 925 at 0, 0
    * Size:		334 x 245 mm²
    * Primary:		True
    * Refresh rate:	60.00 Hz
    * Subpixel layout:	horizontal-rgb

**Comment by trinaldi** [comment]
This seems to be related to VTE. Tilix has [the same issue](https://gitlab.gnome.org/GNOME/vte/-/issues/37)

**Comment by Davidy22** [comment]
I'm on the latest git build with the same VTE version and I'm unable to reproduce the issue. If able, it'd be nice if you could confirm that the latest version in git works. if you can't be installing from source that's fine, but would like an update on next release to see if the issue is fixed for you there.

**Comment by amlamarra** [comment]
I removed Guake and followed the instructions to install from source (https://guake.readthedocs.io/en/latest/user/installing.html#install-from-source). However, I still see the same issue. The version number doesn't seem to have changed:
```
15:39 ~ ❯ guake --version
Guake Terminal: 3.7.1
VTE: 0.60.3
VTE runtime: 0.60.3
Gtk: 3.24.20
```

**Comment by Davidy22** [comment]
Alright, still going to need more information to fix since I can't reproduce but I'll mark this as a bug for now.

**Comment by amlamarra** [comment]
What info do you need?

**Comment by Davidy22** [comment]
Setting my preferences to the ones listed in the original screenshot didn't produce the bug for me so I think it's not among those, if there's any local setting you have that you think might be relevant that might be helpful. If you can find a setting anywhere that, when toggled, makes this stop occurring that'd go a long way to writing a general fix.

**Comment by trinaldi** [comment]
When I was looking into this, using `pdb` the variable didn't change accordingly. Changing to `bash` the issue went away.

```
~ ᐅ guake --version
Guake Terminal: 3.7.1
VTE: 0.64.2
VTE runtime: 0.64.2
Gtk: 3.24.30
```

**Comment by amlamarra** [comment]
@Davidy22 I messed around with a bunch of options with `/usr/bin/zsh` as the Default Interpreter. However, I couldn't get it to change this behavior. I've screenshotted all my settings (except for keyboard shortcuts). Maybe you can find a difference between mine and yours.

![guake1](https://user-images.githubusercontent.com/14570369/132348562-ccb772cb-ef72-4760-b8e4-d73d4581e79a.png)
![guake2](https://user-images.githubusercontent.com/14570369/132348564-1abd636f-f0de-492c-946e-ee96a9d17678.png)
![guake3](https://user-images.githubusercontent.com/14570369/132348568-de810270-744a-46f2-90c6-a3dee5414fa6.png)
![guake4](https://user-images.githubusercontent.com/14570369/132348570-b2bb0906-b35b-4d9f-b5e0-9276c10cd0de.png)
![guake5](https://user-images.githubusercontent.com/14570369/132348571-51f96e35-0bda-416d-a842-ad7e6d192edf.png)
![guake6](https://user-images.githubusercontent.com/14570369/132348572-96737e05-4802-47db-b4c6-36d15cdbcbef.png)
![guake7](https://user-images.githubusercontent.com/14570369/132348574-b5e5a26b-6b2d-4aaa-9ee8-1c05eadda0ef.png)
![guake8](https://user-images.githubusercontent.com/14570369/132348576-ea576753-a280-43c8-a71b-1c0aee245a52.png)

**Comment by amlamarra** [comment]
FYI, I finally fixed this by adding the following to my `.zshrc` file:

```bash
# Set the window title to the current directory
function precmd {
    echo -ne "\033]0;$(basename $(pwd))\a"
}
```

**Comment by trinaldi** [comment]
That's awesome, @amlamarra !

Just awesome!

**Comment by Davidy22** [comment]
Had an idea recently and tested, I have oh my zsh enabled, tried disabling it and was able to reproduce. Quite possibly oh my zsh bundles something to the effect of your fix. Did some testing and seems like zsh doesn't send a signal that the terminal name is usually set on, looking into a fix

**Comment by trinaldi** [comment]
By changing the `.zshrc` implies that it is something can be related to `zsh`, check out @amlamarra solution above.
