### ISSUE TITLE
Bottom placement missing on 3.7.0

### ISSUE THREAD

**Issue by pakyrs** [Guake/guake#1858]
Is bottom placement gone? or is it just me, 

I am running Kde and Fedora 34

![2021-06-06_12-52](https://user-images.githubusercontent.com/56080974/120923401-3c27d600-c6c6-11eb-80e4-7ca5fdd95aae.png)

**Comment by Davidy22** [comment]
Bottom placement can be found under Main Window -> Placement -> Bottom align window instead of top align.
