### ISSUE TITLE
Add key bindings for window resizing

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#186]
Add key bindings for window resizing http://guake.org/ticket/162
Reported by:    astratto    Owned by:   somebody
Priority:   Fix available   Milestone:  0.5.0
Component:  guake   Version:  
Keywords:       Cc:  
Description

This is something that would be very very useful for me. I'm used to resizing the window very often.

By the way, it's strongly related to my patches posted here:  http://trac.guake-terminal.org/ticket/10

**Comment by Stibbons** [comment]
Fixed
