### ISSUE TITLE
How to install guake on RHEL 8?

### ISSUE THREAD

**Issue by skn-goodwin** [Guake/guake#1860]

**Comment by Davidy22** [comment]
Guake should be available [via RPM](https://rpmfind.net/linux/rpm2html/search.php?query=guake), and there is also a [guake snap](https://snapcraft.io/install/guake/rhel) if RPM doesn't bring up any results. You can also `pip install guake` if you can install python and pip, and if all else fails you can [install from source](https://guake.readthedocs.io/en/latest/user/installing.html#install-from-source)
