### ISSUE TITLE
Cannot close tab

### ISSUE THREAD

**Issue by draganbjedov** [Guake/guake#1863]
**Describe the bug**

Cannot close tab

**Expected behavior**

Tab is closed

**Actual behavior**

Tab is not closed with exception.
```
Deleting page index 7
found running pid: 73699
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/guake/boxes.py", line 720, in on_close
    self.notebook.delete_page_by_label(self, prompt=prompt_cfg)
  File "/usr/lib/python3/dist-packages/guake/notebook.py", line 320, in delete_page_by_label
    self.delete_page(self.find_tab_index_by_label(label), kill, prompt)
  File "/usr/lib/python3/dist-packages/guake/notebook.py", line 288, in delete_page
    if not PromptQuitDialog(self.guake.window, procs, -1).close_tab():
TypeError: __init__() missing 1 required positional argument: 'notebooks'
```
**To Reproduce**

Open new tab.
Try to close it with context menu - Close

**Note**

I have on start script set to automatically open some tabs.
```
#!/bin/bash

guake -r "work" -e "cd ~/work && reset"
guake -n "/home/dragan/Projects/project1" -r "project1"
guake -n "/home/dragan/" -r "dragan"
guake -n "/home/dragan/Desktop" -r "setup" -e "./setup.sh"
```

-------------------------------------------------------------------------------

Guake Version:		3.7.0

Vte Version:		0.60.3

Vte Runtime Version:	0.60.3

--------------------------------------------------
GTK+ Version:		3.24.20

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: cinnamon

--------------------------------------------------
Display: :1

RGBA visual: True

Composited: True

* Monitor: 0 - AUO DP-0
    * Geometry:		1920 x 1080 at 1920, 120
    * Size:		344 x 193 mm²
    * Primary:		True
    * Refresh rate:	60.03 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - HPN DP-1.2
    * Geometry:		1920 x 1200 at 0, 0
    * Size:		518 x 324 mm²
    * Primary:		False
    * Refresh rate:	59.95 Hz
    * Subpixel layout:	unknown

**OS**

Ubuntu 20.04 with Cinnamon

**Comment by loxK** [comment]
It happens to me on Ubuntu 21.04 when I try to close a tab where I am connected over SSH.

**Comment by Davidy22** [comment]
Fixed in #1885, will close when that patch is merged.

**Comment by draganbjedov** [comment]
Tested on Ubuntu 20.04 by manually applying fix. Works as expected.

**Comment by Davidy22** [comment]
Sweet, thanks for getting back to us.
