### ISSUE TITLE
We need a new release - maintainer?

### ISSUE THREAD

**Issue by jacksongoode** [Guake/guake#1870]
This project is likely the most developed & mature drop down terminals (and popular alternative terminals _generally_) but is quite infrequently updated and has a number of lingering PR's. This isn't to shame anyone but it might be useful to promote another contributor that is willing to share their time in managing these PR's and building new releases.

There are already a ton of features present that are missing from the latest build - with many more available in PR's. This forces most folks to compile the app themselves without a sense whether the build is "release ready"/stable. Since there haven't been many other calls for maintenance I think it ought to be brought up.

What are your thoughts @gsemet?

**Comment by gsemet** [comment]
Hi. Life being life, baby now sucking up almost all free time, I do not have time to fire up my dev environment to maintain guake. I only work with Mac now…
So if there is someone that is willing to take over the code, freshen it a little bit, yes, sure, contact me and we will make sure the project can live on.
« Candidates » can contact me at gaetan [at] xeberon.net. Share your ideas and goals you want to achieve. I still work with Python on a day to day basis, not on Linux, so I also have some hint on what could be done to increase the code quality. But still, time is not strechable…

**Comment by Davidy22** [comment]
well, put in my email, up to the fates now.

**Comment by Davidy22** [comment]
Well, me and @mlouielu were given access today, so this is resolved now probably

**Comment by gsemet** [comment]
@Davidy22 and @mlouielu will from now help on the maintainance of Guake. Welcome aboard and thanks for your help !
