### ISSUE TITLE
Regenerate a key

### ISSUE THREAD

**Issue by Davidy22** [Guake/guake#1887]
Forgot about this till now, but there was a key that has recently been removed from the repository that probably shouldn't have been in plaintext in the repository, and should be regenerated. The key appeared to be attached to a username stibbons, but @stibbons doesn't autocomplete anyone for me so I think this isn't how I get a hold of them, and I might have just pinged someone who has nothing to do with the project. I also took a look at MAINTANERS and none of the names in there sound much like stibbons. Given that the key being in plaintext hasn't gone bad yet during the time that it's been in the repository, it might not be too urgent that we get this sorted out now that you have to dig through old revisions to see it, but it's a little bit of a concern still.

EDIT: I just went on pypi to check for stibbons and had a realisation. Pinging @gsemet since it's them.

**Comment by gsemet** [comment]
Stibbons is me :) I will look on how I can rework ownership of the pypi repo. 

By the way, I think we should recommend using pipx to install guake, it works great and isolate each app’s virtual env.

**Comment by Davidy22** [comment]
From recent changes it looks like we have a new key in github secrets, so closing this.
