### ISSUE TITLE
Background image renders above the search box

### ISSUE THREAD

**Issue by Davidy22** [Guake/guake#1894]
I missed something when checking the background image feature (in #1604), background image renders above the search box, so when you hit CTRL+SHIFT+F, you can't see the search box. Search still works fine, just can't see it.

Pulling in @mlouielu because they'll know most about how to remedy this having written the background image thing themself

**Describe the bug**

Can't see search box with a background image

**Expected behavior**

Can see the search box

**Actual behavior**

Can't see the box

**To Reproduce**

Set a background image and hit CTRL+SHIFT+F. Must be on git latest to encounter this bug.

-------------------------------------------------------------------------------

Please run `$ guake --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting. And make sure you run the command **OUTSIDE** the Guake.

<details><summary>$ guake --support</summary>

Guake Version:		3.7.1.dev95

Vte Version:		0.60.3

Vte Runtime Version:	0.60.3

--------------------------------------------------
GTK+ Version:		3.24.20

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: cinnamon

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - CMN eDP-1-1
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		344 x 194 mm²
    * Primary:		True
    * Refresh rate:	60.05 Hz
    * Subpixel layout:	unknown

**Comment by mlouielu** [comment]
Do you test it with #1604?

**Comment by Davidy22** [comment]
Yeah, this only occurs with the background image enabled. I did actually try some different arrangements of draw instructions on my own really quickly, I got as far as actually fixing this bug, but breaking the scrollbar render.

**Comment by mlouielu** [comment]
Close as fixed in #1907
