### ISSUE TITLE
Merging translation updates from Weblate

### ISSUE THREAD

**Issue by ersen0** [Guake/guake#1901]
The last translation update is from 2 years ago. There are new/updated translations and this alert on Weblate:

    The VCS repository has many changes compared to the upstream. Please merge the changes manually or set up push to automate this.

**Comment by Davidy22** [comment]
Paging @gsemet because I think they're the one with access to this.

**Comment by gsemet** [comment]
https://hosted.weblate.org/projects/guake/#repository has been merged on head

**Comment by Davidy22** [comment]
The build passes, but would have expected that since I don't think we have checks for po files. There's still alert symbols but clicking through says two hours ago so I think the site just needs a moment to update. Since the merge is done, closing.
