### ISSUE TITLE
show guake above panels

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#194]
show guake above panels http://guake.org/ticket/125
Reported by:    michote     Owned by:   somebody
Priority:   minor   Milestone:  
Component:  guake   Version:  
Keywords:       Cc:  
Description

I'm using some transparent panels, to have borders around fullscreen windows, to use mouse Desktopchanging there. Would it be possible to add a "show above panels" option to guake, like it does in fullscreen mode? thanks

**Comment by Stibbons** [comment]
If you want this feature, please vote on [FeatHub](https://feathub.com/Guake/guake)
