### ISSUE TITLE
Scrollable tab bar 

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#195]
Scrollable tab bar http://guake.org/ticket/65
Reported by:    rooty   Owned by:   somebody
Priority:   major   Milestone:  0.5.0
Component:  guake   Version:    0.4.4
Keywords:       Cc:     gualo82@…, thomas.bouffon@…
Description

Tab bar should become scrollable when tabs exceed the screen width. To reproduce, try creating lot of tabs.

**Comment by ivoshm** [comment]
+1

**Comment by r-barnes** [comment]
Guake 0.8.4 seems to have a scrollbar in it? Could we close this issue?

Unfortunately, that scrollbar also overlaps the tabs, so I've just been looking for a way to remove it from my local copy.

**Comment by Hijis** [comment]
Hi! Seems this is right place for my request.
Usualy I have too much tabs so scrollbar appears, and switch between them using Ctrl+PgUp|PgDown
But when I switch to tab beyond visible space - happens nothing and I loose tab out of my sight.

It would be nice if scrolls automaticly to current active tab. 

Thanks a lot!

![guake_tabs](https://user-images.githubusercontent.com/17022100/29557442-c71e9498-8731-11e7-9d24-1574431e64dd.png)

**Comment by aichingm** [comment]
This issue is fixed via #1382
