### ISSUE TITLE
More appearant lost of focus

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#197]
More appearant lost of focus http://guake.org/ticket/112
Reported by:    gw0     Owned by:   somebody
Priority:   minor   Milestone:  0.5.0
Component:  guake   Version:    0.3.1
Keywords:       Cc:  
Description

I often find myself typing shell commands in varios programs, because I think that guake has focus. Therefore it would be great to have a more distiguishable different appearance when the focus is lost.

I think that a small change of some colors would do the trick. Or maybe just a gray rectangle around the border in shells background... Anything a little bigger than the current change of the blinking cursor. (Hm, maybe the change of cursors color to red.)

**Comment by Stibbons** [comment]
If you want this feature, please vote on [FeatHub](https://feathub.com/Guake/guake)
