### ISSUE TITLE
Transparent Tab Bar

### ISSUE THREAD

**Issue by bryangwilliam** [Guake/guake#1970]
**Describe the bug**
When I open multiple tabs the tab bar is completely transparent which makes it very difficult to read if there is anything behind it.

**Expected behavior**
I expect the tab bar to be opaque. This was the behavior the last time I built from source a few months ago, but when I pull the most recent changes and build I am seeing this undesirable behavior.

**Actual behavior**
The tab bar is transparent.
![image](https://user-images.githubusercontent.com/3506911/141013529-e8062f38-fac0-499c-9272-5eaf86b03901.png)

**To Reproduce**
Build the latest from master and try to open multiple tabs.

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:		3.7.1.dev38

Vte Version:		0.60.3

Vte Runtime Version:	0.60.3

--------------------------------------------------
GTK+ Version:		3.24.20

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: ubuntu

--------------------------------------------------
Display: :1

RGBA visual: True

Composited: True

* Monitor: 0 - SHP eDP-1-1
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		344 x 194 mm²
    * Primary:		True
    * Refresh rate:	59.999 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - GSM DP-1-1
    * Geometry:		1920 x 1080 at 1920, 0
    * Size:		480 x 270 mm²
    * Primary:		False
    * Refresh rate:	60.0 Hz
    * Subpixel layout:	unknown

**Comment by Davidy22** [comment]
Was pinged in the yaru bug tracker about this as well, are you using yaru or a yaru based theme? If not, what theme are you using? And if you go to preferences, uncheck "Use system default theme" and pick a theme from Guake's options does the tab bar render correctly for you?

**Comment by lijinglin3** [comment]
+1

```bash
❯ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Jammy Jellyfish (development branch)
Release:	22.04
Codename:	jammy
```

```bash
❯ guake --support
<details><summary>$ guake --support</summary>

Guake Version:		3.8.1

Vte Version:		0.66.1

Vte Runtime Version:	0.66.1

--------------------------------------------------
GTK+ Version:		3.24.30

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: ubuntu-xorg

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - DEL DP-1
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		509 x 286 mm²
    * Primary:		True
    * Refresh rate:	60.0 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - DEL DP-2
    * Geometry:		1920 x 1080 at 1920, 0
    * Size:		509 x 286 mm²
    * Primary:		False
    * Refresh rate:	60.0 Hz
    * Subpixel layout:	unknown

```

**Comment by lijinglin3** [comment]
> +1
> 
> ```shell
> ❯ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu Jammy Jellyfish (development branch)
> Release:	22.04
> Codename:	jammy
> ```
> 
> ```shell
> ❯ guake --support
> <details><summary>$ guake --support</summary>
> 
> Guake Version:		3.8.1
> 
> Vte Version:		0.66.1
> 
> Vte Runtime Version:	0.66.1
> 
> --------------------------------------------------
> GTK+ Version:		3.24.30
> 
> GDK Backend:		<GdkX11.X11Display
> 
> --------------------------------------------------
> Desktop Session: ubuntu-xorg
> 
> --------------------------------------------------
> Display: :0
> 
> RGBA visual: True
> 
> Composited: True
> 
> * Monitor: 0 - DEL DP-1
>     * Geometry:		1920 x 1080 at 0, 0
>     * Size:		509 x 286 mm²
>     * Primary:		True
>     * Refresh rate:	60.0 Hz
>     * Subpixel layout:	unknown
> * Monitor: 1 - DEL DP-2
>     * Geometry:		1920 x 1080 at 1920, 0
>     * Size:		509 x 286 mm²
>     * Primary:		False
>     * Refresh rate:	60.0 Hz
>     * Subpixel layout:	unknown
> ```

Only appears when using `yaru-dark` theme

**Comment by bryangwilliam** [comment]
Nice catch. Can confirm the problem only happens with the Yaru theme (both dark and light).

**Comment by lijinglin3** [comment]
> Nice catch. Can confirm the problem only happens with the Yaru theme (both dark and light).

It's OK to use `yaru-light`

**Comment by Davidy22** [comment]
I've left some comments in the yaru bug tracker for this issue, will see if the fix is going to come from us or them.

**Comment by Davidy22** [comment]
[Yaru is fixing it,](https://github.com/ubuntu/yaru/issues/2149#issuecomment-966224137) so closing this issue
