### ISSUE TITLE
Guake crashes gnome on wayland

### ISSUE THREAD

**Issue by pbabilas** [Guake/guake#1973]
Hi,
I'm tying to work with guake on Ubuntu 21.10 on Wayland. But when I'm trying with interact with guake somehow (like show about, or any actions from context menu, or shourtcut toggle run) it crashes the whole gnome.

Log below, when I chose Quit from context menu:
```
lis 13 19:05:48 bcode-XPS gnome-calendar[46709]: Error reading events from display: Przerwany potok
lis 13 19:05:48 bcode-XPS nautilus[48087]: Error reading events from display: Przerwany potok
lis 13 19:05:48 bcode-XPS gnome-shell[43426]: == Stack trace for context 0x562f059a31d0 ==
lis 13 19:05:48 bcode-XPS gnome-shell[43426]: GNOME Shell crashed with signal 6
lis 13 19:05:48 bcode-XPS gnome-shell[43426]: Bail out! mutter:ERROR:../src/core/window.c:1591:meta_window_unmanage: assertion failed: (g_list_find (workspace->windows, window) == NULL)
lis 13 19:05:48 bcode-XPS gnome-shell[43426]: mutter:ERROR:../src/core/window.c:1591:meta_window_unmanage: assertion failed: (g_list_find (workspace->windows, window) == NULL)
lis 13 19:05:48 bcode-XPS gnome-shell[43426]: **
lis 13 19:05:48 bcode-XPS systemd[2276]: vte-spawn-da332410-5d0e-4ad4-9878-1569c280e395.scope: Deactivated successfully.
lis 13 19:05:48 bcode-XPS systemd[2276]: app-gnome-guake-43685.scope: Deactivated successfully.
lis 13 19:05:48 bcode-XPS guake.desktop[43685]: Quitting Guake
```
ON X11 it works great.
Guake version 3.8.1-1

Guake support:
`(☸ |dev:gitlab-ce) b-code@bcode-XPS  ~  guake --support
<details><summary>$ guake --support</summary>

Guake Version:		3.8.1

Vte Version:		0.64.2

Vte Runtime Version:	0.64.2

--------------------------------------------------
GTK+ Version:		3.24.30

GDK Backend:		<__gi__.GdkWaylandDisplay

--------------------------------------------------
Desktop Session: ubuntu-wayland

--------------------------------------------------
Display: wayland-0

RGBA visual: True

Composited: True

* Monitor: 0 - SHP 0x14d0
    * Geometry:		3840 x 2400 % 2 at 0, 0
    * Size:		340 x 210 mm²
    * Primary:		False
    * Refresh rate:	59.993 Hz
    * Subpixel layout:	unknown
`

**Comment by pbabilas** [comment]
When I disabled X11 forced it works fine but window is always full size :(

**Comment by mlouielu** [comment]
Can you update the description with `guake --support`?

How do you disabled force x11, do you run Guake from source code?

**Comment by pbabilas** [comment]
HI, I deleted one line from main.py. 
Installed from apt

**Comment by mlouielu** [comment]
> HI, I deleted one line from main.py. Installed from apt

I would like to know the support information in description is done by the modified Guake, am I correct?

If that is true, can you also provide an apt version guake support?

Because your dmesg shows that it is error by mutter, the Gnome WM.

**Comment by pbabilas** [comment]
okej below is support without my change:

`(☸ |dev:gitlab-ce) b-code@bcode-XPS  ~  guake --support
<details><summary>$ guake --support</summary>

Guake Version:		3.8.1

Vte Version:		0.64.2

Vte Runtime Version:	0.64.2

--------------------------------------------------
GTK+ Version:		3.24.30

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: ubuntu-wayland

--------------------------------------------------
Display: :1

RGBA visual: True

Composited: True

* Monitor: 0 - XWAYLAND0
    * Geometry:		1920 x 1200 % 2 at 0, 0
    * Size:		340 x 210 mm²
    * Primary:		True
    * Refresh rate:	59.988 Hz
    * Subpixel layout:	unknown`

And right after change it my gnome crashed again becouse my guake toggle shourtcut was used :D

**Comment by Davidy22** [comment]
I'm looking at the error log:

```
lis 13 19:05:48 bcode-XPS gnome-shell[43426]: Bail out! mutter:ERROR:../src/core/window.c:1591:meta_window_unmanage: assertion failed: (g_list_find (workspace->windows, window) == NULL)
lis 13 19:05:48 bcode-XPS gnome-shell[43426]: mutter:ERROR:../src/core/window.c:1591:meta_window_unmanage: assertion failed: (g_list_find (workspace->windows, window) == NULL)
```

Seems like there's something happening with windows/workspaces? Quick search found [this similar issue](https://gitlab.gnome.org/GNOME/mutter/-/issues/4) someone had, might have some help on how to figure this out.

**Comment by pbabilas** [comment]
Last update fixed thus problem, but I'd love to see guake on native wayland, because fractal scaling makes guake blurry as hell.. :(

**Comment by Davidy22** [comment]
Oh, if the x11 force fixed this then closing.

Next update will add an option to optionally enable wayland #1975, and I'll soon have a machine with wayland on it so I can finally get to see for myself the wayland guake issues.
