### ISSUE TITLE
tabs are missing

### ISSUE THREAD

**Issue by mikk150** [Guake/guake#1978]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Guake.

For how to run the latest Guake in your computer, please refer to [Install from source](https://guake.readthedocs.io/en/latest/user/installing.html#install-from-source).

**Describe the bug**

Lately(presumably from 3.8.1) tab bar started dissapearing

**Expected behavior**

I should see tab(s) under current terminal window

**Actual behavior**

No tab(s) under current terminal window

**To Reproduce**

1. press hotkey to open guake
2. observe tab(s) not below current terminal window

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:		3.8.1

Vte Version:		0.66.1

Vte Runtime Version:	0.66.1

--------------------------------------------------
GTK+ Version:		3.24.30

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: gnome

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - XWAYLAND3
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		520 x 290 mm²
    * Primary:		True
    * Refresh rate:	143.722 Hz
    * Subpixel layout:	unknown
![image](https://user-images.githubusercontent.com/4953629/142763365-dc78a0a1-dedb-4978-909b-a4688e26e443.png)

**Comment by mikk150** [comment]
3.7.0 is fine, 3.8.0 is also broken

**Comment by zeusintuivo** [comment]
This isssue is not about "tabs missing" is about the issue with guake erasing guake.session file
So basically, guake, "forgets tabs" or "renames its contents"  
I have a fix that too., should be merged soon.

**Comment by mikk150** [comment]
if you say so. But, me as a developer, I do not see ever writing so that if session is missing, let's not even give ability to switch tabs or create ones

**Comment by zeusintuivo** [comment]
> if you say so. But, me as a developer, I do not see ever writing so that if session is missing, let's not even give ability to switch tabs or create ones

Is not "sessions is missing" issue is file is broken issue. It just happens that the name of the file that guake writes is called guake.session , this happens writing happens constantly, and sometimes, this read+write operation fails. This file, has a description of the tabs you open and close, so, when the file, gets damaged, so do your tabs. Not the sessions. 
I have fixed this in my local host, and I will push a fix soon.

**Comment by mlouielu** [comment]
Hi @mikk150 , could you help check if `hide tab bar if only one tab` is enable or not?

Also, could you try to use another theme in Guake, so we can know if it is about theme css.

**Comment by mikk150** [comment]
> Hi @mikk150 , could you help check if `hide tab bar if only one tab` is enable or not?
> 
> Also, could you try to use another theme in Guake, so we can know if it is about theme css.

Ah, I get it. you introduced new option that is enabled by default..
It should not be enabled by default then..

**Comment by mlouielu** [comment]
> > Hi @mikk150 , could you help check if `hide tab bar if only one tab` is enable or not?
> > Also, could you try to use another theme in Guake, so we can know if it is about theme css.
> 
> Ah, I get it. you introduced new option that is enabled by default.. It should not be enabled by default then..
> 
> Yes, disabling that works

I believe it is an old option (I can't access to my laptop to pin down), not sure what has been touched, probably the gscheme.

**Comment by mikk150** [comment]
> > > Hi @mikk150 , could you help check if `hide tab bar if only one tab` is enable or not?
> > > Also, could you try to use another theme in Guake, so we can know if it is about theme css.
> > 
> > 
> > Ah, I get it. you introduced new option that is enabled by default.. It should not be enabled by default then..
> > Yes, disabling that works
> 
> I believe it is an old option (I can't access to my laptop to pin down), not sure what has been touched, probably the gscheme.

3.7.0 does not have it, so it is almost 2 months old... It is new...

**Comment by mlouielu** [comment]
You are right on this, I remembered it as another option that hides tab bar (`hide if maximize`).

@Davidy22 what is your thought on this, I think we can make it default disable at next version

**Comment by Davidy22** [comment]
The new hide tab bar toggle is new in 3.8. I have noticed some amount of reports of confusion regarding it, I'm fine with downgrading the setting to disabled by default.
