### ISSUE TITLE
double clicking on tab bar does not do new tab any more

### ISSUE THREAD

**Issue by mikk150** [Guake/guake#1980]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Guake.

For how to run the latest Guake in your computer, please refer to [Install from source](https://guake.readthedocs.io/en/latest/user/installing.html#install-from-source).

**Describe the bug**

up until 3.7.0 double-clicking on tab bar made new tabs, which (to me) was faster to use. since 3.8.0 it does not do that any more

**Expected behavior**

double-clicking on tab bar makes new tabs

**Actual behavior**

double-clicking on tab bar makes absolutely nothing

**To Reproduce**

1. double-click on tab bar
2. observe tab not being created

-------------------------------------------------------------------------------

Please run `$ guake --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting. And make sure you run the command **OUTSIDE** the Guake.

**Comment by mlouielu** [comment]
Introduce in fb8a6ff974758c724db97d0dc22f8e3b3e0e95e9, see #1697 for discussion.

**Comment by mlouielu** [comment]
It is possible to put an option for this.

**Comment by Davidy22** [comment]
Got something else going on right now, but I can look at a PR adding an option or add it later myself.

**Comment by UltimateByte** [comment]
I can confirm on Fedora 35, double clicking a new tab.
On Arch, it doesn't.
Default double click to open a new tab is far better. An option, ticked on by default would be even better.

**Comment by Davidy22** [comment]
Actually, I just went and fixed the original issue that led to the removal of the feature initially so reinstating this feature without an option.

**Comment by UltimateByte** [comment]
Thank you so much @Davidy22 !
