### ISSUE TITLE
ERROR while updating on Ubuntu 20.04

### ISSUE THREAD

**Issue by amishsaxena** [Guake/guake#1984]
**Describe the bug**

Tried to update my Guake using the `sudo apt update` followed by sudo apt upgrade` . It is not able to find the update in the PPA.
I have been using it since past 2 years, and have never faced such an issue.

**Expected behavior**

Update normally as expected.

**Actual behavior**

Got the following error: 
```
E: Failed to fetch http://ppa.launchpad.net/linuxuprising/guake/ubuntu/pool/main/g/guake/guake_3.8.1-1~ppa~focal0_all.deb  404  Not Found [IP: 91.189.95.85 80]
```

**To Reproduce**

To reproduce the behavior:
Run the following in the terminal : 
`sudo apt-get update`
`sudo apt upgrade`

**Comment by Davidy22** [comment]
[The launchpad page looks fine still](https://launchpad.net/~linuxuprising/+archive/ubuntu/guake), what version of ubuntu are you on? Are you still experiencing the issues? Might have been a temporary outage

**Comment by Davidy22** [comment]
Reopen if issue resurfaces
