### ISSUE TITLE
Shortcuts broken on language change

### ISSUE THREAD

**Issue by RuRo** [Guake/guake#1986]
I've just updated from 3.7.0 to 3.8.1 and the update partially broke shortcuts for me.

**Describe the bug**

A bit of context first: I use 2 languages - English and Russian. The keyboard layout is a mostly standard en-US layout, but the letter keys also have Russian letters printed on them. You can switch between the Russian and English "layouts" on the fly. Here's an image:

![image](https://user-images.githubusercontent.com/3747318/144667677-93bccff9-f641-4b6e-b5d6-0a141ff90518.png)

The tricky part is that shortcuts should ignore, which language is selected and should instead respond to the physical keys that are being pressed. For example, if I configure `Shift+Ctrl+Q` to the `New tab` action, then pressing the `Shift`, `Control` and `Q` keys together should open a new tab **even if I have the Russian language enabled**. Note, that with a Russian layout enabled, pressing the physical `Q` key would normally "type" the letter `Й`.

To be clear, this is not a feature request. The behaviour I am describing is the "default" and 99.9% programs with shortcuts work that way. Guake version 3.7.0 handles the shortcuts correctly, so this is a regression.

**Expected behavior**

Keyboard shortcuts should ignore, which keyboard language is currently selected.

**Actual behavior**

The shortcuts are language specific.

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:		3.8.1

Vte Version:		0.66.1

Vte Runtime Version:	0.66.1

--------------------------------------------------
GTK+ Version:		3.24.30

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: plasma

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - CMN eDP-1
    * Geometry:		1920 x 1080 at 1920, 0
    * Size:		382 x 215 mm²
    * Primary:		True
    * Refresh rate:	60.002 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - ACI HDMI-2
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		528 x 310 mm²
    * Primary:		False
    * Refresh rate:	60.0 Hz
    * Subpixel layout:	unknown

</details>

**Comment by Davidy22** [comment]
Oh, we have #1953 merged in master slated for 3.8.2 already, I wanted to fix a deployment to pypi issue before signing off the release but it's taken a while. I'll take another run at it again, maybe I'll just skip pypi again for 3.8.2 if I still can't get the pypi build to work.

**Comment by RuRo** [comment]
I updated to 3.8.5 and so far the issue seems to be fixed, so I am closing this for now. Thanks!
