### ISSUE TITLE
Pip package and Fedora are out of date 

### ISSUE THREAD

**Issue by the-mentor** [Guake/guake#1987]
I looked at the latest pip package here https://pypi.org/project/guake/#description and it is out of date (v3.7.0)

Also the Fedora 35 package is out of date (3.7.0-9.fc35).

I'm not sure if you manage the Fedora package but I guess you do manage the pip one.

Thank you for this amazing application!

-DM

**Comment by Davidy22** [comment]
Fixing the pip package is something I'm coming back to periodically unsuccessfully, the fedora package is out of our direct control.  The prerequisite PR to getting pip updated is at #1956, and I have a branch with some wasted hours of trial and error linked in the comments there from my futile attempts at fixing it.

**Comment by Davidy22** [comment]
Given the auxiliary packages that need to be installed alongside a pip install anyway and how long I've struggled with this infernal pip package, I've half a mind to just abandon the pip install and work with distros more on getting newer versions built.

**Comment by the-mentor** [comment]
Maybe it also makes sense to publish deb/rpm etc instead of pip to provide a way for end users to have a way to install the latest version

**Comment by Davidy22** [comment]
Oh that'll be a new foray into packaging for me, also might help the fedora folks since from their bug tracker it looks like building is holding them up from updating past 3.7 somehow

**Comment by Davidy22** [comment]
Pip upload is working now, and fedora repo is out of our direct control

**Comment by Pysis868** [comment]
Where is the Fedora control then?

**Comment by Davidy22** [comment]
You will have to contact the package maintainer for guake on the fedora end, or take up the mantle yourself if you want to push for more up to date versions of guake in fedora.

**Comment by paseaf** [comment]
> Where is the Fedora control then?

You can find the fedora RPM repo for Guake at https://src.fedoraproject.org/rpms/guake

Someone just submitted a PR to update Guake to 3.9.0 :crossed_fingers:
