### ISSUE TITLE
TypeError: Couldn't find foreign struct converter for 'cairo.Context'

### ISSUE THREAD

**Issue by mraxilus** [Guake/guake#1993]
**Describe the bug**

On PopOS 21.10, upon starting Guake, it constantly throws out this error message.
Eventually, it gets to a point where it produces the following error.

```sh
(guake:19084): Gtk-WARNING **: 12:28:05.931: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Pop/16x16/status/image-missing.png: Error opening file /usr/share/icons/Pop/16x16/status/image-missing.png: Too many open files (g-io-error-quark, 31)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Pop/16x16/status/image-missing.png: Error opening file /usr/share/icons/Pop/16x16/status/image-missing.png: Too many open files (g-io-error-quark, 31)
Aborted (core dumped)
```

**Expected behavior**
No crashing, no repeated error messages.

**Actual behavior**
Crash; makes it unusable.

**To Reproduce**

Run Guake, open and clone the window a few times.
Occasionally, I have to also have the preferences window open, at the same time.

**To Fix**
I fixed it as per https://github.com/rbgirshick/py-faster-rcnn/issues/221#issuecomment-539869886 by installing `python3-gi-cairo`.
Perhaps, cairo should be added as a dependency for guake in apt?
I installed Guake using `sudo apt-get install guake`.

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:		3.6.3

Vte Version:		0.64.2

Vte Runtime Version:	0.64.2

--------------------------------------------------
GTK+ Version:		3.24.30

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: pop

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - AOC DP-2
    * Geometry:		2560 x 1440 at 1440, 472
    * Size:		597 x 336 mm²
    * Primary:		True
    * Refresh rate:	143.91 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - AOC DP-0
    * Geometry:		1440 x 2560 at 0, 0
    * Size:		597 x 336 mm²
    * Primary:		False
    * Refresh rate:	143.91 Hz
    * Subpixel layout:	unknown

**Comment by Davidy22** [comment]
Seems like a dependency of a dependency? Not sure what's happening in pop os's dependency resolution this time for this to be happening but can probably add it since it seems like we need it and can't rely on the distros to always get the dependencies down the chain installed

**Comment by eli-schwartz** [comment]
This error doesn't even come from guake in the first place.

**Comment by Davidy22** [comment]
Closing because this should be dependency resolution issue for pop os.
