### ISSUE TITLE
Lack of desktop integration? (Ubuntu 20.04)

### ISSUE THREAD

**Issue by myocytebd** [Guake/guake#1994]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Guake.

For how to run the latest Guake in your computer, please refer to [Install from source](https://guake.readthedocs.io/en/latest/user/installing.html#install-from-source).

**Describe the bug**
There seems to be no integration with window manager at Ubuntu 20.04. (For both 3.6.3-2 ubuntu and github 3.8.2.dev20)

**Expected behavior**
- guake window appear in alt-tab list and left menu bar.
- guake.desktop can be used for launch.

**Actual behavior**
- guake window does not appear in alt-tab list or left menu bar.
- If guake.desktop is clicked for launch (process not running), guake appears to be stuck in loading forever. Mouse cursor is shown in loading (rotating circle). Window status is shown as in loading (rotating circle).
- If guake.desktop is clicked for launch (process running), it needs click two times to bring guake window to front.
- If guake.desktop is clicked for launch (process not running), it takes ~15 sec and then click two times.

**To Reproduce**
1. Run guake from terminal, guake does not appear in alt-tab list or left menu bar.
2. Launch from guake from guake.desktop, guake window will not pop.
3. Wait 20 sec, and click guake.desktop two times, guake window pops. guake does not appear in alt-tab list or left menu bar.
-------------------------------------------------------------------------------

Please run `$ guake --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting. And make sure you run the command **OUTSIDE** the Guake.

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:		3.8.2.dev20

Vte Version:		0.60.3

Vte Runtime Version:	0.60.3

--------------------------------------------------
GTK+ Version:		3.24.20

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: ubuntu

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - ENC HDMI-A-1
    * Geometry:		1920 x 1200 at 0, 0
    * Size:		519 x 324 mm²
    * Primary:		True
    * Refresh rate:	59.95 Hz
    * Subpixel layout:	unknown

**Comment by Davidy22** [comment]
Guake not appearing in alt-tab and menu bar is expected behavior. Guake on startup opens guake in the background, and when "started" again will pop the existing Guake session open. If a terminal that occupies and behaves like a regular window is desired, there are good alternatives available including the one provided with ubuntu.
