### ISSUE TITLE
Guake 3.8.1 bottom bar is transparent on ubuntu 20.04.3

### ISSUE THREAD

**Issue by nibexo** [Guake/guake#1997]
When I updated Guake from 3.6.3 to 3.8.1 on my Ubuntu 20.04.3 I found that bottom bar become transparent, 
I'm using Tango theme, but when checked another they also have this issue. 

![bottonBar](https://user-images.githubusercontent.com/10156955/147351294-31842a77-343c-4bc2-bc69-255b2ea548b2.jpg)

-------------------------------------------------------------------------------
Guake Version:		3.8.1

Vte Version:		0.60.3

Vte Runtime Version:	0.60.3

--------------------------------------------------
GTK+ Version:		3.24.20

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: ubuntu

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - HPN HDMI-2
    * Geometry:		2560 x 1440 at 0, 0
    * Size:		597 x 336 mm²
    * Primary:		True
    * Refresh rate:	59.95 Hz
    * Subpixel layout:	unknown

**Comment by Davidy22** [comment]
Guake properly auto detects the system default theme in 3.8 onwards, which can sometimes define the tab bar to be transparent. This is a known issue with the Yaru theme, which should be getting patched, but may be an issue with other themes too. If you uncheck "Use system default theme," and pick ssomething out in guake preferences, is this issue resolved?

**Comment by nibexo** [comment]
Yes, after uncheck issue resolved.
Thinks for your help

**Comment by Davidy22** [comment]
Closing since known issue with themes
