### ISSUE TITLE
[SOLVED] Error in building:  Can't copy 'po/*.mo' : doesn't exist or not regular file 

### ISSUE THREAD

**Issue by Lowrida** [Guake/guake#2001]
** For how to run the latest Guake in your computer, please refer to [Install from source]
** (https://guake.readthedocs.io/en/latest/user/installing.html#install-from-source).<
I did..
I ran script bootstrap to install all neccesaries.
Ran 'make', then 'sudo make install' and got the following error:

`
error: can't copy 'po/*.mo': doesn't exist or not a regular file
make: *** [Makefile:93: install-guake] Fout 1
`

I just got me a new system with Mint 20 (previous was 19) and i wanted the latest quake back. But the installation is not going smooth... i have no clue how to fix this. Appreciating some help.

Thanks

**Comment by Davidy22** [comment]
Is there more information above that? What's your version of python and setuptools?

**Comment by Lowrida** [comment]
Yes ofcourse! This is from start until the error message:
`install -dm755                                       "//usr/local/share/applications"
install -Dm644 "/home/admin/.source/guake/guake/data/guake.desktop"       "//usr/local/share/applications/"
install -Dm644 "/home/admin/.source/guake/guake/data/guake-prefs.desktop" "//usr/local/share/applications/"
install -dm755                                       "//usr/local/share/metainfo/"
install -Dm644 "/home/admin/.source/guake/guake/data/guake.desktop.metainfo.xml"  "//usr/local/share/metainfo/"
install -dm755                                 "//usr/local/share/guake/pixmaps"
install -Dm644 "/home/admin/.source/guake/guake/data"/pixmaps/*.png "//usr/local/share/guake/pixmaps/"
install -Dm644 "/home/admin/.source/guake/guake/data"/pixmaps/*.svg "//usr/local/share/guake/pixmaps/"
install -dm755                                     "//usr/local/share/pixmaps"
install -Dm644 "/home/admin/.source/guake/guake/data/pixmaps/guake.png" "//usr/local/share/pixmaps/"
install -dm755                                           "//usr/local/share/guake"
install -Dm644 "/home/admin/.source/guake/guake/data/autostart-guake.desktop" "//usr/local/share/guake/"
install -dm755                           "//usr/local/share/guake"
install -Dm644 "/home/admin/.source/guake/guake/data"/*.glade "//usr/local/share/guake/"
install -dm755                                         "//usr/local/share/glib-2.0/schemas"
install -Dm644 "/home/admin/.source/guake/guake/data/org.guake.gschema.xml" "//usr/local/share/glib-2.0/schemas/"
if [ 1 = 1 ]; then glib-compile-schemas //usr/local/share/glib-2.0/schemas; fi
for f in $(find po -iname "*.mo"); do \
	l="${f%%.*}"; \
	lb=$(basename $l); \
	install -Dm644 "$f" "//usr/local/share/locale/$lb/LC_MESSAGES/guake.mo"; \
done;
# you probably want to execute this target with sudo:
# sudo make install
#############################################################

Installing from source on your system is not recommended.
Please prefer you application package manager (apt, yum, ...)

#############################################################
running install
running build
running build_py
copying guake/paths.py -> build/lib/guake
copying guake/_version.py -> build/lib/guake
running install_lib
copying build/lib/guake/paths.py -> /usr/local/lib/python3.8/dist-packages/guake
copying build/lib/guake/_version.py -> /usr/local/lib/python3.8/dist-packages/guake
byte-compiling /usr/local/lib/python3.8/dist-packages/guake/paths.py to paths.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/guake/_version.py to _version.cpython-38.pyc
writing byte-compilation script '/tmp/tmppmbicele.py'
/usr/bin/python3 /tmp/tmppmbicele.py
removing /tmp/tmppmbicele.py
running install_data
`
Python version is 3.8.2
Setuptools version is 45.2.0-1  (i believe, see image)

![Schermafdruk van 2022-01-11 18-03-59](https://user-images.githubusercontent.com/53632533/148988363-77a83dbf-96b1-43ba-9db7-28cb41c3564b.png)

**Comment by Lowrida** [comment]
For some reason the code tags don't work properly...

**Comment by Davidy22** [comment]
Some of the latest commits merged transfer Guake to a new system for version number handling, setuptools_scm. If that's not installed or not working, Guake version won't come out right either. You might need to update setuptools and install setuptools_scm if it somehow wasn't installed already

**Comment by Lowrida** [comment]
As yo can see on the screenshot, it is installed. Or do i need another version? Or the one with "-git" at the end? I'm sorry if that are dum questions, but i have no experience with setuptools or scm or any of that..

**Comment by Lowrida** [comment]
Upgraded to setuptools 60.x and same error! I don't get it, what am i doing wrong here??

**Comment by Lowrida** [comment]
What the heck..?  I just wanted to check which version i was on and it seems the installation did succeeded after all!?

`
Guake Terminal: 3.8.2.dev27+g6dc23f3
VTE: 0.60.3
VTE runtime: 0.60.3
Gtk: 3.24.20
`

**Comment by Davidy22** [comment]
So it's just newer version of setuptools needed, nice to know. I'll close since this is marked as solved, I presume you're able to run as well if you can see the version.

**Comment by Davidy22** [comment]
Actually, I think I know what's going on, making a PR

**Comment by Lowrida** [comment]
To be honest i don't know for sure. Because after the first time the error showed up, i did not check if the new version of guake already worked. I posted the error here and tried a few things, then your solutions.. and late last night i wanted to check what older version i was on when i discovered that i was already on the newer version!
