### ISSUE TITLE
As root user, can't restore from config.

### ISSUE THREAD

**Issue by Lowrida** [Guake/guake#2003]
**Describe the bug**
`
root@p3300lx:/home/admin# guake --restore-preferences=/home/admin/.guake/config-root
error: De verbinding is gesloten
`

(dutch for connection is closed)

Login as root and try to restore from config

**Expected behavior**
Guake restoring from saved config

**Comment by Lowrida** [comment]
Never mind, i just found out that you can't use different background images per terminal..

**Comment by Davidy22** [comment]
So was this issue about trying to do something as root to set up different background images per terminal tab? If that's the actual issue then I'll close this since per-terminal settings are already a separate issue

**Comment by Lowrida** [comment]
Yes that was the plan. You can close it, i will search for the open issue.
