### ISSUE TITLE
font-width changed when splitting window

### ISSUE THREAD

**Issue by gemini4545** [Guake/guake#2021]
**Describe the bug**

OS：manjaro 21.2.2 Qonos (virtual machine)
Kernel:  x86_64 Linux 5.10.93-1
DE: KDE 5.90.0 / Plasma 5.23.5
Guake: 3.8.1

Everything is normal when just start up the guake.
After splitting the window, the new window is still normal while the fonts in the old window changed, the fonts and width became wide , that looks like the full-width characator. As long as new window split, the old window's content changed. 

before splitting:
![before](https://github.com/gemini4545/img_links/blob/main/before.png?raw=true)

after spliting (left and right):
![after](https://github.com/gemini4545/img_links/blob/main/afer.png?raw=true)

**Expected behavior**

Tried the same guake configuration on ununtu with KDE and Gnome, and KED on Kali Virtaul machine,  nothing abnormal happend when splitting the window.

**Actual behavior**

The font and font's width of the content on old window changed to larger space when splitting on Manjara KDE (virtual machine)

**To Reproduce**
As above

-------------------------------------------------------------------------------

Please run `$ guake --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting. And make sure you run the command **OUTSIDE** the Guake.

<details><summary>$ guake --support</summary>

Guake Version:          3.8.1

Vte Version:            0.66.2

Vte Runtime Version:    0.66.2

--------------------------------------------------
GTK+ Version:           3.24.31

GDK Backend:            <GdkX11.X11Display

--------------------------------------------------
Desktop Session: plasma

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - Virtual1
    * Geometry:         1644 x 906 at 0, 0
    * Size:             435 x 240 mm²
    * Primary:          True
    * Refresh rate:     59.997 Hz
    * Subpixel layout:  horizontal-rgb

**Comment by Davidy22** [comment]
Related to #1747, possibly cause by an interaction between #1747 and some font setting in manjaro

**Comment by gemini4545** [comment]
> Related to #1747, possibly caused by an interaction between #1747 and some font setting in manjaro.
> 
> As an aside, the image links don't seem to work for me. Are they private or something?

No private, just the screenshot before and after spliting to demonstrate the changes, the content is just the `screenfetch` command.

**Comment by gemini4545** [comment]
I've re-upload the image-link for comparision the effect of splitting

**Comment by Davidy22** [comment]
What are your font settings in the appearance tab in Guake preferences?

**Comment by gemini4545** [comment]
> What are your font settings in the appearance tab in Guake preferences?

For now, I'm using the default setting, "use system-wide fonts", then the problems occurs when splitting. 

Additionally, if try to use other font manually, like monospace, then the splitting seems ok.
But no other fonts worked out. So I guess it can't not recognize the system fonts except the monospace?
For example, if choose other fonts (except monospace), the preview below would not display, then the fonts in guake would become large and wide.
![other fonts](https://github.com/gemini4545/img_links/blob/main/change%20fonts.png?raw=true)
But the system do have the font, otherwise it wont show up here for choosing, right?

**Comment by Davidy22** [comment]
Non-monospace fonts are generally not good for use in terminals, you really want to choose monospaced fonts for your terminal. Does this issue still happen for you if you choose a monospaced font?

**Comment by gemini4545** [comment]
> Non-monospace fonts are generally not good for use in terminals, you really want to choose monospaced fonts for your terminal. Does this issue still happen for you if you choose a monospaced font?

OK, this would not be a issue if choose the monospaced font.

on the other side. I also tried to set the "use the system fixed width font" option on my other computers (ubuntu with KDE and Kali with KDE), they all worked well. looks it is a issue only with Manjaro when setting "use the system fixed width font" option!

**Comment by Davidy22** [comment]
Fixed width means monospace. All the other distros should correctly have a monospace font as the default fixed width font. Not sure why the Manjaro installation doesn't, but that would be incorrect behavior from Manjaro. Did you ever adjust the default fonts on your manjaro box yourself?

Closing because this was an issue with non-monospaced fonts in a terminal where we shouldn't be using non-monospaced fonts.

**Comment by gemini4545** [comment]
Nope, I didn't ever change any settings since this is my virtual machine and I leave most settings as default, including the defualt Yakuake. Recently I was just unable to adapt to the Yakuake's shorcut settings, so I decided to go back to the Guake just like my other computers, while the issue happened then.

Anyway, thanks for locating the causes.
