### ISSUE TITLE
Can't toggle Guake on Wayland Gnome, unless I'm using a XWayland app

### ISSUE THREAD

**Issue by Araly** [Guake/guake#2025]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Guake.

For how to run the latest Guake in your computer, please refer to [Install from source](https://guake.readthedocs.io/en/latest/user/installing.html#install-from-source).

**Describe the bug**

When pressing the toggle guake keybind, I can bring up guake (and toggle it off), but only when I have a XWayland app focused. If I have nothing focused (the gnome background) or a wayland app (gnome files), I can't toggle guake.

**Expected behavior**

When I press the guake toggle keybind, guake appears and dissapears no matter the context.

**Actual behavior**

Guake appears and dissapears correctly when I'm focused on discord or vivaldi, but not on gnome backround or gnome files.

**To Reproduce**

- Install Guake on Gnome Wayland (on Arch if it matters)
- set the toggle guake keybind
- press the toggle guake keybind, see that it doesn't work
- launch discord
- when discord is focused, press the toggle guake keybind, see that it works and guake appears

-------------------------------------------------------------------------------

Please run `$ guake --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting. And make sure you run the command **OUTSIDE** the Guake.

<details><summary>$ guake --support</summary>

Guake Version:		3.8.1

Vte Version:		0.66.2

Vte Runtime Version:	0.66.2

--------------------------------------------------
GTK+ Version:		3.24.31

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: gnome

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - XWAYLAND0
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		530 x 300 mm²
    * Primary:		True
    * Refresh rate:	59.962 Hz
    * Subpixel layout:	unknown

**Comment by Davidy22** [comment]
Wayland blocks global keybindings in its crusade against keyloggers. See #2011 for instructions on how to set the keybinding globally and progress on making this more discoverable to users.
