### ISSUE TITLE
Font size can be incremented, but not decremented

### ISSUE THREAD

**Issue by mabushey** [Guake/guake#2026]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Guake.

For how to run the latest Guake in your computer, please refer to [Install from source](https://guake.readthedocs.io/en/latest/user/installing.html#install-from-source).

**Describe the bug**

[Ctrl shift +] increases the font size, but [Ctrl shift -] does not decrement.

**Expected behavior**

Ability to BOTH increase and decrease font size

**Actual behavior**

Only able to increase font size

**To Reproduce**

Hit [Ctrl Shift +] - observe font get bigger. Hit [Ctrl Shift -] - enjoy your larger font that does not scale down

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:		3.6.3

Vte Version:		0.64.2

Vte Runtime Version:	0.64.2

--------------------------------------------------
GTK+ Version:		3.24.30

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: cinnamon

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - SHP eDP-1
    * Geometry:		1920 x 1080 at 0, 1525
    * Size:		344 x 194 mm²
    * Primary:		True
    * Refresh rate:	240.00 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - GSM HDMI-1-1
    * Geometry:		3840 x 2160 at 1920, 0
    * Size:		1600 x 900 mm²
    * Primary:		False
    * Refresh rate:	30.00 Hz
    * Subpixel layout:	unknown

**Comment by Davidy22** [comment]
Your log says that you are using Guake 3.6.3, which is a 3 year old version of Guake. You may want to upgrade, as newer versions have had various fixes to keybindings.
