### ISSUE TITLE
Doesnt remember tab names after closing guake and reopening

### ISSUE THREAD

**Issue by landerson78** [Guake/guake#2044]
In arch guake version 3.8.5.1 doesnt remember tab names if u rename them when u close the program and reopen it. It always defaults back to original name which is the home user folder.  I searched tabs didnt see this bug posted.

arch newest community zen kernal i3

**Comment by mlouielu** [comment]
Please check if your `~/.config/guake/session.json` has created and saved your tab name inside.

**Comment by landerson78** [comment]
"label": "yay",
                    "custom_label_set": true
it has the yay label as 1 and still isnt showing it

**Comment by mlouielu** [comment]
Thank you, I can reproduce it at `c48caa7` from Arch Linux repo.

**Comment by mlouielu** [comment]
Introduce in 2613e02a9e12f94b7c6f8cc4e2dd7805321dda77, #2020

**Comment by mlouielu** [comment]
PR pending #2045.

**Comment by landerson78** [comment]
k ty

**Comment by dxps** [comment]
Now that this is solved as well (I am one of the "affected" users), can we have the `3.8.6` release, please?
Thank you! :pray:  I love this app (at least for the session save & restore) and I'm a daily user.

**Comment by Davidy22** [comment]
My plan was to release a new geany version once #2057 passes review. I'll ping @mlouielu again, if there's still radio silence I guess I'll push it on my own.

**Comment by dxps** [comment]
Kind reminder! :relaxed: Can we have 3.8.6 release these days, please? :pray:

**Comment by anselal** [comment]
I am having the same issue, tab names are set to `Terminal` after a restart

```sh
Guake Terminal: 3.8.5
VTE: 0.68.0
VTE runtime: 0.68.0
Gtk: 3.24.33
```
 on Ubuntu 22.04.2. 

It was working fine on Ubuntu 20

**Comment by anselal** [comment]
The names are saved in the session.json after quiting but are not rendered on restart
