### ISSUE TITLE
guake.desktop link broken in debian

### ISSUE THREAD

**Issue by jessmathews** [Guake/guake#2048]
guake.desktop link is broken under ***/usr/share/applications***
It links as
```
guake.desktop -> ../guake/data/autostart-guake.desktop
```
while it **should be** 
```
guake.desktop -> ../guake/autostart-guake.desktop
```
since there is **no /data folder under guake**
this is messing with my apt upgrade since kali-menu keeps showing this:
```bash
update-kali-menu: error: can't open /usr/share/applications/guake.desktop: No such file or directory
```
guake version:
```
Guake Terminal 3.8.5
VTE 0.66.2
Gtk 3.24.31
```
I use : **Linux kali 5.16.0-kali1-amd64  Debian 5.16.7-2kali1 (2022-02-10) x86_64 GNU/Linux**

**Comment by Davidy22** [comment]
Looks like in the makefiles that the path is being set from SHARE_DIR, which doesn't have a `/data/` appended. Where did you get the package from? Might a config issue on repo side.

**Comment by jessmathews** [comment]
I installed it using apt package manager
```
apt install guake
```

**Comment by Davidy22** [comment]
I'm checking and I assume you're using the [Kali rolling](http://pkg.kali.org/pkg/guake) repo, looks like they're tracking debian unstable, I'll try to download packages along the chain to see where the issue started. Just to make sure, did this work for you correctly in a previous version?

**Comment by jessmathews** [comment]
This is my first time with guake. I haven't tried any earlier versions.

**Comment by chundla** [comment]
I can attest to this issue for me as well. 
OS: Kali-rolling 2022.1
Arch: AMD64 as well as ARM64
Guake did work on previous builds

Error during install: update-kali-menu: error: can't open /usr/share/applications/guake.desktop: No such file or directory

The issue is guake.desktop is linking to /usr/share/guake/data/autostart-guake.desktop but the folder 'data' does not exist.

To resolve this issue i removed guake.desktop from /usr/share/applications and ran 'sudo ln -s /usr/share/guake/autostart-guake.desktop /usr/share/applications/guake.desktop'.

**Comment by Davidy22** [comment]
Git blame says last commit that seems like it should have affected this is fce21e7d9b65ff4ed786a4b8bc99216e789dcc99, and that was two years ago. That and all the reports coming from kali lead me to suspect that there was an issue with the distro package, the kali resource page points to the [same repo](https://salsa.debian.org/debian/guake/-/tree/master) as the debian testing upstream for the package, which pulled five days ago and both updated recently. I'm looking at the commit history and there's [two commits](https://salsa.debian.org/debian/guake/-/commit/ecfddf89291f4b0dbcd3ddfb218e453ba4ea5d76) [from the last five days](https://salsa.debian.org/debian/guake/-/commit/63f63774e5201f88d0203363734915b7225de518) that look like they could be relevant here, will open a ticket forwarding this to the maintainer there.

**Comment by Davidy22** [comment]
For record keeping, ticket opened at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1006680

**Comment by barak** [comment]
Running this script fixed it for me; obviously this is just a stopgap until the package is fixed.
```bash
#!/bin/bash -f
set -e
d=/usr/share/applications
f=guake.desktop
t=../guake/autostart-guake.desktop
echo "current link state:"
ls -l $d/$f
cd $d
if [ -L $f -a \! -a $f -a -a $t ]; then
    echo "Swizzling bad link:"
    ln --force --symbolic --verbose $t $f
else
    echo "Aborting swizzle."
    exit 1
fi
```

**Comment by ObscuredSecurity** [comment]
I have the same issue with Kali rolling 2022

error: can't open /usr/share/applications/guake.desktop: No such file or directory

Is there a resolution? I installed via apt

**Comment by chundla** [comment]
> I have the same issue with Kali rolling 2022
> 
> error: can't open /usr/share/applications/guake.desktop: No such file or directory
> 
> Is there a resolution? I installed via apt

The script in the reply above yours works as well as: `sudo rm /usr/share/applications/guake.desktop && sudo ln -s /usr/share/guake/autostart-guake.desktop /usr/share/applications/guake.desktop`

**Comment by ObscuredSecurity** [comment]
Thanks I'll give it a try!

**Comment by spcristiano** [comment]
> > I have the same issue with Kali rolling 2022
> > error: can't open /usr/share/applications/guake.desktop: No such file or directory
> > Is there a resolution? I installed via apt
> 
> The script in the reply above yours works as well as: `sudo rm /usr/share/applications/guake.desktop && sudo ln -s /usr/share/guake/autostart-guake.desktop /usr/share/applications/guake.desktop`

This works for me. thanks.

**Comment by Davidy22** [comment]
Debian closed the issue, reports as fixed, reopen if debian's fix did not fix.

**Comment by ObscuredSecurity** [comment]
Thanks David, everything is working well!

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
