### ISSUE TITLE
Transparent tab bar

### ISSUE THREAD

**Issue by konahart** [Guake/guake#2053]
**Description**

The tab bar is completely transparent except for the tab text. The tab text appears to change color depending on background, but I have not bee able to determine how the color is picked -- adjusting the palette did not change the tab text color.

Screenshot:
![Screenshot from 2022-03-16 03-18-52](https://user-images.githubusercontent.com/945693/158568478-d68196bf-4240-44d1-b0e7-95f992f75ad0.png)
The purple is the bottom of my terminal. The text is just barely visible in light green.

![Screenshot from 2022-03-16 03-23-21](https://user-images.githubusercontent.com/945693/158569444-8ac29e1e-f24a-4af0-ab56-30d1cf525ae1.png)

Against a dark background, the text becomes white.

![Screenshot from 2022-03-16 03-23-37](https://user-images.githubusercontent.com/945693/158569500-56296da4-80a3-4dd3-8677-c34896c69192.png)
Palette settings (minor customization from Toybox)

I couldn't find any description of this behavior, which leads me to believe it is not intended. In any case, it makes tabs incredibly difficult to use.

**Expected behavior**

I would like to be able to set my tab bar to not be transparent. If this is already an option, it needs to be easier to find in the documentation.

**Actual behavior**

Tab bar is transparent except for text.

**To Reproduce**

Tab bar has been transparent since fresh installation 2 days ago.

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:		3.8.5

Vte Version:		0.67.90

Vte Runtime Version:	0.67.90

--------------------------------------------------
GTK+ Version:		3.24.32

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: ubuntu

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - XWAYLAND0
    * Geometry:		3072 x 1728 at 0, 0
    * Size:		600 x 340 mm²
    * Primary:		True
    * Refresh rate:	59.941 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - XWAYLAND1
    * Geometry:		1920 x 1080 at 3072, 606
    * Size:		480 x 270 mm²
    * Primary:		False
    * Refresh rate:	59.962 Hz
    * Subpixel layout:	unknown

**Comment by Davidy22** [comment]
The color palette decides terminal colors, the parts of the program that aren't the strictly terminal part of Guake are styled by the GTK theme option. Guake also uses the system default theme by default as of 3.8, and we've seen reports in the past of people with the Yaru theme encountering this same issue. Yaru has fixed it and should be rolling a fix out some time, but if you aren't using yaru/it hasn't been pushed out yet for now you can also uncheck the "Use system default theme" box in Guake preferences and manually pick a theme that won't have a transparent tab bar.

**Comment by konahart** [comment]
Unchecking "Use system default theme" fixed the issue. Thank you for your quick response!
