### ISSUE TITLE
pipx install: ModuleNotFoundError: No module named 'gi'

### ISSUE THREAD

**Issue by lamyergeier** [Guake/guake#2054]
**Describe the bug**

Not running after installation using pipx (On Linux Mint 20.3, based on Ubuntu 20.4)

**To Reproduce**

```
$ sudo apt-get install --no-install-recommends -y \
		gir1.2-keybinder-3.0 \
		gir1.2-notify-0.7 \
		gir1.2-vte-2.91 \
		gir1.2-wnck-3.0 \
		libkeybinder-3.0-0 \
		libutempter0 \
		python3 \
		python3-cairo \
		python3-dbus \
		python3-gi \
		python3-setuptools-scm \
		python3-pip \
		libgirepository1.0-dev
$ pipx reinstall guake
uninstalled guake! ✨ 🌟 ✨
  installed package guake 3.8.5, installed using Python 3.8.10
  These apps are now globally available
    - guake
    - guake-toggle
done! ✨ 🌟 ✨
$ guake
Traceback (most recent call last):
  File "/home/nikhil/.local/bin/guake", line 5, in <module>
    from guake.main import exec_main
  File "/home/nikhil/.local/pipx/venvs/guake/lib/python3.8/site-packages/guake/main.py", line 54, in <module>
    from guake.support import print_support
  File "/home/nikhil/.local/pipx/venvs/guake/lib/python3.8/site-packages/guake/support.py", line 5, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```

-------------------------------------------------------------------------------

Please run `$ guake --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting. And make sure you run the command **OUTSIDE** the Guake.

$ guake --support
Traceback (most recent call last):
  File "/home/nikhil/.local/bin/guake", line 5, in <module>
    from guake.main import exec_main
  File "/home/nikhil/.local/pipx/venvs/guake/lib/python3.8/site-packages/guake/main.py", line 54, in <module>
    from guake.support import print_support
  File "/home/nikhil/.local/pipx/venvs/guake/lib/python3.8/site-packages/guake/support.py", line 5, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

**Comment by Davidy22** [comment]
There are some amount of dependencies that Pip won't install, so the pip installation is more for getting the latest Guake than it is for installing Guake the first time. `gi` should be provided by the repo when you install Guake via your distro's package manager

**Comment by anishmittal2020** [comment]
@Davidy22 I have installed using pipx abd not using pip. In the documentation it is mentioned that pipx is recommended way to install it.

**Comment by Davidy22** [comment]
From what I've seen of pipx installs it just guarantees that non-python dependencies fail to link even if they're installed. If you have Guake installed via both pip and apt it may still be running the pip installed version and you'll need to uninstall the pipx version first. Also may need to amend that documentation or figure out what the original writer's intention was.

**Comment by anishmittal2020** [comment]
The apt repository version was not up to date, and stopped working, so I uninstalled it and c installed using pipx.

**Comment by Davidy22** [comment]
Consolidating issues related to #1971, need to figure out why there's multiple cases of pygobject/python-gi not getting installed as deps

**Comment by mertemba** [comment]
In case someone else still wants to install Guake using pipx and finds this page, the following fix worked for me:
```sh
pipx inject guake pygobject pyyaml dbus-python
```
