### ISSUE TITLE
Guake under Wayland works only on one display.

### ISSUE THREAD

**Issue by Hadatko** [Guake/guake#2056]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Guake.
- I tried find existing issue but i didn't

For how to run the latest Guake in your computer, please refer to [Install from source](https://guake.readthedocs.io/en/latest/user/installing.html#install-from-source).
- version ![Screenshot_20220324_065357](https://user-images.githubusercontent.com/13130700/159851630-865e2c09-d5a3-403e-96f0-79db91e08fc9.png)

**Describe the bug**

When external monitor is connected. Guake is working only on that one (maybe only on one display is working and in my case it is external). On laptop display shortcut for minimalizing is working only when guake is focused otherwise not. If focused anything else on laptop display guaky shortcut for minimalizing to system tray is not working.

**Expected behavior**

Minimalizing to system tray should work when focused any application on any monitor.

**Actual behavior**

Minimalizing to system tray works only when focused any application on external monitor.

**To Reproduce**

install guake, connect external monitor using HDMI

-------------------------------------------------------------------------------

Please run `$ guake --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting. And make sure you run the command **OUTSIDE** the Guake.
<details><summary>$ guake --support</summary>

Guake Version:		3.8.1

Vte Version:		0.64.2

Vte Runtime Version:	0.64.2

--------------------------------------------------
GTK+ Version:		3.24.30

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: plasmawayland

--------------------------------------------------
Display: :1

RGBA visual: True

Composited: True

* Monitor: 0 - XWAYLAND0
    * Geometry:		1920 x 1080 at 0, 1080
    * Size:		340 x 190 mm²
    * Primary:		True
    * Refresh rate:	59.962 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - XWAYLAND2
    * Geometry:		1920 x 1080 at 1, 0
    * Size:		520 x 290 mm²
    * Primary:		False
    * Refresh rate:	59.962 Hz
    * Subpixel layout:	unknown

**Comment by kunicmarko20** [comment]
Same problem on ubuntu 22.04,

<details><summary>$ guake --support</summary>

Guake Version:		3.8.5

Vte Version:		0.67.90

Vte Runtime Version:	0.67.90

--------------------------------------------------
GTK+ Version:		3.24.32

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: ubuntu

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - XWAYLAND1
    * Geometry:		1920 x 1200 at 308, 1440
    * Size:		340 x 210 mm²
    * Primary:		True
    * Refresh rate:	59.884 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - XWAYLAND0
    * Geometry:		2560 x 1440 at 0, 0
    * Size:		700 x 400 mm²
    * Primary:		False
    * Refresh rate:	59.912 Hz
    * Subpixel layout:	unknown

**Comment by Hadatko** [comment]
It looks working better when i set in kubuntu  shortcut manually
![image](https://user-images.githubusercontent.com/13130700/164044266-322793ed-2227-473f-85ac-f85fa3c13988.png)

**Comment by Davidy22** [comment]
On wayland, due to intentional design decisions on the part of wayland setting guake-toggle in the window manager's keybindings manager is the recommended way to bind the toggle shortcut.
