### ISSUE TITLE
Open links under terminal cursor

### ISSUE THREAD

**Issue by thibthib18** [Guake/guake#2060]
For a more keyboard driven workflow, it would be great to be able to open links/URLs under terminal cursor via a keyboard shortcut.

I'd also be interested to make a PR if I could get some pointers. 

That functionality is already there for the mouse cursor, so I imagine there's a way to do this without too much effort if we can get the terminal cursor position.

**Comment by Davidy22** [comment]
Keybindings get set  in keybindings.py, and documentation for the methods to interact with the VTE can be found [here](https://lazka.github.io/pgi-docs/Vte-2.91/classes/Terminal.html) if you were looking to put togethor a PR

**Comment by Davidy22** [comment]
PR merged, closing
