### ISSUE TITLE
Can no longer scroll up/down using keyboard

### ISSUE THREAD

**Issue by logileifs** [Guake/guake#2065]
On an older version of guake I used ctrl+shift+up/down arrows to scroll the output of the terminal up/down. This does not work anymore. I don't know if I changed the keybindings myself or not on the older version but on 3.6.3 version there is no option in the keyboard shortcut preferences to set keys to scroll up/down.

**Describe the bug**

Cannot use ctrl+shift+up/down arrows to scroll terminal up and down.

**Expected behavior**

I expect ctrl+shift+up/down to scroll terminal up/down

**Actual behavior**

Transparency indreases/decreases

**To Reproduce**

Open guake and press ctrl+shift+up/down to try scrolling

-------------------------------------------------------------------------------
<details><summary>$ guake --support</summary>

Guake Version:		3.6.3

Vte Version:		0.60.3

Vte Runtime Version:	0.60.3

--------------------------------------------------
GTK+ Version:		3.24.20

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: budgie-desktop

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - AUO eDP-1
    * Geometry:		1920 x 1080 % 2 at 0, 0
    * Size:		344 x 193 mm²
    * Primary:		True
    * Refresh rate:	60.00 Hz
    * Subpixel layout:	unknown

**Comment by Davidy22** [comment]
3.6.x is not the current version of Guake but I can confirm that it does appear to be gone, can look at restoring the feature, hopefully there's just code remnants to reconnect

**Comment by logileifs** [comment]
@Davidy22 I realize that 3.6.3 is not the latest version but I read through the release notes of the later versions and found no mention of any scroll functionality so I assume this applies for the latest version as well

**Comment by Davidy22** [comment]
Ok, figured out what's happening, the shortcut is actually hardcoded into VTE but having it set a level above overrides the shortcut so when the transparency adjust keyboard shortcut was given a default value, it overrode the VTE scroll keys. Transparency adjustment is less critical than the scroll functionality, going to cut that default. You can reclaim the scroll functionality for yourself by unsetting the transparency up/down shortcuts in Guake preferences.

**Comment by Davidy22** [comment]
Resolved in ca0e17a190daf4b50b2843965118b20ec6f8d191, did a little oopsie with push target and sent it straight to the repo but I sort of already am ending up forcing all my commits nowadays anyways with other maintainers rarely checking in to review so I guess it's about the same outcome
