### ISSUE TITLE
Guake will not launch

### ISSUE THREAD

**Issue by jasonrmallet** [Guake/guake#2066]
Guake version:  3.8.5
Linux Distribution:  Ubuntu 22.04 Beta
Gnome version:  42.0

1. In the applications menu, only "Guake Preferences" appears. There is no icon for "Guake Terminal."
2. After clicking on "Guake Preferences," the application crashes.
3. Typing "guake" into the terminal gives this output:

[username redacted]@[computer name redacted]:~$ guake
Guake not running, starting it
Loading Gnome schema from: /usr/share/glib-2.0/schemas
Language previously loaded from: /usr/share/locale
Guake Terminal 3.8.5
VTE 0.68.0
Gtk 3.24.33
created fresh notebook for workspace 0
Spawning new terminal at /home/[username redacted]
current workspace is 0
can't bind show-focus key
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/guake/main.py", line 463, in main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/guake", line 33, in <module>
    sys.exit(load_entry_point('guake==3.8.5', 'console_scripts', 'guake')())
  File "/usr/lib/python3/dist-packages/guake/main.py", line 633, in exec_main
    if not main():
  File "/usr/lib/python3/dist-packages/guake/main.py", line 479, in main
    instance = Guake()
  File "/usr/lib/python3/dist-packages/guake/guake_app.py", line 251, in __init__
    refresh_user_start(self.settings)
  File "/usr/lib/python3/dist-packages/guake/prefs.py", line 218, in refresh_user_start
    shutil.copyfile(
  File "/usr/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/home/[username redacted]/.config/autostart/guake.desktop'

******

Expected action:  guake launches
Actual action:  guake doesn't launch

Any assistance would be very much appreciated as I have been a long-time guake user (and lover!) and this is the first I have ever had any issues with it. I realize this may be due to using it in Ubuntu 22.04 beta.

**Comment by Davidy22** [comment]
That last line looks interesting, given that it's where the desktop file gets copied out. For whatever reason, ~/.config/autostart/ is forbidden to Guake, are there any other .desktop files in there? Maybe ubuntu changed something that we might need to adjust for.

**Comment by jasonrmallet** [comment]
> That last line looks interesting, given that it's where the desktop file gets copied out. For whatever reason, ~/.config/autostart/ is forbidden to Guake, are there any other .desktop files in there? Maybe ubuntu changed something that we might need to adjust for.

Agreed, I thought it was really weird. I've actually only been able to copy other .desktop files into it using sudo for some reason. When trying to add the .desktop files to the startup applications app (or the one in gnome-tweak) it won't let me do it; the only way to do it is copy them from /usr/share/applications; even then, some of them still don't start when I do a fresh login. Originally the only one in there was opensnitch (one of the ones that won't start when I log in).

**Comment by Davidy22** [comment]
I'm checking that dir on my system and the permssions  column reads `drwxr-xr-x`. I assume you haven't touched the permissions on it, I haven't either, and haven't gotten reports about this specific message before so I assume ubuntu's been changing things in 22.04. I can't find any mention of them doing this in a changelog, can send a report up to them but for now you can `chmod +w` on that directory and I think that should do the job.

**Comment by staleo** [comment]
> I realize this may be due to using it in Ubuntu 22.04 beta.

I'm on Ubuntu 20.04.4 and I still have the same issue.

`PermissionError: [Errno 13] Permission denied: '/home/staleo/.config/autostart/guake.desktop'`

**Comment by jasonrmallet** [comment]
> > I realize this may be due to using it in Ubuntu 22.04 beta.
> 
> I'm on Ubuntu 20.04.4 and I still have the same issue.
> 
> `PermissionError: [Errno 13] Permission denied: '/home/staleo/.config/autostart/guake.desktop'`

I'm starting to wonder if it has anything to do with the fact that I encrypt my filesystem using ecryptfs (since I put /home on a different hard drive and have to manually set up the partition table during install).

**Comment by Davidy22** [comment]
Is that staleo's setup too? What's the permissions readout on the directory for you two?

**Comment by staleo** [comment]
> Is that staleo's setup too? What's the permissions readout on the directory for you two?

I just blindly and noobishly `chmod`ed it to 0777 and its now good to go.

**Comment by Davidy22** [comment]
i think you don't need 777 you just need to be able to write there so that guake can put the desktop file in there but I guess that folder's just all desktop launcher files so probably nothing too bad'll happen from generous privileges

**Comment by staleo** [comment]
> i think you don't need 777 you just need to be able to write there so that guake can put the desktop file in there but I guess that folder's just all desktop launcher files so probably nothing too bad'll happen from generous privileges

Yea I thought I had a choice whether I do chmod 0777 right now and get back to work immediately, or I head to refreshing my modest knowledge about those privigedges codes stuff. :)

**Comment by Davidy22** [comment]
I don't actually remember the bit order either, chmod also has +w and +r which I use instead because i can remember w and r

**Comment by Davidy22** [comment]
Closing since this is just a local setup issue
