### ISSUE TITLE
Alternative tray icon

### ISSUE THREAD

**Issue by toastedsocks** [Guake/guake#2071]
I made a custom 20x20px tray icon for guake, it can be found at https://github.com/toastedsocks/magma-bunkhouse/blob/main/guake-tray-compact-v05.png

It's optimised for smallness, so should look pretty sharp when displayed at it's original size. If you're using the Gnome appindicator extension, make sure the icon size is set to 22 or higher for best display.

Cheers, T.

**Comment by Davidy22** [comment]
It does look a bit different from the regular one, wouldn't we want all the icons to be the same so people know it's the same program?

**Comment by toastedsocks** [comment]
It is different, and I agree icons should be consistent. Please consider it as an optional fan-made icon, I'm not pushing for adoption of a new default icon set by any means. I wasn't sure where else to post it, but considering I created it specifically for guake on my machine, this seemed a good place.
