### ISSUE TITLE
Broken/No DNS: Please use [FeatHub](https://feathub.com/Guake/guake) to fill-up a feature request.

### ISSUE THREAD

**Issue by ElijahLynn** [Guake/guake#2087]
> Please use [FeatHub](https://feathub.com/Guake/guake) to fill-up a feature request.

DNS is broken for https://feathub
![image](https://user-images.githubusercontent.com/1504756/167970445-fb5c11d8-fba9-4e67-b688-85c242ea7472.png)

**Comment by Davidy22** [comment]
Feathub website's been down a while, might just strike it from the readme

**Comment by Davidy22** [comment]
I just struck mentions of feathub from the readme etc in 097d84b7019787694e70e17da5f1db9a98616f3f, closing.

**Comment by pabloab** [comment]
JFTR, [here](https://web.archive.org/web/20210512141545/http://feathub.com/Guake/guake) the last archive.org capture.
