### ISSUE TITLE
feature: ability to use custom search engine for "Search on Web" (hardcoded to Google)

### ISSUE THREAD

**Issue by ElijahLynn** [Guake/guake#2088]
The "Search on Web" feature is very useful. I recently switched to a non-Google search engine and noticed that Guake is hardcoded to use Google. It would be nice to have this be user customizable. 

https://github.com/Guake/guake/blob/2cfc9b3ab00f8288fb119c1c6f663552384732cf/guake/callbacks.py#L50-L58

https://github.com/Guake/guake/blob/0db81488d17e34df52c45e75b51d022a118dd9d3/guake/guake_app.py#L1323-L1336

**Comment by PhantomLel** [comment]
can i take this?

**Comment by oewami** [comment]
yes.

**Comment by Davidy22** [comment]
If you want to work on resolving an issue, you can just send in a PR and if it works and looks good I'll merge.

**Comment by hackedd** [comment]
Added with #2134.
