### ISSUE TITLE
Guake bottom ribbon vanishes after the hiding or going full screen.

### ISSUE THREAD

**Issue by atpugludrim** [Guake/guake#2090]
**Describe the bug**

This is happening since I updated to Lubuntu 22.04. When I run Guake, there is this ribbon on the bottom of the terminal which has tab names. Anytime I go full screen, or hide the terminal and show it back, the ribbon vanishes. Though it reappears when I start a new tab. But again goes away once I go full screen or hide the terminal.

**Expected behavior**

The ribbon should be there.

**Actual behavior**
The ribbon ain't there.

**To Reproduce**

Start the guake daemon. Show it (F12). Ribbon is there. Either go full screen (F11) or hide (F12) and go back to the previous size display (F11 again or F12 again). The ribbon is no longer there.

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:          3.8.5

Vte Version:            0.68.0

Vte Runtime Version:    0.68.0

--------------------------------------------------
GTK+ Version:           3.24.33

GDK Backend:            <GdkX11.X11Display

--------------------------------------------------
Desktop Session: Lubuntu

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: False

* Monitor: 0 - AUO eDP-1
    * Geometry:         1920 x 1080 at 0, 0
    * Size:             344 x 193 mm²
    * Primary:          True
    * Refresh rate:     120.212 Hz
    * Subpixel layout:  unknown

**Comment by Davidy22** [comment]
There is a "Hide tabbar when fullscreen" option in the main window tab of the preferences menu that I believe defaults to checked. Do you still experience this issue when you uncheck it?

**Comment by Davidy22** [comment]
Believe this is the same case as #2093, closing
