### ISSUE TITLE
Not taking up 100% width and is not centered as configured - screen capture included

### ISSUE THREAD

**Issue by crunk1** [Guake/guake#2091]
**Describe the bug**
Guake is not 100% the width of the screen as I have configured it. See screen capture:
https://user-images.githubusercontent.com/1885442/169162060-e5dca24b-23d8-4ce5-ae28-78064c29fdc6.mp4

**Expected behavior**
Guake terminal should stretch the entire width of the screen.

**Actual behavior**
Covers only about 66% of the width and is off centered.

**To Reproduce**
Set preferences to 100 width and centered. Close/minimize guake terminal. Reopen.

-------------------------------------------------------------------------------

Guake Version:		3.8.6.dev0

Vte Version:		0.68.0

Vte Runtime Version:	0.68.0

--------------------------------------------------
GTK+ Version:		3.24.33

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: plasma

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - DEL DP-0
    * Geometry:		3440 x 1440 at 0, 0
    * Size:		800 x 340 mm²
    * Primary:		True
    * Refresh rate:	59.972 Hz
    * Subpixel layout:	unknown

**Comment by crunk1** [comment]
I should add, I tried installing from source, etc. 3.8.5 was doing this for me too.

`guake --support` says I'm on `3.8.6.dev0`, but I'm running [this Arch package](https://archlinux.org/packages/community/any/guake/) which is supposedly `3.8.5-1` at this time.

**Comment by Davidy22** [comment]
Can reproduce on a manjaro KDE VM, resolved in deffa2b2f9f59570faba32d2b1af715b7d41f331
