### ISSUE TITLE
Guake tab bar not showing after full screen

### ISSUE THREAD

**Issue by skjo0c** [Guake/guake#2093]
**Describe the bug**

After updating my ubuntu budgie to 22.04, experiencing this issue where if guake is opened/toggled to full screen, tab bar is not showing up. Also, I can see the scroll bar even though there is no context in the terminal.

**Expected behavior**

Tab bar should be shown on full screen.

**Actual behavior**

Tab bar is not shown on full screen and toggling back to half screen.

**To Reproduce**

Start guake in half screen, then toggle to full screen or just start the session in full screen.

-------------------------------------------------------------------------------

guake --support
<details><summary>$ guake --support</summary>

Guake Version:		3.8.5

Vte Version:		0.68.0

Vte Runtime Version:	0.68.0

--------------------------------------------------
GTK+ Version:		3.24.33

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: budgie-desktop

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - BNQ DP-0
    * Geometry:		2560 x 1440 at 1920, 0
    * Size:		597 x 336 mm²
    * Primary:		True
    * Refresh rate:	143.999 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - BOE DP-2
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		344 x 194 mm²
    * Primary:		False
    * Refresh rate:	144.001 Hz
    * Subpixel layout:	unknown

**Comment by cabrace** [comment]
Coming across the same issue myself, following the lead of this [post](https://github.com/Guake/guake/issues/2085); pressing the F11 reduced the window for me because window size in Preferences was ~not set to Max. So then slowly increased to max while testing the 'guake-toggle' set in Ubuntu Keyboard shortcuts seemed to have resolved it, even if it is for this current session.

**Comment by Davidy22** [comment]
Can't reproduce on usual machine with Fedora, GNOME 42, but installed a VM with manjaro and can produce this reliably, can look at a fix.

**Comment by Davidy22** [comment]
Scratch that, during more testing in the VM I remembered the "Hide tabbar when fullscreen" checkbox and unchecked it and can no longer reproduce on the mandriva VM. Checkbox is in the main window tab, though the amount of time it took me to remember it might mean a reshuffling of the preferences menu might be due. Does unchecking the hide tabbar when fullscreen option resolve this for you?

**Comment by skjo0c** [comment]
ya, it worked for me, maybe this used to be unchecked by default previously? idk. But thanks.

**Comment by MattSom** [comment]
Freshly installed Ubuntu 22.04. The issue is still apparent.

**Comment by fredmo** [comment]
The issue is present by doing click right and 2 times "toggle full screen"  on xfce / ubuntu 22.04
But by pressing F11 is restoring.
