### ISSUE TITLE
Scroll the whole page in terminal 

### ISSUE THREAD

**Issue by justanhduc** [Guake/guake#2095]
Hi. Thanks for this great terminal. I am using Terminator in parallel and one great thing I think missing is the functionality to scroll the whole page (like page up/down). Do you think it can be added? Thanks a lot again!
P/S: FeatHub is down!

**Comment by Davidy22** [comment]
CTRL+SHIFT+arrow keys can scroll up and down slowly, shift + pgup/down scrolls a screen height at a time. There may be a default keyboard shortcut bound overriding some of these, I've removed the colliding defaults for 3.9 but you can amend them in preferences if you find that you have a collision.
