### ISSUE TITLE
-e option spawns an additional "Terminal" tab during guake startup

### ISSUE THREAD

**Issue by bennybenjaman** [Guake/guake#2103]
**Describe the bug**

When executing a startup script that contains the --execute-command option guake spawns an additional tab named "Terminal" with each new tab that contains the -e option.

 It only affects  tabs created with the -e option

**Expected behavior**

In previous versions of guake this same startup script worked fine. After the re-implementation of the -e option in the new guake update, startup scripts behave as described above.

#!/usr/bin/zsh
sleep 6
/usr/bin/guake &
sleep 2
guake --hide --rename-tab="Term1"
guake --new-tab=" " -r "Term2"
guake -n " " -r "Term3"
guake -n " " -r "Term4"
guake -n " " -r "Term5"
guake -n " " -r "HtopLogs" -e "/usr/bin/sh -c /home/anon/scripts/tmux-log-diagnostic.sh"
guake -n " " -r "enp3s0" -e "/usr/bin/sh -c /home/anon/scripts/tmux-network-diagnostic-enp3s0.sh"
guake -n " " -r "enp4s0" -e "/usr/bin/sh -c /home/anon/scripts/tmux-network-diagnostic-enp4s0.sh"
guake -n " " -r "pex" -e "/usr/bin/sh -c /usr/bin/ssh pi@192.168.100.111"
guake -n " " -r "RZ" -e "/usr/bin/ssh anon@192.168.100.116"
guake -n " " -r "FF" -e "/usr/bin/ssh anon@192.168.100.200"
guake -n " " -r "TRD" -e "/usr/bin/ssh root@192.168.1.100"
guake -n " " -r "RRV" -e "/usr/bin/ssh root@192.168.20.1"
guake -s 0

**Actual behavior**

Terminal Output after startup as well as guakes tabs bar after startup.

Guake not running, starting it
Loading Gnome schema from: /usr/share/glib-2.0/schemas
Language previously loaded from: /usr/share/locale
Guake Terminal 3.9.0
VTE 0.68.0
Gtk 3.24.34
created fresh notebook for workspace 0
Spawning new terminal at /home/anon
current workspace is 0
can't bind show-focus key
Guake initialized
current workspace is 0
Spawning new terminal at  
Spawning new terminal at  
Spawning new terminal at  
Spawning new terminal at  
Spawning new terminal at  
Spawning new terminal at /home/anon
Spawning new terminal at  
Spawning new terminal at /home/anon
Spawning new terminal at  
Spawning new terminal at /home/anon
Spawning new terminal at  
Spawning new terminal at /home/anon
Spawning new terminal at  
Spawning new terminal at /home/anon
Spawning new terminal at  
Spawning new terminal at /home/anon
Spawning new terminal at  
Spawning new terminal at /home/anon
Spawning new terminal at  
Spawning new terminal at /home/anon

https://imgur.com/o0GZLrY

**To Reproduce**

Execute a startup script with tabs that include the -e option.

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:		3.9.0

Vte Version:		0.68.0

Vte Runtime Version:	0.68.0

--------------------------------------------------
GTK+ Version:		3.24.34

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: plasma

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - BNQ DP-4
    * Geometry:		1920 x 1080 at 1920, 309
    * Size:		544 x 303 mm²
    * Primary:		True
    * Refresh rate:	143.981 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - DEL DP-0
    * Geometry:		1080 x 1920 at 3840, 0
    * Size:		510 x 287 mm²
    * Primary:		False
    * Refresh rate:	60.0 Hz
    * Subpixel layout:	unknown
* Monitor: 2 - DEL DP-2
    * Geometry:		1920 x 1080 at 0, 598
    * Size:		510 x 287 mm²
    * Primary:		False
    * Refresh rate:	60.0 Hz
    * Subpixel layout:	unknown

**Comment by Davidy22** [comment]
The prior behavior of the -e flag created a [security vulnerability](https://security.snyk.io/vuln/SNYK-PYTHON-GUAKE-2386334) that is resolvable by not allowing -e to execute in existing tabs.

**Comment by Davidy22** [comment]
Oh actually I see the double tab thing, can make it hold on making an extra tab with -n and -e specified togethor but for now you should also be able to resolve this by dropping the -n from lines with a command

**Comment by bennybenjaman** [comment]
Worked great everything starts as usual now.

For anyone that needs it, here the corrected startup script.


#!/usr/bin/zsh
sleep 6
/usr/bin/guake &
sleep 2
guake --hide --rename-tab="Term1"
guake --new-tab=" " -r "Term2"
guake -n " " -r "Term3"
guake -n " " -r "Term4"
guake -n " " -r "Term5"
guake -ne "/usr/bin/sh -c /home/anon/scripts/tmux-log-diagnostic" -r "HtopLogs"
guake -ne "/usr/bin/sh -c /home/anon/scripts/tmux-network-diagnostic-enp3s0" -r "enp3s0"
guake -ne "/usr/bin/sh -c /home/anon/scripts/tmux-network-diagnostic-enp4s0" -r "enp4s0"
guake -ne "/usr/bin/sh -c /usr/bin/ssh pi@192.168.123.5" -r "vv3"
guake -ne "/usr/bin/ssh anon@192.168.147.16" -r "sds"
guake -ne "/usr/bin/ssh anon@192.168.101.21" -r "xvf"
guake -ne "/usr/bin/ssh root@192.168.152.100" -r "rrr"
guake -ne "/usr/bin/ssh root@192.168.20.1" -r "sss"
guake -ne "/usr/bin/irssi" -r "irssi"
guake -s 0

**Comment by bennybenjaman** [comment]
Dropping -n was the fix. Thanks for your help

**Comment by Davidy22** [comment]
Executing commands via instructions from any shell was a vulnerability that potentially allowed execution of undesirable commands by a malicious actor in a terminal with escalated privileges. The command now by default opens a new tab to run commands in and there are no plans to reintroduce the previous behavior, as that would reintroduce the security problem.
