### ISSUE TITLE
PPA not working on Ubuntu 22.04

### ISSUE THREAD

**Issue by alanmcg** [Guake/guake#2104]
The ppa at ppa:linuxuprising/guake doesn't yet seem to have a release file for Ubuntu 22.04 LTS "Jammy".

**Comment by nmay231** [comment]
I don't know if it's needed anymore because it's included in `http://us.archive.ubuntu.com/ubuntu/ jammy universe`.

**Comment by alanmcg** [comment]
Great, thank you! It seems to work well also :)
