### ISSUE TITLE
Tab names lost after restart

### ISSUE THREAD

**Issue by esteban-aliverti** [Guake/guake#2105]
This could be a duplicate of #2072, but in there @Davidy22 stated that this should be treated as a separate issue. So here I am reporting it :)

Ever since I upgraded to Pop!_OS 22.04 (from 21.10), Guake started to forget about the name of the tabs. I have normally around 12 open tabs and I set the name of each of them manually. Whenever I reboot, Guake is started (I have it configured to launch on system start) and all the tabs are correctly restored except for their names. 
This is also happening without a reboot, but by simply closing Guake and starting it again.

**Expected behavior**

When Guake starts, the names of the tabs used in a previous session should be restored.

**Actual behavior**

When the tabs are restored, they all have the default title "Terminal"

**To Reproduce**

1. Start Guake
2. Create a second tab
3. Set the name of the tabs
4. Quit Guake
5. The 2 tabs are restored, but the names are not

-------------------------------------------------------------------------------

Guake Version:		3.8.5

Vte Version:		0.68.0

Vte Runtime Version:	0.68.0

--------------------------------------------------
GTK+ Version:		3.24.33

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: pop

--------------------------------------------------
Display: :1

RGBA visual: True

Composited: True

* Monitor: 0 - DEL DP-2-1
    * Geometry:		2560 x 1440 at 0, 0
    * Size:		597 x 336 mm²
    * Primary:		True
    * Refresh rate:	59.95 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - SHP eDP-1
    * Geometry:		1920 x 1200 at 335, 1440
    * Size:		336 x 210 mm²
    * Primary:		False
    * Refresh rate:	59.95 Hz
    * Subpixel layout:	unknown

**Comment by esteban-aliverti** [comment]
I tried with `3.9.1.dev12` and I think this issue is no longer present there.

**Comment by Davidy22** [comment]
Closing because reporter no longer experiences the issue

**Comment by AhmedBHameed** [comment]
I have the same issue here
pop os: Pop!_OS 22.04 LTS

**Comment by pongraczi** [comment]
Same problem in Linux Mint 21.1 Vera 64-bit, up to date in 13/01/2023.  
Guake version: 3.8.5

**Comment by pongraczi** [comment]
Using Ubuntu PPA, version 3.9.0 seems working as expected.

**Comment by sbruinsje** [comment]
I am experiencing this issue on:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.5 LTS
Release:	22.04
Codename:	jammy
```

After every restart the tabs are restored but the names are not.

**Comment by eborgbjerg** [comment]
Same as reported by sbruinsje.
