### ISSUE TITLE
Opening a new tab resets the zoom level/

### ISSUE THREAD

**Issue by tejaskale** [Guake/guake#2109]
**Describe the bug**
- Zoom a guake window to something other than the default zoom level
- Open a new tab

**Expected behavior**

The new tab opens at the same zoom level as the previous tab.

**Actual behavior**

Zoom resets to the default

**To Reproduce**

See above

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:		3.9.0

Vte Version:		0.64.2

Vte Runtime Version:	0.64.2

--------------------------------------------------
GTK+ Version:		3.24.30

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: ubuntu

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - XWAYLAND5
    * Geometry:		1920 x 1080 % 2 at 1920, 0
    * Size:		600 x 340 mm²
    * Primary:		True
    * Refresh rate:	59.980000000000004 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - XWAYLAND0
    * Geometry:		1920 x 1080 % 2 at 0, 0
    * Size:		310 x 170 mm²
    * Primary:		False
    * Refresh rate:	59.980000000000004 Hz
    * Subpixel layout:	unknown

**Comment by hwennnn** [comment]
Encountered this problem as well!

**Comment by Lowrida** [comment]
Is this fixed?
