### ISSUE TITLE
libnotify 8.0 not compatible with Guake

### ISSUE THREAD

**Issue by IvoMajic** [Guake/guake#2110]
**Describe the bug**

After upgrading libnotify to 8.0 Guake no longer starts, downgrading to the latest 7.X fixes the issue.

**Expected behavior**

Guake runs successfully

**Actual behavior**

`Guake not running, starting it
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.10/site-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3.10/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/guake/main.py", line 473, in main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
  File "/usr/lib/python3.10/site-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3.10/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.10/site-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.10/site-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3.10/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/guake", line 33, in <module>
    sys.exit(load_entry_point('guake==3.9.1.dev0', 'console_scripts', 'guake')())
  File "/usr/lib/python3.10/site-packages/guake/main.py", line 648, in exec_main
    if not main():
  File "/usr/lib/python3.10/site-packages/guake/main.py", line 487, in main
    from guake.guake_app import Guake
  File "/usr/lib/python3.10/site-packages/guake/guake_app.py", line 49, in <module>
    from guake import notifier
  File "/usr/lib/python3.10/site-packages/guake/notifier.py", line 23, in <module>
    gi.require_version("Notify", "0.7")
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Notify not available for version 0.7`

**To Reproduce**

Install libnotify 8.0

-------------------------------------------------------------------------------

Please run `$ guake --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting. And make sure you run the command **OUTSIDE** the Guake.

<details><summary>$ guake --support</summary>

Guake Version:		3.9.1.dev0

Vte Version:		0.68.0

Vte Runtime Version:	0.68.0

--------------------------------------------------
GTK+ Version:		3.24.34

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: gnome

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - XWAYLAND0
    * Geometry:		2560 x 1440 at 0, 0
    * Size:		600 x 340 mm²
    * Primary:		True
    * Refresh rate:	59.912 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - XWAYLAND1
    * Geometry:		1920 x 1200 at 376, 1440
    * Size:		300 x 190 mm²
    * Primary:		False
    * Refresh rate:	59.962 Hz
    * Subpixel layout:	unknown

**Comment by ksdrummer** [comment]
Same here

**Comment by Trit34** [comment]
Hi! A member of the Hardware.fr (HFR) forum noticed this line:

```
File "/usr/lib/python3.10/site-packages/guake/notifier.py", line 23, in
gi.require_version("Notify", "0.7")
```

and proposes to edit this ligne by replacing the `0.7` value by `0.8` in the quoted file as a workaround/fix.

**Comment by hartmark** [comment]
[Trit34](https://github.com/Trit34)'s fix worked perfectly for me.

**Comment by joonhyuk** [comment]
+1 here (arch)
and fixed now.
Thanks Trit34!

**Comment by raniaamina** [comment]
It works!
Thanks for saving my workflow :")

**Comment by bugtracker2019** [comment]
Thx for the tip!

**Comment by Trit34** [comment]
> +1 here (arch) and fixed now. Thanks Trit34!

Well, thanks to Elbarto, who is the one who has proposed this fix. I reported it to him already.

**Comment by joekm** [comment]
> Hi! A member of the Hardware.fr (HFR) forum noticed this line:
> 
> ```
> File "/usr/lib/python3.10/site-packages/guake/notifier.py", line 23, in
> gi.require_version("Notify", "0.7")
> ```
> 
> and [proposes to edit this ligne](https://forum.hardware.fr/hfr/OSAlternatifs/Installation/nouveaute-stabilite-simplicite-sujet_37691_445.htm#t1476903) by replacing the `0.7` value by `0.8` in the quoted file as a workaround/fix.

I knew if I checked the forums I'd find someone had likely figured out where to make the "notify" edit.  Thanks :)

**Comment by ghostdevv** [comment]
Worked perfectly!

**Comment by ismaail** [comment]
The new upgrade of **libnotify** to `0.8.1` crashes Guake again,

solution: revert back to `gi.require_version("Notify", "0.7")` in `/usr/lib/python3.10/site-packages/guake/notifier.py`

**Comment by Isegrimm666** [comment]
Solved: ---> [https://github.com/Guake/guake/issues/2113#issuecomment-1186826591](https://github.com/Guake/guake/issues/2113#issuecomment-1186826591)

**Comment by Davidy22** [comment]
I'm looking up context and from [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1015006) report it seems like debian has resolved this on their end? Does anyone other than @Isegrimm666 find that latest packages in the debian repos resolve this issue without the workaround?

**Comment by Trit34** [comment]
> I'm looking up context and from [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1015006) report it seems like debian has resolved this on their end? Does anyone other than @Isegrimm666 find that latest packages in the debian repos resolve this issue without the workaround?

Libnotify itself was updated and version 0.8.1 does not break softwares needing a 0.7 version anymore, so the trick to edit the `/usr/lib/python3.10/site-packages/guake/notifier.py` file is not needed either (as long as you have libnotify 0.8.1 installed, not 0.8.0). I’m on Arch and Guake works well, now.

**Comment by Davidy22** [comment]
I suspect the issue was actually a packaging error and not actually to do with the 0.8 release. Regardless, closing because I believe this was a distro issue that is now resolved.

**Comment by Trit34** [comment]
> I suspect the issue was actually a packaging error and not actually to do with the 0.8 release.

You’re wrong: [it really was a bug coming from libnotify 0.8](https://gitlab.gnome.org/GNOME/libnotify/-/issues/27), not a distro/packaging-related.

**Comment by joekm** [comment]
Yea, once libnotify updated again, the issue went away and, if you tweaked the python script, you need to put it back the way you found it ;)  (I.E. change 0.8 back to 0.7).
