### ISSUE TITLE
Guake crashing after update to  3.9.1

### ISSUE THREAD

**Issue by carloshimura** [Guake/guake#2113]
After updating Guake to the latest version, I am not being able anymore to start it. I am getting this error:

$ guake

Guake not running, starting it
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.10/site-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3.10/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

I have also seen others with the same issue, but the solutions on this issue did not succeed: [Issue 2108](https://github.com/Guake/guake/issues/2108)

I'm currently using arch linux with kernel 5.15.54-1-lts

$ uname -r

5.15.54-1-lts

Here is my guake support information

$ guake --support
<details><summary>$ guake --support</summary>

Guake Version:		3.9.1.dev0

Vte Version:		0.68.0

Vte Runtime Version:	0.68.0

--------------------------------------------------
GTK+ Version:		3.24.34

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: gnome

--------------------------------------------------
Display: :1

RGBA visual: True

Composited: True

* Monitor: 0 - SDC DP-2
    * Geometry:		2560 x 1440 at 0, 0
    * Size:		344 x 194 mm²
    * Primary:		True
    * Refresh rate:	60.0 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - AOC HDMI-0
    * Geometry:		2560 x 1440 at 2560, 0
    * Size:		527 x 296 mm²
    * Primary:		False
    * Refresh rate:	59.95 Hz
    * Subpixel layout:	unknown

**Comment by carloshimura** [comment]
Found the problem real problem here: https://github.com/Guake/guake/issues/2110

**Comment by Isegrimm666** [comment]
**Problem was:**

 [https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1015006](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1015006)

**Solution:**
This night libnotify and other affected Packages have been corrected. 

**Method:**
apt update
apt dist-upgrade
init 6

Guake (and other components) now work as usual.

**Tested:**
18. July 2022, 08:30h
