### ISSUE TITLE
Guake doesn't open with a shortcut key on Wayland session

### ISSUE THREAD

**Issue by kahunsyo** [Guake/guake#2127]
**Describe the bug**

On Wayland session, Guake doesn't open sometimes for applications.
Probably, it works fine when focused on an application with XWayland, but not when focused on an application that has native support for Wayland.
It works fine on X session.

**Expected behavior**

It works fine on Wayland.

**Actual behavior**

doesn't open when focused on an application with Wayland.

**To Reproduce**

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:		3.8.5

Vte Version:		0.68.0

Vte Runtime Version:	0.68.0

--------------------------------------------------
GTK+ Version:		3.24.33

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: ubuntu-wayland

--------------------------------------------------
Display: :1

RGBA visual: True

Composited: True

* Monitor: 0 - XWAYLAND1
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		310 x 170 mm²
    * Primary:		True
    * Refresh rate:	59.962 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - XWAYLAND0
    * Geometry:		1920 x 515 at 0, 1080
    * Size:		310 x 80 mm²
    * Primary:		False
    * Refresh rate:	60.039 Hz
    * Subpixel layout:	unknown

**Comment by Davidy22** [comment]
Wayland intentionally prevents global keybindings, you will need to go into your window manager's general settings and attach `guake-toggle` to a global keybinding from there.

**Comment by kahunsyo** [comment]
Thanks.

I was able to solve it easily as below.

## In Ubuntu 22.04

1. Go to Settings -> Keyboard -> Keyboard Shortcuts

2. Add ``guake-toggle`` as a keyboard shortcut
