### ISSUE TITLE
Using the window manager to move Guake window makes it hang

### ISSUE THREAD

**Issue by fstirlitz** [Guake/guake#213]
I use Xfce. I set up xfwm so that I can drag a window while holding the Super key to move it.

Using that feature on the Guake window makes it hang, and I am forced to restart it. Clearly this not what should happen.

**Comment by aichingm** [comment]
This seams to be fixed in the GTK3 version.
Guake can be moved and resized via the window manager (Alt+Left_Drag, Alt+Right_Drag) in Kwin/KDE.

Closing this issue since 8.x.x is not supported anymore.
