### ISSUE TITLE
Guake sometimes does not get focus when it is opened in Ubuntu 12.04

### ISSUE THREAD

**Issue by jinksong** [Guake/guake#216]
As I use an Ubuntu machine for about a couple of weeks without rebooting, Guake suddenly starts not getting focus when it is opened. The symptom is strange : guake terminal is opened and placed on top. But the focus still remains in the previously focused window such as a web browser.

The only temporary solution for this is to close and reopen guake by pressing F12 twice. Then it finally gets focus.

**Comment by mvf4z7** [comment]
Thank you salvadordiaz! This was driving me crazy on my machine.

**Comment by chadsten** [comment]
This worked for me as well.

**Comment by ncsrberg** [comment]
This worked for me as well, I had to install compizconfig-settings-manager first.

Thank you salvadordiaz!

**Comment by solutus** [comment]
@salvadordiaz, thanks a lot!

**Comment by jonathanstrong** [comment]
thank you +1 - if you've left your machine on for weeks, you usually don't want to restart to fix guake focus, but it was still annoying
