### ISSUE TITLE
Hitting default F12 visibility key fails to open Guake window.

### ISSUE THREAD

**Issue by iconoclasthero** [Guake/guake#2161]
- to **report a bug**, please give the following information:

Guake Terminal: 3.9.0
VTE: 0.70.0
VTE runtime: 0.70.0
Gtk: 3.24.34
 OS: Ubuntu 22.10 kinetic
 Kernel: x86_64 Linux 5.19.0-31-generic
 Shell: bash 5.2.2
 DE: GNOME 43.0
 WM: Mutter
 WM Theme: Flat-Remix-Red-Darkest
 GTK Theme: Yaru-red-dark [GTK2/3]
 Icon Theme: noia_kde_100
 Font: Cantarell 11
XDG_CURRENT_DESKTOP=GNOME
default-display-manager: /usr/sbin/gdm3
Kernel info (uname): Linux 5.19.0-31-generic #32-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 20 15:20:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

When certain applications/windows/etc., are open, hitting the toggle-visibility hotkey (default F12) fails to open the Guake window when closed.  Changing the default to ^-Super-F12 does not solve the problem.  Obviously, the expected behavior is to bring up the Guake window.  This does not seem to ever happen if Chrome is the active window but it does with e.g., FileZilla, Deluge, *GNOME Files/Nautilus*, an empty desktop (i.e., no foreground applications)...and it is—predictably—extremely annoying.

**Comment by iconoclasthero** [comment]
Any updates?

**Comment by Davidy22** [comment]
If you are using a wayland desktop, the regular guake shortcut will not work. Instead, you need to go to the GNOME general settings, to the keyboard section and add a custom shortcut that runs the `guake-toggle` command.

**Comment by iconoclasthero** [comment]
👍

**Comment by iconoclasthero** [comment]
PS - This prompted me to update my "version script" so it now includes $XDG_SESSION_TYPE (... and I used sed for the first time!):

$ ver
screenFetch info:
  OS: Ubuntu 22.10 kinetic
  Kernel: x86_64 Linux 5.19.0-31-generic
  Uptime: 16h 19m
  Shell: bash 5.2.2
  Resolution: 1920x2160
  DE: GNOME 43.0
  WM: Mutter
  CPU: Intel Core i5-8350U @ 8x 3.6GHz [40.0°C]
  GPU: Intel Corporation UHD Graphics 620 (rev 07)
  RAM: 5146MiB / 7825MiB

Display info:
  Default-display-manager: /usr/sbin/gdm3
  XDG current desktop=GNOME
  GNOME_setup_display=:1
  XDG session type=wayland
  Wayland display=wayland-0
