### ISSUE TITLE
Save tab names and restore them at reboot

### ISSUE THREAD

**Issue by williamdes** [Guake/guake#2162]
Currently I use the latest release of guake. It's an amazing daily tool !

One big big issue is that I sometime have to reboot my workstation. And yes cool it will summon back my guake tabs.

But not the tabs names.

And I have to rename them on each reboot.

**Comment by carlosromel** [comment]
On my cenario (v3.9.0), Guake saves tab names, but will be nice if it could save last command of each tab as well.

Alternatively, i use a script way to restore Guake sessions.
```
#!/bin/bash

guake --execute-command='guake --rename-current-tab="Parameters";                  top -s'
guake --execute-command='guake --rename-current-tab="Legacy and new background";   echo "Legacy system"'
guake --execute-command='guake --rename-current-tab="Document signers";            echo "First instance"'
```

**Screenshot**
![image](https://user-images.githubusercontent.com/420052/225338117-30eee2c4-86a1-4851-87ad-a7021dc0ea9c.png)

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:		3.9.0

Vte Version:		0.68.0

Vte Runtime Version:	0.68.0

--------------------------------------------------
GTK+ Version:		3.24.33

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: ubuntu

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - GSM HDMI-2
    * Geometry:		1920 x 1080 at 1600, 0
    * Size:		510 x 290 mm²
    * Primary:		True
    * Refresh rate:	60.0 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - GSM VGA-1
    * Geometry:		1600 x 900 at 0, 180
    * Size:		443 x 249 mm²
    * Primary:		False
    * Refresh rate:	60.0 Hz
    * Subpixel layout:	unknown
* Monitor: 2 - OEM HDMI-3
    * Geometry:		1600 x 900 at 3520, 180
    * Size:		432 x 238 mm²
    * Primary:		False
    * Refresh rate:	60.0 Hz
    * Subpixel layout:	unknown

**Comment by williamdes** [comment]
I use `3.9.0` too and the tab names are not saved

<details><summary>$ guake --support</summary>

Guake Version:		3.9.0

Vte Version:		0.70.3

Vte Runtime Version:	0.70.3

--------------------------------------------------
GTK+ Version:		3.24.36

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: lightdm-xsession

--------------------------------------------------
Display: :0.0

RGBA visual: True

Composited: True

* Monitor: 0 - CMN eDP-1
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		381 x 214 mm²
    * Primary:		True
    * Refresh rate:	60.007 Hz
    * Subpixel layout:	unknown

**Comment by carlosromel** [comment]
![image](https://user-images.githubusercontent.com/420052/225349194-3b4d1899-9ffb-4b38-8dd5-e5a043ba0549.png)

**Comment by paynalton** [comment]
Same problem. 

Label is in session.json

`{
    "schema_version": 2,
    "timestamp": 1681327688,
    "workspace": {
        "0": [
            [
                {
                    "panes": [
                        {
                            "type": "term",
                            "directory": "/home/paynalton/Proyectos/sodigital/imatch",
                            "custom_colors": {
                                "fg_color": null,
                                "bg_color": null,
                                "palette": null
                            }
                        }
                    ],
                    "label": "imatch",
                    "custom_label_set": true
                }
            ]
        ]
    }`

But label name is ignored on guake init

![Captura de pantalla de 2023-04-12 13-38-15](https://user-images.githubusercontent.com/5710791/231566427-0d472102-846b-47bd-bcf6-1c5734c7f40f.png)

**Comment by Davidy22** [comment]
Tab names are being retained for me, what do the preferences window general and main window tabs look like for the people experiencing this? Might also just be already fixed in repo and I need to make a release.

![image](https://user-images.githubusercontent.com/872968/237044064-0b2ef084-7aee-498d-a450-bbe83de0d605.png)
![image](https://user-images.githubusercontent.com/872968/237044094-73bf7a0c-1772-41a1-9c7f-359c78d41ca8.png)

**Comment by williamdes** [comment]
> Tab names are being retained for me, what do the preferences window general and main window tabs look like for the people experiencing this? Might also just be already fixed in repo and I need to make a release.

Well, I had temporarily switched to the i3 window manager: https://i3wm.org/
And noticed the tab names where kept

I am now using xfce, and the tab names I had are kept. Not sure if there is some saving bug somehere.
Also, maybe it's about shutdown saving because my laptop dies out of battery most of the time and gives no chance to the program to save the tab names.

And previously I was using cinnamon as a desktop manager and had the same issue.


Can you check how the code manages the saving of tab names ?

**Comment by williamdes** [comment]
For now, it looks like it's fixed now 🎉
