### ISSUE TITLE
Not opening with F12 key in desktop window

### ISSUE THREAD

**Issue by ali124ali** [Guake/guake#2165]
#994 
guake does not drop down with F12 when i am in desktop window(ubuntu 22.04).

**Comment by Davidy22** [comment]
Does [sebaxtian's guide](https://github.com/Guake/guake/issues/994#issuecomment-1426608634) not resolve the issue for you?

**Comment by ali124ali** [comment]
Thanke you so much.
It solved my problem.🙃

**Comment by ali124ali** [comment]
> Does [sebaxtian's guide](https://github.com/Guake/guake/issues/994#issuecomment-1426608634) not resolve the issue for you?

Thank you so much.
This solved my problem.
🙃
