### ISSUE TITLE
Guake not reappearing in Debian 12 (testing) - Gnome when pressing F12

### ISSUE THREAD

**Issue by Rochelly** [Guake/guake#2169]
**Describe the bug**

In Debian 12 (testing) - Gnome, after launching Guake, it does not reappear when pressing F12.

**Expected behavior**

Guake should appear and disappear when pressing F12.

**Actual behavior**

When pressing F12 to make Guake reappear, it does not show up, and the mouse pointer icon remains in a loading state.

**To Reproduce**

Use Debian 12 with Gnome.
Launch Guake.
Press F12 to hide Guake.
Press F12 again to make Guake reappear.

**Note**: The issue can be worked around by adding a shortcut with the "guake -t" command.
<details><summary>$ guake --support</summary>

Guake Version:		3.9.0

Vte Version:		0.70.3

Vte Runtime Version:	0.70.3

--------------------------------------------------
GTK+ Version:		3.24.37

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: gnome

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - XWAYLAND0
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		508 x 286 mm²
    * Primary:		True
    * Refresh rate:	59.962 Hz
    * Subpixel layout:	unknown

**Comment by Davidy22** [comment]
Individual programs can't assign global hotkeys as part of an intentional design decision in wayland. The stated workaround is the recommended way to do this in now in wayland.
