### ISSUE TITLE
F12 does't work inside of Files/Windows/Folder

### ISSUE THREAD

**Issue by asyba** [Guake/guake#2189]
**Describe the bug**

If Im in a Folder/Files/Windows and click F12 it does't show up, if Im on desktop, chrome, etc it works

**Expected behavior**

Open Guake terminal always when pressing F12

**Actual behavior**

Does't work when focus on a Folder Window.

**To Reproduce**

Open Files and press F12

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:		3.8.5

Vte Version:		0.68.0

Vte Runtime Version:	0.68.0

--------------------------------------------------
GTK+ Version:		3.24.33

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: ubuntu

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - XWAYLAND7
    * Geometry:		2560 x 1440 at 0, 0
    * Size:		600 x 340 mm²
    * Primary:		True
    * Refresh rate:	59.912 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - XWAYLAND0
    * Geometry:		1920 x 1080 at 2560, 0
    * Size:		480 x 270 mm²
    * Primary:		False
    * Refresh rate:	59.962 Hz
    * Subpixel layout:	unknown

**Comment by enomado** [comment]
The same after Arch Linux updated on KDE 6.

Look there is some event bubbling on WM level, that prevents event to be sended in global guake's event-handler

**Comment by enomado** [comment]
https://github.com/Guake/guake/issues/492#issuecomment-119075514

**Comment by Davidy22** [comment]
Set the keyboard shortcut in your window manager's keyboard settings to `guake-toggle` or `guake -t` instead of doing it in Guake, as per what @enomado linked

**Comment by enomado** [comment]
BTW this happens in wayland

**Comment by dxps** [comment]
@Davidy22 Thanks! I can confirm that it works. 
In a Zorin OS 17.2, before setting that global keyboard shortcut, if Firefox was active, hitting F12 opened the Dev Tools. Now it always toggle Guake, as expected.
