### ISSUE TITLE
Dropdown terminal doesn't work

### ISSUE THREAD

**Issue by DarthSett** [Guake/guake#2221]
Dropdown hotkey doesn't work as expected. It works when I have vsCode open in the front, or when i have the dropdown open and I need to close the dropdown terminal, but on the desktop or when some other applications like mozilla firefox is in the front, it would not be working. I am using Ubuntu 22.04 LTS 

It used to work fine just before the new years. I don't know if its an update that was released recently that messed it up.

<details><summary>$ guake --support</summary>

Guake Version:		3.10

Vte Version:		0.68.0

Vte Runtime Version:	0.68.0

--------------------------------------------------
GTK+ Version:		3.24.33

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: ubuntu

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - XWAYLAND0
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		310 x 170 mm²
    * Primary:		True
    * Refresh rate:	59.962 Hz
    * Subpixel layout:	unknown

**Comment by welhoilija** [comment]
There hasn't been an update in a while, and for me the exact same setup works pretty well. 

Could it be that the hotkey you are using is reserved for Firefox or Ubuntu?

**Comment by DarthSett** [comment]
@welhoilija  I thought about that and changed the hotkey. Still its behaving in the same way.

**Comment by DarthSett** [comment]
I implemented a workaround for now where I went to the linux settings and added a shortcut to there to show/hide guake.

**Comment by kunicmarko20** [comment]
`guake toggle` worked! thanks for the idea @DarthSett, this "solves" it.
