### ISSUE TITLE
[feature] Run GUI app in Guake Tab

### ISSUE THREAD

**Issue by dror-g** [Guake/guake#2224]
Is it possible to run a graphical app, i.e web browser, as a Guake tab?  
  
Would be very useful I think. Fast switching from terminal tabs to it and back, having an app always on, taking it to other screens/desktops.. endless possibilities!   
  
Going over Guake code I believe the key challenge is having an app nested inside a Gtk window?  
  
Thanks for an amazing tool, been using it for decades!

**Comment by novaTopFlex** [comment]
The Guake terminal emulator was mainly intended to be a terminal emulator for GNOME Desktop setups. Having a multi-purpose application is not generally considered acceptable in the GNOME community, unlike in the KDE Plasma community that you may be mistaking GNOME for.
***
I would like to see a separate drop-down for graphical application and web browser support, but not as part of the Guake terminal.

**Comment by dror-g** [comment]
It's true, I was never into adhering to philosophies that made great software, and am at fault.
And while I dislike KDE, I do see a trend in terminal environments becoming more feature rich than before - 
From the shell itself becoming more "capable" (Fish, zsh), to the terminals themselves handling images, graphics, videos, multiplexing (which is actually Guake, innit?) and such.

One could even say Guake is a bit "behind the times" at this point.
Another would say "It's a tool and it should do what I want, not the other way around".

**Comment by Davidy22** [comment]
This would probably be a different program entirely from what guake is and isn't on the forseeable roadmap. Would most likely be a different, separate program.
