### ISSUE TITLE
Guake need best integration Wayland

### ISSUE THREAD

**Issue by maykel535** [Guake/guake#2234]
I love guake in GNOME and yakuake in KDE plasma.

Yakuake was update in kde plasma.

Guake will need a hard hand for wayland and have a better updated look

**Comment by novaTopFlex** [comment]
Currently, Wayland integration in the Guake terminal, and various other desktop programs for the matter, is often difficult to implement. I would recommend falling back on X11 (Xorg) systems. If your distribution ships as a Wayland-only distro, I would advise you to discover X11-based solutions and your problem may be less relevant as Guake integrates best on the legacy compositor.

**Comment by Davidy22** [comment]
Improved behaviour on wayland is a good thing, but closing this issue as this description doesn't provide a particularly actionable report
