### ISSUE TITLE
The running process goes to sleep after 30 seconds

### ISSUE THREAD

**Issue by joo0ne** [Guake/guake#2247]
If you start a process in guake and hide it, the running process runs for about 30 seconds and falls asleep.

You can visually check it using mplayer. You need to start playing the video with the mplayer command and hide guake. After half a minute the video will stop.

This is clearly related to hiding guake, because if you don't hide it, then everything works as it should.

-------------------------------------------------------------------------------
<details><summary>$ guake --support</summary>

Guake Version:          3.10

Vte Version:            0.75.91

Vte Runtime Version:    0.75.91

--------------------------------------------------
GTK+ Version:           3.24.41

GDK Backend:            <GdkX11.X11Display

--------------------------------------------------
Desktop Session: lightdm-xsession

--------------------------------------------------
Display: :0.0

RGBA visual: True

Composited: True

* Monitor: 0 - CMT DP-2
    * Geometry:         2560 x 1440 at 1920, 0
    * Size:             598 x 336 mm²
    * Primary:          True
    * Refresh rate:     74.998 Hz
    * Subpixel layout:  unknown
* Monitor: 1 - PHL DP-0
    * Geometry:         1920 x 1080 at 0, 177
    * Size:             527 x 296 mm²
    * Primary:          False
    * Refresh rate:     74.97200000000001 Hz
    * Subpixel layout:  unknown

**Comment by egmontkob** [comment]
This is a known bug in vte 0.75.91, fixed in 0.75.92.

I assume you're on Debian testing, you might want to replace your libvte-2.91-0 and related packages from unstable.

**Comment by joo0ne** [comment]
> I assume you're on Debian testing, you might want to replace your libvte-2.91-0 and related packages from unstable.

Thank you. Updating libvte helped.
