### ISSUE TITLE
Add "Start automatically at login" setting in guake's Preferences

### ISSUE THREAD

**Issue by gsemet** [Guake/guake#251]
Add an option in panel: autostart at session login" to easily set the guake autostart at login (when the machine power up).

Guake could be still added in gnome session start, but having an option in panel is still easier.

Action: copy the autostart desktop file in ./config/autostart

**Comment by Stibbons** [comment]
If you want this feature, please vote on [FeatHub](https://feathub.com/Guake/guake)

**Comment by Firerouge** [comment]
Unless I'm mistaken, this was implemented and should be closed.

**Comment by gsemet** [comment]
Indeed !
