### ISSUE TITLE
Test on various linux

### ISSUE THREAD

**Issue by gsemet** [Guake/guake#260]
Test: 
- Ubuntu 12.04 2D
- Ubuntu 13.10 3D
- Fluxbox
- Ubuntu Mint / Cinamon
- RedHat
- xubuntu

In both "Stay on top" and "Hide of focu loss" enabled and disabled

**Comment by Thetoxicarcade** [comment]
I've got similar errors, and a floating point exception, on Fedora. 
![screenshot from 2015-01-17 22 31 19](https://cloud.githubusercontent.com/assets/4575799/5791533/d6bd9e6e-9e98-11e4-98ac-19daf616ee52.png)
