### ISSUE TITLE
After hitting F12 repeatadly, guake is no longer painted on screen

### ISSUE THREAD

**Issue by Pilsburgh** [Guake/guake#266]
After hitting F12 several times rather quickly, guake is no longer painted on screen and only displays a white box where guake should be. 

Bug occured on Ubuntu 13.10 and the version of guake that is in the Ubuntu repository. (0.4.4)

<b>Guake Visible</b>
![guakeerror](https://f.cloud.github.com/assets/2728459/2241621/d0b35688-9cd9-11e3-8f52-4b9d0bd830a7.png)

<b>Guake not Visible</b>
![guakeerrorcomparison](https://f.cloud.github.com/assets/2728459/2241622/d59fc5be-9cd9-11e3-92cc-d09701851975.png)

**Comment by mosteo** [comment]
This happens sporadically to me in Ubuntu 15.04 with version:

    $ wajig policy guake
    guake:
      Installed: 0.5.0-2

**Comment by cj8scrambler** [comment]
I've been running 0.7.2 for 2 months and have not seen this happen any more.

**Comment by Stibbons** [comment]
great :)

**Comment by AlexAtkinson** [comment]
Hey. Seeing this issue for several weeks now. Running guake 0.7.2 on Kubuntu 15.10. Thanks.

**Comment by mosteo** [comment]
Same thing, just today I experienced it for the first time on plain Ubuntu desktop 15.10.

**Comment by Stibbons** [comment]
I see it from time to time... it's an old bug...

**Comment by feridmovsumov** [comment]
I have the same issue. I think it occurs when RAM is %100

**Comment by untra** [comment]
same for me.

**Comment by sshishov** [comment]
When it will be fixed? I have already 0.8.4 version and this problem is still reproducible

**Comment by ilix** [comment]
Confirmed, the issue is still around in 0.8.4. Please let me know if I can help somehow by sending logs or testing something.

**Comment by Stibbons** [comment]
I don't want to spend time on this matter, since I am rewriting the software from scratch, and this is a corner case. Just don't let the button hold too long until guake is ported to gtk3

**Comment by ilix** [comment]
@Stibbons Thank you for getting back to quickly. Glad to hear you are working on a fresh rewrite, I really love guake! :-)

**Comment by sshishov** [comment]
Stibbons! Cool thanks for updates!

**Comment by mkrishtopa** [comment]
ubuntu 14.04, guake 0.4.4
same shit, just lost few tabs. Seems this happens when laptop out of memory and started to swap. Please fix, I really love guake and use it for few years.

**Comment by ArtStepanyuk** [comment]
Getting same issue no matter which hotkey for opening a console, issue started to appear recently

WM awesome
distro Arch

**Comment by DannyMexen** [comment]
Just ran into this for the first time on Ubuntu 17.10.

**Comment by pataquets** [comment]
Same here under Trusty, package version: 0.4.4-1ubuntu1 0. Gnome classic.
