### ISSUE TITLE
Build a PPA for latest

### ISSUE THREAD

**Issue by gsemet** [Guake/guake#269]
It could be a good exercice to build an official ubuntu PPA for latest version of guake.

Ideally, the artifact is generated by travis builder (nota: we cannot extract artifacts from travis :( )
- https://launchpad.net/ubuntu/vivid/+source/guake: is from an external author

**Comment by Stibbons** [comment]
This ppa seems to sync release of guake: https://launchpad.net/~webupd8team/+archive/ubuntu/unstable

**Comment by Stibbons** [comment]
This ppa seems to sync release of guake: https://launchpad.net/~webupd8team/+archive/ubuntu/unstable

**Comment by Stibbons** [comment]
This ppa seems to sync release of guake: https://launchpad.net/~webupd8team/+archive/ubuntu/unstable
