### ISSUE TITLE
Ctrl + mouse scroll for fast scroll

### ISSUE THREAD

**Issue by gsemet** [Guake/guake#271]
I like this behavior of my sublime text or eclipse : Ctrl + mouse scroll doubles the speed of the scolling.

**Comment by Stibbons** [comment]
If you want this feature, please vote on [FeatHub](https://feathub.com/Guake/guake)

**Comment by Davidy22** [comment]
The merged pull request effectively resolves this, not bound to ctrl but that's a ui semantics matter
