### ISSUE TITLE
Add (more) colour schemes 

### ISSUE THREAD

**Issue by lightonflux** [Guake/guake#273]
The XFCE Terminal has some nice colour scheme presets, it would be great if Guake could profit from that.

The colour schemes there are now look a bit old (IMHO).
It would also make easy for XFCE User to match the schemes of XFCE-Terminal and Guake, without installing or configuring. 

Here their presets: 

http://git.xfce.org/apps/xfce4-terminal/tree/colorschemes

**Edit**: I guess Guake uses the GtkSourceView XML files. Is there an upstream or does every application ship what they need?

**Comment by varemenos** [comment]
I use the following script to inject a monokai theme to guake:

```
COLORS="#1C1C1D1D1919:#D0D01B1B2424:#A7A7D3D32C2C:#D8D8CFCF6767:#6161B8B8D0D0:#69695A5ABBBB:#D5D538386464:#fefefffffefe:#1C1C1D1D1919:#D0D01B1B2424:#A7A7D3D32C2C:#D8D8CFCF6767:#6161B8B8D0D0:#69695A5ABBBB:#D5D538386464:#fefefffffefe"
FOREGROUND="#F6F6F5F5EEEE"
BACKGROUND="#232325252626"

gconftool-2 -s -t string /apps/guake/style/background/color $BACKGROUND
gconftool-2 -s -t string /apps/guake/style/font/palette $COLORS
gconftool-2 -s -t string /apps/guake/style/font/color $FOREGROUND
```

I'm not entirely sure where those values are stored in the source so I can't add a new Palette but I'm certain it would be pretty easy to do so if you have them.

**Comment by Stibbons** [comment]
Palettes are in src/guake/prefs.py, they are ordered the same than in data/pref.glade (palette_name combobox)

**Comment by varemenos** [comment]
@Stibbons I've sent 2 color palettes and I'm preparing more (if you are willing to accept them), what I wanted to ask though is if there is a way to set the foreground and background colors because most color palettes will look ugly without their proper ones.

**Comment by varemenos** [comment]
I've ported all the [iterm2 color schemes](https://github.com/mbadolato/iTerm2-Color-Schemes) to ones compatible with guake: https://github.com/varemenos/guake-color-palettes

let me know if you are interested in integrating them in guake.

**Comment by Stibbons** [comment]
Of course it would be interesting. However it will be quite hard for the user. I propose the following mutual work:
- you integrate in a single Pull request ( ;) ) all these and prepare a small screen shot of each palette
- I will then modify the preference panel so the user will directly see this picture automatically so he can choose more easily his prefered color scheme.

Of course, we can split the making of these screenshots in half so I can help you if you want.

**Comment by varemenos** [comment]
There is one thing I'd like you to consider before continuing with this. The [current guake palettes](https://github.com/Guake/guake/blob/master/src/guake/prefs.py#L147-L201) don't set the foreground and background color of the terminal which makes most of them look "ugly" (since the colors don't fit). Would you consider adding those 2 values to the palette settings as well? [Here is an example](https://github.com/varemenos/guake-color-palettes/blob/master/palettes/guake-3024-night.sh) of what values are set by the scripts.

**Comment by Stibbons** [comment]
ok, i see why you override /apps/guake/style/[font/background]/color. Ok, let me think on how to deal this this in an elegant fashion :)

**Comment by varemenos** [comment]
Cool, just let me know when to start working on this

**Comment by Stibbons** [comment]
I think it will be pretty simple:
- if palette is splitable in 16 parts, background and foreground will use default settings
- if palette has extra 2 items, foreground and background will be overriden.

Ex: 

# tango
    '#000000000000:#cccc00000000:#4e4e9a9a0606:#c4c4a0a00000:#34346565a4a4:'
    '#757550507b7b:#060698209a9a:#d3d3d7d7cfcf:#555557575353:#efef29292929:'
    '#8a8ae2e23434:#fcfce9e94f4f:#72729f9fcfcf:#adad7f7fa8a8:#3434e2e2e2e2:'
    '#eeeeeeeeecec',

=> 16 parts 

# tango_forced
    '#000000000000:#cccc00000000:#4e4e9a9a0606:#c4c4a0a00000:#34346565a4a4:'
    '#757550507b7b:#060698209a9a:#d3d3d7d7cfcf:#555557575353:#efef29292929:'
    '#8a8ae2e23434:#fcfce9e94f4f:#72729f9fcfcf:#adad7f7fa8a8:#3434e2e2e2e2:'
    '#eeeeeeeeecec:#0000000:#FFFFFFFF"

=> 18 parts :)

I cannot work on this for the moment, but you can start doing screenshots (400x400 would be enough)

**Comment by varemenos** [comment]
Why not just have it always at 18 parts? I can add the missing colors to the current palettes

**Comment by Stibbons** [comment]
I don't know. Do it has sense to let the user change the color and background color on the palette?

**Comment by varemenos** [comment]
I think that the front and background colors should be changed only in custom themes, doesn't that make more sense? Or if the user tries to change any color the palette setting should switch from a named palette to "custom"

**Comment by Stibbons** [comment]
let's have palette with 18 parts. 17th is background and 18th is foreground (font) colors

**Comment by varemenos** [comment]
Could you please check [this branch](https://github.com/varemenos/guake/tree/extra-color-schemes) I've forked from master? I've gone ahead and fixed the old color palettes and loaded all the new ones I've ported from that iterm2 color schemes repository.

**Comment by Stibbons** [comment]
look good. i ve uploaded a version with foreground background readable from palette string. i let you sync with master...

for the screenshots, it should be really small actually, 150x150 only.

**Comment by Stibbons** [comment]
anyway, thank you very much for your work :) feel free to add yourself in the contribution file and in the about dialog

**Comment by varemenos** [comment]
I can't seem to generate a decent screenshot of the color palette table, it seems like some columns are uneven (?). 
![screenshot from 2015-04-12 09-55-01](https://cloud.githubusercontent.com/assets/626343/7104670/1fcc2cbc-e0fa-11e4-92b2-41eea01cc50a.png)

I just realized how annoying it will be to create a screenshot for 100+ color schemes :smile:

**Comment by Stibbons** [comment]
let's forget about screenshot, l'll manage it differently. For me, you can
just prepare your PL

Also, is it possible for you to add tooltip with the meaning on each button
so the user can see which color matches which terminal "object", like I did
for background and font color on the two buttons I've added.

-----
Gaetan


2015-04-12 9:01 GMT+02:00 Adonis K. <notifications@github.com>:

**Comment by varemenos** [comment]
Well, I'm not familiar with python but I will give it a try. I got the diffs from your commits so it will most probably be an easy job. Now I gotta find which colors does what :P

**Comment by Stibbons** [comment]
Just edit prefs.glade or use glade2 to edit it

-----
Gaetan


2015-04-12 11:42 GMT+02:00 Adonis K. <notifications@github.com>:

**Comment by varemenos** [comment]
I've tried searching descriptions for the palette but all I've found are vague descriptions like "Palette color 1", "Palette color 2" etc...

I will try searching a bit more and If I don't find anything better I will just leave them without labels for now

**Comment by Stibbons** [comment]
no pbl
