### ISSUE TITLE
How to disable blinking cursor?

### ISSUE THREAD

**Issue by maximvl** [Guake/guake#276]
Hi, I spent many hours trying to disable cursor blinking in guake, 

```
>gconftool-2 -g /apps/gnome-terminal/profiles/Default/cursor_blink_mode
off
>gconftool-2 -g /desktop/gnome/interface/cursor_blink                  
false
>gsettings get org.gnome.desktop.interface cursor-blink                  
false
>cat ~/.gtkrc-2.0 
gtk-cursor-blink = 0
>cat ~/.gtkrc-3.0 
gtk-cursor-blink = 0
```

Is there any way to turn this annoying blinking off?

**Comment by xaxxon** [comment]
So can you turn off the fucking blinking cursor?  I'm not seeing the option anywhere..

**Comment by Stibbons** [comment]
Just saw this comment that has been deleted "So can you turn off the fucking blinking cursor? I'm not seeing the option anywhere.". So the person is not able to open the pref window + uses a familiar language that remind me the "space vs tab" flameware in "Silicon Valley" TV series. So ridiculous. Next time I see someone using that kind of language, I tell him to go to hell.

**Comment by xaxxon** [comment]
Read the fucking ticket.

**Comment by pypingou** [comment]
@xaxxon  no need to speak like this, it's only putting fuel on fire

**Comment by xaxxon** [comment]
I was fucking joking, since that was the general fucking feel of the thread.

**Comment by xaxxon** [comment]
anyhow, I found it and erased my original comment.  and now I'll erase
these.

**Comment by Stibbons** [comment]
Please uninstall Guake and don't mess us anymore. Thanks

**Comment by xaxxon** [comment]
sudo apt-get install sense-of-humor

**Comment by phil294** [comment]
the cursor-blinking option "use gtk setting+" doesn't seem to work. I have set `gtk-cursor-blink = false` into both `~/.config/gtk-3.0/settings.ini` and `~/.config/gtk-4.0/settings.ini`, restarted and the cursor is still blinking. But anyway, the override setting in the dropdown works just fine.

**Comment by jabbalaci** [comment]
It also disables the blinking:

```
echo -en "\e[2 q"
```

I use fish shell and added to the end of my .bashrc equivalent.
