### ISSUE TITLE
Set Window title to name of active tab

### ISSUE THREAD

**Issue by hillbicks** [Guake/guake#280]
Hey there, 
it seems that the actual window title for guake is always set to Guake!. It would be nice to change the window title from guake to the name of the active tab. Since guake doesn't register as a visible window in the DE, it doesn't bother most people I guess, but I'm trying to interact with keepass and it's autotype function. KeePass uses the window title to identify a programm and therefore it is not possible to identify a tab, since the window title seems to be hardcoded Guake!. 

It would be nice to get such a feature. If you need further information, just let me know. 

Thanks.

**Comment by naodesu** [comment]
Guake's window title can be used by time tracker called arbtt.
It can be used to provide a statistic on how much time you spent working with some program in guake or working with some host using ssh.

http://arbtt.nomeata.de/doc/users_guide/effective-use.html

**Comment by Suor** [comment]
Also using time tracker (my own), meaningful window titles would be great.

**Comment by Stibbons** [comment]
If you want this feature, please vote on [FeatHub](https://feathub.com/Guake/guake)

**Comment by naodesu** [comment]
@Stibbons The list of features is empty, should someone add a new feature or this issue will be imported to feathub?

**Comment by Stibbons** [comment]
yes, add it and put a link to this ticket if you want
