### ISSUE TITLE
F12 not works to hide Guake

### ISSUE THREAD

**Issue by spvkgn** [Guake/guake#281]
I have compiled latest 0.5 and I have this issue - F12 key works to show Guake, but it not works to hide it. I'm using Ubuntu 12.04 with MATE Desktop.

**Comment by mmuruev** [comment]
Just install this one and have this issue.. Works for any other button but F12.

**Comment by oromay** [comment]
same thing for me... F12 wont bind with fresh installed ubuntu 16.04, but it wasn't working with 14.04 either. So annoying.

**Comment by karthicktv** [comment]
Did any one resolve this issue? I click on the Guake terminal and it indicates that it is opened but I can't see it. I pressed F12 too. Please help!
