### ISSUE TITLE
Preferences don't applying from file

### ISSUE THREAD

**Issue by ewancoder** [Guake/guake#286]
I want to store guake prefs (gconf/apps/guake/*) in my dotfiles github repo, but when I do so and reinstall my linux, then clone repo and setup those files already tweaked, then I ran guake and it was not configured, with popup message and tray icon showing (I usually turn them off). Then, when I change any option within preferences window, my git status command shows that all my settings was changed to default. So, where guake actually stores it settings or how can I force it to load settings on startup?

**Comment by dawnofthedev** [comment]
So is it possible or not to store Guake settings in some kind of dotfiles?

**Comment by ewancoder** [comment]
@dawnofthedev I switched to tilda

**Comment by Stibbons** [comment]
Using gconf is indeed really efficient from the program point of view. I understand your point, as I use a lot dot files stored on GitHub. I don't work on it but will think on a solution for gtk3 version of guake.

**Comment by Stibbons** [comment]
If you want this feature, please vote on [FeatHub](https://feathub.com/Guake/guake)
