### ISSUE TITLE
import/export [g|d]conf settings to a file

### ISSUE THREAD

**Issue by gsemet** [Guake/guake#292]
Use case: store settings in a file to easily backup to github repository

**Comment by elgalu** [comment]
What about simply adding `~/.gconf/apps/guake` directory into a github repository? that's not enough?

**Comment by Stibbons** [comment]
Not sure it will work, conf is stored in gconf

**Comment by elgalu** [comment]
Ah ok, so backing up gconf `/apps/guake` and `/schemas/apps/guake` paths recursively should suffice?

**Comment by elgalu** [comment]
i.e. is this correct?

### Backup

    gconftool-2 --dump /apps/guake > apps-guake.xml
    gconftool-2 --dump /schemas/apps/guake > schemas-apps-guake.xml

### Restore

    gconftool-2 --load apps-guake.xml
    gconftool-2 --load schemas-apps-guake.xml

**Comment by Stibbons** [comment]
Give a try. I test it next week

**Comment by bernardolm** [comment]
https://feathub.com/Guake/guake/+14

**Comment by etem** [comment]
> i.e. is this correct?
> Backup
> gconftool-2 --dump /apps/guake > apps-guake.xml
> gconftool-2 --dump /schemas/apps/guake > schemas-apps-guake.xml
> Restore
> gconftool-2 --load apps-guake.xml
> gconftool-2 --load schemas-apps-guake.xml
> 
Doesn't work with Ubuntu 18.04 :(

**Comment by gsemet** [comment]
Guake now use dconf and no more gconf

**Comment by bernardolm** [comment]
Nowadays, with dconf, I have be resolved with this:

```sh
backup_guake () {
    dconf dump /apps/guake/ > ${HOME}/Dropbox/backup_of_my_guake_settings
}

restore_guake () {
    dconf reset -f /apps/guake/
    dconf load /apps/guake/ < ${HOME}/Dropbox/backup_of_my_guake_settings
    # sudo dconf update
}
```

... but I guess it isn't a good solution yet

**Comment by gsemet** [comment]
seems legit :) I would love to have it integrated in the preference panel :)

**Comment by mlouielu** [comment]
This should be done by #1517 (using dconf)
