### ISSUE TITLE
Tighter integration with gnome-shell

### ISSUE THREAD

**Issue by viccuad** [Guake/guake#304]
I have come by this gnome-shell extension: [https://github.com/zzrough/gs-extensions-drop-down-terminal](https://github.com/zzrough/gs-extensions-drop-down-terminal) which provides a quake-like terminal also, and the animation is pretty smooth.

Is it possible to implement something like this in guake?

thanks in advance

**Comment by kwill** [comment]
Duplicate of https://github.com/Guake/guake/issues/701 ?

**Comment by Stibbons** [comment]
If you want this feature, please vote on [FeatHub](https://feathub.com/Guake/guake)
