### ISSUE TITLE
Remap left and right click functions 

### ISSUE THREAD

**Issue by navpap1029** [Guake/guake#315]
Hi, 
I am new to GITHUB, PYTHON and GUAKE too. 
so excuse me if this is not the right place to post this.
I am using an HP elitebook with trackball (but no middle button as thinkpad, fyi), 

I am looking for a feature as in putty for copy, paste.
Left (double) click -> select and copy (current word)
Left (triple) click ->  select and copy (current line)
Right click -> paste

It would be really good, if anyone would get this known to me?

**Comment by emedentsii** [comment]
Maybe, somebody can advice me workaround for right click using Quake?

**Comment by Gerrit-K** [comment]
Sorry for digging up this corpse, but in my opinion, using the middle instead of the right button is *not* a solution to the original issue. Would it be possible to let guake pass the right click to the underlying shell (e.g. for `tmux` bindings)?
