### ISSUE TITLE
Workspace-specific guake

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#32]
Workspace-specific guake http://guake.org/ticket/543
Reported by:    PietroB     Owned by:   somebody
Priority:   major   Milestone:  0.5.0
Component:  guake   Version:    0.4.4
Keywords:       Cc:     me@…
Description

I just discovered guake, and I felt in love with it: it's nice and fast (and well documented Python code too!).

But I have another love: workspaces. And it clearly makes no sense that the same shell which I just used to batch rename some songs in my "Free time" workspace comes out in my "University" workspace. I want another one.

Please put an option so that guake can be ran as workspace-specific.

This requires two steps: - guake should not run on all workspaces - when re-run, it should trigger via dbus the existing instance only if it's in the same workspace

Actually, I'm willing to try to produce a patch. But I feel very stupid: looking at guake's code (and glade file!), I wasn't able to understand _how_ it sets its presence on all workscreens.

An alternative, maybe nicer, is that the instance is single, but guake shows different terminals depending on the workspace. Nicer, but probably harder (at least, I would have to dig more in guakes' internals).

**Comment by cikaRadule** [comment]
Hi, guys what has happened with this feature request?
Seems it's dead in the water for more than two years now. :/
I could try to pick it up, but can't seem to find any current work on this issue...

**Comment by Stibbons** [comment]
no found time to work on it. Would be part of next rework of guake with gtk3, but it does not have advanced that much sadly :(

**Comment by toobaz** [comment]
I have been using my version modified with workspaces until recently, but it diverged since long, not sure when I'll find the time to rebase. Anyway, it still had some bugs (apart from the fact that the functionality could not be switched on/off).

**Comment by cikaRadule** [comment]
Is there any chance I can take a look at your work, at least to try to make it run on my machine?
And if possible to try to see if it can be prepared for some future releases...

**Comment by Stibbons** [comment]
work has not much advanced... there are two attempt on (guake3 and gtk3 branches). But you can rebase on master and submit a pull request on the current version

**Comment by toobaz** [comment]
@cikaRadule see #820

**Comment by cikaRadule** [comment]
@toobaz thanks, I'll take a look and hopefully manage to make some progress. I'll leave status update here....

**Comment by AlexWayfer** [comment]
Some updates? :sweat:

**Comment by candoz** [comment]
I want to believe

**Comment by Stibbons** [comment]
I unplan this feature, no time to work on it. I am open to pull request for some that wants to dig it :)

**Comment by helix84** [comment]
See also: #604 (could help back this feature)
