### ISSUE TITLE
Guake's config can't be save

### ISSUE THREAD

**Issue by xfight0** [Guake/guake#322]
When I restart my computer after I configured guake, the guake's config that I saved before restarting is lost.
But configure the guake by root user can make config saved.
OS info: Ubuntu 14.04 LTS 64bit.

**Comment by n3ziniuka5** [comment]
I had the same issue. This may happen if at first you tried to run guake as root (autostart).
Now in `~/.gconf/apps/guake` some subdirectories might be owned by root. `chown` the whole `~/.gconf/apps/guake` to your user and group and only start guake as your user.

**Comment by Stibbons** [comment]
good catch

**Comment by addicted2sounds** [comment]
I have the same problem. However, chowning setting folder doesn't help. It's really nice alternative for standart terminal, but this issue is critical for me

**Comment by addicted2sounds** [comment]
strange thing, but I was able to edit terminal setting only trhough global config editor. Program settings are not saved anyway. FYI I owned all mentioned config folder just in case

**Comment by Sajjadhosn** [comment]
@n3ziniuka5 your solution solved my problem. Thanks a lot!
FYI, I had to run the chown recursively on the mentioned folder:
sudo chown -R username:groups ~/.gconf/apps/guake

**Comment by oranges13** [comment]
This is occuring for me in guake 0.7.2 on Xubuntu 15.10

The general settings are saved, but the shell settings are never saved.

**Comment by MEGApixel23** [comment]
@Sajjadhosn your solution worked on Ubuntu 16.04. Thanks!

**Comment by Stibbons** [comment]
can you update the readme please?
