### ISSUE TITLE
Guake loses focus after renaming tab

### ISSUE THREAD

**Issue by selivan** [Guake/guake#324]
Guake version: 0.4.4
OS: Ubuntu 13.04
WM: xfwm4(XFCE)

Steps to reproduce:
* Open guake
* Press "Rename tab" key (Ctrl+Shift+F2 in my setup)
* Type new tab name and press Enter
* Guake is opened, but focus is in other window

**Comment by Stibbons** [comment]
I can clearly reproduce it. Renaming a tab add a mess in focus order, so the terminal is no more focussed automatically when switching to the tab, but only after a rename throught the UI (no pbl with the guake -r command line).

**Comment by Stibbons** [comment]
Fixed in HEAD
