### ISSUE TITLE
Move Tabs

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#35]
Move Tabs  http://guake.org/ticket/527
Reported by:    anasalkouz  Owned by:   somebody
Priority:   major   Milestone:  0.5.0
Component:  guake   Version:  
Keywords:       Cc:     anasalkouz@…
Description

Can you add a small feature to your awesome appliction, that lets you move tabs

**Comment by murarisumit** [comment]
How to move tabs, I wasn't able to find, how to do this.. ?

**Comment by pypingou** [comment]
You can move them by the mouse or with the keyboard if you compile guake from sources.

**Comment by tavisca-smurari** [comment]
I've installed it using apt-get , will I be able to do it?
 I wasn't able to move it mouse and what is keybinding to move using keyboard..?
