### ISSUE TITLE
Port Guake to GTK3

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#36]
Port Guake to GTK3  http://guake.org/ticket/526
Reported by:    legendario  Owned by:   somebody
Priority:   major   Milestone:  0.5.0
Component:  guake   Version:    0.4.3
Keywords:   port, gtk3, gnome3  Cc:  
Description

I like Guake very much and use it on a daily basis. Please, port it to GTK3 in order to help achieve a GTK3 only environment. Since guake intends to be a shell terminal for the Gnome environment, it would be nice to port it to GTK3 too, since the Gnome project is abandoning Gnome version 2.

**Comment by Stibbons** [comment]
Seems like vte binding to python 3 is buggy (see http://stackoverflow.com/questions/14453209/how-to-get-text-from-vte-using-pygobject-gtk3-in-python)

**Comment by Jiehong** [comment]
Hello,

Any news on this feature?

**Comment by Stibbons** [comment]
Still on going, I'll have much time to work on it during christmas vacation ;)

**Comment by Jiehong** [comment]
So nice of you :)

**Comment by shirishag75** [comment]
Any updates as using the latest under Debian I get this in my .xsession-errors file -

```
(guake:2509): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:2509): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:2509): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:2509): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:2509): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:2509): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:2509): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:2509): libglade-WARNING **: unknown attribute `swapped' for <signal>.
```

Have no idea what the above is apart from it's not good. 

Look forward to see that being merged.  That said https://github.com/Guake/guake/tree/gtk3 doesn't seem to have anything happen there :(

**Comment by varemenos** [comment]
is this issue `done` or `wontfix`?

**Comment by Stibbons** [comment]
Replaced by #872
