### ISSUE TITLE
Feature request : Multi-background images

### ISSUE THREAD

**Issue by polygbrl** [Guake/guake#369]
Priority : Low

Using guake a lot, I found myself tired of having the same background-color / image each time I make guake scroll down. While I'm not a customization fan, I must say that it could be nice to select multiple images as backgrounds and make it change from one image to an other each time we make Guake pop.

Could be a fancy idea.

**Comment by ulukyn** [comment]
I have made changes to be able to set the background image using the command line
Here the issue : https://github.com/Guake/guake/issues/695

So, with the new --bgimg, It's possible to bind the F12 key (or another) to a script who will change the background before show Guake. Something like :

`#!/bin/sh`
`# The path of all images to set randomly`
`IMG_PATH="/xxx/xxx"`
`TAB=$(guake -g)`
`SELECTED_IMG=$(ls $IMG_PATH |sort -R |tail -1)`
`echo "$SELECTED_IMG"`
`guake -s $TAB --bgimg="$IMG_PATH/$SELECTED_IMG" --show`

**Comment by Stibbons** [comment]
Backgroup image no more supported

**Comment by cloudsemail** [comment]
Dang.... the background image was one of the coolest things about guake... no chance it'll come back?

**Comment by gsemet** [comment]
I’ll be glad to reintroduce it once vte support it again
