### ISSUE TITLE
Progress bar in python blinking in Guake

### ISSUE THREAD

**Issue by bryant1410** [Guake/guake#419]
I'm having problemass using [progress](https://github.com/verigak/progress/) library in python in Guake terminal, it horribly blinks instead of "progressing".

You need to have python and pip installed.

To check this out, have progress package installed. Then open python:
```shell
$ sudo pip install progress
$ python
```

And then
```python
from progress.bar import Bar
bar = Bar('Processing', max=10000)
for i in range(10000):
    bar.next()
bar.finish()
```

**Comment by Stibbons** [comment]
Work the same in guake and in gnome-terminal. Do'nt know why. Closing

**Comment by bryant1410** [comment]
why this was closed?

**Comment by Stibbons** [comment]
because it is not related to guake. I don't see what we can do
