### ISSUE TITLE
Resizing window height with mouse not works

### ISSUE THREAD

**Issue by spvkgn** [Guake/guake#421]
With 0.5.2 I can't resize guake window height with mouse using MATE Desktop. With 0.5.0 it works well.

**Comment by farzadab** [comment]
This problem is back in 3.0.4.
I'm using Manjaro with GNOME shell version 3.26.2.

**Comment by tduriez** [comment]
I have the same problem in 3.0.5 with GNOME 3.28.1 on Ubuntu 18.04

**Comment by ChrisHaPunkt** [comment]
https://github.com/Guake/guake/issues/1339

**Comment by albuckley** [comment]
Same problem on fresh install of MATE on Ubuntu 18.04.
Latest version of guake 3.0.5-1

**Comment by spvkgn** [comment]
@albuckley 3.0.5 is too old version, latest is 3.6.2. 
You can try to download 3.4.0 .deb from here: https://packages.ubuntu.com/disco/all/guake/download and install manually

**Comment by samehraban** [comment]
Why aren't newer package available in bionic repository?
