### ISSUE TITLE
Paste text - strange behavior

### ISSUE THREAD

**Issue by svyd** [Guake/guake#425]
Guake! 0.4.4
Ubuntu 14.10

When copy text to buffer (from web-site for example) and paste it in guake using Shift+Insert or Right_button_click-Select Paste text appeared betwen 0~ and 1~
For example: If user copies text "You can install it by typing" and inserts it in guake Shift+Insert:

0~You can install it by typing1~ 

In default Terminal it works as expected.

**Comment by mbirth** [comment]
I still have this in Guake 0.8.4-1 (from the WebUpd8 PPA) in Ubuntu 15.10. It is related to Midnight Commander, Ctrl-O and "bracketed paste mode" as explained there:

https://bugs.launchpad.net/ubuntu/+source/vte3/+bug/1506166
https://bugs.launchpad.net/ubuntu/+source/vte/+bug/1350334

**Comment by wiecia** [comment]
Same problem - everything works fine ulness i start MC in Guake. No need to press ctrl+o though, just open and close MC. After closing it, pasting text that was in clipboard gets 0~..~1

Guake 0.8.5, Archlinux current

**Comment by pensnarik** [comment]
Can reproduce this in 0.8.5 in Ubuntu 16.10. It seems to be related to the bracketed paste mode.
