### ISSUE TITLE
window height goes to max

### ISSUE THREAD

**Issue by alipoor90** [Guake/guake#427]
Hi
how to reproduce:
1- set guake to "buttom aligment instead of top alignment"
2- set and "main windows height" to about 30% 
3-enable "show tab bar"
4-click and hold on lower edge of guake tab bar and drag a bit(try to resize guake)
5-"main windows height" goes to max (it thinks you pulled tab bar from top of screen to the end of screen and doesn't take into account that you are in "buttom alignment" mode )

version: guake-0.5.0-3.fc21.x86_64  (fedora 21)

Thanks

**Comment by varemenos** [comment]
I think #513 is a double of this issue

**Comment by dandyd449** [comment]
Anyone know of a work around? This is super annoying.
