### ISSUE TITLE
Tab bar

### ISSUE THREAD

**Issue by ikstlan** [Guake/guake#428]
Hello,

At first thank you for your great work.

I'm now looking solution about working around using many tabs oppened with GUAKE  

Will it be more easy to add simply new tab's bar line below after a screen is ended? 

http://gyazo.com/fbdf6e67a055f643e3b6c66439a8377b

Thank you

**Comment by Davidy22** [comment]
Guake is on the preferred solution now, scrolling left and right tab bar instead of multiplying tab bars or compressing tabs chrome-style. Closing.
