### ISSUE TITLE
How do I get rid of the window border in Guake?

### ISSUE THREAD

**Issue by coolplay** [Guake/guake#430]
Here is an [image](http://i.imgur.com/CzHcP63.jpg) showing this annoying problem. I digged into the source code without figuring out a solution. It seems that [someone](http://www.reddit.com/r/archlinux/comments/2knh2i/how_do_i_get_rid_of_the_window_border_in_guake/) has encountered the same issue without promising reply. Hope to find a way out. I think the guake.glade file is the place, but am not familiar with that stuff.

**Comment by stevelacy** [comment]
I'd also like to see at least an option (or config at compile time) to remove All borders.

**Comment by Stibbons** [comment]
It should be an option, or even better, remove all border by default if this doesn't impact user 'experience'.

**Comment by anywhim** [comment]
+1

**Comment by juancarloscruz** [comment]
+1 
I'd love an option to hide any borders.

**Comment by Chumba** [comment]
+1, the only thing missing from this great tool

**Comment by dakt** [comment]
+1

**Comment by dakt** [comment]
+1

**Comment by jarlopez** [comment]
+1

**Comment by CodeSammich** [comment]
+1

**Comment by borislt** [comment]
+1
Absolutely need a way to remove that bottom border. It's ugly

**Comment by Legendin** [comment]
+1
I'm not familiar with glade/gtk, but let me know if there's anything I can do to help with this.

**Comment by joaokamun** [comment]
+1

**Comment by worm2fed** [comment]
I fix this issue by editing /usr/share/guake/guake.glade

You can set False at every resize option is <widget class="GtkVPaned" id="resizer">

**Comment by georgesamy** [comment]
+1

**Comment by jarlopez** [comment]
@Stibbons this has been solved by commit 9d32e4 which is a merge of a pull request I submitted with a fix for this. The fix introduces a "Show Resizer" in the Appearance|General section of Guake Preferences.

**Comment by Davidy22** [comment]
Solved by both @jarlopez's pr and the switch to gtk3. Closing
