### ISSUE TITLE
toggling visibility leaves blank lines

### ISSUE THREAD

**Issue by qq1693129601** [Guake/guake#438]
archlinux gnome
before:
![screenshot from 2015-01-07 14 29 35](https://cloud.githubusercontent.com/assets/3761211/5641822/71c975c6-967a-11e4-80ac-fbc88da06ca9.png)

after:
![screenshot from 2015-01-07 14 29 39](https://cloud.githubusercontent.com/assets/3761211/5641827/86c15944-967a-11e4-8daf-29cd00013322.png)

**Comment by manoevis** [comment]
for me it scrolls up for one line each time and I need ctrl+l to get my prompt back

**Comment by qq1693129601** [comment]
@manoevis it scrolls up random lines for me

**Comment by manoevis** [comment]
maybe it's related, how could I investigate this? any help? thanks :+1:

**Comment by Stibbons** [comment]
I would be glad to have more information. I use guake everyday and of course always doing hide/unhide and I don't have this behavior.

**Comment by qq1693129601** [comment]
@Stibbons 
System info:
Linux localhost 3.17.6-1-ARCH #1 SMP PREEMPT Sun Dec 7 23:43:32 UTC 2014 x86_64 GNU/Linux
gnome 3.14.3
Guake! 0.5.2

**Comment by manoevis** [comment]
I had 3.18.1 kernel Ubuntu 14.10 Intel HD Graphics with Mesa10.5 drivers. Guake 0.6.0

**Comment by fprawits** [comment]
Just found this open issue, the following issues seem to be duplicates, so there are more people affected:
[#832](https://github.com/Guake/guake/issues/832l)
[#784](https://github.com/Guake/guake/issues/784)

**Comment by Davidy22** [comment]
A rewrite was done, issue no longer appears to occur and no reports submitted since the rewrite, closing.
