### ISSUE TITLE
Not focused on openning if tab was moved

### ISSUE THREAD

**Issue by adisos** [Guake/guake#441]
Version: 0.6.0

How to reproduce:
1. Open 3 tabs.
2. Move swap 2nd and 3rd tabs.
3. Go to 2nd tab
4. Close and open guake. -> window not focused, we need to click on window to focus this.

**Comment by adisos** [comment]
Any progress?

**Comment by Stibbons** [comment]
Idon't reproduce. Which are your settings?

**Comment by adisos** [comment]
What settings? I fetched last source code from github and reinstalled guake.

My OS Ubuntu 14.04 x64 Unity

Later I'll post a screencast

**Comment by Stibbons** [comment]
I reproduce from time to time. This indeed requires to create a new tab, and then move.
