### ISSUE TITLE
Full screen issues.

### ISSUE THREAD

**Issue by joowh85** [Guake/guake#445]
1. Sometimes console text is gone when showing.
2. Sometimes Texts  shows in random verticality position.

Hum.. I can't found this problem at the code.
What development environment are you guys using?

I uploaded this issue video at the Youtube.

http://www.youtube.com/watch?v=7Pag9kYescA

At 0:50 second in video

**Comment by Thy-Duang** [comment]
I experience the same bug. Every time I hide and show guake while it's on full screen the text goes up about half a screen. When I press a key to write it goes to its desired position.
When I hide and show the terminal one time it goes half of a screen up. When I do it again, the text goes higher and becomes invisible to me. Again - text goes higher.

**Comment by lolihunter** [comment]
I had this same issue - but you can reduce the amount the text jumps up by setting the "Main Window Height" in guake preferences to max. When set to the default (about half), the text always jumps half way up the screen. Setting this to max makes it only jump up one line, which is way less noticeable.
