### ISSUE TITLE
Feature request: Add support for multiple keybindings on the same functionality

### ISSUE THREAD

**Issue by diosney** [Guake/guake#447]
As title says, it could be great if I can bind multiple keys on the same functionality.

A possible use case is when having multiple languages installed and one has had bound the dead grave key, in some languages this key is keyed as "dead grave" but others have it as the backtick.

**Comment by Stibbons** [comment]
I'm closing this ticket. This is clearly a niche feature. I would welcome a PL on this matter, but this would require large among of work to support n binding on one action. 2 may be easy to do, but I leave this as an exercise to contributor
