### ISSUE TITLE
Unset COLORTERM

### ISSUE THREAD

**Issue by dolmen** [Guake/guake#448]
`COLORTERM` is an environment variable set by some terminal emulators such as `gnome-terminal`.
To avoid confusing applications running inside Guake it would be better to clean up `COLORTERM` (or set it to a custom value).

How to reproduce the issue:
- launch `guake` from a shell running in `gnome-terminal`
- `F12`
- from Guake, `echo $COLORTERM` gives `gnome-terminal`

**Comment by Stibbons** [comment]
nice one. Noted for next version
