### ISSUE TITLE
Crashes when toggling on Fedora 21 w/ Gnome 3.14.2

### ISSUE THREAD

**Issue by alexwalterbos** [Guake/guake#449]
### Steps to reproduce
1. Install `guake` from the Fedora repos using `yum`.
1. Run `guake` (from terminal for warnings & error message below).
1. Using F12, toggle the Guake Terminal visibility.

### Desired outcome
Guake, there and ready, in all its glory.

### Actual outcome
Ever since I've upgraded to Fedora 21, Guake crashes when I try to use it.
When starting Guake Terminal from terminal, I get this warning 18 times:

```(guake:4671): libglade-WARNING **: unknown attribute `swapped' for <signal>.```

Guake seems to be running fine in the background, but upon tapping F12 to toggle visibility, Guake crashes with only this message in the terminal:

`Floating point exception (core dumped)`

### System details
| | |
| --- | --- |
| OS | Fedora 21 with Gnome 3.14.2 |
| GPU drivers | RPMFusion `nvidia-akmod`, on `2560x1440` screen |

It seems to affect @Thetoxicarcade too as he reports similar findings [here](https://github.com/Guake/guake/issues/260#issuecomment-70397267) in issue #260

**Comment by pypingou** [comment]
https://admin.fedoraproject.org/updates/guake-0.5.2-1.fc21

**Comment by alexwalterbos** [comment]
@pypingou I can confirm that this is solved in `0.5.2-1.fc21`; I have installed it manually via the link that you provided. Thank you!

**Comment by Stibbons** [comment]
is it fixed in 0.5.2 ? (do I have something to backmerge?)

**Comment by alexwalterbos** [comment]
The pending update, version `0.5.2`, fixed my issue. I'd say it's just a matter of releasing that when testing is finished.

**Comment by pypingou** [comment]
It has already been released ;-)
