### ISSUE TITLE
Guake terminal not opening

### ISSUE THREAD

**Issue by kvsrikanth** [Guake/guake#456]
hi team..

i am a big fan of guake terminal...really love it...
unfortunately after failing to install rabbit VCS...i couldnt able to open Guake terminal though i click on it's icon....installed/uninstalled guake terminal multiple time wid out luck...could you able to advise on this ? Thanks..

**Comment by pypingou** [comment]
did you try running it from a terminal?

**Comment by kvsrikanth** [comment]
Thanks for quick revert...
I tried and got the below error :
Traceback (most recent call last):
  File "/usr/lib/guake/guake.py", line 40, in <module>
    import globalhotkeys
ImportError: /usr/lib/libpython2.7.so.1.0: cannot read file data: Is a directory

googled it for the above issue, and as per suggestions, tried to created symoblic link , run ldconfig
But still the issue persists...pls let me know the resolution..that would be great help... 

     On Friday, 30 January 2015 1:26 AM, Pierre-Yves Chibon <notifications@github.com> wrote:
   

 did you try running it from a terminal?—

**Comment by pypingou** [comment]
How did you install guake?

**Comment by Stibbons** [comment]
Look like and installation issue. Please read the README file.
