### ISSUE TITLE
[Feature Request] "Quick Edit" mode

### ISSUE THREAD

**Issue by teodesian** [Guake/guake#457]
Having used iterm2.app on OSX and cmd.exe on Windows, I'm pretty used to the text I select with the mouse being copied to my paste buffer.  It'd be nice to have a checkbox in guake-preferences to control this sort of behavior.

On windows, right-click in quick edit mode de-selects the text, and pastes the buffer when text is selected.  This too would be a desirable feature.

I am working on a patch to do these things in my fork.

**Comment by Stibbons** [comment]
For me, this is a window manager problem. Mine (metacity) does that automatically in every window on my Ubuntu workstation.

**Comment by teodesian** [comment]
agreed, things like parcellite do the former feature, but the latter is not handled necessarily by any other tool I see.  That said, allowing RMB to be the paste hotkey would do the deed; allowing multiple paste hotkeys might be the proper remedy here.

**Comment by hackel** [comment]
X11/Xorg has automatically copied selected text in any application to the primary selection for literally decades (where do you think Mac and Windows stole the idea from?).  A middle-click will paste it into any input field.  I use this functionality constantly.  Let's not adapt Guake to the poor usage habits of people stuck on proprietary operating systems.

**Comment by Stibbons** [comment]
I would recommend you to set the setting in your window manager that trigger this behavior. There should be one. I close this issue
