### ISSUE TITLE
Fedora - divide by zero errors and evident fix

### ISSUE THREAD

**Issue by Thetoxicarcade** [Guake/guake#458]
I was working on another project in fedora/cinnamon with a broken guake install. Wasn't focused on it. During working on that project, I installed the following packages, that solved guake's errors (which involved dividing by zero??)
```
sudo yum install intltool texi2html texinfo libssl-dev libgmp-dev libmpfr-dev mpc gcc-multilib libgtest-dev
sudo yum install python-devel mpfr-devel gcc-cpp
```
I have no idea what packages are relevant but that fixed my issue.

**Comment by Stibbons** [comment]
Fedora integration issue. Closing

**Comment by pypingou** [comment]
Fedora ??

**Comment by Stibbons** [comment]
installing new package version on the user fedora install fixed this issue. I can't see what we can do for it

**Comment by pypingou** [comment]
I agree we can't do it, but I doubt it comes from Fedora, I have had no problem on Fedora with guake for a long while

**Comment by Stibbons** [comment]
I guess this user had an old version of a package that go update after these yum install
