### ISSUE TITLE
Bad font rendering compared to gnome-terminal

### ISSUE THREAD

**Issue by sumitsahrawat** [Guake/guake#459]
The font rendering looks strange compared to gnome-terminal.

gnome-terminal:

![image](https://cloud.githubusercontent.com/assets/5645741/6096038/0f176f96-afa2-11e4-8919-9de82d67cccd.png)

guake:

![calc2](https://cloud.githubusercontent.com/assets/5645741/6096042/4da8aee6-afa2-11e4-9be8-211263aada90.png)

The rendering for the red font and the bold font is different.
Both using the same font (Inconsolata for Powerline Medium 16pt).

**Comment by Stibbons** [comment]
Thanks for the report

**Comment by sumitsahrawat** [comment]
You're welcome.

I'm new to the project, and would like to contribute. Can you give me a bird's eye view of the source, or tell me where the files relevant to this issue live.

I'll be happy to create a contributing.md from the information you give me.

**Comment by Stibbons** [comment]
Feel free to use .dev.sh to start hacking. Code is in src/guake. Python is pretty easy to use. We use python-vte as terminal emulator

**Comment by Stibbons** [comment]
Closing this ticket since it's pure esthetic, and I think this would requires intervention on python-vte
