### ISSUE TITLE
Tab names not remembered

### ISSUE THREAD

**Issue by david-saracini** [Guake/guake#460]
I'm using Mint 17. Here is uname -a info:

`Linux 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

I'm using Guake! 0.4.4

I psql to access various PostgreSQL databases, and often have multiple tabs open in with a different psql session running in each tab (switching back and forth as needed).  If I exit psql, the "prompt" changes.  for example, when connected it has the db name:

	psql $DB_EX1_PROD
	Border style is 2.
	Pager usage is off.
	psql (9.3.5, server 9.3.3)
	SSL connection (cipher: DHE-RSA-AES256-SHA, bits: 256)
	Type "help" for help.

	prod-db-name=> 

When I `\q' (quit) the session, the prompt changes back to my normal prompt.

`myusername@mycomputername:~$`

At this point, the tab will rename to "myusername@mycomputername"

This is undesirable and I it did not work this way in the past.  Obviously, what I would like is for it to retain the name of the tab.

**Comment by david-saracini** [comment]
I've downloaded and installed "0.6" and this issue has been fixed.

**Comment by Stibbons** [comment]
ok
