### ISSUE TITLE
Guake crashes when F12 pressed

### ISSUE THREAD

**Issue by TheMetMan** [Guake/guake#463]
I am running Guake v0.5.0 installed from portage in Gentoo (have done for ages), but recently in Xfce4 and Mate it crashes when summoned by F12. I have an up to date system running. It only started happening recently (end of December)
Guake starts OK on startup (I put it in the start Applications from the desktop control panel), but when I press F12 it disappears.
So running guake from a terminal without the & at the end so I can see the output I get 12 lines of the following

'(guake:19461): libglade-WARNING **: unknown attribute `swapped' for <signal>.  '

then if I press F12 I get

'Floating point exception'

and Guake disappears.
Very odd.! 
I tried installing it from github and compiling from source, but I cannot get it to run.
Any ideas?

**Comment by Davidy22** [comment]
Guake UI has been ported to GTK3 since this was created, reopen if this still occurs.
