### ISSUE TITLE
Allow setting a maximum size for the tab vte title

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#47]
Allow setting a maximum size for the tab vte title  http://guake.org/ticket/504
Reported by: 	clopez 	Owned by: 	somebody
Priority: 	Fix available 	Milestone: 	0.5.0
Component: 	guake 	Version: 	
Keywords: 	patch, tab, title, vte 	Cc: 	clopez@…
Description

Since #164 guake can display the tab title.

The problem is that as soon as you start digging into the files system, many times the title of each tab grows until you end with all the horizontal space filled by just 4 or 5 tabs.

This is very annoying.

The attached patch adds a new configuration variable that allows to put a limit on how much a table title can grow.

[PATCH] Allow setting a maximum size for the tab titles:

 * Change the value with:
   gconftool-2 --type integer --set /apps/guake/general/max_vte_title_size N

    * if N = 0 disables the maximum size (unlimited)

    * Otherwise cuts the tab titles at the Nth char.

**Comment by Stibbons** [comment]
Hum, still not fixed...

**Comment by krlmlr** [comment]
As a workaround, I have the following override for my title in `.bashrc`:

```
case "$TERM" in
xterm*|rxvt*)
    PROMPT_COMMAND='PS1X=$(pwd | sed -r "s-^$HOME/--;s-^$HOME-~-;s-^(.[^/]*/.).*/-\1.../-")'
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}"'$PS1X'"\a\]$PS1"
    ;;
*)
    ;;
esac
```

It uses the name of the first and last path component in full (stripping `$HOME` if below it), and the first letter of the second path component. Examples:

`$HOME/dir` -> `dir`
`$HOME/some/deep/sub/dir` -> `some/d.../dir`
`/etc` -> `/etc`
