### ISSUE TITLE
Hotkey for moving tabs

### ISSUE THREAD

**Issue by selivan** [Guake/guake#472]
Hello!

It would be very useful to have hotkeys for tab moving: left, right, optionaly - to first and last position.

**Comment by adisos** [comment]
you can set your own shortcuts in preferences
![](http://i.imgur.com/zujce3C.png)

**Comment by Stibbons** [comment]
it has been merged a few days ago on HEAD:)

**Comment by selivan** [comment]
adisos , I meant moving tabs, not between tabs

Stibbons, thank you, I'll check it
