### ISSUE TITLE
Paste from clipboard not working

### ISSUE THREAD

**Issue by slashdash** [Guake/guake#474]
build commit c03b57b29c2cdacdb06773cd551bdd70de639bdd and I can't paste into terminal

**Comment by pypingou** [comment]
ctrl+shift+c/v ? or middle click ?

**Comment by Stibbons** [comment]
I use copy paste every day. Can you describe more precisely what is broken?

**Comment by Stibbons** [comment]
Reproduced similar issue: copy from context menu is broken. Copy on selection works

**Comment by Stibbons** [comment]
Confirmed: fixed
