### ISSUE TITLE
Feature request: Keybinding for exchanging tab positions

### ISSUE THREAD

**Issue by Meistache** [Guake/guake#475]
Hello, I've been using Guake for a month right now and I thought that a harmless, cool addition to the features would be giving an option of shortcut keybinding for changing position between tabs. Since this is already supported through drag-and-drop I just thought it would be okay to suggest it. Cheers!

**Comment by Stibbons** [comment]
you have such a feature in the preference. I have defined Ctrl+Shift+Left/Right to move the current tab left or right
