### ISSUE TITLE
Horizontal alignment issues - left edge of Guake is outside the screen

### ISSUE THREAD

**Issue by karoliina** [Guake/guake#478]
Here's a screenshot of what happened when I rebooted this morning. I had no issues with Guake prior to this. The window width is set to 100%, with horizontal alignment set to center. I'm running Guake 0.5.2 on Manjaro XFCE 0.8.12. The only display I have is my laptop screen, here's the xrandr output:
```
[karo@puffin ~]$ xrandr
Screen 0: minimum 8 x 8, current 1366 x 768, maximum 32767 x 32767
LVDS1 connected 1366x768+0+0 (normal left inverted right x axis y axis) 293mm x 165mm
   1366x768      59.97*+
   1024x768      60.00  
   800x600       60.32    56.25  
   640x480       59.94  
DP1 disconnected (normal left inverted right x axis y axis)
HDMI1 disconnected (normal left inverted right x axis y axis)
VGA2 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
```

I logged out and back in a couple of times, trying to start Guake both automatically on XFCE startup and manually, but the problem persisted. Let me know if you need any additional info about my system to investigate this issue.
![un0fzxh](https://cloud.githubusercontent.com/assets/1027823/6665767/547c1d2c-cbc0-11e4-943b-ab9738664752.png)

**Comment by ivoshm** [comment]
I had similar problem ... but it was resolved by Sunday hotfix of stable Manjaro.

**Comment by karoliina** [comment]
I had installed all the updates yesterday and then rebooted, but looks like another reboot was needed before Guake went back to normal. Weird, but it works now.

**Comment by Stibbons** [comment]
weird indeed...
