### ISSUE TITLE
Issue with shift-ctrl-v / copy / paste in 0.6.0

### ISSUE THREAD

**Issue by danlherman** [Guake/guake#480]
Running Ubuntu 14.04 and shift-ctrl-v and shift-ctrl-c do not seem to be working. The keyboard shortcuts are set properly in the preferences and this worked fine for me in previous versions of Guake.

I can still right-click copy / paste.

**Comment by jschwanebeck** [comment]
Happens for me as well on 14.10, the workaround [here])https://wiki.archlinux.org/index.php/Guake#.27Ctrl.27_keybind_problem) doesn't work.

**Comment by coxbrandon** [comment]
I was facing the same issue.  I ran guake from the command line, and saw the following stacktrace:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/guake/gconfhandler.py", line 345, in reload_accelerators
    self.load_accelerators()
  File "/usr/local/lib/python2.7/dist-packages/guake/gconfhandler.py", line 378, in load_accelerators
    key, mask = gtk.accelerator_parse(gets('move_tab_left'))
TypeError: Gtk.accelerator_parse() argument 1 must be string, not None

So the problem for me was that it was failing on "move_tab_left", and causing every accelerator after that to fail to load.

I changed the "gets" function inside "load_accelerators" to read:
gets = lambda x: "" if not self.client.get_string(LKEY(x)) else self.client.get_string(LKEY(x))

Re-compiled and installed.  Hacky workaround, but copy/paste is working fine for me now!

**Comment by Stibbons** [comment]
The guake schema hasn't been updated. I have uploaded the fix in 0ea78739a9a95c150c8afac6626371bc24d4ddc1. I don't have an environment to test it here. Can you check it? You need to reinstall guake completely (./dev.sh) or install and restart the computer.

**Comment by coxbrandon** [comment]
I have backed out my workaround, applied the fix, and run ./dev.sh.  It has resolved the copy/paste issue for me.

**Comment by danlherman** [comment]
I re-installed guake and it's working for me too!  Thanks!

**Comment by Stibbons** [comment]
thanks a lot guys :)
