### ISSUE TITLE
"Always on Top" windows always steals focus from last focused window when guake hides

### ISSUE THREAD

**Issue by lieryan** [Guake/guake#483]
To reproduce:
1. Start guake and hide it
2. Open two windows of any applications, call them "Window A" and "Window B"
3. Right click on "Window A" title bar: check "Always on Top"
4. Switch Focus to "Window B"
5. Open guake with F12
6. Hide guake with F12

Actual result:
1. Focus is on Window A

Expected result:
1. Focus should be on Window B

This issue is noted on GNOME Shell 3.10.4 on Ubuntu 14.04.

**Comment by Davidy22** [comment]
Did some testing and noticed that this is just the default behavior of always on top, regardless of what program is being minimized. Disagreements with GNOME's defaults should be taken up with the GNOME project.
