### ISSUE TITLE
ctrl+shift+w closing mulitple tabs

### ISSUE THREAD

**Issue by Jonnymcc** [Guake/guake#484]
On Lubuntu 14.04 with Guake 5.02 installed when I use ctrl+shift+w to close a tab, it closes two tabs instead of just one.

**Comment by Stibbons** [comment]
thanks for this report

**Comment by Stibbons** [comment]
not reproduced, I only close only tab on Ctrl+shift+w. Do you have changed the hotkey? Are you on latest HEAD?

**Comment by Jonnymcc** [comment]
I have not changed any hotkeys, I have compiled from source at commit 7fdec8dfa4a70186c66cd527450325d5717e8917. I am also running Lubuntu inside a virtualbox guest on a Windows 7 host.

Steps to reproduce,
1. press F12
2. use ctrl+shift+t to make a new tab
3. press ctrl+shift+w and both tabs are closed
4. press F12
5. repeat step 2 twice so that 3 tabs are now open
6. pres ctrl+shift+w and the two newest tabs are closed at the same time

**Comment by cyrus-** [comment]
I am having this problem as well on Ubuntu 14.10, not in a VM (but running the 4.0RC5 kernel). I did change the close tab hotkey at some point after installing it (recently) but I have reset it to ctrl+shift+w after noticing the problem. This is quite annoying.
