### ISSUE TITLE
Function key shortcuts not working

### ISSUE THREAD

**Issue by kookerus** [Guake/guake#485]
On 3/29/15, I pulled and installed Guake. Now, the only function key shortcut working is F1, which I use to toggle the visibility of Guake. F2-F4 does nothing, and F5-F12 prints a tilde (~) to the terminal.

**Comment by Stibbons** [comment]
That's weird because it works fine on my system :( Which window manager do you have?

**Comment by kookerus** [comment]
I'm using Metacity. I uninstalled the git version, and installed from the ElementaryOS repos, and it only prints a tilde for keys not mapped to shortcuts. Everything else is fine.

Just rebuilt and installed from source, and it works fine. I must have just screwed up my shortcuts.
