### ISSUE TITLE
how to use tmux in Guake?

### ISSUE THREAD

**Issue by ranlei** [Guake/guake#487]

**Comment by pypingou** [comment]
It's really simple, it involves two steps:

1/ start guake
2/ start tmux

:-)
Does it not work for you?

**Comment by ranlei** [comment]
not work,Throw a wrong:
  sessions should be nested with care, unset $TMUX to force

**Comment by Stibbons** [comment]
I confirm it works like a charm. You should already have the "TMUX" environment variable already set.
