### ISSUE TITLE
Problem with writting

### ISSUE THREAD

**Issue by karmeljuk** [Guake/guake#490]
Hello

My OS is Ubuntu 14.04. I have one problem: after migration from another PC guake starts, but I can not write anything to the terminal and window is total clear

Maybe somebody can help me with this problem
![guake](https://cloud.githubusercontent.com/assets/5672886/7040477/7aa3e3e8-ddd8-11e4-8156-228ce06ecb21.png)

**Comment by Stibbons** [comment]
look like the shell doesn't start. Can you check your configuration (preferences panel)?

**Comment by karmeljuk** [comment]
Thank you. I changed *Default interprete* to **/bin/bash** and it works
