### ISSUE TITLE
Tray icon not centered

### ISSUE THREAD

**Issue by nilehmann** [Guake/guake#493]
When the icon is displayed in the message tray the image is not center and it looks a bit ugly beacause is not lined whit the others icons.

Anyways, is there a reason to keep the icon in the message tray? As some people suggest this is a abuse of the spec.

**Comment by Stibbons** [comment]
Yes I can remove it

**Comment by Stibbons** [comment]
can you send a screencapture?

**Comment by kookerus** [comment]
nilehmann may be referring to something like this screencap
![screenshot from 2015-04-18 00 10 16](https://cloud.githubusercontent.com/assets/8160403/7213944/6ca28e8c-e55f-11e4-9fae-2083cba5917e.png)
Granted, my panel is only like 25 pixels, but it's still WAY too big. It isn't harmful, it's not even annoying IMO.

Another screenshot to show how large it is.
![screenshot from 2015-04-18 00 12 25](https://cloud.githubusercontent.com/assets/8160403/7213951/9aa72e5a-e55f-11e4-93df-deb5a0fbc3d0.png)

**Comment by nilehmann** [comment]
The icon left transparent pixel in the bottom of the image. An look a little bit odd between the other icons in the systray. I think this is intentional trying to show that the icon is a dropdown.

![screenshot from 2015-04-18 11-03-03](https://cloud.githubusercontent.com/assets/2400776/7215720/8422fb18-e5ba-11e4-8080-e64898a56de7.png)

I'm using this extension https://extensions.gnome.org/extension/495/topicons/ to put the tray icons in top in gnome 3.16.1.

But I thing that the actual question is why have an icon in the systray. I never interact with it anyways.

**Comment by nilehmann** [comment]
Oooh, I didn't know I could remove the systray icon in the setting. That kind of resolve my problem

**Comment by Stibbons** [comment]
won't fix. Tray icon can be disabled. Gnome 3.16 is not officially supported. If it work with it fine

**Comment by wuxinyumrx** [comment]
gnome 3.18 has same issue.
