### ISSUE TITLE
Double click select does not consider ~ a word character

### ISSUE THREAD

**Issue by rbu** [Guake/guake#497]
Both (Gnome) Terminal and Konsole consider ~ to be a word character when double clicking to select a word. This allows you to quickly select and copy a path where your home directory is replaced by a tilde character.

Double clicking "mail" in Terminal yields:
![double-click-terminal](https://cloud.githubusercontent.com/assets/65913/7201965/e67ddba0-e50d-11e4-89ae-f27267022c14.png)

Wheras double clicking "mail" in Guake yields:
![double-click-guake](https://cloud.githubusercontent.com/assets/65913/7201964/e56007ca-e50d-11e4-862b-6d17504c492e.png)

**Comment by Stibbons** [comment]
Easily fixed: 143efbd80cd3e5abdad3347d35b10ea0dfb0ffb4

**Comment by rbu** [comment]
Yay, thank you so much.

**Comment by jsikorsky** [comment]
User editable key should be /apps/guake/general/word_chars, /schemas/apps/guake/general/word_chars is a schema for this key.
`gconftool-2 --type string --set /apps/guake/general/word_chars -- '-A-Za-z0-9,./?%&#_~'`
