### ISSUE TITLE
Release ordering

### ISSUE THREAD

**Issue by pypingou** [Guake/guake#502]
You tagged a 0.6.0 release and since then you have tagged two ``-rc`` releases which you marked as being ``pre-release``. This is wrong, either do the pre-release first or just do bug fix releases after the 0.6.0, ie: release 0.6.1, 0.6.2... That's what this third digit is for after all ;-)

**Comment by rumpelsepp** [comment]
Yeah. I have flagged to arch linux package out of data. Fortunately they havent updated to 0.6.0 yet.  It's not possible (without bumping epoch) to *update* from 0.6.0 to 0.6.0.rc. So I would prefer if you would just release a 0.6.1, 0.6.2 (as @pypingou pointed out) with the relevant bugfixes and drop the rc ones. :)

**Comment by Stibbons** [comment]
my mistake. I jump to 0.6.1

**Comment by Stibbons** [comment]
I though I would bypass the rc cycle, but there are always last minute fix to do :( 
So it's ok for you if I continue using rc: 0.6.2-rc1, 0.6.2-rc2, ... and then 0.6.2 ?

**Comment by pypingou** [comment]
On Mon, Apr 20, 2015 at 12:53:17AM -0700, Gaetan Semet wrote:
>    I though I would bypass the rc cycle, but there are always last minute fix
>    to do :(
>    So it's ok for you if I continue using rc: 0.6.2-rc1, 0.6.2-rc2, ... and
>    then 0.6.2 ?

As long as we do not go backward, it's fine for me :)

Thanks!

**Comment by rumpelsepp** [comment]
> As long as we do not go backward, it's fine for me :)

:+1: 

Personally I would say "keep it easy". So just bump the patch revision number whenever there is a bugfix release; no need for seperate release candidates here (0.7.1, 0.7.2, …). For minor or major releases rc versions are fine, such as 0.7.0.rc1, 0.8.0.rc1, 1.0.0.rc1.

But as long we do not go backwards everything is fine, tough. :)
