### ISSUE TITLE
Traceback in Quick Open settings

### ISSUE THREAD

**Issue by rumpelsepp** [Guake/guake#503]
See screenshots
![screenshot from 2015-04-20 21-37-25](https://cloud.githubusercontent.com/assets/1961699/7238829/802b7908-e7a5-11e4-9a04-5567cf054a98.png)

![screenshot from 2015-04-20 21-37-16](https://cloud.githubusercontent.com/assets/1961699/7238832/8343dd24-e7a5-11e4-9517-4468199733cd.png)

**Comment by Stibbons** [comment]
This is information. This display you the current pattern supported by this feature:
- python traceback + the regular expression
- line starting by a filename

**Comment by rumpelsepp** [comment]
Ahh. okay. I always thought this was an internal error which was displayed… :)
