### ISSUE TITLE
Backspace and Ctrl+Backspace emit the same (erase) character.

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#51]
Backspace and Ctrl+Backspace emit the same (erase) character.
http://guake.org/ticket/498
Reported by:    mihaid  Owned by:   somebody
Priority:   major   Milestone:  0.5.0
Component:  guake   Version:    0.4.2
Keywords:   ctrl backspace  Cc:  
Description

In most apps (Chrome, Firefox, gedit, eclipse, ..) Ctrl+Backspace deletes the previous word. In guake, there is NO way to maintain the same behavior, because both Backspace and Ctrl+Backspace emit the same character.

Typing Ctrl+V then Backspace: ^?

Actual: Typing Ctrl+V then Ctrl+Backspace: ^?

Expected: Typing Ctrl+V then Ctrl+Backspace: ^H

In the Guake preferences there is a way to change what character Backspace emits, however, there is no way to change it to make it emit different characters for Backspace and Ctrl+Backspace.

Note: In other terminals (xterm, (u)rxvt, kterm) it is possible to set Ctrl+Backspace to delete the previous word by running:

```
stty werase ^H}}}
```

**Comment by SlimeQ** [comment]
this is possible in [terminator](http://superuser.com/questions/296572/using-ctrl-or-alt-and-backspace-to-delete-last-word-in-bash), i see no reason why the same couldn't be accomplished with guake. of course dropdown/persistence functionality is awful on terminator, so i'd rather not make a complete switch :)
