### ISSUE TITLE
window height goes to max (bis)

### ISSUE THREAD

**Issue by Thy-Duang** [Guake/guake#513]
How to reproduce:
-open up terminal
-press fullscreen
-hide terminal
-press fulscreen to get back to small terminal size
then the terminal height is maximized and cannot be changed to any smaller value. The only way to get the size correct is to kill the process and run it again.
The change  introducing it is somewhere between 6.0.1 (does not have this bug) and 0.6.2.rc1. Possibly introduced by 1e2b84c6d713bf186f41ec690c95bf93f5faa05d

**Comment by Stibbons** [comment]
Thanks for the report. I'll work on it on Monday, I cannot do anything this week end. Sad I just prepared a new release 0.7.0. This should be fixed in 0.7.1.

**Comment by Thy-Duang** [comment]
by the way, reproducing this bug on many screens is not so straightforward - one must do a lot of stuff like 'ls -l' (to fill the terminal) show/hide, fullscreen, normal screen size to see that the terminal behaves strangely (appears on random screens, text goes up, resize blocks). On single display it's just these steps.

**Comment by varemenos** [comment]
@Thy-Duang did you by any chance use the shellshape gnome extension?

**Comment by Thy-Duang** [comment]
@adonis never heard of it

2015-05-07 22:51 GMT+02:00 Adonis K. <notifications@github.com>:
