### ISSUE TITLE
Guake width wrong on non-Unity Ubuntu desktop

### ISSUE THREAD

**Issue by hotice** [Guake/guake#517]
When using Guake (0.7.0) on a non-Unity desktop (for instance, in Ubuntu GNOME which uses GNOME Shell instead of Unity), the app assumes I'm somehow using Unity and adds a gap to Guake which doesn't fill the screen 100% horizontally. Here's a screenshot: http://i.imgur.com/cDJhkY9.jpg (notice the space on the right).

And here's the output:
```
$ guake
/usr/lib/python2.7/dist-packages/guake/guake_app.py:1480: GtkWarning: gtk_box_pack: assertion 'child->parent == NULL' failed
  self.mainframe.pack_start(self.mainframe, expand=True, fill=True, padding=0)
correcting window width because of launcher width 17 (from 1920 to 1903)
correcting window width because of launcher width 17 (from 1920 to 1903)
do not set background from user
DBG Window display
DBG: Showing the terminal
correcting window width because of launcher width 17 (from 1920 to 1903)
correcting window width because of launcher width 17 (from 1920 to 1903)
```

Tested in Ubuntu GNOME 15.04, Unity is not installed and /apps/compiz-1/ doesn't exist in dconf so I'm really not sure why Guake does this...

**Comment by hotice** [comment]
I managed to fix this by modifying src/guake/guake_app.py and replacing:
```
        if platform.linux_distribution()[0].lower() == "ubuntu":
```
with:
```
        if os.environ.get('DESKTOP_SESSION') == "ubuntu":
```

Apparently the DESKTOP_SESSION is "ubuntu" when the user is using Unity, but it's different for the other Ubuntu flavors (it's "gnome" for Ubuntu GNOME, "mate" for Ubuntu MATE, "Lubuntu" for Lubuntu, etc.). I'm not sure if this is the best approach, but it works for me :)

**Comment by Seraff** [comment]
I have the same problem. Ubuntu 14.10 + Gnome 3.12.2.

**Comment by Stibbons** [comment]
I moved this code to a dedicated method. It should work on ubuntu 14.10 and 15.04 at least

**Comment by hotice** [comment]
For the commit in which you've fixed this: Ubuntu is very inconsistent when it comes to "DESKTOP_SESSION" naming. For instance, the session name is "Lubuntu" and not "lubuntu" like in your commit. The Xubuntu (Xfce) session is called "xubuntu" (lowercase) and so on. You can try to only detect Unity or get a complete list of what "DESKTOP_SESSION" returns under each desktop environment...

**Comment by Stibbons** [comment]
that's why I used lower() to remove this ambiguity

**Comment by Stibbons** [comment]
I guess that you won't use unity on lubuntu, xubuntu, etc. Only on "ubuntu"

**Comment by hotice** [comment]
Sorry, I noticed that after and removed my comment. I'm not a programmer, I'm just trying to improve what I can in Guake with my limited knowledge. 

Can't the code just detect Unity since the left launcher-specific code is only needed there? Because there are quite a few Ubuntu flavors... your code is missing Xubuntu and Kubuntu for instance and it's easy to figure out if the users runs Unity - only when running Unity, "DESKTOP_SESSION" returns "ubuntu" (for Ubuntu 14.04 and newer at least).

**Comment by hotice** [comment]
Or I may have misunderstood your code, like I said I'm not a programmer. If that's the case, ignore my comment above :)

**Comment by Stibbons** [comment]
I managed to setup a Ubuntu Gnome 15.04 VM and it works :)

**Comment by JSteunou** [comment]
Issue is still here on Ubuntu 15.04 stock install. I tried 0.5.0 which is in 15.04 then 0.7.2 from webupt8 ppa
