### ISSUE TITLE
Preferences icon missing

### ISSUE THREAD

**Issue by hotice** [Guake/guake#518]
(Guake 0.7.0) The Preferences icon is not displayed in the taskbar. This occurs when opening the Preferences via right clicking in Guake terminal and selecting "Preferences".

**Comment by Stibbons** [comment]
Can you restart your PC? I don't reproduce on both Ubuntu 14.04 and 15.04

**Comment by hotice** [comment]
Yes, it still occurs for me, I tried Ubuntu 15.04 with Unity and Xubuntu 15.04, happens in both...

**Comment by varemenos** [comment]
It occurs to me as well, the Guake application icon is fixed though

**Comment by felagund** [comment]
Yes, it happens to me too. When I launch /usr/share/applications/guake-prefs-desktop from nautilus, the icon is shown, so probably something goes wrong when launching preferences from the indicator.

**Comment by tawanda** [comment]
me too 

![image](https://cloud.githubusercontent.com/assets/7323136/8750334/1c411906-2ca7-11e5-9274-ef01a0c5e282.png)

**Comment by Davidy22** [comment]
Bug not present in current version of Guake, closing
