### ISSUE TITLE
Double prompt line after clear screen, hide and show only when in SSH session

### ISSUE THREAD

**Issue by Vizzard** [Guake/guake#520]
Ubuntu 14.10 x64, guake 0.7.0:
Having SSH session opened, clearing screen (one prompt line) and then hide and show guake gives me two prompt lines one under the other (just like i would hit Enter once). 
Only when in SSH session. Local console don't have this issue.
Opposite of #308 i guess :)

**Comment by Stibbons** [comment]
can you describe your use case completely I don't understand how to reproduce it. I don't see any problem with my ssh terminal...

**Comment by Vizzard** [comment]
1. Run guake, obviously :)
2. Connect via SSH to some remote machine.
3. Clear screen with 'clear' command or Ctrl-L shortcut.
- At this point you have one line in terminal
4. Hide guake with shortcut.
5. Show guake with shortcut.
- At this point you have two prompt lines (as if you hit Enter key once).
- Expected: one line (state before hiding guake in point 4)

It won't happen if you dont have 100% height set. I have. Now I see it's related.

Will check later today if it will happen on Ubuntu 15.04 x64 and guake 0.7.0.

**Comment by Stibbons** [comment]
Easier:
- run guake
- set height to 100%
- show/hide/show/hide/show/hide/show/hide/show/hide/show/hide/show/hide/show/hide/
- the terminal slowly goes up :)

**Comment by Vizzard** [comment]
That's #308. I guess it's related but i don't have it when I have SSH connection. Just double prompt I described. It's true for local console though.

**Comment by aichingm** [comment]
Can not be reproduced with current head. Seams to be an issue with an older version of vte.
