### ISSUE TITLE
0.7 not installing system-wide

### ISSUE THREAD

**Issue by presianbg** [Guake/guake#521]
Hello, 

I'm building latest git source on Fedora 21 (up to date) and when I run:
```
PYTHONPATH=src python src/guake/main.py
```
It is starting fine.
After sudo make install and trying to run it :
```
/usr/bin/python2: No module named guake
```

Can you help me ? Thank you in advance.

**Comment by pypingou** [comment]
If you want the RPM to be updated you could just ask for it ;-)
Might be simpler ;-)

**Comment by presianbg** [comment]
@pypingou  I doubt it will be simpler, since the official version in Fedora is still 0.5. So... Is there something that I miss in the installation process?

**Comment by pypingou** [comment]
The official version in Fedora is at 0.6 which is 2 weeks old.

https://admin.fedoraproject.org/updates/guake It is still in updates-testing though

**Comment by presianbg** [comment]
Ok... I've got your point.  But still I'm curious. It's building fine (no errors), since I can run it with :
 PYTHONPATH=src python src/guake/main.py

Why I'm unable to install it system-wide ?

**Comment by pypingou** [comment]
We would need more information to determine this.

**Comment by Stibbons** [comment]
Can you check your lib directory (/usr/lib/python2.7/.../guake) and clean every pyc/pyo there are here

**Comment by presianbg** [comment]
By default It is installing in /usr/local/lib/python2.7/site-packages/guake . Could it be the problem? It this case, ./configure should be run with --prefix=/usr ?

**Comment by Stibbons** [comment]
I had a problem recently because some ghost pyo files were kept in this directory

**Comment by presianbg** [comment]
Okey, building it with  ./configure --prefix=/usr placing the files in /usr/lib/python.... not in /usr/local/... 
Now it's complaining for some libs(globalkeys.so...) which are in /usr/lib64... Copying them in /usr/lib... fixing it all and guake is running OK. So my final question is : How can build it in the right way (placing all  files in /usr/lib64/...) ?

**Comment by Stibbons** [comment]
I actually use ./dev.sh --install on my ubuntu 64 bits without probl...

**Comment by presianbg** [comment]
Okey... Clearly It's for developers. I'm not on that level. Closing this issue. Thank for your time :)
