### ISSUE TITLE
Please consider adding this interface to guake

### ISSUE THREAD

**Issue by Ozzyboshi** [Guake/guake#527]
I'd like to have a new get_gtktab_name interface on guake, this would be useful for Guake indicator. You would allow Guake indicator to select a tab by name and not by index.

More info at 

http://guake-indicator.ozzyboshi.com/issues.html#findtabbynameissue

As you can see It's only 3 lines of code, I would be very happy if you add this 3 lines to guake/dbusiface.py in the next release.

Thanks in advance

**Comment by pypingou** [comment]
Why not make a pull-request? :)

**Comment by Stibbons** [comment]
I didn't knew this project and wonder a lot why did they never contacted us to integrate this into guake directly...

and why don't you have a Github !

Anyway, I don't see any objection about providing this interface to external project, it looks like 2 lines of code to add to a file, let's do it! I let you submit this pull request, on week end I cannot work on Guake unfortunately.

**Comment by Ozzyboshi** [comment]
Actually i tried to contact max ulidtko and asked the same thing some months ago but no response yet.
I have a github: https://github.com/Ozzyboshi/guake-indicator , i opened this branch because my debian sponsor asked to do that, that's why the same project is hosted on launchpad and on github.

Anyway i have some issues with guake version 0.7, for example it seems that get_tab_count() interface is not working anymore but maybe it's just me doing something wrong during the update process, if the bug is confirmed i will open a new issue on github

Thanks a lot to stibbons for your help, if you want I am willing to make a pull-request if you prefer.

**Comment by pypingou** [comment]
Well a pull-request will actually keep the attribution of the change, so it seems like the best approach to me ;-)

**Comment by Stibbons** [comment]
I close this issue. If you need more work from our side, please open a new issue
