### ISSUE TITLE
Retrieve back guake.org

### ISSUE THREAD

**Issue by Stibbons** [Guake/guake#541]
I open this issue to track the problem we have with the guake.org domain. (follows #245).

A person has registered the guake.org domain without contacting anyone from guake project. He now asks for a certain among money to give back the domain. I really count on him to find a more constructive way to contribute to the Guake project.

**Comment by Stibbons** [comment]
Just to share with you his behavior:

> There are more than 300 domains linking to this domain name. Within the hour I can sell this name for $900 or more but if someone would offer me $900 right now I would say no.
>
> I offer this for you for $400 because you need it in your project, I am just trying to be nice.

**Comment by pypingou** [comment]
\cc

**Comment by kookerus** [comment]
Do you really need that specific domain?

**Comment by pypingou** [comment]
you can always do without, but people are used to one domain, google/yahoo&co know about it, so it would be better to get it back, but looks like we won't be able to, so plan b) it is :/

**Comment by Stibbons** [comment]
Maybe be guy will drop the domain if he cannot sell it

**Comment by Stibbons** [comment]
Hello everyone. I've started working on a new design for the official guake website. Can you tell me what you think of it?
Url: http://guake-project.org/

**Comment by pypingou** [comment]
It looks neat!

Just maybe we should use another computer than a mac (if even it runs ubuntu) as it might give a wrong idea to the people not paying attention to the image on the desktop.

**Comment by Stibbons** [comment]
I cannot do to much to hide it is a macbook, just remove the distinctive egde

**Comment by pypingou** [comment]
Use another image maybe?
Where did you find it?

**Comment by Stibbons** [comment]
I welcome to new picture. I've brough it actually, but I can use it on other project.

**Comment by s0r00t** [comment]
As of today, did you manage to get guake.org back?
Else, you might try to contact the registrar (seems to be Tucows).

**Comment by Stibbons** [comment]
yes, I tried to contact the registrar. No reponse.
There is no legal way of retrieving it if the current user does not want.

Let's us guake-project.org from now.

**Comment by dorian-marchal** [comment]
The organization page still point to guake.org :

![capture du 2015-07-06 18 04 27](https://cloud.githubusercontent.com/assets/6225979/8526882/ada263c4-2409-11e5-9090-286f2b8fc8dc.png)

**Comment by Stibbons** [comment]
For a mysterious reason, guake.org is still here.
