### ISSUE TITLE
Close tab keyboard accelerator closes two tabs at a time

### ISSUE THREAD

**Issue by tobz1000** [Guake/guake#548]
When I hit ctrl-shift-w, two tabs close instead of one.

Oddly, if I have the close-prompt enabled, this doesn't happen. I.e. if I say "yes", the first tab closes but the next tab is left alone: no prompt, not closed.

Changing the key combination doesn't seem to change anything.

Here is a python trace of the problem occurring: http://pastebin.com/2g4R7TQ0

I can't see what's triggering the second close tab; I suspect something in the C code?

**Comment by Stibbons** [comment]
Thanks for this interesting report!

**Comment by sohoffice** [comment]
I think it has something to do with xwindow default keybinding. If I change the close tab combination to ctrl-w, it doesn't change anything. But changing it to alt-w, it doesn't close the second tab. So I guess, if you avoid using ctrl-alt-w or ctrl-w, the function itself is fine.

I'm using linuxmint 17 with Cinnamon.

**Comment by npodhornyi** [comment]
I had the same problem with ctrl+D but when I change keys to alt+D it solved my problem too.

**Comment by lisu60** [comment]
My accelerator key is Ctrl+Shift+w. The thing happens when I have ibus running. If I quit ibus, then the keys work well. When ibus running, Ctrl+Shift+w closes two tabs.

**Comment by mart-st-manov** [comment]
Remapping the shortcut does nothing for me. No matter what it is it always closes 2 tabs. I'm using Mint 19.1, the default version is 3.0.5 but even after manually upgrading to 3.6.3 it still happens. I did not have this issue on Ubuntu up to 18.04 when I stopped using it.

**Comment by Davidy22** [comment]
Keyboard shortcut code has been somewhat rewritten in git master. Does this still occur for the affected?

**Comment by Davidy22** [comment]
Closing due to no reply, reopen if still relevant.
