### ISSUE TITLE
Ctrl+D doesn't close tab

### ISSUE THREAD

**Issue by alexwhitman** [Guake/guake#550]
Ctrl+D would normally exit a shell and cause the tab to close.  In 0.7.1 this no longer happens.  Instead `exit` is entered to the shell but the tab doesn't close.  At that point it's then impossible to close the tab or quit Guake entirely requiring the process to be manually killed.

**Comment by Thy-Duang** [comment]
right, Ctrl+D dooms us for another opened tab which we can't get rid of

2015-05-19 13:58 GMT+02:00 Alex Whitman <notifications@github.com>:

**Comment by Stibbons** [comment]
good point!

**Comment by Stibbons** [comment]
good point!

**Comment by Stibbons** [comment]
good point!
