### ISSUE TITLE
Tab freezes and makes Guake unable to close when using exit

### ISSUE THREAD

**Issue by KevinCotrone** [Guake/guake#551]
Whenever I use
```
exit
```

in a tab it used to close the current tab. Now the tab freezes and I'm not able to quit Guake in any of the usual ways.

If I start Guake through another terminal, attempting to run exit results in

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/guake/guake_app.py", line 1085, in on_terminal_exited
    self.delete_tab(self.notebook.page_num(widget), kill=False)
  File "/usr/local/lib/python2.7/dist-packages/guake/guake_app.py", line 1477, in delete_tab
    procs = self.notebook.get_running_fg_processes_tab(pagepos)
  File "/usr/local/lib/python2.7/dist-packages/guake/guake_notebook.py", line 60, in get_running_fg_processes_tab
    fgpid = posix.tcgetpgrp(fdpty)
OSError: [Errno 9] Bad file descriptor
Received window state event: <flags GDK_WINDOW_STATE_STICKY | GDK_WINDOW_STATE_ABOVE of type GdkWindowState>
```

**Comment by Stibbons** [comment]
Fixed by be0c3522c9aa579d60ca9dec9b552054f08c5908

**Comment by Stibbons** [comment]
Released in 0.7.2

**Comment by gsemet** [comment]
Similar behavior seen on 3.0. Fixed in 3.0.5

**Comment by t0mcat1337** [comment]
Having a similar issue with guake 3.0.5 in Ubuntu 18.04... closing one tab with "ctrl+d" or "exit" the tab freezes and guake has to be killed. Running guake from a terminal doesn't show the above error anyway... This is the only output after trying to close a tab:

```
Updated window position: (root_x=67, root_y=27)
order to present and deiconify
Current window position: (root_x=67, root_y=27)
Received window state event: <flags GDK_WINDOW_STATE_STICKY | GDK_WINDOW_STATE_ABOVE | GDK_WINDOW_STATE_FOCUSED of type Gdk.WindowState>
Received window state event: <flags GDK_WINDOW_STATE_STICKY | GDK_WINDOW_STATE_ABOVE | GDK_WINDOW_STATE_FOCUSED | GDK_WINDOW_STATE_TOP_RESIZABLE | GDK_WINDOW_STATE_RIGHT_RESIZABLE | GDK_WINDOW_STATE_BOTTOM_RESIZABLE | GDK_WINDOW_STATE_LEFT_RESIZABLE of type Gdk.WindowState>
Received window state event: <flags GDK_WINDOW_STATE_STICKY | GDK_WINDOW_STATE_ABOVE | GDK_WINDOW_STATE_TOP_RESIZABLE | GDK_WINDOW_STATE_RIGHT_RESIZABLE | GDK_WINDOW_STATE_BOTTOM_RESIZABLE | GDK_WINDOW_STATE_LEFT_RESIZABLE of type Gdk.WindowState>
Received window state event: <flags GDK_WINDOW_STATE_STICKY | GDK_WINDOW_STATE_ABOVE | GDK_WINDOW_STATE_FOCUSED | GDK_WINDOW_STATE_TOP_RESIZABLE | GDK_WINDOW_STATE_RIGHT_RESIZABLE | GDK_WINDOW_STATE_BOTTOM_RESIZABLE | GDK_WINDOW_STATE_LEFT_RESIZABLE of type Gdk.WindowState>
Terminal exited: <terminal.GuakeTerminal object at 0x7f79b5ff7b88 (guake+terminal+GuakeTerminal at 0x3260400)>
```

**Comment by PHLAK** [comment]
I'm having the same problem as @t0mcat1337 described.

**Comment by jelovac** [comment]
Same issue here on Ubuntu 18.04 version 3.0.5-1 installed from Ubuntu repositories.

**Comment by anupamsobti** [comment]
Why isn't this marked Open yet? Same issue on Ubuntu 18.04 with version 3.0.5-1. Shall we open a new issue?

**Comment by gsemet** [comment]
This should be fixed in HEAD

**Comment by PHLAK** [comment]
The issue has already been fixed in Guake, Ubuntu 18.04 includes an old version with the bug still present. See the discussion here: https://bugs.launchpad.net/ubuntu/+source/guake/+bug/1760621

That thread includes the following solution that fixes the issue. Edit line 1420 of `/usr/lib/python3/dist-packages/guake/guake_app.py` and remove one indent. The specific line looks like this:

    self.delete_tab(self.notebook.page_num(widget), kill=False, prompt=False)

**Comment by t0mcat1337** [comment]
Indeed this fixes the issue! 
Thx for the hint

**Comment by komlenic** [comment]
Thanks @PHLAK for the tip.  This fixes the issue perfectly!
