### ISSUE TITLE
Hide tabbar on fullscreen

### ISSUE THREAD

**Issue by sanderboom** [Guake/guake#554]
If I remember correctly this was the previous behavior. 

Running Guake 0.7.0-1 on ArchLinux

**Comment by Stibbons** [comment]
it is probable that i ve change it. need a new settings panel

**Comment by sanderboom** [comment]
Thanks for looking into this!
Keep up the good stuff. Guake is very nice.

**Comment by Davidy22** [comment]
pr resolves the issue, closing
