### ISSUE TITLE
No way to delete key bindings(by default F1--F10 is used by other applications inside terminal)

### ISSUE THREAD

**Issue by CyborTronik** [Guake/guake#555]
No way to remove key bindings from preferences.
So usual a lot of terminal applications use keys F1-F10 (example MC - Midnight commander), so now you are unable to remove key bindings from guake.
My usual scenario is next: 
 - F12 to show/hide terminal (for which is used Guake, btw great app)
 - use `tmux` for screen split
 - often (by needs) use MC

So now you have added these key bindings by default and is not possible to use some of applications that uses these keys from dozen years ago. That's a bit creepy. Rebinding also do trouble because key bindings are used by other apps also and I don't use bindings for guake tabs, no need for that cause I'm using tmux as many of my collegues as well.

So please remove key bindings for tabs by default also add posibility to be able to remove key for other features(!!!not rebinding!!!)

**Comment by Stibbons** [comment]
With latest version you can disable hotkey easily by pressing the backspace key.

**Comment by CyborTronik** [comment]
Thanks
