### ISSUE TITLE
Disabled key bindings still considered

### ISSUE THREAD

**Issue by pypingou** [Guake/guake#556]
Steps to reproduce

* Open the preference window and go to the key bindings
* Select: go to first tab (defaults tp ctrl+F1 here)
* Press backspace to disable it
* Try re-setting it to ctrl+F1

**Comment by Stibbons** [comment]
it doesn't work ?

**Comment by thardev** [comment]
Hello, I checked this issue and as far as I know is a "bad configuration" problem the keybinding (Ctrl+F1) of "go  to first tab" is assigned to "toggle hide on lose focus" also in "guake.schemas" file.

On the other hand, I see that the "hide on lose focus" feature is disabled so the keybind of "toggle hide on lose focus" makes no sense until that feature is working again. 
I will made a PR if you want with the "guake.schemas" file updated, but I'm worrying about to leave the keybind disabled or add a shorcut like "Ctrl+F12"?
