### ISSUE TITLE
Guake systray icon missing in hidpi mode

### ISSUE THREAD

**Issue by anandtrex** [Guake/guake#557]
Guake systray icon missing in hidpi mode on Cinnamon desktop. See attached image.
![guake-missing-systray-icon](https://cloud.githubusercontent.com/assets/1858015/7873827/7c42e630-05a7-11e5-87c8-a4a4173dee2a.png)

**Comment by Stibbons** [comment]
thanks for reporting. What is "hidpi" ?

**Comment by anandtrex** [comment]
On closer inspection, this is happening at both 1680 x 1050 and 2560 x 1440. So I'm thinking this might be related to the desktop rather then the resolution? I'm running ArchLinux with Cinnamon desktop and on both monitors, this happens, even after restarting Cinnamon (after each switch).

**Comment by Stibbons** [comment]
hum... is there a different icon files read at different resolution?

**Comment by anandtrex** [comment]
Ok, so I tried running gauke from commandline (I also tried this with the latest code from github). This is the error I get:
```
INFO:guake.guake_app:Logging configuration complete
/usr/lib/python2.7/site-packages/guake/guake_app.py:192: Warning: gsignal.c:2451: signal 'child-added' is invalid for instance '0x299f3e0' of type 'GtkMenu'
  self.tray_icon.set_menu(menu)
/usr/lib/python2.7/site-packages/guake/guake_app.py:1625: GtkWarning: gtk_box_pack: assertion 'child->parent == NULL' failed
  self.mainframe.pack_start(self.mainframe, expand=True, fill=True, padding=0)
```

To answer your question, from what I've observed with other applications, it *seems* like if icons of the right size aren't present, the program just uses one of the available smaller icons.

**Comment by anandtrex** [comment]
This seems to be fixed now.
