### ISSUE TITLE
Guake won't start on LXDE

### ISSUE THREAD

**Issue by armanx** [Guake/guake#561]
After installing Guake on LXDE (Lubuntu) using the `./dev/.sh` method, I'm getting this error:

```
Installed schema `/schemas/apps/guake/general/focus_if_open' for locale `C'
Traceback (most recent call last):
  File "src/guake/main.py", line 43, in <module>
    from guake.guake_app import Guake
  File "/home/arman/Downloads/guake-master/src/guake/guake_app.py", line 40, in <module>
    import xdg.Exceptions
ImportError: No module named xdg.Exceptions
```

Running `which guake` gives me  `/usr/local/bin/guake`, I can even open the preferences control window, but Guake won't run.

**Comment by Stibbons** [comment]
try ./dev.sh --install to install you env.

you probably needs to install the package {{python-xdg}}

**Comment by Stibbons** [comment]
it other packages are missing, can you tell me which one (remember dev.sh is my installation script, when you are compiling from source, you need to manually install each dependency... most of the time you just try ``apt-get install python-NAMEOFTHEDEPENDENCY``

**Comment by armanx** [comment]
Thank you, installing `python-xdg` and running `./dev.sh --install` fixed it.

**Comment by Stibbons** [comment]
great :)
