### ISSUE TITLE
Guake won't start

### ISSUE THREAD

**Issue by kookerus** [Guake/guake#563]
Running the most recent (as of the time of this post) version of guake's master branch will throw an error saying `No module named keybinder`. Screenshot of trying to run in a terminal below
![error](https://cloud.githubusercontent.com/assets/8160403/8022223/f05aa9c2-0c91-11e5-9a9f-7c938dd66094.png)

**Comment by kookerus** [comment]
I saw the part in README.rst talking about this and felt like a complete idiot, but nothing relevent exists in src/guake, and running dev.sh gives the error above.

**Comment by Stibbons** [comment]
try sudo apt-get install python-keybinder. I have just updated the readme, and dev.sh

**Comment by kookerus** [comment]
Ah, now it works. Thanks!
