### ISSUE TITLE
a-la guake-indicator custom commands

### ISSUE THREAD

**Issue by Stibbons** [Guake/guake#564]
Feature: allow users to define there own commands they often use
This can work like guake-indicator, but not with the same level of customization. The source code is heavily using C code, and reimplement lot of trivial stuff in python world (json parsing, GTK event handling,...)

Inserting guake-indicator custom feature in guake has the following advantage:
- compatible with the "hide on focus loss" mode
- automatically available to the user

I also tend to prefere having a custom xml/json file, so the user can back it up easily, vs an import/export feature that is too heavy to use

Screenshot: http://guake-indicator.ozzyboshi.com/screenshots.html
Related issue: #527

@Ozzyboshi what do you think about this?

**Comment by Ozzyboshi** [comment]
I am very glad that Stibbons deems Guake Indicator a useful and valuable project.
I can rewrite or help rewriting the core of guake-indicator in python, we can take advantage of the current Guake "app indicator" to show some custom commands read from an xml or json configuration file.
Are you planning to let the users write their own xml/json file with a text editor?
We could add a tab on the Guake preferences window to provide a GUI interface but this would be more complex.

Another faster and trouble-free way to achieve this could be to merge a light version of guake indicator into the guake package or just advertise guake-indicator within guake (a link/button in the preferences window?)

Unfortunately when I wrote Guake Indicator I didn't think about the possibility to merge my code inside Guake so I used the C language (my favourite). Furthermode Guake indicator is full of extra stuff customized for my own needs and it's very unlikely that Guake users need all the features.

Right now I am improving the scrollbar management, in my opinion it's a more useful feature, after that we could start developing the custom command features if you want.

**Comment by Stibbons** [comment]
I wanted the custom commands to be directly accessible in the contextual menu inside the terminal. For example, I use "hide on focus loss", it is very useful to hide guake when a command is launched, but you cannot click on something in the indicator area and keep guake open.

Also, people that doesn't use ubuntu might also need such commands, even when they don't have an indicator aera (indicator = ubuntu). Will it work on other platform straight forward (fedora, xfce,...) ?

If you manage to integrate your indicator inside the guake icon (to have only 1 icon), it could be a good start.

The things is users (and I) have some "common" commands to execute quite often. I heavily use "custom start script", but having a menu with the custom command display on an hotkey (Ctrl+Alt+b for instance) right inside the terminal would be a killer feature.

My first thought was to have a simple version of these custom commands, without all the menu editor and so on. I could be done pretty easily. And indeed in a json files (the pref menu only points to this json, with a button to edit this file). Json is simpler to read/write, and indeed rewriting all in python is not so difficult.

I let you work on the scrollarea, I've merged your first PL. I try to have it resized seemlessly when scroll area appears and automatically scrolled. If you want to do more work on it I ll welcome PL with gratitude !

**Comment by Ozzyboshi** [comment]
Ok where do we put the json file?I suggest ~/.guake/guake-custom-command.json 
For now let's put the custom commands on the contextual menu.
For now no directories and subdirectories just plain flat structure

**Comment by pypingou** [comment]
What about ``~/.config`` instead of creating another folder in ``~``?

**Comment by Stibbons** [comment]
I would let the user choose. You can provide by default ~/.config/guake/custom-command.json. I prefere letting the user decide where this file is stored, so he can easily backup it. I am not sure whether this is good or bad for all people, but I like having my dotfiles where I want so I can easily backup them (in a dotfiles project)

**Comment by Ozzyboshi** [comment]
The config hidden directory is more standardized, it should exist in all linux distros (please let me know if not), anyway we can store the file path under the dconf settings al let the user change it

**Comment by Ozzyboshi** [comment]
I tried to write something today... please give a look, i forked the Guake official repo on https://github.com/Ozzyboshi/guake and made some additions.

At startup guake tries to open ~/.config/guake/custom_command.json (it works on my ubuntu but I don't know if the home reference is correct in windows systems).

the json file must be like this
{
 "cmds":[
         "ls","df","ping google.it"
        ]
}

then try to right click on the terminal, you should see the above commands listed after the "Quit" menuitem and if you click on the command it should be automatically executed on Guake terminal.

Next step could be to manage the file name in the dconf settings.
Please let me know if this is what you had in mind, if it works and your comments.

**Comment by Stibbons** [comment]
Look great :) I could be a hidden feature for the moment, but if you have time to add a panel in the settings, with a label to quickly describe how it works and how to change the path (the path should be stored in gconf), with this path by default, it will be good enough for next release.

Please keep "quit" at the bottom of the menu, I think it is pretty common, and add a separator and the new submenu ("Quick commands"?) for example, abrove of "Preferences" items in context menu.

**Comment by Ozzyboshi** [comment]
Glad that you like it.I am fear that my coding style is not appropriate, python is not my favorite language but I'll do my best also for the separator,gconf settings and preferences panel. I'll post a message here when I 'll have something to show.

**Comment by Stibbons** [comment]
you can submit a pl, and I take care of it. Just a bit hard to find time to work on it these days...

**Comment by Ozzyboshi** [comment]
Just pushed a new commit on my personal repository master branch :

1. read path from gconf under apps/guake/general/custom_command_file
I manually created the key on my Laptop by gconf-editor, for now guake doesn't care about the creation
If the file in the gconf-settings is readable and in proper json format it will be read otherwise ~/.config/guake/custom_command.json will be the fallback, if the latter does not exist or it's not in proper json format the command list won't be built.
The value stored in gconf should be a full absolute path.

2. custom commands now moved above the quit menuitem, i am assuming that 'Quit' will be always the last menuitem so i count 2 from the bottom of the list (the Quit menuitem and his separator).
If you are planning to change the guake gladefle with a new context menu without Quit and his separator as the last elements we are in trouble.Maybe is better to look for a Menuitem named Quit and do the math?

3. If there's at least one custom command, a new separator is added on top of the custom command list.

Considerations:
1. Planning to delete the fallback json file (probably it is useless what do you think?)
2. Planning to add some way to allow the user to select the jsonfile (or just tell them to edit and link on the preferences i don't know)
3 I am killing my own project probably :)

**Comment by Stibbons** [comment]
can you create a Pull Request? I ll see what we can do with it for next release.

Indeed, the indicator in the taskbar becames quite duplicate with what you are doing, however you have a complete UI to edit the menu which is not for the moment planned. So for simple command one can edit the json manually, but for more complex use case, guake-indicator will still be useful, I guess.

**Comment by Ozzyboshi** [comment]
@Stibbons do you have something else in mind for this thread or should we close it?

**Comment by jazzmale** [comment]
Hi,
tried to create and set the custom-command.json file like in your example. 
And this doesn't work for me. Havn't got any sub menu in "custom commands".  

Ubuntu 14.4.3
Guake Terminal 0.8.3

**Comment by Ozzyboshi** [comment]
if you give me the custom-command.json file i will look at it

**Comment by jazzmale** [comment]
I inserted as you wrote below, with no changes: 
 ```Ruby
{
 "cmds":[
         "ls","df","ping google.it"
        ]
}
```

**Comment by Ozzyboshi** [comment]
Did you select the right file under Preferences-> TAB General -> Custom command file path?

**Comment by jazzmale** [comment]
**@Ozzyboshi** , sure. yes. 

![screenshot from 2016-01-12 22 43 35](https://cloud.githubusercontent.com/assets/8709470/12276405/452a1552-b97e-11e5-95ed-f0695c0799c9.png)
![screenshot from 2016-01-12 22 43 12](https://cloud.githubusercontent.com/assets/8709470/12276406/452f38fc-b97e-11e5-95f6-94e6dae2a446.png)

**Comment by Ozzyboshi** [comment]
Ok now I remember, the syntax you are using refers to a previous Guake version, to achieve what you want try something like this:

```json
[
    {
        "description": "List all files",
        "cmd": [
            "ls",
            "-ls"
        ]
    }
]
```

This will display a single entry named List all files that execute the command ls with -ls argument.

You can also do some command grouping under a submenu like this

```json
[
    {
        "description": "List all files",
        "cmd": [
            "ls",
            "-ls"
        ]
    },
    {
        "type": "menu",
        "description": "Remote commands",
        "items": [
            {
                "description": "ssh to host",
                "cmd": [
                    "ssh",
                    "hostname"
                ]
            }
        ]
    }
]
```

I think it would be better to add a button on the prefs.glade file that pops out a modal dialogue displaying this examples or (better) a json template to make this feature more accessible to the Guake uers, what do you think @Stibbons ?

@jazzmale Let me know if you solved the problem and sorry for the late answer.

**Comment by jazzmale** [comment]
Thank you. Now it works.

**Comment by skraelings** [comment]
Is it possible to specify I want to pass the current mouse selection as argument?

**Comment by Ozzyboshi** [comment]
do you mean the selected text within the terminal?

**Comment by skraelings** [comment]
yes, pass the text selection as argument

**Comment by Ozzyboshi** [comment]
@skraelings  take a look at https://github.com/Ozzyboshi/Guake , I implemented your feature there.
In order to pass the text selection you must put the '1' value (integer) in the cmds array.
For example


   ```
{
    "description": "File stat",
    "cmd": ["stat",1]
}
```
The above JSON object causes Guake to print "stat + current selection".
If nothing is selected withing the terminal It just issues "stat".
note that 1 is an integer, if you write

` "cmd": ["stat","1"]
`

The command "stat 1" is issued.
The could use the following numbers for other uses for example "stat",2 could print "stat + clipboard paste".

If you are happy with this I could issue a PR to @Stibbons .

**Comment by Stibbons** [comment]
no pbl, can you add some doc in order to explain how this syntax works. There is not "online" help in guake, I guess README is the only place where to explain this feature to the user

**Comment by Ozzyboshi** [comment]
@skraelings any news on this issue?

**Comment by Stibbons** [comment]
Supported
