### ISSUE TITLE
Trim path before quick open

### ISSUE THREAD

**Issue by IanVS** [Guake/guake#569]
Some error reporting formatters I use place some initial spaces in front of a filename for alignment, and guake seems to treat these initial spaces as part of the path.  Is it possible for quake to ignore those spaces?

e.g. this works:
```
▶ echo "/home/ian/test.md" 
/home/ian/test.md
```

But this does not:
```
▶ echo "  /home/ian/test.md"
  /home/ian/test.md
```

**Comment by Stibbons** [comment]
thanks!
