### ISSUE TITLE
Return focus to shell after rename

### ISSUE THREAD

**Issue by abcarroll** [Guake/guake#571]
Just a very minor annoyance, in my particular instance I have "Rename tab" binded to alt+/.
So after pressing alt+/, the rename prompt comes up and, without using the mouse at all, I can type the new name I'd like for my Tab, and press return to rename the tab.

Afterwards, the focus is not returned to the shell but, in my cases, to the window behind Guake.  It just slightly disrupts the flow of things. It would be nice if, immediately after pressing return, focus was returned to the shell prompt if it was already focused there previously.

**Comment by bittorf** [comment]
this is confusing me also.

**Comment by Stibbons** [comment]
Indeed, but this is a mess. Wait for rewrite in gtk3

**Comment by Stibbons** [comment]
not reproduced
