### ISSUE TITLE
Guake Fails to Build: "could not create GladeXML Object"

### ISSUE THREAD

**Issue by zschuessler** [Guake/guake#574]
Attempted to install Guake via three methods: install of stable through software center (v0.4), install of 0.7 through newer repository, and finally building it myself.

The farthest I was able to get (after encountering many issues) was the build to succeed, but attempting to use the `guake` command would result in:

    could not create GladeXML object

Unfortunately I do not have the stack trace, as I purged the package in favor of using Tilda. Wanted to log this error and my environment so this issue was at least known.

Environment (stock install, no other packages) -
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.1
DISTRIB_CODENAME=rebecca
DISTRIB_DESCRIPTION="Linux Mint 17.1 Rebecca"

Should be easy enough to reproduce.

**Comment by Stibbons** [comment]
weird, especially if you installed from software center.... What produces ./dev.sh ?

**Comment by thardev** [comment]
Hello, actually I tested to **install** and/or compile with **./dev.sh**  on the same OS (Linux Mint 17.1 Rebecca), and there's no bad behavior. I tested version from the software center (Guake 0.4.4), Guake 0.7.2 too and Guake 0.8.1. Everything works ok for me, so if you cannot reproduce it anymore @zschuessler maybe it's ok to close this?

**Comment by zschuessler** [comment]
Yeah I was able to get it working after I did a fresh install. Thanks.
