### ISSUE TITLE
Quick Open does not work with dashes

### ISSUE THREAD

**Issue by IanVS** [Guake/guake#576]
If there is a `-` in the filename or path, guake does not recognize the string as a file.  For example:

``` bash
$ touch /home/user/test.txt:1
$ echo /home/user/test.txt:1
/home/user/test.txt:1
$ # ^ This will be underlined and opens on ctrl+click

$ touch /home/user/test-file.txt:1
$ echo /home/user/test-file.txt:1
/home/user/test-file.txt:1
$ # ^ This is not recognized as a file, no underline, no opening.
```

**Comment by pypingou** [comment]
Put the path between quotes

(and it's guake, not quake ;-))

**Comment by IanVS** [comment]
That does not help, unfortunately.

Re: spelling - wish there was a spell checker I could blame that on.

**Comment by pypingou** [comment]
> Re: spelling - wish there was a spell checker I could blame that on.
Old habits die hard :)

**Comment by Stibbons** [comment]
need to update the regular expression in global.py...

**Comment by IanVS** [comment]
Seems to me like QUICK_OPEN_MATCHERS in `terminal.py` is okay, as long as the file does not end in a dash or other non-alphanumeric character.

```
 r"^[a-zA-Z0-9\/\_\-\.\ ]+\.?[a-zA-Z0-9]+\:[0-9]+",
```

Is there another regex somewhere?  I can't find a global.py, and globals.py.in doesn't have any regex that I can see.  I think it was moved to terminal.py in https://github.com/Guake/guake/commit/6101c1bbd2ccc49fb372643b6a39bc2843f8047d

So, what could be causing this regex to fail when encountering dashes?

**Comment by IanVS** [comment]
Regex is definitely okay: https://regex101.com/r/wH7aF6/1

**Comment by IanVS** [comment]
Maybe this is a problem within VTE?

**Comment by IanVS** [comment]
I did what I could to investigate, but I was not able to make a fix.  Any chance someone else could take a look?  Thanks!

**Comment by denis-gonzo** [comment]
Got a fix.
I just edit regexp in guake/terminal.py, put dash at start of range.
old: r"^[a-zA-Z0-9\/\_\-\.\ ]+\.?[a-zA-Z0-9]+\:[0-9]+"
new: r"^[-a-zA-Z0-9\/\_\.\ ]+\.?[a-zA-Z0-9]+\:[0-9]+",

**Comment by Stibbons** [comment]
Can you submit a pull request
