### ISSUE TITLE
Guake doesn't have a PID

### ISSUE THREAD

**Issue by PrimordialHelios** [Guake/guake#580]
Not exactly sure if this is a bug or not, but after starting guake, running `killall guake` or `pidof guake` won't work. Any way to change this behavior?

**Comment by pypingou** [comment]
``
$ ps aux |grep guake
pingou   2533  0.0  0.4 918540 33164 ?        Sl   Jun26   4:31 python2 -m guake.main
``
Like a lot of python program.

Granted this does not change your final question :)
