### ISSUE TITLE
inconsistent languages in menus

### ISSUE THREAD

**Issue by step21** [Guake/guake#581]
So not sure if this is guake or just packaging error - but since some update a while ago, right click menu is mostly in german, 'rename tab' is in English and new tab is "nueva pestana" which is Spanish as far as I know. Is there anyway to change this? The version shown in the --about window is 0.7.2.
This is running on Ubuntu 14.04., with guake installed from the webupd8.org ppa.

**Comment by step21** [comment]
actually does not seem to be a packaging problem ... https://github.com/Guake/guake/blob/master/po/de.po line 114-116 I will fix it and create a pull request, if that is ok?

**Comment by Stibbons** [comment]
ok for me!

**Comment by step21** [comment]
Fixed here https://github.com/step21/guake/commit/24169a604c70b98301345bd084fe8e2cd8518323

**Comment by thardev** [comment]
Hello @Stibbons isn't already fixed? :smiley:

**Comment by Stibbons** [comment]
indeed german has been updated!

**Comment by step21** [comment]
Yeah, was merged some time ago. Though depending on packaging/versions, some people might still notice it.
