### ISSUE TITLE
Guake hides others tray icons in Linux Mint

### ISSUE THREAD

**Issue by andrebrito** [Guake/guake#586]
Hello.

Guake hides others tray icons in Linux Mint, sporadically. If I close Guake (by clicking in the tray icon > close or exit), the trays that were hidden appear.

Using Dell Desktop Optiplex 990 with Linux Mint 17 Quiana (Cinnamon) (or Ubuntu 14.04.1 LTS, Trusty Tahr).

Thanks.

Regards,
Andre.

**Comment by andrebrito** [comment]
Dear @Stibbons 

I'm sorry. I believe this is not a Guake problema. It's a cinnamon or Linux Mint.

Thanks a lot and sorry again.

Regards,
Andre.

**Comment by pypingou** [comment]
Let's close then :)
