### ISSUE TITLE
Add python-keybinder as dependecy

### ISSUE THREAD

**Issue by mont5piques** [Guake/guake#593]
I installed guake on a new system following the classic procedure (configure, make, make install).
No errors noticed.

When launching guake, I had a traceback telling me that keybinder module is not installed.
Installing python-keybinder solved the issue.

**Comment by Stibbons** [comment]
NEWS is already updated with this information. This is a packaging problem. I use "dev.sh" to build guake on ubuntu

**Comment by EifX** [comment]
This dependency is missing in dev.sh

**Comment by chyld** [comment]
After a fresh clone, and install
```
 ./dev.sh --install
```

This was my error
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/guake/main.py", line 43, in <module>
    from guake.guake_app import Guake
  File "/usr/local/lib/python2.7/dist-packages/guake/guake_app.py", line 49, in <module>
    import keybinder
ImportError: No module named keybinder
```

**Comment by thardev** [comment]
Hello @Stibbons :smiley: tell me if I'm wrong, but this is not already added in the **./dev.sh** script?

Code --> https://github.com/Guake/guake/blob/589131ac2383dd871d20dd34a3501717b09039ad/dev.sh#L38

Commit --> https://github.com/Guake/guake/commit/872dfa495ec967ffefb75247bf9235719952c2b6

**Comment by Stibbons** [comment]
yes and in the readme. Normally, the package maintainers are warned
