### ISSUE TITLE
Colors are refreshed after opening a new tab

### ISSUE THREAD

**Issue by rumpelsepp** [Guake/guake#596]
I use [base16 shell](https://github.com/chriskempson/base16-shell) to set my colorscheme in my `.zshrc`. The problem with guake is, that after opening a new tab, the colors in all other open tabs are reloaded and my cursor turns black. 

![color](https://cloud.githubusercontent.com/assets/1961699/9270628/74f5f2c4-4273-11e5-9d6a-e349e9fb250f.gif)

**Comment by ounos** [comment]
:+1:  I suffer by the same bug.

**Comment by Davidy22** [comment]
No longer occurs in current version, last reporting user states is fixed now, closing.
