### ISSUE TITLE
New Tab icon not found and very big tab bar

### ISSUE THREAD

**Issue by Bubu** [Guake/guake#599]
See screenshot: 
![screenshot - 08192015 - 01 42 16 pm](https://cloud.githubusercontent.com/assets/105185/9355342/c820a1f2-4678-11e5-84d0-e5451a345f22.png)

I'm not sure but I guess the two problems are related.

System is Xubuntu 14.04 and I installed guake 0.8.0 from this ppa: https://launchpad.net/~webupd8team/+archive/ubuntu/unstable

**Comment by Bubu** [comment]
Mmh, weird. Their is no reference to the add_tab.png in the current source files. Am I missing something?

**Comment by Ozzyboshi** [comment]
If you look at old git commits you'll find this:

commit c6314aea554ed28780acd45ce4e2dfe8ffdb6c43 (2015-05-15 10:04:45)

In this commit the following lines were removed from the guake_app.py file 

-        ipath = pixmapfile('add_tab.png')
-        self.get_widget('image2').set_from_file(ipath)

I think this is why the icon is missing (I am experiencing same problem on my ubuntu 14.04)
The question is: why @Stibbons  did this? Maybe he wanted to set the image from glade.
Waiting from clarifications from @Stibbons

**Comment by Stibbons** [comment]
indeed, this can be questionnable... I am rewriting everything from the bottom up so I hope to handle it properly in 1.0.0...

**Comment by Bubu** [comment]
Ok, I re-added thse two lines to my local install and the icon does indeed appear again. But unfortunately the huge tab bar remains. Any idea where this is coming from?

**Comment by Ozzyboshi** [comment]
Maybe the tab bar got bigger because a few months ago i added a scrolledwindow and a tabviewport in data/guake.glade.
When I did this I didn't notice visual changes on my ubuntu, can you try deleting this 2 components or using an old guake.glade file and see if something changes?

**Comment by Bubu** [comment]
Yes, that seems indeed to be the case. Using the guake.glade from before this commit 652cd8565b1d52ef1fbce0ece4121ad24ce8e255 the tab bar is back to the old height.

You said you didn't notice any visual change in your config. Can I provide any more debug info why this problem happens on my setup?

**Comment by Ozzyboshi** [comment]
In the next days I will spin up a new virtual machine with XUbuntu 14.04 installed on it and see if i can do something for the glade file (but i really doubt it).
If in the meantime if you have a better solution just tell us. Actually the scrolled window in my opinion is very useful because i work with a lot of open tabs and a low res monitor, it would be a shame removing this feature in my opinion. Maybe @Stibbons has a quick fix for that?

**Comment by Stibbons** [comment]
Indeed, the scrolled panel is good, and it takes quite lot of space. Since I am reworking everything, I don't plan to work on this too much in the near futur...

**Comment by Ozzyboshi** [comment]
@bubu give a look at my new data/guake.glade file and tell me if it's better now

the new glade file is a https://github.com/Ozzyboshi/guake

**Comment by Bubu** [comment]
@Ozzyboshi this fixes the big tab bar problem, yes. 
The missing new tab icon remains though. (But still fixable with the above workaround.) And not having this icon the tab bar is still a few pixels too high but much smaller than before. When the correct icon is found everything works fine.

**Comment by Ozzyboshi** [comment]
I will try to submit a new pull request with the new glade file and the icon, let's see if @Stibbons  will accept it even if he's rewriting the whole project.

**Comment by Stibbons** [comment]
i will certainly :) rewrite takes more time as you can see I have not that much advanced in the rewrite. But since everything will be rewritten, we don't have to take care of maintaining gtk2 and gtk3 code. Just do it for 0.8. I'll take care of syncing the feature set on the long term
