### ISSUE TITLE
Port guake to vte 2.91

### ISSUE THREAD

**Issue by Justinzobel** [Guake/guake#600]

**Comment by Stibbons** [comment]
Since vte 0.29.0, GTK2 is no more supported, and there is no more binding to VTE. There is indeed a threat of the futur of guake on this matter, since GTK2 will one day be deprecated AND the main component of Guake is no more accessible through python, even with GTK3

```
NEWS:

0.29.0
======
- Drop GTK 2 support

```

**Comment by pypingou** [comment]
Closed as in done or wontfix?

**Comment by Stibbons** [comment]
close as "will be done when swiching to gtk3", which I started working on it :)
