### ISSUE TITLE
Is package `python-keybinder` required? 

### ISSUE THREAD

**Issue by sbbird** [Guake/guake#602]
I tried installing via both Ubuntu Software Center and `./dev.sh install` on Ubuntu 14.04. I found guake failed to start because python module `keybinder` is missing. I fixed that by simply installing `python-keybinder`. Is it something should be added into dependency list?

**Comment by sbbird** [comment]
Oh sorry, I didn't realize there is one issue already.

**Comment by Stibbons** [comment]
yes it is now required
