### ISSUE TITLE
"Reset terminal" shortcut

### ISSUE THREAD

**Issue by iammordaty** [Guake/guake#614]
It would be nice to have the ability to assign a keyboard shortcut to "Reset terminal" (#608) menu entry.

**Comment by thardev** [comment]
Hello :smiley:  I've this ready to do the pull request, just one thing before, which default key combination should I put? It's better to leave it empty? I think about something like Ctrl+Alt+R @Stibbons @iammordaty

**Comment by Stibbons** [comment]
why not

**Comment by iammordaty** [comment]
I prefer Ctrl+Shift+L, but I suggest to leave this shortcut unset.
