### ISSUE TITLE
Add setting for dark theme variant

### ISSUE THREAD

**Issue by aleho** [Guake/guake#618]
I know it's too early right now, but I wanted to add this as a feature request nevertheless after reading the release notes for 0.8.1.

With GTK3 there'd be the possibility of using the dark theme variant, which I think might be a great addition to an already dark terminal. Something like:

`Gtk.Settings.get_default().set_property('gtk-application-prefer-dark-theme', True)`

**Comment by FujiMakoto** [comment]
+1

**Comment by Stibbons** [comment]
that for gtk3 port :)

**Comment by Stibbons** [comment]
in gtk3

**Comment by Stibbons** [comment]
If you want this feature, please vote on [FeatHub](https://feathub.com/Guake/guake)

**Comment by Stibbons** [comment]
TODO:
- add "select GTK theme" in pref window
- add "prefere dark theme" in pref window
Change the `_select_gtk_theme` function accordingly

**Comment by Davidy22** [comment]
Guake now has a prefer dark theme checkbox
