### ISSUE TITLE
Unable to set Shell -> Default Interpreter

### ISSUE THREAD

**Issue by fersherr** [Guake/guake#619]
Everytime I select and save (close) the preferences tool, the interpreter info does not save.  When I re-open preferences or open a new tab or restart guake, the '<user shell>' is always selected.

**Comment by lkorba** [comment]
As a workaround for #619 : Unable to set default interpreter you may add to ~/.gconf/apps/guake/general/%gconf.xml
```
        <entry name="default_shell" mtime="1452614719" type="string">
                <stringvalue>/path/to/shell</stringvalue>
        </entry>
```

**Comment by oranges13** [comment]
I added the value suggested by @lkorba and it did not make a difference.

**Comment by iwex** [comment]
Confirm

**Comment by Davidy22** [comment]
Some amount has changed in the code since last report, does still still occur for the affected users?

**Comment by jkiljanski** [comment]
> Some amount has changed in the code since last report, does still still occur for the affected users?

I was following this issue since I have experienced the problem. Now it is gone. I can change and save a chosen shell. Thanks!

**Comment by gsemet** [comment]
So, I close this ticket. Thanks
