### ISSUE TITLE
Guake Drawing Issue Gnome 3.16.3 Arch Linux

### ISSUE THREAD

**Issue by ghost** [Guake/guake#620]
![screenshot from 2015-09-20 22-29-03](https://cloud.githubusercontent.com/assets/13573113/9984596/ce8c08cc-5fe8-11e5-8ace-072b9be8a25d.png)

I am having an issue with drawing issus with Guake in Gnome 3.16.3 on Arch Linux. It worked perfectly with no drawing issues when I first installed it, and now I'm having this issue.

**Comment by Davidy22** [comment]
Guake has been ported to GTK 3, reopen if still relevant.
