### ISSUE TITLE
cannot disable tray icon

### ISSUE THREAD

**Issue by ondrejhajek** [Guake/guake#623]
Gnome Shell 3.14.4
Guake 0.8.1

i have problem with guake in the my gnome shell

i use gnome extension Topicons, but icon for guake is broken there:

![Alt text](http://oi57.tinypic.com/15x21hv.jpg)

anyway, i want to disable this icon, but in guake settings this option is missing

![Alt text](http://oi57.tinypic.com/xnympk.jpg)

**Comment by mrshu** [comment]
@ondrejhajek wouldn't this option be what your locale translates as 'Zobrazit ikonu v oznamovací oblasti'?

**Comment by ondrejhajek** [comment]
@mrshu omg sorry, i'am idiot, i cant believe that i overlooked that option for so many times

**Comment by mrshu** [comment]
@ondrejhajek no problem at all.

Would you mind closing this issue if it is resolved?

**Comment by Stibbons** [comment]
:)
