### ISSUE TITLE
Gnome 3.18.0 problem

### ISSUE THREAD

**Issue by jkubrynski** [Guake/guake#624]
After upgrading to Gnome 3.18 I get such problem with Guake (guake-0.7.2-3.fc23.x86_64):

Sep 27 21:54:47 host.codearte gnome-session[2298]: /usr/lib64/python2.7/site-packages/guake/guake_app.py:1625: GtkWarning: gtk_box_pack: assertion 'child->parent == NULL' failed
Sep 27 21:54:47 host.codearte python2[2679]: detected unhandled Python exception in '/usr/lib64/python2.7/site-packages/guake/main.py'

**Comment by wuxinyumrx** [comment]
same problem.
and text selecting is error.

**Comment by jkubrynski** [comment]
I've just ugraded to Guake 0.8.1 and it works

**Comment by Stibbons** [comment]
great :)
