### ISSUE TITLE
Changing the tab bar color/theme

### ISSUE THREAD

**Issue by cyberalex4life** [Guake/guake#625]
Would be nice if guake would have an option to change the colour of the tab bar. I would prefer a darker colour, but others may like something else.

**Comment by tirkarthi** [comment]
https://github.com/Guake/guake/blob/master/src/guake/guake_app.py#L776 which could be modified to have the color for different states of the first tab and https://github.com/Guake/guake/blob/master/src/guake/guake_app.py#L1531 has the code to add the color to tabs that are created in a guake session. It also needs different colors for different states as in http://www.pygtk.org/pygtk2reference/gtk-constants.html. It also requires a new config in the menu for the tab color at different states and text color for the respective states. I don't know the part where the tab-bar color can be set. I don't know the exact specific type of widget used for tab-bar. Hope it helps. @cyberalex4life

**Comment by Stibbons** [comment]
This would be part of guake 1.0, rewriten in gtk3

**Comment by sebhahn** [comment]
Any plans to implement this feature soon?

**Comment by Stibbons** [comment]
not in a near futur, for personal and professional reason, sadly
