### ISSUE TITLE
Bizarre output when cd within a terminal

### ISSUE THREAD

**Issue by luispabon** [Guake/guake#626]
I'm on master/b500576e83f0c7af253b6e4416fa30a918051693, just did my monthly update to guake and upon guake restart, every time I CD on to any folder, I get this output on the console:

```
[development@localhost ~] cd Projects/guake
]7;file://LuisFujitsuLaptop/%68%6f%6d%65/%64%65%76%65%6c%6f%70%6d%65%6e%74/%50%72%6f%6a%65%63%74%73/%67%75%61%6b%65⏎             [development@localhost ~/P/guake] (master) cd
]7;file://LuisFujitsuLaptop/%68%6f%6d%65/%64%65%76%65%6c%6f%70%6d%65%6e%74⏎                                                      [development@localhost ~] 
```
![image](https://cloud.githubusercontent.com/assets/6388823/10159821/9a0a25a6-6692-11e5-8c17-1a4b612dc6de.png)

Which are urlencoded transcriptions of the folder I just CD into. I'm using fish. Not sure how guake could possibly do it but it started happening with the upgrade.

Stuff:
  * Downgrading however doesn't get rid of the issue.
  * It doesn't happen on gnome terminal.
  * Neither does it on terminator. 
  * Doesn't happen with bash, zsh or sh
  * Previous build I was using without this issue I built from master on Aug the 26th.

**Comment by luispabon** [comment]
It doesn't happen gnome terminal with the same shell, fish.

**Comment by luispabon** [comment]
Neither does it on terminator. Definitely confined within guake.

**Comment by luispabon** [comment]
Previous build I was using without this issue I built from master on Aug the 26th.

**Comment by Stibbons** [comment]
can you type bash to go in a sub bash process? Also, unset xterm environment variable?

**Comment by luispabon** [comment]
I'm closing this as, bizarrely, a reboot stopped this issue where an app reload wouldn't :+1:

**Comment by AlexWayfer** [comment]
App reload helped for me!

But it's strange… in the first launch.
