### ISSUE TITLE
Guake cannot restore from fullscreen

### ISSUE THREAD

**Issue by cleydyr** [Guake/guake#628]
Steps to reproduce:

1) open Guake and make it visible
2) make it fullscreen
3) hide Guake
4) show Guake
5) try to restore Guake windows size

Expected behavior: the Guake window restores its size
Current behavior: the Guake window seems to receive the command but cannot actually restore its size even after several commands to do so

**Comment by cleydyr** [comment]
Linux 4.1.6-1-ARCH
GNOME Shell 3.16.3

**Comment by tirkarthi** [comment]
Hi @cleydyr . I tried it with the latest git repo at work and it din't work. I tried again at home to turn debug mode on in data/guake.schemas (Line 8) and it started working as expected. I also switched off the debug and it worked without any issues. As far as I see from the code the settings values are saved correctly and are reflected back in the preference window. No clue over why it got working with debug mode on and off. Can you give it a try?

P.S. : I am on Linux Mint 15. I don't have an Arch to try it out.

**Comment by cleydyr** [comment]
Hi, @tirkarthi. Thank you for your update. I can see it is working now @ version 0.8.0, though when I'm using two displays it has a small glitch, with which it can be dealt in another issue. You can close this issue now.

Regards.
