### ISSUE TITLE
New Keybind for Hiding ES 

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#63]
New Keybind for Hiding ES http://guake.org/ticket/477
Reported by:    flare   Owned by:   somebody
Priority:   minor   Milestone:  
Component:  guake   Version:  
Keywords:       Cc:  
Description

A very practical way of hiding the terminal would be using the key ESC. Is possible to have a Boolean in the preferences windows enabling this feature?

thanks

**Comment by neilcsmith-net** [comment]
@pypingou just came across this while looking for how to configure `ESC` to close.  Could you elaborate on why this is not desirable?

**Comment by gsemet** [comment]
If you manage to have it working without conflicting with other (ex: midnight commander, vim) where esc touch should be transfered to the app, I would look at this pull request. But for me it is a bad option I will not work on it

**Comment by neilcsmith-net** [comment]
@gsemet OK, thanks, that gives me a sense of the concerns. What I'd like to see, and I think the OP is alluding to, is separate actions for show and hide, which could be set to the same shortcut (eg. `F12` as now by default).  While I understand the concern about key clashes, this also applies on the GUI side.  I've found `F12` conflicting with other things, so have been using a more complex key shortcut instead, hence wanting something simpler to close (at least when focused).  It's the flexibility to handle different GUI and CLI shortcut collisions that I'm really after.
