### ISSUE TITLE
Sending C-D slightly destroys guake

### ISSUE THREAD

**Issue by 5nizza** [Guake/guake#632]
I am used to call Control-D to quit gnome terminal.
In the guake this results in weird symbols to be prefixed before the intro:

![weird-symbols](https://cloud.githubusercontent.com/assets/928552/10312385/753566dc-6c64-11e5-99a1-1e31008db543.png)

instead of clean

![clean](https://cloud.githubusercontent.com/assets/928552/10312402/85a9d1ec-6c64-11e5-9553-77193dc1dc17.png)

May be that is not good practice to send Control-D -- please note this, then.)

**Comment by jenrik** [comment]
fixed in 0.8.3

**Comment by pypingou** [comment]
Closing then :)
