### ISSUE TITLE
Guake terminal turns white when we press the guake shortcut for sometime and leave it suddenly. 

### ISSUE THREAD

**Issue by snehasish02** [Guake/guake#635]
We get back to proper state again when we kill all guake processes and restart guake
Guake build: 0.4.4
Envoironment: Ubuntu 14.04 
Ram on system - 8GB

**Comment by snehasish02** [comment]
![screenshot from 2015-10-12 15 43 29](https://cloud.githubusercontent.com/assets/11257848/10425825/6a6e3c22-70f8-11e5-9433-8a2f1b600f50.png)

Attached screenshot

**Comment by ajahongir** [comment]
Having same issue sometimes.  have same params: ubuntu 14.4 8gb

**Comment by Stibbons** [comment]
is it reproductible?

**Comment by snehasish02** [comment]
I checked on my recent setup. This issue s not happening now.

**Comment by Stibbons** [comment]
ok. please reopen this ticket if it happens again
