### ISSUE TITLE
Feature request - alert sound in guake . 

### ISSUE THREAD

**Issue by shirishag75** [Guake/guake#640]
In guake I cannot hear an alert sound which I can hear in
gnome-terminal or chromium. The test-case is go to either the location
bar in chromium and hit backspace (each time the alert sound will be
played). Same or similar experience can be shared in gnome-terminal.
You hit backspace at the $ prompt itself and the alert sound will be
played.This can also be seen in editors like leafpad when they reach
the end or beginning of the document and go no further. This is in
gnome-flashback.

Having such alert sounds helps whenever you are absent-minded or feeling sleepy and working on the terminal.

**Comment by pypingou** [comment]
In the preference, there is a "Play system alert sound on bell", is this what you meant?

**Comment by shirishag75** [comment]
oh... that is far and yes that is what I meant. Actually that doesn't work at all. I did check it but nothing...nada, no sound :(

**Comment by r-barnes** [comment]
No sound for me either.

**Comment by jddantes** [comment]
Seems this really is from Guake, I thought it was due to zsh. Printing '\a' (whether through C, Python, or using echo -e '\a') triggers the sound on other terminals, but not on Guake.

**Comment by jddantes** [comment]
@r-barnes Did you restart Guake after ticking the "Play system alert" setting? Does `echo -e '\a'` (or even manually printing `\`a` with C or Python) play something in other terminals?

**Comment by r-barnes** [comment]
@jddantes: None of the terminals on my computer give alert sounds. I think that's because I don't have an internal beeper.

One solution I've come up with is to modify the way Guake catches alerts, and have it play a wav file. Right now the player and wav file are hard-coded, but I've been meaning to break them out as user-settable properties and submit this as a patch if the maintainers are interested.

**Comment by Stibbons** [comment]
I'll leave such feature as a plugin in next iteration of Guake. This is not up to Guake to circumvent the absence of beeper. Maybe the system can be configured to play a wav instead of a beep, but I don't know how

**Comment by r-barnes** [comment]
I don't know how to configure the system to do this either.

Does the above mean you'll implement such a plug-in, or that this should be implemented as a plug-in if it is to be implemented at all?
