### ISSUE TITLE
Hide Dots

### ISSUE THREAD

**Issue by vendforce** [Guake/guake#645]
can anyone tell me how to build guake and remove the dots at the end of the sceen in the middle 
![screenshot](https://cloud.githubusercontent.com/assets/15267883/10700026/fa9f4c4c-79b2-11e5-8588-23860abdac9d.png) 

I think its a placement holder for the height adjustment of the terminal I want to either hide it or chnage the color from white to black

I know this is not an issue its by design but I want hide them from my blackbackground and theme

**Comment by Stibbons** [comment]
You can try with ./dev.sh if you are under ubuntu.

**Comment by Davidy22** [comment]
Guake has been ported to GTK 3, no longer has the handlebar
