### ISSUE TITLE
Guake not showing up

### ISSUE THREAD

**Issue by petey33** [Guake/guake#646]
Hi,

I can't get guake to show up when I press F12. It shows up but only for a very short while. Then is dissappears.

Best regards
Petey

**Comment by thardev** [comment]
Hello @petey33 :smiley: can you post the operating system you're using and Guake version?

**Comment by pypingou** [comment]
maybe also try to start `guake` from a terminal and see if it gives an error or so.

**Comment by petey33** [comment]
I'm using Ubuntu 15.04.

Guake works again. The problem was somehow related to tmux. 

I normally start tmux from .bashrc. I disabled this and then guake and F12 works again.

Thanks a lot for your help :-).
