### ISSUE TITLE
Can't hide the window when it's not fullscreen

### ISSUE THREAD

**Issue by elkebirmed** [Guake/guake#647]

**Comment by pypingou** [comment]
You'll need to give more information than this :)

**Comment by pypingou** [comment]
or not :)

**Comment by elkebirmed** [comment]
Clicking `F12` bring the terminal window, and `F11` make it bigger (full screes).
when the window is not bigger and i want to close it with `F12` it wont.
but when it's full screen (bigger) it wil be clossed.

I have Ubuntu 15.04

thank you @pypingou :smile:

**Comment by Stibbons** [comment]
you means it does not hide when fullscreen?

**Comment by elkebirmed** [comment]
@Stibbons yup

**Comment by elkebirmed** [comment]
The same issue #648

**Comment by pypingou** [comment]
Then let's close this as a duplicate of #648 and keep the discussion there.

**Comment by elkebirmed** [comment]
OK :+1:
