### ISSUE TITLE
Won't run on Fedora 23 x64 with gnome 3.18

### ISSUE THREAD

**Issue by hAh0L13** [Guake/guake#659]
````
$ guake
INFO:guake.guake_app:Logging configuration complete
/usr/lib64/python2.7/site-packages/guake/guake_app.py:1625: GtkWarning: gtk_box_pack: assertion 'child->parent == NULL' failed
  self.mainframe.pack_start(self.mainframe, expand=True, fill=True, padding=0)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.7/site-packages/guake/main.py", line 239, in <module>
    exec_main()
  File "/usr/lib64/python2.7/site-packages/guake/main.py", line 235, in exec_main
    if not main():
  File "/usr/lib64/python2.7/site-packages/guake/main.py", line 151, in main
    instance = Guake()
  File "/usr/lib64/python2.7/site-packages/guake/guake_app.py", line 308, in __init__
    self.hotkeys = guake.globalhotkeys.GlobalHotkey()
SystemError: NULL result without error in PyObject_Call
````

Using guake on fedora 22, but after upgrade to F23 (using official instructions) guake won't ran.

**Comment by pypingou** [comment]
Tried using guake from updates-testing?

**Comment by alejandrodnm** [comment]
The same happens to me, guake crashes at startup on a Fedora 23 x86_64 machine (Upgraded from 22). 

Calling the `guake` command from a terminal sometimes gives me @hAh0L13 error and other times, but not always, it starts a tmux session on the terminal and tmux initializes.

If I close the tmux session, the guake process keeps running with the following message

```
$ guake
INFO:guake.guake_app:Logging configuration complete
/usr/lib64/python2.7/site-packages/guake/guake_app.py:1625: GtkWarning: gtk_box_pack: assertion 'child->parent == NULL' failed
  self.mainframe.pack_start(self.mainframe, expand=True, fill=True, padding=0)
INFO:__main__:Calling startup script: /usr/bin/tmux
INFO:__main__:Startup script started with pid: <subprocess.Popen object at 0x7f9fc4d6e090>
[exited]
```

I have installed guake Version 0.7.2-3.fc23

**Comment by hAh0L13** [comment]
`$ sudo dnf list installed | grep guake`
`guake.noarch                          0.8.3-1.fc23                 @updates-testing`

and after that:
`$ guake`

(guake:14651): libglade-WARNING **: unknown attribute `swapped' for <signal>.

%truncated..%

(guake:14651): libglade-WARNING **: unknown attribute `swapped' for <signal>.
INFO:guake.guake_app:Logging configuration complete
/usr/lib/python2.7/site-packages/guake/guake_app.py:1749: GtkWarning: gtk_box_pack: assertion 'child->parent == NULL' failed
 self.mainframe.pack_start(self.notebook, expand=True, fill=True, padding=0)
/usr/lib/python2.7/site-packages/guake/guake_app.py:820: GtkWarning: IA__gtk_window_set_type_hint: assertion '!gtk_widget_get_mapped (GTK_WIDGET (window))' failed
  self.window.set_type_hint(gtk.gdk.WINDOW_TYPE_HINT_DOCK)
/usr/lib/python2.7/site-packages/guake/guake_app.py:821: GtkWarning: IA__gtk_window_set_type_hint: assertion '!gtk_widget_get_mapped (GTK_WIDGET (window))' failed
 self.window.set_type_hint(gtk.gdk.WINDOW_TYPE_HINT_NORMAL)

guake started, but have some mistakes:

]777;notify;Command completed;ls]7;file://Exploding/home/hah0l[hah0l@Exploding ~] $ pwd
/home/hah0l
]777;notify;Command completed;pwd]7;file://Exploding/home/hah0l[hah0l@Exploding ~] $

**Comment by pypingou** [comment]
Small hint: ``rpm -q guake`` will return you which version of a rpm you have installed (faster than going through dnf list installed|grep...)

I had a similar issue on F23 but for me installing 0.8.3 fixed it. Maybe restarting gnome could help?

**Comment by hAh0L13** [comment]
I just forgot this command and dnf manual is at hand :) Yes, restarting session solved this problem.

Thank you for helping!

**Comment by alejandrodnm** [comment]
Installing the rawhide version solve the problem.

Thx.

**Comment by pypingou** [comment]
Why rawhide? It's in updates-testing (``dnf update guake --enablerepo=updates-testing``)

**Comment by pypingou** [comment]
Anyway, if it's solved, let's close this ticket :)
