### ISSUE TITLE
guake crashed with OSError in delete_shell(): [Errno 3] No such process

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#66]
guake crashed with OSError in delete_shell(): [Errno 3] No such process
http://guake.org/ticket/474
Reported by:    melchiaros  Owned by:   somebody
Priority:   critical    Milestone:  0.5.0
Component:  guake   Version:    0.4.3
Keywords:       Cc:  
Description

Hi, I am on Ubuntu12.10 alpha2 64bit with guke 4.3

I got a crash of guake recognized by the crash reporting deamon apport.

For the full report(with traceback) please look at:

 https://bugs.launchpad.net/ubuntu/+source/guake/+bug/1019559

Header from launchpad bug:

"Guake 4.3 crashed on Quantal.

Reproducing:

1.I have adjusted the transparence with guake settings. 2.Closed guake settings 3.Called guake with key F12 4.Close guake with Ctrl+Shift+W 5.Iterate some lopps over steps 1 to 4.

The crash must happend there arround.

ProblemType?: Crash DistroRelease?: Ubuntu 12.10 Package: guake 0.4.3-2" . . .

**Comment by fievelk** [comment]
I am still experiencing this issue on version `0.4.4-1ubuntu1`

> Guake crashed with OSError in delete_shell(): [Errno 3] No such process

**Comment by Stibbons** [comment]
please update to latest version
