### ISSUE TITLE
Can't bind toggle visibility shortcut on relogin (Alt+,)

### ISSUE THREAD

**Issue by Suor** [Guake/guake#660]
I use `Alt+,` as shortcut to show/hide guake, but when I reboot and guake launches it says "Can't bind Alt+, shortcut" (or something alike). My workaround now is opening preferences rebind it to F12 and then rebind back.

**Comment by Stibbons** [comment]
I also have this issue, I have set up a script with a sleep of 5 seconds before actually starting guake.
