### ISSUE TITLE
Will not toggle with scroll lock enabled

### ISSUE THREAD

**Issue by amayer5125** [Guake/guake#662]
I just installed Fedora 23. My keyboard backlight is enabled by scroll lock. While I have scroll lock enabled, to light up my keyboard, I can not toggle Guake open or closed.

**Comment by amayer5125** [comment]
So I switched the way I enable scroll lock and now Guake toggles fine. I was using `xmodmap -e 'add mod3 = Scroll_Lock'`. Now I use `xset led named 'Scroll Lock'`.

**Comment by Stibbons** [comment]
not a guake issue, or it is a problem with keybinder module. You should ensure you set the right shortcut in the pref panel, with the "scroll lock". 

I personnaly always have my keyboard lighten on. Don't bind to scroll lock.
