### ISSUE TITLE
Ctrl+F2 is default shortcut for both "Rename current tab" and "Go to second tab"

### ISSUE THREAD

**Issue by erihe251** [Guake/guake#664]
I would suggest using Shift+Ctrl+F2 for "Rename current tab", as it would fit in with the create and close tab shortcuts.

But maybe there is some reason for the current default that I'm missing?

**Comment by robert-matusewicz** [comment]
I think that bug is outdated:
- CTRL+F2 is "Go to second tab"
- CTRL+SHIFT+R is fo "Rename current tab"

**Comment by Davidy22** [comment]
Can confirm that the collision no longer exists, closing ticket.
