### ISSUE TITLE
fresh clone won't build

### ISSUE THREAD

**Issue by iplayfast** [Guake/guake#667]
./configure gives 
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."

autogen.sh gives
configure.ac:79: warning: macro 'AM_GCONF_SOURCE_2' not found in library
autoreconf: running: /usr/bin/autoconf --force --warnings=no-portability
configure.ac:79: error: possibly undefined macro: AM_GCONF_SOURCE_2
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by kradan** [comment]
you need to install `libgconf2-dev`

**Comment by Stibbons** [comment]
use dev.sh
