### ISSUE TITLE
how to disable command complete notify

### ISSUE THREAD

**Issue by gouyang** [Guake/guake#670]
I always got a notify before the Prompt when execute guake from another terminal, can I disable it?
version: guake-0.8.3-1.fc23.noarch

```
]777;notify;Command completed;cd]7;file://localhost/home/guohua guohua  ~  
]777;notify;Command completed;cd]7;file://localhost/home/guohua guohua  ~  
]777;notify;Command completed;cd]7;file://localhost/home/guohua guohua  ~  
```

**Comment by pypingou** [comment]
Did you restart gnome-shell or reboot since you have this?

**Comment by gouyang** [comment]
restart gnome-terminal or reboot does not work

**Comment by gouyang** [comment]
BTW, I'm using awesome wm(awesome-3.5.6-3.fc23.x86_64)

**Comment by gouyang** [comment]
It seems the issue only happens when run guake from another terminal.
If run it from a shorcut which defines by awesome rc.lua or run it from gnome application, no this issue.

**Comment by gouyang** [comment]
close this since it works most of time
