### ISSUE TITLE
feature request: resize font with 'CTRL +' and 'CTRL -'

### ISSUE THREAD

**Issue by bittorf** [Guake/guake#671]
very helpful.
when somebody implements this:
keep it different for all tabs (so resizing tab-X must have no effect on tab-Y"

**Comment by Stibbons** [comment]
what is STRG ?

**Comment by bittorf** [comment]
@Stibbons sorry, it's CTRL on an english keyboard.

**Comment by JavaJens** [comment]
As I see this already works? At least for all tabs.
I'd really like to be able to reset my zoom to the default using Ctrl+0 as is used in many programs today, e.g. Firefox.

**Comment by Davidy22** [comment]
Feature is implemented, closing.
