### ISSUE TITLE
Shortcuts to increase and decrease window height not working

### ISSUE THREAD

**Issue by seth--** [Guake/guake#673]
I have no idea what could be causing this bug. The code looks the same as it was in https://github.com/Guake/guake/pull/361 

I'm using 0.8.3, but this stopped working a few months ago.

**Comment by pypingou** [comment]
Which OS?

**Comment by seth--** [comment]
Linux

I'm also using openbox

**Comment by simontong** [comment]
I'm also being affected by this issue after I upgraded from Ubuntu 15.04 to 15.10.

**Comment by Stibbons** [comment]
other shortcuts are working ?

**Comment by simontong** [comment]
Yes, just the height one. Thanks

**Comment by miko007** [comment]
same issue on all my arch and ubuntu systems. this is really a slow down.

**Comment by Stibbons** [comment]
should work on HEAD now

**Comment by yngvark** [comment]
Doesn't work for me. Running Guake 0.8.4, Xubuntu 16.04.
