### ISSUE TITLE
guake is behind GNOME shell's top bar

### ISSUE THREAD

**Issue by eychenz** [Guake/guake#679]
On Fedora 23 GNOME 3.18.2,
When there are two displays arranged vertically, and bottom display is the primary one,
guake terminal appears behind the GNOME shell's top bar which makes the first two lines useless.
screenshot attached.
![screenshot from 2015-12-15 22-01-22](https://cloud.githubusercontent.com/assets/10549219/11824068/db82e1fe-a377-11e5-8712-0f23cf92dd5d.png)

**Comment by Stibbons** [comment]
Guake is not compatible gnome 3.18, seem too many bugs. Wait for gtk3 port
