### ISSUE TITLE
Terminal %s

### ISSUE THREAD

**Issue by chok** [Guake/guake#680]
The label for my local computer is always "Terminal %s". When I login on a server via ssh, it change to a correct value. I tried to change my PS1 value for the one of server but it didn't change nothing.

I have installed guake 0.8.3 from the ppa with the same result.

**Comment by Stibbons** [comment]
which language?

**Comment by chok** [comment]
In french

**Comment by chagam** [comment]
Hi, same here.
Latest mint, french language
