### ISSUE TITLE
Feature request - enable reordering of tabs

### ISSUE THREAD

**Issue by flo2k** [Guake/guake#684]
Hi guake team,

I'm using guake a lot. I love the tabbing feature - but I still miss a feature to reorder the tabs. It would be welcome if it is possible to drag & drop the tabs to a new position.

Best regards,

Florian

**Comment by pypingou** [comment]
Doesn't it already work? Using the mouse I can just drag and drop them as I want, with guake 0.8.3.

**Comment by flo2k** [comment]
I'm using Linux Mint 17.3 Rosa and there is guake 0.4.4 packaged. So it seems this is quite an old version. I will try to manually update to a newer version, and give a short report.

**Comment by Stibbons** [comment]
It has been added in 0.5. Still works :)

**Comment by flo2k** [comment]
Thank you for that information. I just installed guake version 0.8.3 from this https://launchpad.net/~webupd8team/+archive/ubuntu/unstable ppa and it works.
