### ISSUE TITLE
Problem with "hide on focus loss" feature

### ISSUE THREAD

**Issue by proDOOMman** [Guake/guake#687]
When "hide on focus loss" feature is enabled and I pressing hotkey for switching between keyboard layouts, guake is hiding. I tried to change hotkey from Ctrl+Shift to Alt+Shift or Super+Space, but bug still exists.
I'm using ubuntu 16.10 with unity 7.4.0 and guake 0.8.3.

**Comment by Stibbons** [comment]
Alt isn't working, you cannot use it as accelerator for your hotkey. This is a know issue

**Comment by danielkanzel** [comment]
Its really annoying

**Comment by Davidy22** [comment]
Resolved by #1892
