### ISSUE TITLE
Problem with tabs

### ISSUE THREAD

**Issue by s777s** [Guake/guake#689]
I have a problem, when closing tabs.
I have 5 tabs opened and active e.g. 2nd tab. I look on progress in it and want to close other tabs, coz I don't need them. I rifght-click on exact name of 5th tab to close it. And my active (2nd tab is closed) :(

**Comment by Ozzyboshi** [comment]
I think you should first select the tab you want to close, then you right click.
Maybe it would be better if the tab is selected automatically when you right click on it

**Comment by Stibbons** [comment]
Never had this issue, I always select the tab before deletion. But this is a bug indeed

**Comment by aichingm** [comment]
I hit this bug a while ago. It was fixed before but it is definitively fixed since #1390
