### ISSUE TITLE
qt creator does not accept guake

### ISSUE THREAD

**Issue by CharlesPL** [Guake/guake#690]
I' m wondering why I cannot use guake in QT Creator. I mean that I wanted to change default gnome terminal with a guake so i typed a command usr/bin/guake -e and my program does not appear into guake. Any solution?

**Comment by Stibbons** [comment]
no sure to understand the link between qt creator and guake... guake uses python and GTK framework, while QT creator is for QT under C++...

**Comment by CharlesPL** [comment]
ok so why i can use gnome terminal in qt creator and i cannot use guake?

**Comment by Stibbons** [comment]
ah, you want to open guake as the terminal. Look at the option, since when launched, guake is not relaunched. Use guake -n new term or similar + guake --show to display the guake windows. Use a bash script.
