### ISSUE TITLE
Tab UUIDs and guake env variables

### ISSUE THREAD

**Issue by SoniEx2** [Guake/guake#691]
Each tab should have its own UUID, so that you can rearrange tabs without breaking programs that integrate with guake (e.g. setting tab title).

**Comment by SoniEx2** [comment]
Also, it should get set as an environment variable, to allow easy testing for "are we running in guake?".

**Comment by Stibbons** [comment]
Thanks for your proposal. Feel free to submit PL

**Comment by Patola** [comment]
Hi, is that really as planned? From the shell I can get the UUID via environment variable but there are only two dbus commands that use it: org.guake3.RemoteControl.rename_tab_uuid and org.guake3.RemoteControl.execute_command_by_uuid. It seems as though I can't get the current tab number or title, is that correct?
