### ISSUE TITLE
htop shortcuts

### ISSUE THREAD

**Issue by elmerehbi** [Guake/guake#692]
Guake interferes with htop's shortcuts. Particularly F4.

OS: Ubuntu

**Comment by Stibbons** [comment]
replace the shortcut in your pref panels if you need these shortcuts

**Comment by elmerehbi** [comment]
@Stibbons I click to change it but how can I remove it?

**Comment by pypingou** [comment]
In the same way

**Comment by elmerehbi** [comment]
After upgrading to the latest version I saw the message above the shortcuts window and that helped.
