### ISSUE TITLE
Configuration via escape sequence

### ISSUE THREAD

**Issue by milgner** [Guake/guake#695]
Is there a way to configure Guake using escape sequences?

I currently use Terminology as my terminal emulator and when I ssh in to important server systems, I set a corresponding background image via escape sequence so I can see at a glance when such a session is still open.

**Comment by milgner** [comment]
I did some digging into the [python-vte](https://github.com/linuxdeepin/python-vte/) code and at first glance it looks like all escape sequences are hardcoded in [vteseq-n.c](https://github.com/linuxdeepin/python-vte/blob/master/src/vteseq-n.c) without any possibility to register additional ones. I'll do some additional investigation and try to come up with an idea...

**Comment by Stibbons** [comment]
seems a bad idea to hack in the escape characters. we can react to other events to replace the background image, but indeed, it is not possible for the moment to customize image per tab

**Comment by ulukyn** [comment]
I have made some changes to be able to set a custom image per tab using --bgimg parameters.
No idea if my changes are right and completes. But works nice for me using command like

guake -s 1 --bgimg="path_to_image/image.jpg" -r PrettyTab


Attached patch:
[image_per_tab.patch.txt](https://github.com/Guake/guake/files/506716/image_per_tab.patch.txt)

**Comment by aichingm** [comment]
Setting background images is not supported anymore. This has changed in the vte 2.90 or something like this.
