### ISSUE TITLE
Zoom not working 0.8.3 or 0.7.2

### ISSUE THREAD

**Issue by ElijahLynn** [Guake/guake#696]
I see https://github.com/Guake/guake/pull/207 add zoom support, which is awesome! However, I cannot get it to work.

When I press `ctrl + X` series of shortcuts it enters the character `=`, `-`, or `+`. 

![image](https://cloud.githubusercontent.com/assets/1504756/12654164/d009e46a-c5c0-11e5-9789-1398e31580ea.png)

**Comment by KLVTZ** [comment]
> http://askubuntu.com/questions/524025/how-to-zoom-in-out-of-text-within-guake-terminal/525772

@ElijahLynn thanks for commenting. I'm not near by ubuntu machine at the moment but I recall using a combo of `Ctrl and +` to zoom and `Ctrl and 0` to reset view. When I get home from the office, I can provide you the Guake build I am running.

**Comment by ElijahLynn** [comment]
Thanks @KLVTZ any chance you had time to check?

**Comment by ElijahLynn** [comment]
I had to jump back to 0.7.2 in #697 and I am getting the same behavior.

**Comment by Stibbons** [comment]
Works on my system (Ubuntu 15.10)

**Comment by KLVTZ** [comment]
@ElijahLynn Sorry for the delay. Here is my specs:
- Ubuntu: 14.04
- Guake: 0.5.0

I want to confirm that the above build does work and am able to zoom in and out with `Ctrl+` and `Ctrl-`.

**Comment by ElijahLynn** [comment]
Okay, I will try 0.5.0 later and report back.

**Comment by ElijahLynn** [comment]
Possibly related to #560

**Comment by ElijahLynn** [comment]
Let's close this as we are on 3.7.0 now and this is working fine on my latest Gnome 3.6 setup.
