### ISSUE TITLE
No copy/paste with ctrl+shift+c/v in 0.7.2 or 0.8.3

### ISSUE THREAD

**Issue by ElijahLynn** [Guake/guake#699]
I cannot copy/paste anymore since upgrading from 0.4.4 (Ubtuntu 14.04 latest package) to 0.8.3 and then back down to 0.7.2. 

Any ideas? 

Might be related to - #697

**Comment by Stibbons** [comment]
and this also works on mine. Please describe your system

**Comment by ElijahLynn** [comment]
I think what might be easier is me learning how to debug Guake. Do you have any tips you can share on how to debug this? They can be generic, high level. I can figure out the technical details.

**Comment by Stibbons** [comment]
there is a dev script => ./dev.sh for ubuntu. I use it to debug without installing guake. It's python so quite easy to debug. But for all shortcut related stuffs, it way be related to keybinder library (https://github.com/engla/keybinder)

**Comment by ElijahLynn** [comment]
Ahh, so I should be able to step debug in Pycharm or something like that?

**Comment by Cediddi** [comment]
I can second that. I have mint 17.3 with Cinnamon. I can provide any information you want.

**Comment by Stibbons** [comment]
I use it on a daily basis. What's you systems?

**Comment by ElijahLynn** [comment]
Python 2.7.6
Ubuntu 14.04
Guake 0.7.2 OR 0.8.3

Does this help? I can provide more specific information if needed, but please tell me what that should be.

**Comment by ElijahLynn** [comment]
I still plan on debugging this but just haven't had much time lately.

**Comment by ElijahLynn** [comment]
Ahh, I see that while it is mostly written in C the part that looks compiled is the Global Hotkeys Capture. I don't think I can step debug that. 

"Guake is mostly written in python and has a little piece in C (global hotkeys capture). "

**Comment by ElijahLynn** [comment]
Actually, it appears that the global hotkeys capture is no more. I found this PR suggesting so https://github.com/Guake/guake/issues/510

I think the readme.md file should be updated.

**Comment by ElijahLynn** [comment]
Submitted https://github.com/Guake/guake/pull/716 to update readme file.

**Comment by ElijahLynn** [comment]
Possibly related to #560

**Comment by ElijahLynn** [comment]
Interesting, just habitually tried to ctrl+shift paste today and it works again. This leads me to think a dependency was updated upstream... Hrm...

**Comment by Stibbons** [comment]
You probably need to restart in this case...

**Comment by ElijahLynn** [comment]
I don't think it was a restart, I had this issue for many months and had restarted quite a bit over that time.
