### ISSUE TITLE
Italic text support

### ISSUE THREAD

**Issue by oblitum** [Guake/guake#703]
I've verified that `echo -e "\e[3mHello\e[23m"` doesn't produce italic text as in Gnome Terminal. It would be nice to have it.

**Comment by Stibbons** [comment]
should be supported by python-vte gtk3

**Comment by AriaAsuka** [comment]
I've found this issue.
Is there solution to have italic text support?

**Comment by Stibbons** [comment]
gtk3 ... soon

**Comment by aichingm** [comment]
![image](https://user-images.githubusercontent.com/6470959/45885457-ce70da00-bdb6-11e8-8266-fafeb085aa03.png)

Works now (with the gtk3 version)!
