### ISSUE TITLE
Nano does not behave as expected in Guake terminal.

### ISSUE THREAD

**Issue by ykartal** [Guake/guake#704]
I am using Centos Release 6.7 and installed Guake.
But when type nano <filename> on guake terminal, it is not possible to modify content or doing anything because a black empty screen is opened though there are texts in file.

Any idea?

**Comment by Stibbons** [comment]
Don't have this problem under ubuntu and 0.8.4

**Comment by ykartal** [comment]
As below image, guake shows nothing after the below command run
`nano install_chrome.sh`
PS: Take care of the right bottom of the screen

![Image of Guake]
(http://i.imgur.com/yEko0nl.png)

**Comment by Davidy22** [comment]
Unable to reproduce, does this still occur for you?

**Comment by Davidy22** [comment]
Closing due to no reply, reopen if still relevant
