### ISSUE TITLE
Split terminal functionnality

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#71]
Split terminal functionnality http://guake.org/ticket/145
Reported by:    LaMs    Owned by:   somebody
Priority:   minor   Milestone:  
Component:  guake   Version:  
Keywords:       Cc:     mkudro@…
Description

Yakuake and Terminator have this particular functionnality. I was using Yakuake when I was developing on KDE but now that I'm running on gnome I'm using Guake. Guake is perfect for me at the exception of this little functionality. Example of what I'm talking:
http://www.kde-apps.org/content/preview.php?preview=2&id=29153&file1=29153-1.png&file2=29153-2.png&file3=29153-3.png&name=Yakuake  
http://www.64bitjungle.com/wp-content/uploads/2008/09/screenshot-terminator.png

Having this in a drop down console like Guake would be very useful for an embedded developer addict to Vim like me.

**Comment by ranlei** [comment]
+1

**Comment by varemenos** [comment]
:+1:

**Comment by giacmir** [comment]
+1

**Comment by sent1nel** [comment]
+1

**Comment by Gronkdalonka** [comment]
+1

**Comment by Vizzard** [comment]
+1

**Comment by Stibbons** [comment]
Look like I will not have choice for the next big feature :)

**Comment by presianbg** [comment]
+1

**Comment by SomeKittens** [comment]
Would love to have this, thanks!

**Comment by 1beb** [comment]
+1e6

**Comment by rumpelsepp** [comment]
:+1:

**Comment by Sebastock** [comment]
+π

**Comment by pypingou** [comment]
To all the people that said, are saying or will say, +1, :+1: : This will not make guake get this feature any sooner.

The former upstream of guake said that he didn't want guake to have it, the new upstream of guake says that he is interesting in it, but unless someone actually comes up with the pull-request, saying +1 won't change anything.
There are other parts of guake that need work (port to gtk3, port to dconf...) and those should have the priority over adding new features as otherwise guake will simply stop working some time soon.

**Comment by Stibbons** [comment]
I'd like to have time to work on 0.8 and start working on split tab and save/restore session functionnality.  would really love to have these feature on Guake. Guake is my main tool at work, that's why I am so much interested in adding useful feature to it. But these months has been completely crazy, I hope august will leave me more free time with everyone else in vacation....

Port to dbus and gtk3 is harder, need more time on short duration (1 week or 2 full time) to jump to new libraries since lot of stuff might break and need to be ported. I clearly don't have this among of time available, I don't know how to deal with it. Maybe start from scrach on a side project that would be matured. But for example, the gtk3 branch has not been maintained, now lot of stuff has moved merging the main and gtk3 branch is not trivial.... no idea how to handle it gracefully :(

**Comment by Caroga** [comment]
+1

**Comment by PombaM** [comment]
+1

**Comment by PombaM** [comment]
This feature could be godsend for us how use solely Guake for dev purposes! Dear maintainers please consider this feature at your earliest. Thanks.

**Comment by pypingou** [comment]
>    This feature could be godsend for us how use solely Guake for dev
>    purposes! Dear maintainers please consider this feature at your earliest.
>    Thanks.

I believe the opinion of the developers on this feature has already be made
clear and all the +1 won't change much to it.

**Comment by Caroga** [comment]
>I believe the opinion of the developers on this feature has already be made
clear and all the +1 won't change much to it.

Meaning that it gets implemented?

**Comment by PombaM** [comment]
> Meaning that it gets implemented?

I think it's contrary!

**Comment by PombaM** [comment]
> already be made clear

Links or it didn't happen :)

**Comment by varemenos** [comment]
Please read the issue's labels and the comments above.
There is no need to spam the issue to get an answer, it's already available.

**Comment by Stibbons** [comment]
back from my vacation, I'll be able to restart working on it... don't expect such feature until 2016

**Comment by MarkOSullivan94** [comment]
Big +1. I only use Terminator because it has the option to split the current terminal into two terminals either horizontally or vertically.

**Comment by rlimaeco** [comment]
+1 !!! The feauture to say goodbye to yakuake in gnome

**Comment by Stibbons** [comment]
why don't use tmux in guake?

**Comment by Ozzyboshi** [comment]
there is also byobu (http://byobu.co/), however terminal splitting would be great even if a little hard to implement.

**Comment by Stibbons** [comment]
thanks for this link! Look amazing. I don't see how Guake would do better. Maybe a tight integration between byobu and guake would be better (an option "automatically start byoby terminal splitting in tab" + able to retrieve the information we read from VTE). Don't know if it is feasible, but I think I'll use byobu from now on :)

**Comment by Ozzyboshi** [comment]
@Stibbons ,
actually byobu relies on tmux and/or screen multiplexers so my answer is not so different from yours. We must first say that the feature requested by @rlimaeco  is a native guake split terminal implementation (in my opinion not so trivial).
For now we could figure out a way to start byobu automatically (default interpreter under preferences->shell??) .
If you want to split the terminal just use byobu shortcuts or some contextual menu inside guake (to be implemented). The split function however must be visible (or usable) only if byoubu is enabled.

**Comment by Stibbons** [comment]
+1

**Comment by pabloab** [comment]
If I'm not getting all wrong:

1. `# apt-get install byobu && which byobu | tee -a /etc/shells`
1. Run `guake-prefs` and change Default interpreter.

**Comment by Ozzyboshi** [comment]
yes that's how i use guake, in addition i set the horizontal and vertical split command in guake indicator so i dont' have to remember all the byobu shortcuts.
Maybe it would be better to put the same commands into the custom commands menu but they will work only if you are using byobu.

**Comment by alexxtasi** [comment]
byobu rocks!!!!
byobu and guake in combination would be great!!
+1

**Comment by MorganAntonsson** [comment]
+1

**Comment by Ozzyboshi** [comment]
I'd like to share with you my method for splitting a terminal inside a guake tab with byobu.
My goal is to reuse the guake custom command feature to split the terminal with byobu shortcuts.

- Install byobu
- Install xdotool
- Use my own guake version at https://github.com/Ozzyboshi/guake ( I will explain later why)
- Create a json file like this:

[test.txt](https://github.com/Guake/guake/files/187424/test.txt)

- rename test.txt in test.json and select it from guake prefs->general->custom command file path

Now go to your terminal and start 'byobu'
Now to horizontal split just right click on the terminal and go to 'custom commands' ->  Byobu vertical split

There are some other commands in the test file, the one i use more, you can customize it according to your needs and your byobu shortcut configuration.

The test file is quite straightforward, it just tells guake to emulate some keypresses with xdotool, please notice the syscall section, if this field is present and set to 1, guake will execute a system call instead of sending the command to the terminal, this is very useful because users don't want to see the xdotool command on the screen and because it works under remote sessions like telnet or ssh.
The syscall field is implemented in my custom guake version, if @Stibbons likes it i will be happy to issue a pull request.
I know this is not what was requested but please tell me if you think this is a viable workaround.

**Comment by Stibbons** [comment]
Look indeed quite complex... like this, I don't think it is a good path to follow. But even if I implement split terminal functionality in Guake next gen, it won't be as mature are byobu...
Maybe we can think about a plugin system that would give ability to easily add such extension, so you can maintain this plugin independentely... I'll see how I can add hooks for plugins in the rework I am still doing (overloaded by work since january, I don't have any time to work on guake..)

**Comment by Chyzwar** [comment]
@Stibbons I think just have option to split vertically would be enough for most of us.
 Anyway I think that guake is great :), thanks for your work.

**Comment by rubo77** [comment]
Thanks for the tip!

Yakuake is cool, I will use that one now, it also works on standard Ubuntu without KDE ;)

**Comment by tomchor** [comment]
I don't know if it's just me, but Yakuake, as great as it is, it's really buggy for gnome, which is what I use. So unfortunately, as far as I know, gnome lacks a good terminal that has both the drop-down and the split-screen feature. (As far as I know byobu doesn't have the drop-down part.) So I really support this issue of adding split screen to guake!

**Comment by rubo77** [comment]
I did notice only one bug in yakuake: the support of [custom cursor keys ](http://askubuntu.com/questions/684459/configure-caps-lock-as-altgr-and-arrows-like-in-vim) configured by xkb, that made me use guake again.

If i need a split screen,i use **tmux** now inside guake.

**Comment by tomchor** [comment]
I had noticed some more, but it was a while ago and I don't remember all. The most annoying one was that the feature that would allow every new tab to be open in the current directory didn't work.

If anyone is interested, by now the option that gave me the best result was `which byobu | tee -a /etc/shells` and then changing the default interpreter.

**Comment by rubo77** [comment]
Please share how did you configure that exactly? Maybe better on stackoverflow.com

**Comment by tomchor** [comment]
No problem. Can you please create a question there and tag me so I can know exactly what you want to know? I'll gladly answer it.

**Comment by pabloab** [comment]
I'm a happy user of Guake with [Byobu](http://byobu.co/) and tmux. [unix.stackexchange.com](https://unix.stackexchange.com) is the right place for this kind of question. Please take a look at [my answer here](http://unix.stackexchange.com/a/355145/209677).
@Stibbons might consider this as an official alternative to have tmux/scren features and more on Guake.

**Comment by Stibbons** [comment]
i like this approach, however i also would like a completely integrated split feature in guake 3...

**Comment by tomchor** [comment]
This approach is fine, but means doing extra work and learning a few extra shortcuts. Also, I tend to change computers and distros a lot, so that means having to install everything all over again and re-doing your `.conf` files for everything. A completely integrated split feature for guake would be much better in my opinion because then I'd just have to worry about guake's shortcuts, portability etc.

So I think think this is a high priority issue.

**Comment by JendaPlhak** [comment]
Would it be possible to support development of this feature by some donations or something? I think it is clear many people are interested in this and possibly would be willing to contribute at least with their resources if not work.

**Comment by Stibbons** [comment]
You can put a bounty indeed, here: https://www.bountysource.com/teams/guake
I am in the middle of the rewriting, losting a little bit of motivation (said otherwize, getting other motivations). So it might not change anything for myself, but could help motivate external contributions !

**Comment by chyzwar** [comment]
I put 15$ :) Split terminal would be really cool:)

**Comment by kah-ell** [comment]
Why not wrap Terminator? It already does everything we need except for popping out of a screen-edge.

**Comment by MomchilGorchev** [comment]
+1

**Comment by woodworker** [comment]
Split terminal that can be split/moved/unsplit also via mouse would be awesome, did also put 15 USD on bountysource for this ticket

**Comment by Stibbons** [comment]
Awesome :)

**Comment by meridius** [comment]
As mentioned on https://askubuntu.com/a/489789/48461 the **`Alt + F12`** enables scrolling in Byobu splits within Guake. Which is AWESOME!

**Comment by j0131n** [comment]
+1 for this

**Comment by flybysun** [comment]
+1

**Comment by Stibbons** [comment]
Planned for 3.1

**Comment by tomchor** [comment]
This may be a very naive question, given that I don't know much about the subject, but does the porting to GTK3 make it easier to code this?

**Comment by Stibbons** [comment]
in the sense that now the big work has been done, we can more safely work on this split terminal functionnality

**Comment by kah-ell** [comment]
May I Ask what the end game is? I already mentioned it once, but Terminator already does splitting and a lot of other fancy stuff. What is Guake going to bring to the table that warrants the effort of coding all those features from scratch?

**Comment by Stibbons** [comment]
I use guake daily at work, I think I'll be happy to have a clean split screen functionnality :)

**Comment by shirishag75** [comment]
@kah-ell  if we all thought like that, we would have only single application for one thing. The reason free software works is people are free to have features that they want. 

There's probably another point that you might or might not have thought of. Each year we have some improvements or changes for e.g. GTK2 to GTK3 and eventually to GTK4 or from QT4 to QT5 and above. 

Nobody can guarantee that app. X would make it to the next round hence it makes sense to have same/similar functionality. 

By the same logic, yukake, terminix, terminology, should not have been invented as guake has the drop-down emulator bit. 

Looking forward to seeing this functionality in Debian.

**Comment by ijann** [comment]
https://feathub.com/Guake/guake/+8 
give a like

**Comment by tomchor** [comment]
@ijann Very good idea!
However, I hope you do not take this the wrong way but your feature request was very difficult to understand (according to you, you used google translate). So I created another issue to replace yours. I hope you don't mind.

I suggest to vote on the feature request here!: https://feathub.com/Guake/guake/+9 
where I think it will attract more people.

Let's make this happen!

**Comment by ijann** [comment]
no problem mate,
if you improved my request request -
it will be well come from me,
I give you a "like" on my part,
mine I discard it so it does not create confusion and
yours will be voted.
regards

google translate, sorry the english

**Comment by hridaydutta123** [comment]
Is this feature merged?

**Comment by gsemet** [comment]
Nop, I need to find time to rework the notebook structure that this will enable 3 features at once
- search/find
- split terminal
- save/load sessions

be patient !

**Comment by solofeed** [comment]
+1, waiting for split screen)

**Comment by austinjdean** [comment]
Really happy to see that this will be rolled out in 3.1!

**Comment by oliverjc** [comment]
Could somebody link me the upcoming features please?

**Comment by austinjdean** [comment]
Here's everything planned for 3.1, ETA April 1st: https://github.com/Guake/guake/milestone/21

**Comment by gsemet** [comment]
Hi guys ! So, at last I manage to find the end of the big transition to GTK3. The only major issue left is the drag and drop on the tab bar that still does not work. After that, at last, I will work on the most wanted Guake features: Find in terminal, save session and split terminal. I do not want to rush that, so it may still take some time. Lot of rework of the internal tab structure is needed to enable these three features, so I ask you all to be patient !

**Comment by mturley** [comment]
Thanks for your hard work @gsemet.  Can't wait to switch back to Guake for split terminals, I always liked it better than the alternatives.

**Comment by iamtodor** [comment]
@gsemet you promised us feature would be rolled out with 3.1.0 milestone, now I see even 3.2.0 milestone was released. Do you plan to make this most desired and hottest functionality real?
Seriously, this issue was opened 4 years ago

**Comment by chyzwar** [comment]
@iamtodor How much did you put into bounty program? You are free to submit PR for this feature.

**Comment by matheo** [comment]
After the Ubuntu upgrade from 17.10 to 18.04 my custom script to open some default tabs is broken :(
```
#!/bin/bash
sleep 3

guake -r "local"

guake -n "/media/work/git/..."
guake -r "DevOPs"

guake -n "/media/work/git/..."
guake -r "api"

guake -n "/media/work/git/..."
guake -r "common"
```

**Comment by gsemet** [comment]
what error?

**Comment by matheo** [comment]
@gsemet It just doesn't execute the script, and when I try to select the `.sh` in the settings the process halts. It seems to ask for a JSON config; it's there an example of that `.json` file?

**Comment by fusion809** [comment]
Seems like this feature is likely to take a while to enter Guake, that is if ever. If there's a way I, someone with limited programming ability aside from in shell script, can help accelerate this process please do say as this is the main reason why I tend to favour Yakuake over Guake.

**Comment by gsemet** [comment]
I understand, I have no time of the moment to work on it in short term. I have a big rework to do internally before doing the split feature, that is hard now but after refactor it should be a piece of cake. 

Hope to get enough free time this summer to do it !

**Comment by alexanderjohn** [comment]
+1 any progress?

**Comment by alexanderjohn** [comment]
@aichingm I have been using iTerm2 at work on a mac (not by choice) for almost 2 years now and it's terminal window splitting, and navigation is pretty phenomenal. 

I JUST installed Terminator for the first time about an hour ago to play around with its window splitting and I am 100% blown away by it. The key bindings are super smart and it does everything iTerm2 does that I use on a daily basis.

For you, I would honestly install Terminator and play with it and you will see what we are looking for. 

Personally, Tmux has a really strange set of keybindings and modes that dont smoothly integrate into my workflow.  To me, if I were to try to integrate Tmux, I might as well install and learn Emacs (it has full buffer window splitting).  Personally I dont want to do that.

**Comment by aichingm** [comment]
@alexanderjohn interesting, is there something else except the smart key bindings? 

I will have a look at how Terminator is handling the split functionality.

**Comment by rasmus25** [comment]
The biggest reason I like Terminator's split panes better than Tmux's is that when I have split the window into two panes side by side, I easily select multiple lines of text in one pane with the mouse. If I try to do the same thing with Tmux, it will instead select the lines from both panes, including the pane separator.

Additionally, when text in one pane is scrolling very fast, I cannot select text in the other pane. This is all because Tmux handles its own panes, whereas Terminator uses the window manager's widgets and hence behaves natively.

I guess these are not problems for people who don't use the mouse, but I find the mouse very useful with a terminal emulator like Guake when the terminal covers half the screen and is always on top, so I can select text from a web browser and middle-click-paste it to the relevant terminal pane very quickly.

**Comment by farisachugthai** [comment]
@alexanderjohn in the GUI Guake Preferences, there's a section for 'on show hooks'. I'm sure you could set yours to some variation of `exec terminator`

I have my "on start" set to `tmux split-window -h` and while that's not a native solution, I'd definitely recommend it for anyone trying to find a quick workaround

**Comment by sent1nel** [comment]
I use tmux also. Its commands aren't intuitive for a day or two, but it does not take long to pick up.

```
ctrl+b + " // ctrl+b %  -- split horizontally and vertically
ctrl+b + tap an arrow key -- move between panes
ctrl+b + q, tap a number -- display pane "ids", then jump to a pane
hold ctrl+b while tapping arrow keys -- resize pane
```

**Comment by ailionx** [comment]
+1

**Comment by dialvarezs** [comment]
I personally use Tilix as my main window-terminal, and it's awesome; it has good usability with mouse and kb, and it looks great in gnome. I like it's shortcouts too, specially the alt+arrows to move around.
I hope Guake can get a split functionality as good as the Tilix one, because Guake is my "always open" terminal and the tabs are not enough when I want to check 2 things at the same time.

**Comment by iamtodor** [comment]
@gsemet Does it mean we will have split terminal feature in nearest future? :)

**Comment by fusion809** [comment]
@iamtodor Seems like it, after all you see that merged pull referenced above (#1415), it seems to implement it we just have to wait for a new release of this fine terminal and then wait for our distro packagers to package this new release.

**Comment by solofeed** [comment]
5 years of waiting, and it comes )) @gsemet thank you)

**Comment by gsemet** [comment]
Aye aye aye !! You should thanks @aichingm who did the big work on this one !

**Comment by gsemet** [comment]
@fusion809 If your package is too old, you can install guake with `pip3 install --user guake`. But yes, you may have to wait for a few days/weeks until we finalize the split terminal feature and fix latest bugs to get the next release (will be 3.4.0), or build from source ;)

**Comment by fusion809** [comment]
Yep I know,. I was talking about most users that just use their package manager and default repos, but your advice is still very helpful, so I thank you :). Personally, I'm about to create my own RPM package for the latest build. I favour using my distro's package manager too.

**Comment by fusion809** [comment]
That was easy anyone that's using Tumbleweed can go forth and install it &mdash; https://build.opensuse.org/package/show/home:fusion809/guake. Trying to fix the Leap 15 build too.

**Comment by iamtodor** [comment]
Hello. Where can I find how can I use split function?
I have `Guake Terminal 0.8.4`

**Comment by tincho** [comment]
I literally just googled this feature. Guake 3.0.5 on Ubuntu 18 here and don't see any split/tiling options.

**Comment by tomchor** [comment]
@iamtodor 
I'm pretty sure you have to get the latest version (3.4) to get the functionality.
I still don't have it myself (since the maintainer of Arch still hasn't updated it for some reason), but I'm sure it's there once you get v3.4.

**Comment by iamtodor** [comment]
@tomchor could you please help me how to get this version `3.4`? download from github and compile it by myself, and is there some instruction for compilation?

**Comment by gsemet** [comment]
Pip install —user guake

**Comment by iamtodor** [comment]
@gsemet installed successfully, but can't run:
```
tdr@tdr-HP:~$ pip install --user guake
Collecting guake
  Downloading https://files.pythonhosted.org/packages/21/ec/f45a5410a5b56d80bd3bbd9ed621865f63fcbecb8e6142401a24621a0f81/Guake-3.4.0-py2.py3-none-any.whl (1.2MB)
    100% |████████████████████████████████| 1.2MB 4.2MB/s 
Collecting pbr (from guake)
  Downloading https://files.pythonhosted.org/packages/f3/04/fddc1c2dd75b256eda4d360024692231a2c19a0c61ad7f4a162407c1ab58/pbr-5.1.1-py2.py3-none-any.whl (106kB)
    100% |████████████████████████████████| 112kB 10.0MB/s 
Collecting typing; python_version < "3.5" (from guake)
  Downloading https://files.pythonhosted.org/packages/cc/3e/29f92b7aeda5b078c86d14f550bf85cff809042e3429ace7af6193c3bc9f/typing-3.6.6-py2-none-any.whl
Installing collected packages: pbr, typing, guake
Successfully installed guake-3.4.0 pbr-5.1.1 typing-3.6.6
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
tdr@tdr-HP:~$ guake
[ERROR] Unable to start Guake, missing mandatory dependency: Keybinder 3
tdr@tdr-HP:~$ pip3 install guake
Collecting guake
  Downloading https://files.pythonhosted.org/packages/21/ec/f45a5410a5b56d80bd3bbd9ed621865f63fcbecb8e6142401a24621a0f81/Guake-3.4.0-py2.py3-none-any.whl (1.2MB)
    100% |████████████████████████████████| 1.2MB 1.2MB/s 
Collecting pbr (from guake)
  Downloading https://files.pythonhosted.org/packages/f3/04/fddc1c2dd75b256eda4d360024692231a2c19a0c61ad7f4a162407c1ab58/pbr-5.1.1-py2.py3-none-any.whl (106kB)
    100% |████████████████████████████████| 112kB 8.3MB/s 
Installing collected packages: pbr, guake
Successfully installed guake-3.4.0 pbr-5.1.1
You are using pip version 8.1.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
tdr@tdr-HP:~$ guake
[ERROR] Unable to start Guake, missing mandatory dependency: Keybinder 3
```

**Comment by gsemet** [comment]
Please read our documentation for the list of system dependency you need to install

**Comment by iamtodor** [comment]
@gsemet could you please help me figure out what do I do wrong?
```
tdr@tdr-HP:~$ pip install gir1.2-keybinder-3.0
Collecting gir1.2-keybinder-3.0
  Could not find a version that satisfies the requirement gir1.2-keybinder-3.0 (from versions: )
No matching distribution found for gir1.2-keybinder-3.0
```
Got this library from the [page](https://guake.readthedocs.io/en/stable/user/installing.html)

**Comment by gsemet** [comment]
Use apt-get install

**Comment by gsemet** [comment]
And never use pip install. Always pip install —user.

**Comment by iamtodor** [comment]
@gsemet got the following error:
```
tdr@tdr-HP:~/xor/projects/tools$ guake
Guake not running, starting it
Unable to load the GLib schema, try to compile it
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tdr/.local/lib/python3.5/site-packages/guake/main.py", line 295, in main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tdr/.local/lib/python3.5/site-packages/guake/guake_app.py", line 123, in __init__
    schema_source = load_schema()
  File "/home/tdr/.local/lib/python3.5/site-packages/guake/guake_app.py", line 119, in load_schema
    SCHEMA_DIR, Gio.SettingsSchemaSource.get_default(), False
GLib.GError: g-file-error-quark: Failed to open file '/home/tdr/.local/lib/python3.5/site-packages/data/gschemas.compiled': open() failed: No such file or directory (4)
Error opening directory '/home/tdr/.local/lib/python3.5/site-packages/data': No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.guake3.RemoteControl': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tdr/.local/lib/python3.5/site-packages/guake/main.py", line 295, in main
    remote_object = bus.get_object(DBUS_NAME, DBUS_PATH)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.guake3.RemoteControl was not provided by any .service files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tdr/.local/lib/python3.5/site-packages/guake/guake_app.py", line 123, in __init__
    schema_source = load_schema()
  File "/home/tdr/.local/lib/python3.5/site-packages/guake/guake_app.py", line 119, in load_schema
    SCHEMA_DIR, Gio.SettingsSchemaSource.get_default(), False
GLib.Error: g-file-error-quark: Failed to open file '/home/tdr/.local/lib/python3.5/site-packages/data/gschemas.compiled': open() failed: No such file or directory (4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tdr/.local/bin/guake", line 11, in <module>
    sys.exit(exec_main())
  File "/home/tdr/.local/lib/python3.5/site-packages/guake/main.py", line 410, in exec_main
    if not main():
  File "/home/tdr/.local/lib/python3.5/site-packages/guake/main.py", line 310, in main
    instance = Guake()
  File "/home/tdr/.local/lib/python3.5/site-packages/guake/guake_app.py", line 126, in __init__
    try_to_compile_glib_schemas()
  File "/home/tdr/.local/lib/python3.5/site-packages/guake/paths.py", line 97, in try_to_compile_glib_schemas
    subprocess.check_call(["glib-compile-schemas", "--strict", SCHEMA_DIR])
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['glib-compile-schemas', '--strict', '/home/tdr/.local/lib/python3.5/site-packages/data']' returned non-zero exit status 1
```

**Comment by gsemet** [comment]
no idea :( 

/home/tdr/.local/lib/python3.5/site-packages/data/gschemas.compiled does not seem to exist

**Comment by iamtodor** [comment]
@gsemet so true. I checked, I have no dir `data` in the following path: `/home/tdr/.local/lib/python3.5/site-packages/`. Although, I have there `guake` and `Guake-3.4.0.dist-info/` dirs.
Do you know what I could miss, what might be the reason for missing `data`?
