### ISSUE TITLE
Very big tray icon with Xfce and guake 0.8.4 

### ISSUE THREAD

**Issue by Bubu** [Guake/guake#710]
Reverting b2ce441ec40b7b053af18337c78ac2ed84cb1047 fixes this for me.

Related: #598

Before:
![guake-big-icon](https://cloud.githubusercontent.com/assets/105185/13111942/f3eec454-d588-11e5-9091-a7b8937c0e4f.png)

After fix:
![guake-normal-icon](https://cloud.githubusercontent.com/assets/105185/13111949/0416e4f6-d589-11e5-9bb0-cccf57f4c4e8.png)

**Comment by Bubu** [comment]
Still happening in 0.8.7 for me.

**Comment by Stibbons** [comment]
thx
