### ISSUE TITLE
Right click on tab + Rename = rename current tab instead of clicked tab

### ISSUE THREAD

**Issue by wmcmurray** [Guake/guake#718]
Steps to reproduce :
- Open at least two tabs
- Right click on a tab that is not your current tab
- Select "Rename" and rename the tab

This will rename the current tab instead of the clicked tab (as unexpected). I'm using Guake 0.7.2, maybe it has been fixed in 0.8.\* but I see no mentions of it in release logs !

BTW: Thanks **a lot** for this project, it's always the first package I install when landing on a fresh linux installation. I use Guake everyday and I vomit (mentally) when I use a computer without it !!

**Comment by micnic** [comment]
This bug is still persisting in the fresh version 0.8.8.

I would like to add that both, rename and close, commands from the context menu are targeting only the current tab instead of the one on which the context menu was opened.

**Comment by Stibbons** [comment]
This will be completely rewritten soon

**Comment by aichingm** [comment]
0.8.x ist not longer maintained, but this bug does not exist in the on the current 3.x.x version.

**Comment by phu** [comment]
Thanks for the update. I think it would be clearer to close 0.8.x-specific issues as wontfix (or otherwise change their status so they don't just show as open) to clarify that.

**Comment by Davidy22** [comment]
Many years later and this bug is fixed in the latest version, so I'm going to close this issue.
