### ISSUE TITLE
Feature Request : functionality to do guake -e [command [args]]

### ISSUE THREAD

**Issue by ashishgaurav13** [Guake/guake#720]
First off, great work with guake! I'm on Arch, and I use guake for nearly all of my cli activities. Recently, I got it to work with spacefm, by specifying the default terminal command to be
`guake -n $(pwd) --show`
Basically, if this command is TERM, then spacefm works by doing
`$TERM -e <command, args>`
The problem is that while urxvt etc. allow this natively, like you can do
`urxvt -e /bin/bash -c zip --help`
and this would open bash and pass
`zip --help`
to it, guake has the execute command functionality in the middle. So, you can do
`guake -e <one-word-command> [more options]`
or try
`guake -e "command in quotes" [more options]`
Unfortunately, spacefm doesn't have the option to set the command being passed in the TERM field. Would you be willing to accept a PR that adds this functionality? Like, if the last option is -e, the functionality becomes
`guake -e [command [args]]`
It's usually standard to have such execution abilities, I think.
Thanks once again, and guake is a great piece of software :)

**Comment by Davidy22** [comment]
Feature is implemented, closing.
