### ISSUE TITLE
Buggy $LINES and $COLUMNS not being set properly

### ISSUE THREAD

**Issue by sagebind** [Guake/guake#725]
When opening the first Guake tab, `$LINES` and `$COLUMNS` aren't set to reflect the size of the actual terminal, and are set as the default `24` and `80`, respectively.

I'm using Fish shell, and here is how to identify the issue. Add the following to the init file (`~/.config/fish/config.fish`):

```fish
echo "Size: $LINES x $COLUMNS"
```

Then opening the terminal gives the following output, even when the terminal is of a different size:

```fish
Size: 24 x 80
$> echo "Size: $LINES x $COLUMNS"
Size: 38 x 239
$> 
```

Observe that the variables are set correctly _after_ config files are loaded, which causes issues when running programs in init files that care about the terminal size.

Using a signal hook, I could observe the reason for this bug. Guake is sending `SIGWINCH` to the terminal, but after an unacceptable delay that causes issues with init scripts. `~/.config/fish/config.fish`:

```fish
echo "Size: $LINES x $COLUMNS"

function signal-hook --on-signal SIGWINCH
  echo "Size: $LINES x $COLUMNS"
end
```

And opening the terminal again:

```fish
Size: 24 x 80
$> Size: 38 x 239
$> 
```

The signal handler is triggered after some time (less than 1 second) showing the correct values.

Interestingly enough, none of these issues occur when creating a _new_ tab after this already happens to the first tab.

**Comment by Stibbons** [comment]
interesting indeed!

**Comment by sagebind** [comment]
Not sure what changed, but this doesn't seem to happen any more. Feel free to re-open the issue if any user seems to experience this.
