### ISSUE TITLE
even when set to linux console, colors are not the same as systems terminal

### ISSUE THREAD

**Issue by grg2rsr** [Guake/guake#731]
In my systems terminal, the prompt itself has a different color from the text. This is not the case for guake, even when the color settings are explicitly set to be equal to the system terminals. I found this to be a very nice visual guide to identify points in which I have issued commands when scrolling through a lot of output.

![screenshot from 2016-04-06 14-16-34](https://cloud.githubusercontent.com/assets/9695626/14316376/eb793818-fc02-11e5-932e-469fa8dc233c.png)

**Comment by nick-walt** [comment]
Surprised that there aren't any comments against this request. Coloration aids UX by reducing information noise. Would be a great experience if the themes could apply granular colouration to console elements, like the prompt.

**Comment by Stibbons** [comment]
I do have a customized prompt with plenty of colors using guake and zsh. there is no reason custom prompt cannot have colors in guake
