### ISSUE TITLE
Is there away to run guake as a standalone window

### ISSUE THREAD

**Issue by kmf** [Guake/guake#739]
I'm using Unity and when I <alt>+ <tab> between windows the app disappears, 
even though "Hide on loose focus" is disabled.

**Comment by ph-One** [comment]
What would be the benefit of running Guake as a standalone, versus running your standard windowed terminal (think {Gnome,Lx,Qt} Terminal)?

**Comment by Stibbons** [comment]
gnome-terminal ?

**Comment by kmf** [comment]
Better Desktop support eg. window functions, it's more for usability, a user can alt-tab between windows, the window manager is aware of the Application, that is more the feature that I would like.

**Comment by kmf** [comment]
Altyo has this feature

**Comment by sshishov** [comment]
I find guake usable because you may use hotkeys, i always on top and you may hide it when it is not needed. Very quick and useful.
If you need standalone terminal then you may use other terminals which are designed as standalone applications. Just IMO

**Comment by coffe-ok** [comment]
Is there a way for add Guake in Alt-Tab Menu, without show it in the panel?

**Comment by Stibbons** [comment]
guake and alt-tab are really not friend :(
