### ISSUE TITLE
Check portuguese translation

### ISSUE THREAD

**Issue by fit087** [Guake/guake#743]
at line 576 in

> guake/po/pt_BR.po

```
#: ../data/prefs.glade.h:106
msgid "_Reset Compatibility Options to Defaults"
msgstr "_Restaurar padrões para as opções de compatibilidade"

```
«`Reset Compatibility Options to Defaults`» can't be translated to «`Restaurar padrões para as opções de compatibilidade`»
the right translation is «`Restaurar opções de compatibilidade padrão`» or «`Redefinir opções de compatibilidade padrão`»

![guake](https://cloud.githubusercontent.com/assets/8249751/15098496/923bc640-1515-11e6-8bce-3c5865ace3d4.png)

**Comment by Stibbons** [comment]
Can you update the PO files?

**Comment by fit087** [comment]
sure! I sent a pull request
