### ISSUE TITLE
Esperanto translation

### ISSUE THREAD

**Issue by RobinvanderVliet** [Guake/guake#746]
I currently use Guake on an Esperanto version of Xubuntu, but the interface is still in English. I would like to translate Guake to Esperanto. I already requested Esperanto on Transifex, but I am still waiting for somebody to accept the language and add me (Transifex username: robin0van0der0vliet) as a translator/reviewer.

**Comment by Stibbons** [comment]
Submit a pull request

**Comment by robin0van0der0v** [comment]
A pull request? Shouldn't it be added [here](https://www.transifex.com/lincoln/guake/) first for me to translate everything easily?

**Comment by Stibbons** [comment]
Never used. Maybe it can create PL automatically. Normally you need to checkout and use poedit to edit a new po file with your translation. If you manage to use your site, please update the doc on how user can do it as well

**Comment by Davidy22** [comment]
Guake is now on [weblate](https://hosted.weblate.org/projects/guake/guake/) which should be a little easier to contribute on.

**Comment by Davidy22** [comment]
Weblate should allow opening any language without approval, closing.
