### ISSUE TITLE
Entered command cleared in the first tab when the second one is closed

### ISSUE THREAD

**Issue by drws** [Guake/guake#748]
Let me show you the bug by step-by-step reproduction:
1. enter a command into the first tab (and don't press the Enter key)
2. open another tab
3. close it
4. the last field of command input in the first tab is cleared ("ls -l" becomes "ls ", etc.)

Can someone reproduce this behaviour?

I'm currently on version 0.8.4 and Arch Linux.

**Comment by krassowski** [comment]
I can reproduce it in version 0.8.4

**Comment by souravbadami** [comment]
It can't be reproduced on Ubuntu 14.04.

**Comment by drws** [comment]
...where the latest version in the repository is 0.4.4. Apparently the bug appeared sometime in between.

**Comment by Stibbons** [comment]
indeed. Don't have time to dig it, but if one can hack in the python code to see when a clear command is sent to VTE, I'll welcome the PR

**Comment by drws** [comment]
Which bug is it a duplicate of?

**Comment by koter84** [comment]
i'm on Fedora 24 with guake 0.8.5 and i only get this bug when i use the hotkey (Crtl-Shift-W)
i can't reproduce when using the mouse with a rightclick on either the screen or the tab-panel

**Comment by drws** [comment]
This has been observed before - see #769, which also resolves this one. I have not updated this bug as I expect it to be closed in favor of #769 (which is more generalized).
