### ISSUE TITLE
Toggle quake visibility and BLOCK MAIUSC

### ISSUE THREAD

**Issue by cirelli94** [Guake/guake#751]
If I choose Alt + A as combination to toggle quake visibility and I have block maiusc off it works perfectly, if I have block maiusc on it just doesn't work!
If I go to change that preference in the prompt, and I try to set ALT+A, it says MAIUSC+ALT+A just because I have block maiusc on!
I think this is an involuntary behavior of the program!

**Comment by magebarf** [comment]
For anyone as stumped as me; MAIUSC is the shift key, in Italian terminology...

**Comment by cirelli94** [comment]
Oh yes, sorry...
Btw I don't know if the bug affects someone else

**Comment by Stibbons** [comment]
thanks for the report

**Comment by cirelli94** [comment]
I hope I explain well. I'll test the software if needed.

**Comment by cirelli94** [comment]
@magebarf with MAIUSC I mean both shift key pressed and caps lock on!
