### ISSUE TITLE
Guake requires three keystrokes before coming down

### ISSUE THREAD

**Issue by Spaak** [Guake/guake#753]
This has been bugging me for a while now (definitely several weeks/months, before that it was all fine): Guake often comes down only when I strike the toggle (tried setting the key to either backtick or F12, doesn't matter) three times in succession. This seems to be due to the currently active window having focus or something, because if Guake was previously showing, and then I click outside the window (causing it to hide, because I have 'hide on lose focus' set to on), and strike the toggle key again, Guake comes down immediately. However, if I (after hiding Guake) actively click in some other window and THEN strike the Guake toggle key, it again comes down only after three strikes.

Any idea what might be going on?

I am on Ubuntu 14.04, using Guake 0.8.4, just updated from a [.deb available at webupd8](http://ppa.launchpad.net/webupd8team/unstable/ubuntu/pool/main/g/guake/).

(Apologies if this is not the correct forum for this kind of support; I would have emailed a mailing list or so first but could not find one.)

**Comment by Spaak** [comment]
While I still have no idea what caused this, it seems to have been fixed by a simple reboot. (Note that just restarting Guake was not sufficient, it required a whole machine reboot.)

**Comment by Stibbons** [comment]
weird...
