### ISSUE TITLE
Paste "0~text1~"

### ISSUE THREAD

**Issue by mrlioncub** [Guake/guake#763]
Guake 0.8.4
Ubuntu 14.04,16.04 x64

After running Midnight Commander over time dosen't work pasting text in Guake.

Copy "text"
Inserted "0~text1~"

**Comment by corvus1** [comment]
It is a vte issue. You can find more information and a patch here https://bugs.launchpad.net/ubuntu/+source/vte/+bug/1350334

**Comment by Stibbons** [comment]
not related to guake. Cannot fix ti (however the switch to gtk3 might fix it)

**Comment by zend0** [comment]
Ubuntu 16.04.1
guake: 0.8.4-1

I have faced with the same problem, followed the link [https://bugs.launchpad.net/ubuntu/+source/vte/+bug/1350334](https://bugs.launchpad.net/ubuntu/+source/vte/+bug/1350334)  and I could not reproduce this problem in gnome-terminal, while at the same time in guake it is reproduced. What could be done in this case?

**Comment by corvus1** [comment]
> I have faced with the same problem, followed the link https://bugs.launchpad.net/ubuntu/+source/vte/+bug/1350334 and I could not reproduce this problem in gnome-terminal, while at the same time in guake it is reproduced. What could be done in this case?

Guess what, gnome-terminal already moved to the newer version of vte.

**Comment by zend0** [comment]
And how then guake turn to new VTE?

**Comment by corvus1** [comment]
> And how then guake turn to new VTE?

It will. Eventually. Some time in the future. Now there are two things you can do. You can path vte and fix the problem or you can wait indefinitely long for other people to fix it for you. The issue has been there for a couple of years now, and I don't see it going anywhere until guake switches to GTK3. Which might be a while.

**Comment by Stibbons** [comment]
indeed... gtk3 will solve many issues...

**Comment by corvus1** [comment]
And no doubt create many more.

**Comment by corvus1** [comment]
It's been fixed, guake switched to GTK3

**Comment by minerchuck** [comment]
Glad you made the switch :) I guess I should have checked my version (0.8.4). I must have removed the ppa line from apt. I've added it back and updated to 0.8.10 - no more spurious guff!

**Comment by corvus1** [comment]
0.8.10 is still GTK2
