### ISSUE TITLE
Guake uses deprecated gnome-common macros/variables

### ISSUE THREAD

**Issue by epsilon77** [Guake/guake#764]
Hi!

gnome-common did a cleanup upstream and deprecated quite a few macros
and variables. More info Please see: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=829969

Regards!

**Comment by Stibbons** [comment]
Damned!

**Comment by Davidy22** [comment]
Grepping for the items in the list brings up no results. Closing.
