### ISSUE TITLE
Closing the tab with hotkey produces unwanted input

### ISSUE THREAD

**Issue by drws** [Guake/guake#769]
Step-by-step reproduction:
1. in tab1 run a binary or a script which waits for an input
2. open tab2
3. close tab2 **with hotkey** (Ctrl+Shift+W)
4. ^W is produced in tab1, which kills the script waiting for an input

I'm currently on version 0.8.5 on Arch Linux and I am also enclosing a script for easier demo. It only echoes and waits for an input. The bug can be also observed using the reproduction steps in #748.

[guake_bug_demo.sh.txt](https://github.com/Guake/guake/files/356724/guake_bug_demo.sh.txt)

I think this bug also resolves #748 and its duplicate (doesn't say which one it is).

**Comment by Davidy22** [comment]
Keyboard shortcut code has been somewhat rewritten in git master. Does this still occur for the affected?

**Comment by drws** [comment]
Sorry I missed your months-old question... Confirming now that this issue seems resolved.
