### ISSUE TITLE
Can't show guake if nautilus is the current front/using software.

### ISSUE THREAD

**Issue by roachsinai** [Guake/guake#779]
I mean if I'm using the `Chrome, atom, terminator` and so on, I can use `guake` by press `F12`.

But if the current software my mouse focus on was `nautilus, gedit`, the `guake` didn't show.

`Fedora 24 upgrade from 23`

`Gnome 3.20.3`

**Comment by Stibbons** [comment]
that's really weird. Nothing appear? I use nautilus and gedit and guake still works, but not under gnome 3.20

**Comment by roachsinai** [comment]
Nothing appear, if my current using softwares are gnome's. Like `gnome-tweak-tool, caculator`.
And my Gnome was upgraded with the upgrading of Fedora.

**Comment by randUsr** [comment]
Same issue here. I cannot toggle the visibility with any Gnome application in focus. (tested with nautilus, tweaktool, calendar)

Running Arch Linux with GNOME 3.22.1

**Comment by andyfitz** [comment]
+1   have had to switch to drop down terminal extension (not as themable as Guake)

**Comment by randUsr** [comment]
Tried it again, running normal again! 
Still using Arch Linux but now Gnome 3.26.1

@andyfitz which version of Gnome are you using?

**Comment by EtaoinWu** [comment]
Cannot work as well in nautilus, gedit, and gnome-terminal.
Here's the screenfetch:
```
                          ./+o+-       Username@Computer
                  yyyyy- -yyyyyy+      OS: Ubuntu 17.10 artful
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 4.13.0-21-generic
           .++ .:/++++++/-.+sss/`      Uptime: 21h 56m
         .:++o:  /++++++++/:--:/-      Packages: 2185
        o:+o+:++.`..```.-/oo+++++/     Shell: zsh 5.2
       .:+o:+o/.          `+sssoo+/    Resolution: 1440x900
  .++/+:+oo+o:`             /sssooo.   DE: GNOME 
 /+++//+:`oo+o               /::--:.   WM: GNOME Shell
 \+/+o+++`o++o               ++////.   WM Theme: Adwaita
  .++.o+++oo+:`             /dddhhh.   GTK Theme: Numix-Dark [GTK2/3]
       .+.o+oo:.          `oddhhhh+    Icon Theme: PlataroNumix
        \+.++o+o``-````.:ohdhhhhh+     Font: 更纱黑体 UI SC 11
         `:o+++ `ohhhhhhhhyo++os:      CPU: Intel Core i3-3240 @ 4x 3.4GHz [27.8°C]
           .o:`.syhhhhhhh/.oo++o`      GPU: intel
               /osyyyyyyo++ooo+++/     RAM: 2306MiB / 3772MiB
                   ````` +oo+++o\:    
                          `oo++.      
```
Note that ubuntu 17.10 is running on wayland.

**Comment by EtaoinWu** [comment]
Relative to #1041 , #1024

**Comment by roachsinai** [comment]
Setting follow the README.md, guake drop down can work with gnome.
