### ISSUE TITLE
problem is drawn to a specific team

### ISSUE THREAD

**Issue by Artlant** [Guake/guake#785]
if you insert a link of this type that gets off the display on the terminal. The problem is not just with formatting and with rendering. Scroll does not work. Only the terminal restart

`wget http://st22.unibytes.com/fdload/fileGZtV9f5RgIKH6TEz4W90vo1nmK.moCCjxLVwu_kIcK.RKlrMLsPWkYjbJ7Z_iwTQ_28J6PjJvyRWYpfCbWwexGuQznzRLEEhSplgbpLlyYcQdYKGZtEDTgBB/Unfriended.2014.mp4v.ru.mp4?hj=12`
![screenshot from 2016-08-04 14-56-01](https://cloud.githubusercontent.com/assets/13064767/17400980/9b3eec62-5a53-11e6-9771-023fb60fbf19.png)

**Comment by Stibbons** [comment]
Cannot reproduce, works fine on my guake

**Comment by Artlant** [comment]
strange. I also can not repeat it Now
And if again you can somehow make a dump of the application or debug mode?  perhaps this bug is corrected version was then 0 8 4

**Comment by Stibbons** [comment]
you have logs if you start guake within a terminal

**Comment by Artlant** [comment]
I do not know which way but again I was able to repeat the bug. Maybe it's not the guake. The bug appears in strange circumstances. Perhaps the point is X11 or conky rear terminal. I have it always at the top. And sometimes stops updating content quake window (even the scroll bars), but if the team is to introduce new characters typed / team fray frozen contents of the terminal window. It is interesting that in other apps such was observed.

press but to reveal nature of the error I can not. But it appears when changing the status window (resize / fullscreen / show-hide) and remains until a complete restart quake

uname -a
Linux pc 4.6.4-1-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux
