### ISSUE TITLE
Guake shortcut stops working after using brightness keys

### ISSUE THREAD

**Issue by ccantill** [Guake/guake#789]
Whenever I use the brightness keys or the WiFi toggle key guake stops responding to the global shortcut until I restart guake. Tested on master.
- Dell Studio XPS 9550
- Elementary OS 0.4 Loki

**Comment by Stibbons** [comment]
I am affraid I'll not have enough information to do anything. It may be a bug in libkeybinder, please open a bug here: https://github.com/engla/keybinder

**Comment by Davidy22** [comment]
Keybinding has been rewritten somewhat, no longer occurs in git master. Also was likely a bug in other project. Closing.
