### ISSUE TITLE
Ubuntu 16.04 default python environment in my user profile is Anaconda Python2, unable to run guake “anaconda2/bin/python2: No module named guake”

### ISSUE THREAD

**Issue by enlighter** [Guake/guake#790]
I am creating an issue for this. Problem already described in this stackoverflow help request:

http://stackoverflow.com/questions/38922328/ubuntu-16-04-default-python-environment-in-my-user-profile-is-anaconda-python2

**Comment by Davidy22** [comment]
As described in the chosen answer, you'll want to make sure you're installing to the environment you're using.
