### ISSUE TITLE
Wronmg terminal width reported to bash prompt

### ISSUE THREAD

**Issue by refcodes** [Guake/guake#791]
I have a bash prompt defined in **~/.bashrc** as such:

<code>PS1=$(printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _)'\n\[\e[32m\]\u@\h\[\e[0m\] \[\e[33m\]\w\[\e[0m\] <\[\e[36m\]$(git symbolic-ref HEAD 2>/dev/null | cut -d"/" -f 3)$(svn info 2>/dev/null | sed -n "/URL:/s/.*\///p" | head -n 1 )\[\e[0m\]>\n> \[\e[33m\]\t\[\e[0m\] \[\e[36m\]\j \[\e[33m\]\s\[\e[0m\] \$ '</code>

The result of "**tput cols**" at evaluation time of **~/.bashrc** (setting up the prompt to P1) when hitting **F12** seems to be **80**, afterwards "**tput cols**" returns the correct value (in my case 277). When launching a new bash instance within that existing one, "tput cols" within evaluation of **~/.bashrc** correctly returns 277. 

Maybe we have a bug upon first initializing a bash within guake at evaluation time of **~/.bashrc** (resulting in an ugly prompt in my case). Other terminal windows do not have that problem, even though launching with console widths > 80 chars.

**Comment by Stibbons** [comment]
i use zsh and not have this pbl

**Comment by Stibbons** [comment]
not reproducted. Might comes from your environment
