### ISSUE TITLE
when I enter the command in Guake,the next line display the same command

### ISSUE THREAD

**Issue by bnpysse** [Guake/guake#794]
` donglida  ~  ls download/guake_0.8.4-1~webupd8~xenial0_amd64.deb 
klsdownload/guake_0.8.4-1~webupd8~xenial0_amd64.deb

 donglida  ~  ls
klsclone  download  examples.desktop  公共的  模板  视频  图片  文档  下载  音乐  桌面

 donglida  ~  `

`kls` will display the next line,Why?

And when I start the guake in the terminal,and the warning message will display:
`(guake:12952): libglade-WARNING **: unknown attribute`swapped' for <signal>.

(guake:12952): libglade-WARNING **: unknown attribute `swapped' for <signal>.
INFO:guake.guake_app:Logging configuration complete
/usr/lib/python2.7/dist-packages/guake/guake_app.py:1785: GtkWarning: gtk_box_pack: assertion 'child->parent == NULL' failed
  self.mainframe.pack_start(self.notebook, expand=True, fill=True, padding=0)
`

**Comment by Davidy22** [comment]
Guake has been ported to GTK3 since this was opened, reopen if this still applies
