### ISSUE TITLE
Guake looses keyboard setting

### ISSUE THREAD

**Issue by sm8ps** [Guake/guake#796]
Guake is running well here on Ubuntu 16.04 except for one little thing: I use an international keyboard layout in the desktop environment. For the Guake terminal I want to use the US keyboard (as for any terminal). I have made the layouts available and can switch between them by a key combination. However, I have to do this anew each time Guake becomes visible. For some reason the layout is always reset to the standard one. That becomes tiresome quite soon. 

In the system settings for keyboard layouts, I allow for different layouts among the windows and have new windows use the standard layout. If I change any of these then the behavior of Guake changes accordingly. So it seems that Guake is considered as a new window each time it is made visible. This conflicts with the usage of multiple keyboard layouts as described above. Is there anything that can be done about this behavior?

**Comment by synchrone** [comment]
On vanilla Ubuntu 16.10 I see this too. The settings persist after log-out, but not after reboot.

Any idea how to debug this?

**Comment by sm8ps** [comment]
Issue closed as per the #793.
