### ISSUE TITLE
Error message when running guake -h / guake -q / ...

### ISSUE THREAD

**Issue by Allaing** [Guake/guake#807]
Good evening sir

I get errors using any option when running guake
Your help is appreciated

I am using Debian Jessie 8.5 upgraded to stretch
My terminal is guake, GUI is Gnome 3.20

Regards
Alain

# guake -h

(main.py:4378): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(main.py:4378): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4378): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4378): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4378): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4378): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4378): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4378): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4378): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4378): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4378): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4378): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4378): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4378): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4378): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4378): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4378): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4378): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4378): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4378): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4378): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(main.py:4378): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(guake:4378): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/dist-packages/guake/main.py", line 243, in <module>
    exec_main()
  File "/usr/lib/python2.7/dist-packages/guake/main.py", line 234, in exec_main
    if not test_gconf():
  File "/usr/lib/python2.7/dist-packages/guake/common.py", line 53, in test_gconf
    return c.dir_exists('/apps/guake')
glib.GError: No D-BUS daemon running

--------------------------------------------------------------------------------------------------------------------------------

# guake -q

(main.py:4380): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(main.py:4380): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4380): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4380): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4380): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4380): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4380): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4380): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4380): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4380): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4380): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4380): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4380): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4380): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4380): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4380): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4380): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4380): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4380): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4380): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(main.py:4380): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(main.py:4380): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(guake:4380): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/dist-packages/guake/main.py", line 243, in <module>
    exec_main()
  File "/usr/lib/python2.7/dist-packages/guake/main.py", line 234, in exec_main
    if not test_gconf():
  File "/usr/lib/python2.7/dist-packages/guake/common.py", line 53, in test_gconf
    return c.dir_exists('/apps/guake')
glib.GError: No D-BUS daemon running

**Comment by Allaing** [comment]
I have found the solution
It's  a Gnome problem
gnome-themes-standard must be installed
Thank you for creating Guake

**Comment by Stibbons** [comment]
cool :p
