### ISSUE TITLE
Tab bar is too thin on HiDpi displays

### ISSUE THREAD

**Issue by jonathanballs** [Guake/guake#809]
The tab bar is too thin on UHD displays. This [screenshot](http://i.imgur.com/ag4Kwns.jpg) should demonstrate the problem.

This should be an easy fix but I'm not really sure where to start. If you tell me where to look I can work on it?

This is guake 0.8.4.

**Comment by bonniejools** [comment]
[The preferences](http://imgur.com/a/wd4bd) are also breaking.

**Comment by bonniejools** [comment]
I'm using a 4k screen.

I don't think the problem is the resolution per se but the scaling. I use 2x scaling for my monitor. I guess that the tab bar is ignoring the scaling factor and using a number of pixels suitable for normal 1x scaled monitor.

**Comment by ktrance** [comment]
I have the same issue and can confirm @bonniejools report that it is not a problem with the resolution but the scaling.

Zero display problem without the scaling

setup: dell xps13, Resolution 3200*1800, scale factor 2, ubuntu 16.04

**Comment by CyanBlob** [comment]
I have the same issue. 4k display, 1.5x scaling. Mine's slightly less pronounced, though. Probably do to the slightly lower scaling
![screenshot from 2016-09-17 22-04-39](https://cloud.githubusercontent.com/assets/5949523/18612550/cca2bcce-7d22-11e6-81a1-fcc682c21a71.png)

**Comment by josephbergevin** [comment]
I'm experiencing this issue on my 4k laptop monitor. Resolution 3840*2160, scale factor 2x. I agree that this is probably due to the scale factor (found in tweak tool) not being considered.

**Comment by nmaggioni** [comment]
Seems fixed - _at least for me_ - in v0.8.7 .

![schermata da 2016-10-26 08-49-51](https://cloud.githubusercontent.com/assets/3594528/19715962/3a25b8f6-9b59-11e6-9189-e92183f74045.png)

**Comment by bonniejools** [comment]
@nmaggioni Doesn't look fixed to me. Look at your username in the tab bar - the bottom of the g's are clipped. It's not as bad as some of the others but I don't think you're scaling is set as high.

**Comment by nmaggioni** [comment]
@bonniejools Might be, sorry for misreporting.

**Comment by zlatin** [comment]
Look like the cause of the problem is that [GTK2 does not support scaling](https://wiki.archlinux.org/index.php/HiDPI#GTK.2B_2).

**Comment by Stibbons** [comment]
Have you tried to scale gtk2 app with oomox-git ?

**Comment by zlatin** [comment]
In oomox you can create themes with GTK2 HiDPI option, which scales GTK2 UI. Here my try
![scale](https://cloud.githubusercontent.com/assets/5042466/20216145/a48952b4-a821-11e6-94a3-c4187fb8d872.png)
Black theme is 2x scaled. Could someone with 4k display try this?

**Comment by ljwagerfield** [comment]
Did this issue get resolved?

**Comment by bonniejools** [comment]
@ljwagerfield No it still seems to be quite broken on my arch setup.

**Comment by Stibbons** [comment]
Patience guys ! We were very active on the gtk3 branch!

**Comment by nmaggioni** [comment]
@ljwagerfield It is on my system (Manjaro, Gnome 3.26, XPS 13 QHD) :thinking:

**Comment by bonniejools** [comment]
@Stibbons Apologies. Wasn't trying to disparage anything :grin:

**Comment by aichingm** [comment]
@jonathanballs @ktrance @CyanBlob I have no display >FHD could you test and report if this issue still exists with the current guake version (>3.1.0)?

**Comment by jonathanballs** [comment]
@aichingm Yes I can confirm that scaling issues seem to be fixed. Thank you for your work on this! I tried to open the preferences but it caused guake to crash (this doesn't happen at normal DPI).

This may be an unrelated issue so I will investigate further and make a different report. I am happy for this issue to be closed however as it seems that the tab bar is now fixed :+1:
