### ISSUE TITLE
Ubuntu16.04 CTRL + super key + d closes terminal forever

### ISSUE THREAD

**Issue by jQrgen** [Guake/guake#817]
Hello

I am running Ubuntu 16.04

When i have the guake terminal open and focused and i press ctrl + super key + d it closes and i view the desktop.

Then my hotkey for opening the guake app (F3) stops working and i cannot open guake anymore.

**Comment by riotrick** [comment]
It's probably still running, but hidden by compiz, which won't let you reopen it.
An easy solution is to install compizconfig-settings-manager, open it (ccsm) and go to general -> general options. Disable "Hide Skip Taskbar Windows". That should fix your issue.

**Comment by jQrgen** [comment]
That worked, thanks!
