### ISSUE TITLE
Hide/show on fullscreen changes size

### ISSUE THREAD

**Issue by aykevl** [Guake/guake#819]
Possibly related to issue #445.

When I'm in full screen mode and I toggle guake (using F9 in my case), the terminal size (as seen from the program running in it) appears to change drastically. In this case, I'm running apt with the `Dpkg::Progress-Fancy` preference set to `"1"` and running big updates. Normally, when resizing a terminal with apt in it (using the fancy progressbar), this normally doesn't even happen unless I resize it fast enough. I suspect the width and the height changes at the same time.

![screenshot at 2016-09-29 11-40-31](https://cloud.githubusercontent.com/assets/729697/18949323/27b2b8c8-863b-11e6-9167-9b59bdeba942.png)

Settings:
![screenshot at 2016-09-29 12-09-25](https://cloud.githubusercontent.com/assets/729697/18949886/9c119f16-863d-11e6-9ab4-c2355272c8c0.png)

Guake version: 0.8.7-1 (in Debian testing/stretch)
Desktop: MATE 1.14.1 (window manager: marco 1.14.2).

**Comment by castorinop** [comment]
same problem
Guakeversion 0.8.8 (Fedora 25)
Desktop: Gnome 3.22

**Comment by Penaz91** [comment]
The same issue is visible in this screenshot: Guake 0.8.8 on Gentoo and NeoVIM.
It's particularly annoying since I have to untoggle/toggle fullscreen again to resize neovim as it was before.
![screen](https://cloud.githubusercontent.com/assets/6682630/22466401/5cae3214-e7c0-11e6-9088-62b15887f257.png)

**Comment by pecavalheiro** [comment]
Same here:

Guake 0.8.8
Debian 9 Stretch
Gnome 3.22.3

**Comment by karuvally** [comment]
Same issue on Vim.
Guake 0.8.8
Fedora 28 Workstation
Vim 8.1.233
