### ISSUE TITLE
Fontsize change shortcut support

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#82]
Fontsize change shortcut support http://guake.org/ticket/447
Reported by:    deathwarrior    Owned by:   somebody
Priority:   Fix available   Milestone:  0.5.0
Component:  guake   Version:    0.4.2
Keywords:   shortcut,keybinding,font,size   Cc:  
Description

In the version 0.4.2 of guake there is a lack of a shortcut for increase/decrease the fontsize(just like firefox and gnome-terminal).

I wrote the features, and I attach the patch files to do that. Tested and working.

Greetings folks and keep the awesome work, Ivan

**Comment by mabushey** [comment]
lol, almost a decade old and still relevant. Increment works, but decrement does not.

**Comment by Davidy22** [comment]
This is a different issue to yours, this issue refers to the shortcut not existing at all in options.
