### ISSUE TITLE
[Wayland] Guake does not appear when a GNOME application is focus

### ISSUE THREAD

**Issue by N3mesis98** [Guake/guake#825]
On GNOME 3.22 with Wayland (archlinux), if a GNOME application (like nautilus) is currently focused, typing on F12 does not make the Guake window appear.

**Comment by grafenhofer** [comment]
I experience the same issue unter Fedora 25 beta (i.e. Gnome 3.22.0, guake-0.8.7).

**Comment by grafenhofer** [comment]
This seems related to /a duplicate of the following issue: https://github.com/Guake/guake/issues/492

The following workaround works for me: https://github.com/Guake/guake/issues/492#issuecomment-119075514

**Comment by N3mesis98** [comment]
Ok, thank you for the workaround.
