### ISSUE TITLE
Font size in tabs and panel header

### ISSUE THREAD

**Issue by spekulatius** [Guake/guake#827]
Hello @Guake team!

thanks for building this awesome console! Its my favorite console tool :) After reinstalling the new elementary os 0.4 (based on Ubuntu 16.04) I noticed that the tab text is quite big. See screenshot: 

![screenshot from 2016-10-16 13 56 25](https://cloud.githubusercontent.com/assets/8433587/19414424/2a2fb332-93a9-11e6-98df-2d1804e1c273.png)

The same font size seems to apply to the preferences panel:

![screenshot from 2016-10-16 14 03 11](https://cloud.githubusercontent.com/assets/8433587/19414430/6fb6a8a2-93a9-11e6-968e-cf6cdfa61361.png)

Please let me know if you need any other information from my system.

Spek

**Comment by zlatin** [comment]
Do you use scaling? Issue #809 looks very similar to yours.

**Comment by spekulatius** [comment]
Yes, that looks very similar.

@zlatin I'm not sure if scaling is active. How can I verify this?

**Comment by Stibbons** [comment]
Look scaling is messing with guake :(

**Comment by zlatin** [comment]
You can try 
`gsettings get org.gnome.desktop.interface scaling-factor`
if it's not 0 or 1, your UI is scaled.

**Comment by spekulatius** [comment]
Thanks @zlatin It seems to be off:

peter@xps:~$  gsettings get org.gnome.desktop.interface scaling-factor
uint32 0

**Comment by ringe** [comment]
This is an issue for me also. The scaling is off, yet the fonts are too large.

Ubuntu Gnome 16.10

![guake-font](https://cloud.githubusercontent.com/assets/778570/21696057/9280ed02-d38c-11e6-8506-f936e4fc5d7c.png)

**Comment by ringe** [comment]
By the way, I'm on the Dell XPS 13 developer edition, so I'm thinking this is related to #809. Does guake run on GTK2 still?

**Comment by ck-alpha** [comment]
I can confirm that this bug still exists running Guake in ubuntu 14.04. My scaling factor is 1

**Comment by ck-alpha** [comment]
I purposely have the text bigger because guake is on my HTPC viewed on a TV at a distance. But the bar is not enlarging to fit the text

**Comment by Stibbons** [comment]
can you try with latest HEAD?

**Comment by ck-alpha** [comment]
I am trying to build but when I 'make dev' I get an error about dulwich==0.18.6 and can't figure out why as I have it already ..
Failed building wheel for dulwich

**Comment by Stibbons** [comment]
You are still on ubuntu 14.04 ? I am afraid this will be quite a too old version of ubuntu to support...

**Comment by ck-alpha** [comment]
Ubuntu 14.04 is LTS so I have every intention of using it for the supported 5 years

**Comment by Stibbons** [comment]
dulwich is installed by `reno`. Can you try a `pip install --user reno` to see if it can be installed?
```
reno==2.6.0
  - dulwich [required: >=0.15.0, installed: 0.18.6]
  - pbr [required: Any, installed: 3.1.1]
  - PyYAML [required: >=3.1.0, installed: 3.12]
  - six [required: >=1.9.0, installed: 1.11.0]
```

**Comment by ck-alpha** [comment]
make dev had almost succeeded (i hadn't installed python dev package which is why dulwich wasn't building) but there were missing .git dir as I had cloned via zip file... so did git clone and tried again,

but now make dev is failing on reno although I can install via pip install...

it's probably my setup...

**Comment by Davidy22** [comment]
Guake has been ported to GTK 3 since this was filed, reopen if still relevant
