### ISSUE TITLE
Toggling guake scrolls terminal

### ISSUE THREAD

**Issue by fprawits** [Guake/guake#832]
Hitting F12 twice to toggle guake on and off scrolls the whole output as if a bunch of new lines would have been added (see included images).

Guake with some random output to fill the screen and show maximum effect of unexpected behaviour:
![screenshot from 2016-10-27 13-56-55](https://cloud.githubusercontent.com/assets/10351100/19766695/94734bba-9c4f-11e6-86f7-5aca5174e3f5.png)
Guake after hitting F12 twice:
![screenshot from 2016-10-27 13-57-07](https://cloud.githubusercontent.com/assets/10351100/19766698/97a50418-9c4f-11e6-9914-c9f0b9b9ff6c.png)

Note that hitting F12 afterwards will again scroll the screen by probably the same amount. I can't tell for sure since after hitting F12 another two times the terminal is scrolled so far that I am left with a blank screen.

Typing anything other than the keybindings F12 (toggle guake) and F11 (min/max window) however instantly "jumps" everything back to normal. This bug started appearing when I upgraded my guake version to 0.8.7 on my unbuntu 16.04 x64 machine, unfortunately I cannot remember which version I was using before. I did a `git pull`and install via `./dev.sh --install` a few minutes ago and the bug is still persistent in the current master branch. The bug also appears when toggling fullscreen via F11.

Additionally I noticed the following output when I start guake via the terminal, which might be related to this issue:
when starting guake:

> (guake:4408): libglade-WARNING **: unknown attribute `swapped' for <signal>.
> INFO     Logging configuration complete
> DEBUG    do not set background from user

and after pressing F12 twice the following lines appear:

> /usr/local/lib/python2.7/dist-packages/guake/guake_app.py:884: GtkWarning: IA__gtk_window_set_type_hint: assertion '!gtk_widget_get_mapped (GTK_WIDGET (window))' failed
>   self.window.set_type_hint(gtk.gdk.WINDOW_TYPE_HINT_DOCK)
> /usr/local/lib/python2.7/dist-packages/guake/guake_app.py:885: GtkWarning: IA__gtk_window_set_type_hint: assertion '!gtk_widget_get_mapped (GTK_WIDGET (window))' failed
>   self.window.set_type_hint(gtk.gdk.WINDOW_TYPE_HINT_NORMAL)
> DEBUG    do not set background from user

additional F12 toggling afterwards just reproduces the DEBUG message.

Please let me know whether this information is sufficient to tackle this issue and if this even is a bug in the current branch or just a problem on my machine due to some faulty configuration. I am happy to provide any additional info in case something is missing and would be very grateful for any help for the case that I simply misconfigured guake. Note that I haven't installed the glade-gtk2 package since it isn't in the repositories for ubuntu 16.04, but from what I figured it should not be needed for guake to work properly.

**Comment by fprawits** [comment]
Just noticed that this is very likely to be a duplcate of [this issue](https://github.com/Guake/guake/issues/784l), so it seems that multiple people are affected by this.

**Comment by fievelk** [comment]
I have the same issue using xubuntu 16.04.

**Comment by jatindhankhar** [comment]
Sorry to ping a old thread but exact same issues happens with me. I have two machines both running Arch Linux with Gnome along with guake. 
Only workaround is to run each session inside tmux which uses explicit keys to scroll.

**Comment by melmi** [comment]
I've never had this issue until updated to ubuntu 17.04.

**Comment by narukamiko** [comment]
I also have this issue. Is there some solutions now?

**Comment by YanDoroshenko** [comment]
Can confirm. Arch Linux, guake 0.8.11.

**Comment by Davidy22** [comment]
A rewrite was done, issue no longer appears to occur and no reports submitted since the rewrite, closing.

**Comment by zugzwang** [comment]
I am seeing this on Ubuntu 24 after an upgrade from Ubuntu 20. First time to ever encounter this.
```
$ guake --support
<details><summary>$ guake --support</summary>

Guake Version:		3.10

Vte Version:		0.76.0

Vte Runtime Version:	0.76.0

--------------------------------------------------
GTK+ Version:		3.24.41

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: i3

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - CMN eDP1
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		310 x 170 mm²
    * Primary:		True
    * Refresh rate:	60.001000000000005 Hz
    * Subpixel layout:	unknown
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.2 LTS
Release:	24.04
Codename:	noble
```

**Comment by jakwinkler** [comment]
Same issue on Fedora Workstation 42, Gnome Env.

```<details><summary>$ guake --support</summary>

Guake Version:		3.7.0

Vte Version:		0.80.3

Vte Runtime Version:	0.80.3

--------------------------------------------------
GTK+ Version:		3.24.49

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: gnome

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 -  DP-1
    * Geometry:		5120 x 1440 at 0, 0
    * Size:		1190 x 340 mm²
    * Primary:		True
    * Refresh rate:	119.95 Hz
    * Subpixel layout:	unknown
