### ISSUE TITLE
Tab Renaming Broken By New Tabs

### ISSUE THREAD

**Issue by machineghost** [Guake/guake#833]
Previously (https://github.com/Guake/guake/issues/795) I was able to set Guake to start up with a pre-specified tab set using the following pattern in my `.guake-start.sh` file:

    #!/bin/bash

    /usr/bin/guake &
    sleep 2 # let main guake process start and initialize D-Bus session
    guake -r "Name of First Tab" -e "commandToRunToStartFirstTab"
    guake -n " " -r "Name of Second Tab" -e "commandToRunToStartSecondTab"
    guake -n " " -r "Name of Third Tab" -e "commandToRunToStartThirdTab"
    guake -s 0

However, I recently tried to setup Guake on a new machine with version 0.8.7 (the latest version in the alternative PPA listed on the GitHub front page) and discovered that the above pattern no longer works.  While it does still generate the desired tabs, and does run the desired commands, it does not rename any of the tabs except the last one ...

... or, to be more accurate, it does rename each tab initially, but then milliseconds later when it adds the next tab the act of adding the next tab somehow resets the name of the previous tab to "Terminal".  Because of this only the last tab keeps its name.

If this is user error, and I should use a different pattern for renaming my startup tabs, please let me know, but based on `guake --help` (and given that the commands used to work) this *seems* like a bug.

**Comment by ivoshm** [comment]
Looks line #804 or #812 ...

**Comment by TheJavaGuy** [comment]
It still happens to me, guake 0.8.8, Ubuntu 14.04 LTS

**Comment by machineghost** [comment]
Just noticed this also breaks tab naming when you create a new tab, ie.

1. Name a tab
2. Open a new tab
3. Your name from #1 is gone

**Comment by Davidy22** [comment]
Fixed since this was filed, closing.
