### ISSUE TITLE
Splitting feature

### ISSUE THREAD

**Issue by ehouarn-perret** [Guake/guake#834]
Would be nice to be able to split the terminal (a bit like terminator or other terms), I mean vertically that would be useful.
Dunno whether it's doable or not (need to dig into the sources someday).

Anyway nice job overall!

**Comment by zlatin** [comment]
@ehouarn-perret  look at this thread #71 
I'd recommend looking at byobu if you really need splitting feature right now.

**Comment by ehouarn-perret** [comment]
@zlatin thanks, I was pretty sure I was not the only one looking for that feature
