### ISSUE TITLE
Guake disappears after pressing ctrl

### ISSUE THREAD

**Issue by RuijieYu** [Guake/guake#836]
Hello. 
I am reporting a bug that guake disappears after pressing ctrl key, when in preferences the option "hide on lose focus" is enabled.

I have a freshly installed Ubuntu Mate 16.10, with newest version of guake. According to `guake -a` it is version 0.8.5. 
In preferences I have turned on "hide on lose focus" (which is the problem), changed the appearance to "Wild Cherry", turned on "Scroll on output", changed the toggle guake to F10, had a different window height and transparency, and nothing else. 
The first time I noticed it is when I tried to copy some text (with ctrl+shift+C), and the window disappeared. I later tried to only press ctrl, and the window also disappeared.
I tried to disable the "hide on lose focus", and this time the window did not disappear, so my guess would be that there is something buggy in this choice. 

Thank you for looking into this problem!
James

**Comment by Stibbons** [comment]
I have the same issue with Alt key :(

**Comment by schnittchen** [comment]
I have the same now with gnome 3 after upgrading to Ubuntu 17.4

**Comment by lvm3n** [comment]
Same here on elementary os Loki 0.4.1.

**Comment by schnittchen** [comment]
There's an accessibility setting to show the mouse cursor with a glow when, IIRC, hitting the Ctrl key. Maybe this has the effect of guake losing focus?

**Comment by RaiSaugat** [comment]
Faced the same issue. Disable hide on lose focus and it's working fine now.:)

**Comment by croxx5f** [comment]
Hey @schnittchen , just checked and I had Locate pointer activated in Gnome, after disabling it Guake continues to work as expected **without** disabling hide on lose focus. Thanks!

**Comment by maisonhai3** [comment]
> Hey @schnittchen , just checked and I had Locate pointer activated in Gnome, after disabling it Guake continues to work as expected **without** disabling hide on lose focus. Thanks!

Yes, deactivate `Pointer Location` will correct this issue.

To to that, you could install `tweak` tool with [this guide](https://linuxconfig.org/how-to-install-tweak-tool-on-ubuntu-18-04-bionic-beaver-linux).

**Comment by Davidy22** [comment]
Resolved by turning off accessibility tools that activate on hitting control. Such tools should probably be bound to a ctrl+[key] binding anyways, closing.
