### ISSUE TITLE
Add tab clone

### ISSUE THREAD

**Issue by micnic** [Guake/guake#846]
*This is a feature request*

I do need often to open two (or more) tabs with the same working directory, it would be nice to have the possibility to clone the tab and have the same working directory in the new one. I would suggest to add a new item in the context menu of the tabs, something like "Clone tab" or "Duplicate tab".

**Comment by mad-gooze** [comment]
You can execute `guake --new-tab=$(pwd)` which will open new guake tab in current directory. You can also make an alias for that command.

If you use fish and its oh-my-fish plugin manager, you can install [plugin-tab](https://github.com/oh-my-fish/plugin-tab), which now supports guake.

**Comment by zqb-all** [comment]
You can try to add this to .bashrc

> alias cloneguake='tablabel=`guake -l` && guake -n `pwd` && guake -r $tablabel'

or

> alias cloneguake='tablabel=`guake -l` && tabpath=`pwd` && guake -n 1 && guake -e "cd $tabpath" && guake -r $tablabel'

**Comment by Davidy22** [comment]
Guake now has a "Open new tab in current directory" option under shell in Guake preferences.
