### ISSUE TITLE
Is there a way to enable guake to intercept Ctrl+Tab

### ISSUE THREAD

**Issue by guakamole** [Guake/guake#852]
Hello,

Thank you for Guake, it is a tremendously useful tool that I use on a daily basis. :green_heart:

Is there a way to enable guake to intercept `Ctrl`+`Tab` and the likes (`Ctrl`+`Shift`+`Tab` etc.)?

It seems like it is doable in other term emulators (see [xterm](http://www.staldal.nu/tech/2009/01/10/how-to-use-ctrl-tab-in-gnu-screen/) for example).

**Comment by Stibbons** [comment]
seems to be a limitation of libkeybinder :(

**Comment by Davidy22** [comment]
Guake now supports tabs in keyboard shortcuts
