### ISSUE TITLE
Is there a way to customize the tab-bar style?

### ISSUE THREAD

**Issue by guakamole** [Guake/guake#853]
Hello,

(this question might be related to #390)

I use Guake in Debian (8.4) with Gnome (3.14.1) and the Global Dark Theme (and _Adwaita_ for everything else).

This how the Guake tab-bar looks like:

![screenshot from 2016-11-25 01 26 30](https://cloud.githubusercontent.com/assets/23730133/20611714/adba04da-b2af-11e6-8230-b2bdf85b98b1.png)

And this is how my other menu bars looks like system-wide:

![screenshot from 2016-11-25 01 34 22](https://cloud.githubusercontent.com/assets/23730133/20611699/66cd8128-b2af-11e6-9382-37c9a180a6cf.png)

I could do the styling myself but I do not know if it is possible and where are the relevant config files. Is there a way to customize the tab-bar style?

**Comment by kitingChris** [comment]
I would also like to see to at least switch to a dark theme.

**Comment by Stibbons** [comment]
Indeed, this has been requested several times :) #618
Hopeful now using gtk3 it should only be a matter of time before dark theme land in Guake.

I think the tab bar by itself should be redesigned, tab such as gnome terminal is really nice looking and helpful (it displays the current running command). So yes, it is definitively a must have :)

I cannot give too much hint on how to change the tabbar, it is one of the legacy code that actually needs to complete rewrite :(

**Comment by dermidgen** [comment]
@guakamole #1693 lets you modify `~/.config/gtk-3.0/gtk.css` and theme it how you want.  While we wait for official support, you can modify `guake_app.py` to set the window ID.  On my system it's an older version and it's at `/usr/lib/python3/dist-packages/guake/guake_app.py`. 

From there you can update `~/.config/gtk-3.0/gtk.css` with something like:

```
#guake-terminal {
  background-color: #333;
  font-size: 11px;
}

#guake-terminal box box scrolledwindow viewport widget {
  padding: 0px;
  margin: 0px;
  font-size: 11px;
}

#guake-terminal box box scrolledwindow viewport widget box.horizontal button {
  padding: 0px;
  margin: 2px 0px;
  border: 0px;
  border-radius: 0px;
  background-image: none;
}

#guake-terminal box box scrolledwindow viewport widget box.horizontal button label {
  padding: 0px 8px;
  background-color: #222;
  margin: 0px;
  border-radius: 4px;
  border: 1px solid #333;
  color: #eaeaea;
}

#guake-terminal box box scrolledwindow viewport widget box.horizontal button:hover label {
  padding: 0px 8px;
  background-color: #555;
  margin: 0px;
  border-radius: 4px;
  border: 1px solid #333;
  border-top-color: #666;
  border-right-color: #666;
  border-bottom-color: #555;
  border-left-color: #555;
  color: #eaeaea;
}

#guake-terminal box box scrolledwindow viewport widget box.horizontal button:checked label {
  padding: 0px 8px;
  background-color: #444;
  margin: 0px;
  border-radius: 4px;
  border: 1px solid #333;
  border-top-color: #555;
  border-right-color: #555;
  border-bottom-color: #444;
  border-left-color: #444;
  color: #eaeaea;
}
```

**Comment by dermidgen** [comment]
@gsemet we can probably close this ticket now

**Comment by Davidy22** [comment]
Closing since patch pulled and we're also on gtk 3 with the look that original poster wanted anyway now.
