### ISSUE TITLE
Custom tab names lost after opening new tab

### ISSUE THREAD

**Issue by wil93** [Guake/guake#855]
If I have some tabs, and then I rename them (double click on the tab name, in the bottom, and then type new name), and then I open a new tab (CTRL+SHIFT+T) all tab names get reset to the default name.

The correct behavior should be: the tab names are always kept unchanged if they have been customized

**Comment by zlatin** [comment]
Try latest version from trunk. The bug is fixed there.

**Comment by wil93** [comment]
@Stibbons what about a 0.8.8 release? :pray: :smile:

**Comment by wil93** [comment]
This is really annoying please fix :sob:

**Comment by Stibbons** [comment]
I am on it :)
