### ISSUE TITLE
Terminal position at bottom problem with Gnome3/Wayland

### ISSUE THREAD

**Issue by phyrog** [Guake/guake#860]
When setting the terminal to open at the bottom, the terminal is opened at the top of the screen and then jumps down to the bottom.

I'm using Guake 0.8.7 and Gnome 3.22.1 on Arch Linux with a Wayland session.

**Comment by stanfieldr** [comment]
My pull request in #844 seems to fix this issue as well

**Comment by phyrog** [comment]
Can confirm that this issue is fixed on the master branch. Thanks for your PR, @stanfieldr
