### ISSUE TITLE
Active tab indistinguishable from inactive tabs

### ISSUE THREAD

**Issue by wil93** [Guake/guake#861]
The "active tab" color makes it indistinguishable from other inactive tabs, on my PC. I can't tell right away which is the active tab, and I need to quickly switch between two tabs in order to see which tabs I am in.

Can I set the background color of the tab to some color with higher contrast like red instead of gray?

**Comment by Stibbons** [comment]
indeed. We will see how we can address that in a full rewroten version, in the future

**Comment by ojura** [comment]
I have something to add here:
https://github.com/Guake/guake/blob/master/src/guake/guake_app.py#L840

When using dark gtk themes, the "light" gtk widget color makes the active tab unreadable (on my machine, I swapped this with "dark").

**Comment by Stibbons** [comment]
good catch

**Comment by saddy001** [comment]
I wanted to open an issue but now found this one.

**Comment by ka4eli** [comment]
+1

**Comment by ismaail** [comment]
This if fixed in v3.0.5
![image](https://i.imgur.com/D9ptscl.png)

**Comment by gsemet** [comment]
thanks for your report!
