### ISSUE TITLE
Hiding tabs section so i can use guake truly fullscreen

### ISSUE THREAD

**Issue by NikosEfthias** [Guake/guake#862]
Is there an option to hide the bar where tabs are?

**Comment by Davidy22** [comment]
There are presently now a multitude of tab bar visibility options, closing.

**Comment by NikosEfthias** [comment]
@Davidy22 well this is from 2016 tho :D.

**Comment by Davidy22** [comment]
Yeah, was appointed new maintainer near end of last year and I'm very slowly digging through the issues backlog
