### ISSUE TITLE
guake depends on python-gnome2 which deprecated in Debian

### ISSUE THREAD

**Issue by epsilon77** [Guake/guake#863]
Hi

guake depends on python-gnome2 or python-gconf, or has a build-dependency on one those packages. Those are built from gnome-python which is long deprecated and going to be removed from the archive. guake should be ported away from it.

it's necessary to port it if we want to Guake continues in the Debian Archive :(

Please more info about this issue
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=845949

Really thank you very much!

**Comment by Stibbons** [comment]
Indeed, I started to port to guake3, gtk3, and dconf. Need quite some time to finish it, but I need to do it

**Comment by mouseratti** [comment]
@Stibbons I'd like to join to the process. May I?

**Comment by Stibbons** [comment]
hum i'll need some days to proper the environment, i actually want to start from scratch, but yes, help would be welcome on some module! There are some module that will need rewrite: window placement and overall management, dconf, stuff like this

**Comment by mouseratti** [comment]
can we use **setuptools** in project? maybe, we could move gtk3 files to another branch?

**Comment by Stibbons** [comment]
of course, I want to use pbr, setup tool, pip and everything else. There is already an old gtk3 branch... but quite old

**Comment by mouseratti** [comment]
we can also use python3 and pytest for testing. Can you give me a work plan or roadmap or I can make it 	
independently?

**Comment by Stibbons** [comment]
of course :) ok, if you want to participate, I'll build a roadmap this week end

**Comment by Stibbons** [comment]
done
