### ISSUE TITLE
alt/ctrl keys do not passthrough to terminal applications

### ISSUE THREAD

**Issue by saterHATER** [Guake/guake#865]
using tmux version 0.2.3 I am unable to use alt-based or ctrl-based hotkeys within guake. I can, for example use alt-based hotkeys in gnome-terminal for my tmux-y goodness.

For example, here's a bit of my ~/.tmux.conf: 
```
bind -n M-h select-pane -L 
bind -n M-j select-pane -D 
bind -n M-k select-pane -U 
bind -n M-l select-pane -R 
```
And if basically moves me around my panes with the vim bindings. If I press alt-k, i'd move down a pane. This, of course, doesn't happen when I run tmux in guake. 

I am aware this is likely an identified issue listed in another defect. I apologize that I was not able to find such a defect in my 5 minutes of searching through your defects.

**Comment by vasilakisfil** [comment]
I guess comes from tmux-vim integration? Works for me on Guake 0.8.5..

**Comment by saterHATER** [comment]
Hmm, I seem t o be using 0.8.0. I'll update my version and see where we're at. I kinda wish it was easier to get the version.

**Comment by saterHATER** [comment]
I'm failing to build the most-recent update. I found that I was using 0.8.3, so I think I'll close this issue based on @vasilakisfil observations. If I find any evidence to the contrary I'll re-open this issue if I can.
