### ISSUE TITLE
Guake 0.8.8-1 full width

### ISSUE THREAD

**Issue by Upgreydd** [Guake/guake#870]
In guake 0.8.8-1 when I set full width, everytime I hide and show guake i see width 3/4. I need to create new tab or change width in settings, then width fallback to full until I again hide and show.
I falledback to 0.8.7-1 - there's no problem with that.

**Comment by Stibbons** [comment]
can you describe you system?

**Comment by Upgreydd** [comment]
@Stibbons Arch linux standard instalation with gnome shell. I'll get back to home and add you more info

**Comment by wiecia** [comment]
I have exactly the same setup and the same problem - every hide & show sets guake window to 3/4 screen width. In additional I'm using laptop with additional monitor. When guake opens on my monitor it's width is clipped but when it opens on laptop everything is fine. My guess is it somehow takes th resolution of my laptop screen when opening on standalone monitor (which res is much higher)

**Comment by LaurentDumont** [comment]
Same issue here with 8.8-1 - Falling back to 7-1 fixes the issue. On 8-1, if I open a new tab, the guake goes full screen but closing and reopening guake makes it go 3 third of the screen wide again. If I select the fullscreen option, it does go fullscreen.

```
Distributor ID:	Debian
Description:	Debian GNU/Linux unstable (sid)
Release:	unstable
Codename:	sid
```

`Linux petitepatate 4.8.0-2-amd64 #1 SMP Debian 4.8.11-1 (2016-12-02) x86_64 GNU/Linux`

```
[laurent@petitepatate:~] 130 $ sudo cat /usr/share/gnome/gnome-version.xml
<?xml version="1.0" encoding="UTF-8"?>
<gnome-version>
 <platform>3</platform>
 <minor>22</minor>
 <micro>2</micro>
 <distributor>Debian</distributor>

```

**Comment by tombriden** [comment]
I've been having this problem too and narrowed it down to this commit https://github.com/Guake/guake/commit/9999e714994d5de3255899c6da62066d937d175c

Reverting that fixes the issue.

**Comment by SgLy** [comment]
Some problem here with latest arch linux, standard gnome 3 installation

**Comment by Stibbons** [comment]
ok I revert this patch
