### ISSUE TITLE
guake doesn't display UTF-8 characters

### ISSUE THREAD

**Issue by initzx** [Guake/guake#877]
init0@init6 ��� ~ ��� 

I get these symbols when running zsh powerline in guake, but it has proven to work in terminator as shown here.

init0@init6  ~  

I am currently running Arch linux and I am quite sure this has something to do with the character encoding used by guake. are there any ways to change this?

**Comment by lokeshthegenius** [comment]
Make sure you have powerline fonts installed and configured on your system. You also need to restart guake to have its font in guake-prefs.

In Ubuntu it can be done by following commands, you can seek out for Arch yourself: 

    sudo apt install fonts-powerline
    sudo fc-cache -f -v
    

After then, make sure the font is set to **powerline symbols medium** in appearence tab in guake-prefs.

**Comment by Stibbons** [comment]
works indeed on my screen. I also suspect gtk2 which is pretty old
