### ISSUE TITLE
complete guake main window (gtk3)

### ISSUE THREAD

**Issue by mouseratti** [Guake/guake#879]
I'd like to make main window, if you don't mind

**Comment by mouseratti** [comment]
``` 
python guake/main.py 
Traceback (most recent call last):
  File "guake/main.py", line 25, in <module>
    import logging
  File "/home/mfast/PROJ/guake3.git/guake/logging.py", line 29, in <module>
    import logging.config
ImportError: No module named 'logging.config'; 'logging' is not a package
```
Looks like names crossing of **guake.logging** and python builtin module **logging**
I propose to rename guake.logging to guake.log or something similar.

**Comment by Stibbons** [comment]
Can you describe me what do you plan, so i can see if we do not overlap our work?

beware, guake.py will only handle the general behaviour, interactions with setting etc. Current `Guake` module is far too huge, does too many things. I'd like to follow the max of [SOLID principles](https://en.wikipedia.org/wiki/Single_responsibility_principle). For the very window ported to gtk3, maybe it is a good idea to write a component `GuakeWindow`. Also, I would like to have each component in a single file (a la java) for easing unit tests.


For logging stuff, do you use absolute_import ? it a pity if we cannot name a module `guake.logging` and still have the standart `logging` module both available. If it does work, rename to `guake_logging.py`

**Comment by mouseratti** [comment]
> For logging stuff, do you use absolute_import ?

Sorry, my fault, didn't know about that. It works well with **absolute_import**

**Comment by mouseratti** [comment]
> Can you describe me what do you plan, so i can see if we do not overlap our work?

I'm going to make an Application, Window classes and use GuakeTerminal class from guake/terminal.py
According to http://python-gtk-3-tutorial.readthedocs.io/en/latest/application.html, a proper way to write gtk3    apps  is using Application instance.
I also have converted ***.glade** files to actual ***.ui** format and now plan to use them as sources for [Gtk.Builder](http://python-gtk-3-tutorial.readthedocs.io/en/latest/builder.html)

You can find current result of my work in PR #880, but do not need to merge it.

**Comment by Stibbons** [comment]
Look great! I encourage you to multiple the mergeable pl so we can work in parallel, even if the program is not functional on the guake3 branch. I don't like having several big bang pull request waiting, this make the merges/rebases a nightmare. guake3 branch is here for experimentation so as soon as you have something, we merge it and advance :)

**Comment by mouseratti** [comment]
Also, as I understand, [documentation](http://python-gtk-3-tutorial.readthedocs.io/en/latest/application.html#example) says that we can make a single instance of Application class and attach **about**-dialog as  Gtk.AboutDialog and **prefs**-dialog  as Gtk.Window to an app.  I mean we do not need to make preferences as a separated process.

**Comment by Stibbons** [comment]
ok, i prefer everything in a single app. just have a way to start the pref window to reset the hotkey for example with `guake --prefs`

**Comment by mouseratti** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/6256753/22039059/e8a22abc-dd27-11e6-8dde-7145845f6b2f.png)
I have added a notebook with "add new page" button placed into tab. @Stibbons what do you think?

**Comment by Stibbons** [comment]
done
