### ISSUE TITLE
Add option to start at startup

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#88]
Add option to start at startup http://guake.org/ticket/438
Reported by:    daho    Owned by:   somebody
Priority:   major   Milestone:  0.5.0
Component:  guake   Version:  
Keywords:       Cc:  
Description

I now always first have to startup Guake before being able to use the shortcuts to call the terminal. As I regularly need the terminal it would be much more convenient for me to be able to select an option to start quake when logging in. (in the same way as i.e. GnomeDo?)

**Comment by sayanriju** [comment]
https://github.com/linuxmint/Cinnamon/issues/2364
