### ISSUE TITLE
Guake Won't Start...Maybe there's an association with the latest python updates?

### ISSUE THREAD

**Issue by spookykidmm** [Guake/guake#887]
inxi -SG
System:    Host: GoldenArches Kernel: 4.8.14-1-zen x86_64 (64 bit)
           Desktop: Openbox 3.6.1 Distro: OBRevenge
Graphics:  Card: Intel Core Processor Integrated Graphics Controller
           Display Server: X.Org 1.18.4 drivers: intel (unloaded: modesetting,fbdev)
           Resolution: 1366x768@60.00hz
           GLX Renderer: Mesa DRI Intel Ironlake Mobile
           GLX Version: 2.1 Mesa 13.0.3
guake

(guake:6537): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:6537): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:6537): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:6537): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:6537): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:6537): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:6537): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:6537): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:6537): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:6537): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:6537): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:6537): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:6537): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:6537): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:6537): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:6537): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:6537): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:6537): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:6537): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:6537): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:6537): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:6537): libglade-WARNING **: unknown attribute `swapped' for <signal>.
INFO:guake.guake_app:Logging configuration complete
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/guake/main.py", line 253, in <module>
    exec_main()
  File "/usr/lib/python2.7/site-packages/guake/main.py", line 249, in exec_main
    if not main():
  File "/usr/lib/python2.7/site-packages/guake/main.py", line 158, in main
    instance = Guake()
  File "/usr/lib/python2.7/site-packages/guake/guake_app.py", line 359, in __init__
    self.add_tab()
  File "/usr/lib/python2.7/site-packages/guake/guake_app.py", line 1683, in add_tab
    box = GuakeTerminalBox()
  File "/usr/lib/python2.7/site-packages/guake/terminal.py", line 321, in __init__
    self.terminal = GuakeTerminal()
  File "/usr/lib/python2.7/site-packages/guake/terminal.py", line 86, in __init__
    self.configure_terminal()
  File "/usr/lib/python2.7/site-packages/guake/terminal.py", line 116, in configure_terminal
    client.set_int(KEY('/style/cursor_blink_mode'), cursor_blink_mode)
glib.GError: Configuration server couldn't be contacted: D-BUS error: Can't overwrite existing read-only value: Value for `/apps/guake/style/cursor_blink_mode' set in a read-only source at the front of your configuration path

**Comment by Stibbons** [comment]
Look like an issue with gconf. Can you restart your system?

**Comment by spookykidmm** [comment]
Yeah I'll restart when I get home and let you know what happens
