### ISSUE TITLE
Guake 8.8 python-dbus is not included in dev.sh

### ISSUE THREAD

**Issue by rubenbonilla** [Guake/guake#898]
I was trying to install Guake from `dev.sh --install` and it gets me the following error while trying to run the virtual env:

```python
Launching guake inside virtualenv
Traceback (most recent call last):
  File "src/guake/main.py", line 27, in <module>
    import dbus
ImportError: No module named dbus
```

I know is in **Dependencies** section of README.rst but also is said if you run `./dev.sh --install` all dependencies will be installed.

So it is very clear that it should be resolved in the script `./dev.sh`. If i have time i will pull request the changes.

**Comment by Stibbons** [comment]
Yes, please adapt dev.sh accordingly. This file is provided "as it", without any garantee. Maintaining such distribution dependency is actually difficult, to test I need to use a fresh install each time :(

**Comment by azjkjensen** [comment]
It may be worth mentioning how to fix this. On debian/ubuntu you can run 
`sudo apt-get install python-dbus`

**Comment by rubenbonilla** [comment]
You are rigth @azjkjensen, thanks for writting the fastest solution! Anyway someone would have to modify the install file. As i said if i have time i will do it.
