### ISSUE TITLE
loss of focus after renaming tab

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#90]
loss of focus after renaming tab http://guake.org/ticket/435
Reported by:    tdimdimich  Owned by:   somebody
Priority:   major   Milestone:  0.5.0
Component:  guake   Version:    0.4.2
Keywords:   window_losefocus,focus,tab,renaming     Cc:     tdimdimich@…
Description

guake-0.4.2-5
window_losefocus=true

Then opening the rename dialog, guake loses focus, but after click Ok or Cancel, focus don't return on guake terminal and at the same time guake is opened, it is confusing.

**Comment by martincammiteracode** [comment]
I'm still getting this problem on Ubuntu 16.04.2 LTS for Guake version 0.8.4
