### ISSUE TITLE
Compaint about the name

### ISSUE THREAD

**Issue by hudson6666** [Guake/guake#902]
Sorry but I can't help telling you this. The word *Guake* in Chinese means fail in exam. I like this program and I let it autostart when session starts. And as a result I can see a message "Guake is running..... Press F12.....", making me feel strange and panic and somewhat uncomfortable...

And I'm curious about why you choose this name.

Nothing serious, just ignore me

**Comment by Stibbons** [comment]
I am not the original author but I understand your point. Originaly it is a contraction of GNOME and Quake, the game. It could have been worst, we never know the translation of some words in any language...
