### ISSUE TITLE
Change dropdown animation to be like quake?

### ISSUE THREAD

**Issue by cruftytheclown** [Guake/guake#904]
I'm on mint cinnamon 18.1, and when I open guake it has an animation where it appears in the top middle of the screen and then quickly zooms and grows to fill the top half of the screen.

I want it to simply drop down like the way the quake console does in quake. Is there a way I can make it do that?

**Comment by Stibbons** [comment]
The animation is not handled by guake itself, it comes from your window manager. I'll try to make it more flexible on the next version of guake

**Comment by kwill** [comment]
Duplicate of https://github.com/Guake/guake/issues/701 ?

**Comment by Davidy22** [comment]
Closing because duplicate of #701
