### ISSUE TITLE
Guake preferences doesn't fit screen.

### ISSUE THREAD

**Issue by mccrack1985** [Guake/guake#905]
Even with moving my panels the window doesn't fix my screen. 
Asus Eee netbook.
![screenshot](https://cloud.githubusercontent.com/assets/15166637/22591636/38cf9b54-e9db-11e6-8f31-50fc19cb5723.png)

**Comment by unalterable** [comment]
Oh +1 on this

**Comment by sha-red** [comment]
+1 It's even worse on the release, doesn't fit on a Thinkpad X2xx screen (768 height).

**Comment by Stibbons** [comment]
just tested HEAD on a 1024x768 screen, prefs now fits :)

**Comment by ulidtko** [comment]
NOTE: for the tormented souls out there having to deal with even smaller screens: you aren't doomed.

## Workaround ##
You can **alt-drag windows**, grabbing by any point of it, not just the title-bar.

The modifier might not be <kbd>Alt</kbd> — also try <kbd>win/meta</kbd>.

Works at least in Ubuntu Unity and GNOME.
