### ISSUE TITLE
Scaling issues on 4k screen

### ISSUE THREAD

**Issue by ziflex** [Guake/guake#912]
Hi guys,

recently, I switched to a new laptop which has 4k screen. The terminal works fine except some scaling issues in settings window and a tab footer/header.

System:
Fedora 25
Wayland

![screenshot from 2017-02-17 12-33-37](https://cloud.githubusercontent.com/assets/1607148/23076203/6bf0cc32-f50d-11e6-8e47-5930d47c26f7.png)
![screenshot from 2017-02-17 12-34-18](https://cloud.githubusercontent.com/assets/1607148/23076210/6efb05d2-f50d-11e6-975a-1566c21d37eb.png)

**Comment by ziflex** [comment]
Same as here #809

**Comment by Stibbons** [comment]
Closed as duplicated
