### ISSUE TITLE
Is possible guake support rz/sz upload/download files like iterm2, SecureCRT?

### ISSUE THREAD

**Issue by netroby** [Guake/guake#922]
Is possible guake support rz/sz upload/download files like iterm2, SecureCRT?

download file/upload files from remote to local , or from local to remote

**Comment by ivoshm** [comment]
Will be great ...

As universal workaround I'm using zssh ... look at http://zssh.sourceforge.net/.

**Comment by Stibbons** [comment]
I would prefer an integration with tools such as zssh

**Comment by Stibbons** [comment]
this feature is not planned, but I am open to Pull requests

**Comment by Stibbons** [comment]
If you want this feature, please vote on [FeatHub](https://feathub.com/Guake/guake)
