### ISSUE TITLE
Python2 from Anaconda conflicting with Guake

### ISSUE THREAD

**Issue by rmondaini** [Guake/guake#930]
Guake (0.8.5-1) usually works just fine in my Ubuntu 16.10 but recently it doesn't open. I noticed the reason behind it is the conflict with the python provided in Anaconda package.

The error I get is the following:
user@user:~$ guake
/home/rmondaini/anaconda2/bin/python2: No module named guake

I tried to edit the file /usr/bin/guake by selecting the standard python as the default but this didn't help either.

PYTHON="/usr/bin/env python2"
#PYTHON="/usr/bin/python2"

exec $PYTHON -m guake.main "$@"

Any ideas?

**Comment by Stibbons** [comment]
guake is probably installed on your system so you should start it before entering into a virtualenv or a conda environment
