### ISSUE TITLE
Pixel Saver add-on & Guake 

### ISSUE THREAD

**Issue by jimouris** [Guake/guake#936]
Hello,

I am using the "Pixel saver" extension in Ubuntu Gnome which messes up Guake's configurations. Without the extension everything works fine.

With the extension enabled:
If height and width are set to 100, every time I hide and then un-hide the terminal, it adds a lot of new lines (I have to scroll up in order to find previous outputs).
If height and width are not set to 100, the position of the window is not aligned and height and width do not have correct values in addition.

Thanks in advance,
Dimitris

**Comment by Stibbons** [comment]
indeed, these size are hardcoded in the source code... I don't know how to deal with these flexible size...

**Comment by jimouris** [comment]
Actually in some applications (e.g. nautilus) pixel saver does not change anything. Guake does not have space between the top bar and the actual window (like chrome has), and it shouldn't be modified at all.

**Comment by hackel** [comment]
How odd, I also use Pixel Saver (version 15, gnome-shell 3.24) and have not experienced this issue at all.

**Comment by jimouris** [comment]
@hackel Guake Terminal 0.8.8, GNOME Shell 3.24.1, Pixel Saver (latest installed from gnome-shell-extensions) and it is still an issue. It's strange that you did not experience it..

**Comment by kwill** [comment]
FWIW I'm using Guake 0.8.8 and the "No Title Bar" extension [1] without problems.

[1] https://extensions.gnome.org/extension/1267/no-title-bar/

**Comment by jimouris** [comment]
@kwill Thanks, "No Title Bar" works great!
