### ISSUE TITLE
Feature that permits to configure an alert

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#94]
Feature that permits to configure an alert http://guake.org/ticket/420
Reported by:    slartibartfast  Owned by:   ulidtko
Priority:   trivial     Milestone:  
Component:  guake   Version:  
Keywords:       Cc:  
Description

I would find useful a feature that permits to send a desktop notification when something happens on guake tab. I imagine a right click on the tab and a "listen for changes" option. When something changes in that terminal a notification is sent.

**Comment by markkrj** [comment]
I like this feature too, and I use it on Terminator. I love Guake and I hate needing to use multiple terminals for achieving features like window splitting and this activity monitoring one. As Terminator is written in Python too, you could take a look at their plugin to get some ideas. I gona link it here: [activitywatch.py](http://bazaar.launchpad.net/~gnome-terminator/terminator/gtk3/view/head:/terminatorlib/plugins/activitywatch.py)

**Comment by Stibbons** [comment]
Not guake work. I use an command to be notified:
```bash
bing='notify-send "Stacked work finished" "Work being done in your favorite terminal is now finished. You can come back !!" -i /usr/share/pixmaps/apple-red.png -t 6000'
```

**Comment by Stibbons** [comment]
If you want this feature, please vote on [FeatHub](https://feathub.com/Guake/guake)
