### ISSUE TITLE
[gtk3] Use match_check_event instead of deprecated match_check

### ISSUE THREAD

**Issue by egmontkob** [Guake/guake#944]
This bugreport is for the gtk3-based branch.

As of VTE version 0.44, `vte_terminal_match_check()` is deprecated, `vte_terminal_match_check_event()` should be used instead. The latter one is available since VTE version 0.38, that is, VTE library version 2.91.

VTE 0.44 implements "super smooth scrolling", that is, with the touchpad the contents can be scrolled back pixel by pixel, rather than row by row. `vte_terminal_match_check()` by design cannot cope with this situation and potentially examines the wrong line (off by one). Using `vte_terminal_match_check_event()` eliminates this problem.

**Comment by egmontkob** [comment]
Friendly ping: Please don't forget about this one. Should be a damn trivial code change at two places.

**Comment by Stibbons** [comment]
Nice reminder. I’ll see what I can do
