### ISSUE TITLE
Feature Request: about vertically or horizontally splitable windows

### ISSUE THREAD

**Issue by shivabhusal** [Guake/guake#949]
Are we gonna see this feature in Guake any soon? It would be very much helpful; we would not have to toggle through two tabs. Its so easy if we could switch between two spitted windows [ always visible].

thanks

**Comment by zlatin** [comment]
Try byobu. It's mature project and have some nice additional features.

**Comment by tomchor** [comment]
This is currently being discussed [here](https://github.com/Guake/guake/issues/71), if I understand your question correctly. People have implemented this in an ad hoc manner with both byobu and tmux.

**Comment by phil294** [comment]
this could be closed now since it is implemented
