### ISSUE TITLE
Right-click tab options don't work properly

### ISSUE THREAD

**Issue by drws** [Guake/guake#970]
Step by step reproduction:

1. open tab1
2. open tab2 (it's assumed it is the focused tab now)
3. while tab2 is focused (selected), right-click on tab1 and select Close or Rename
4. tab2 is closed or renamed instead of tab1

I'm currently on version 0.8.9 on Arch Linux.

**Comment by aichingm** [comment]
I can confirm that this also happens with 0.8.10 on Arch Linux.
