### ISSUE TITLE
[Regression] Key-Combination needs to be hit twice to close guake when it is not focused

### ISSUE THREAD

**Issue by aichingm** [Guake/guake#976]
Hay, I'm on Archlinux with guake 0.8.9 - 0.8.10.

1. Set the key combination to open to open guake to any thing (happens with every combination which I have tested)
2. Hit said combination which opens guake 
3.  Focus any other program or just click on the desktop
     * If this step is skip guake works just fine
4. Hit the combination to close guake: Nothing happens but `xev` shows that X fires both events. :-1: 
5. Hit the combination a second time and guake closes :+1: 

This is a real productivity bummer (at least for me).

If you need any more information please just ask. I would be really happy to help resolving this issue.

EDIT:
I did some more testing this happens with the versions 0.8.9 and 0.8.10, 0.8.8 works just fine!

**Comment by denis-gonzo** [comment]
Look here: https://github.com/Guake/guake/pull/938

**Comment by aichingm** [comment]
Is there any way to disable this feature? Some thing like a checkbox I missed?

**Comment by denis-gonzo** [comment]
I dont think so, only "Hide on lose focus".

**Comment by dorian-marchal** [comment]
I just saw that, I thought it was a bug, too.
