### ISSUE TITLE
Delete and backspace word by word

### ISSUE THREAD

**Issue by oowekyala** [Guake/guake#979]
Hi, is there a way to delete entire words at once in guake? Something like Ctrl + Backspace and Ctrl + Del? Thanks

**Comment by Stibbons** [comment]
I would like it too !

**Comment by arvchristos** [comment]
I think that the `Ctrl + W` shortcut does exactly what you want

**Comment by oowekyala** [comment]
@arvchristos Thanks for that! `Ctrl + W` is nice but when doing that e.g. on a path it doesn't delete one segment at a time, only the entire path. Though I found what I was looking for [here](https://help.gnome.org/users/gnome-terminal/stable/adv-keyboard-shortcuts.html.en#bash-shortcuts), the shortcut is `Esc + Backspace`
