### ISSUE TITLE
Get tab index of the running command

### ISSUE THREAD

**Issue by dorian-marchal** [Guake/guake#980]
How can I get the tab index of a long running command which is not focused ?

`guake -g` returns the index of the currently focused tab, not the tab in which `guake -g` is running.

For example, run :
```shell
guake -g
```

Then, run :
```shell
sleep 5; guake -g
```

And switch tab before `guake -g` is triggered to see that returned indexes are different.

**Comment by Stibbons** [comment]
This would requires to add an additional features.
