### ISSUE TITLE
Guake takes a while to appear when I have some apps open

### ISSUE THREAD

**Issue by alex-left** [Guake/guake#982]
Hello. 

I have an reciently install of gnome ubuntu 16.04 because i have a new more powerful laptop and as always I do, i install guake terminal.  

The point is if I dont have opened any other application, guake responds fine. But as soon as I open an other application (like atom or chrome, for example) guake turns very slow to appear, about 3 second since I pulse f12. It's really annoying and not it is very agile. Of course, is not problem of the resources, I have 16Gb RAM, and the I/O it's fine too (ssd disk)
Never happened to me something like this. In logs I can't see anything. I tried multiple versions: 0.8.4 from oficial repos, 0.8.5 from webupdate repo and 0.8.10, cloning the from git hub. 
I have gnome-shell from stack, 18.5 with xorg. The graphical drivers are the free drivers included in the kernel (intel) 4.10.0-27

any idea? thanks!

**Comment by Stibbons** [comment]
I don't have any such issue. On Ubuntu 16.10 and 17.04 it works just great. Can you disable animations in your Window Manager?

**Comment by tekmark** [comment]
I have the same issue. My desktop has a 6gen i7 cpu and 16GB dd44 ram. there is a 3-sec delay after I press the hotkey F12.

**Comment by cosminj** [comment]
Same issue happening on gnome ubuntu 18.04, with 2-3 apps open.
My system is a core i7 with 32GB of RAM, ssd disk, nvidia 1070.

The hardware is not the issue here.

How can I debug why is Guake showing so slow, after about 5-7 seconds of pressing F12?

**Comment by gsemet** [comment]
you can start Guake from a terminal with `guake --verbose`

**Comment by aichingm** [comment]
which apps do you have open?

**Comment by zeusintuivo** [comment]
This is a non issue -
This can be closed too 
@Davidy22  
I also have "some-tabs" open like 80 tabs, so it will take time. plus I have zsh, brew, pyenv, etc etc, which will add load time to each terminal session. 
If users overload their terminals, is not Guake issue, 
It could a good feature to record time it takes load each terminal and warn users if the times are too long, or color tabs red if that in the case they take too long to load.

**Comment by Davidy22** [comment]
I think the original commenter is talking about non-terminal programs lagging Guake. A bit of an indeterminate report though, unable to reproduce and fuzzy on how I would. Guake toggling being slow should be much improved by using `guake-toggle` instead of running guake directly, and otherwise going to close because the issue is a bit nebulous and four years has probably done a good bit to remedy speed on its own.
