### ISSUE TITLE
Not focus on last window

### ISSUE THREAD

**Issue by pati-ni** [Guake/guake#991]
When dropping down guake and hiding it again it does not focus on last window if there is another window that has the "Always on top" property set. Instead focus is on the always on top window.

Using guake 0.8.8 from the debian repo.

**Comment by Stibbons** [comment]
not sure if this can be changed, we don't have this level of control over other windows

**Comment by pati-ni** [comment]
You are right, this behavior is present with other windows as well. It is a Gnome issue.
