### ISSUE TITLE
While Pressing Backspace key, there is weird behaviour 

### ISSUE THREAD

**Issue by karimmd** [Guake/guake#996]
I am using Ubuntu 16.04 and Guake was working normally.

But since yesterday the backspace key is not working as it supposed to be...

Also before pressing "Ctrl+L" would take me to a clear screen on the left but now with the same combo, it is coming in the center.

while pressing backspace key there is a space between character and keep pressing it displaying some weird character.
I am very confused on what may be the issue.

![selection_020](https://user-images.githubusercontent.com/6984392/29857162-cfdf03f2-8d89-11e7-9430-1f78dadd63ab.png)
![selection_021](https://user-images.githubusercontent.com/6984392/29857161-cfdd9c7e-8d89-11e7-9cec-896a9bb39882.png)

**Comment by Davidy22** [comment]
This would almost certainly be a local general shell config issue outside of Guake, reopen if this still persists and doesn't happen with other terminal programs.
